- demos/common/ota/bootloader/utility/binary_image_generator.py
- demos/common/ota/bootloader/utility/ota_image_generator.py
- demos/common/ota/bootloader/utility/util.py
- demos/microchip/curiosity_pic32mzef/mplab/nbproject/configurations.xml
Description
-----------
There were two problems:
1. MPLab IDE's Post Build step invokes python 2.7 and we were using
python 3 constructs in some of our scripts which caused build failure.
This commit removes those python 3 constructs and uses python 2.7 ones
instead.
2. Post Build command was {MP_CC_DIR}\xc32-objcopy which failed on mac
because of backslash. Changing it to forward slash i.e.
{MP_CC_DIR}/xc32-objcopy caused it to fail windows. This commit adds a
python script which is invoked in Post Build step. This script handles
this path issue in a platform agnostic way.
Testing
----------
Compared the generated binaries using diff both with and without changes:
```
$ diff -r -s b1/ b2/
Files b1/memoryfile.xml and b2/memoryfile.xml are identical
Files b1/mplab.production.bin and …
```
> fix: Microchip demo project build failure on Mac

- tools/git/hooks/src/pre_commit.py
Description
-----------
This PR fixes 2 problems:
- `git-secrets` won't work on Windows since it's not an executable but a script that can be picked up by git, so that you can call `git secrets`. This PR fix the the commit check hook.
- staged files were not passed to git secrets checks.
Checklist:
----------
> Fix git secrets checks in git hooks

- tools/checks/afqp/afqp_check/src/afqp_check.py
Why:
The argparse add_argument parameter must be nargs='+' for a flat list input.
The input argument for --files was not being properly handled.
Checklist:
----------
> fix: Update nargs parameter in afqp_check argparse

- tools/git/hooks/src/pre_commit.py
Description
-----------
If staged files are in ignore list, git secrets will check the entire working tree. Instead, it should simply return and pass the check.
Testing:
----------
Local unit tests passed, result:
`81 passed in 0.43 seconds`
Also tested with repo set up in a same way described in description,
```
On branch fix/git_hook
Your branch is up to date with 'origin/fix/git_hook'.
Changes to be committed:
(use "git reset HEAD <file>..." to unstage)
modified:   lib/ota/portable/ti/cc3220_launchpad/aws_ota_pal.c
Changes not staged for commit:
(use "git add <file>..." to update what will be committed)
(use "git checkout -- <file>..." to discard changes in working directory)
modified:   tests/common/include/aws_clientcredential.h
modified: …
```
> fix: Do not run git secrets if no file changed

- tools/git/hooks/install_hooks.ps1
- tools/git/hooks/install_hooks.sh
Description
-----------
Git hooks were set up with hard link before. However, git checkout will remove local file and replace it with a new file, thus breaking the hard link. We should use symbolic links instead.
Checklist:
----------
> fix: Use symbolic links for git hooks

- demos/common/ota/bootloader/utility/codesigner_cert_utility/codesigner_cert_utility.py
- demos/common/ota/bootloader/utility/factory_image_generator.py
- lib/ota/portable/espressif/esp32_devkitc_esp_wrover_kit/aws_ota_pal.c
- lib/ota/portable/microchip/curiosity_pic32mzef/aws_ota_pal.c
git issue #90
aws_ota_pal.c for Microchip and ESP did not check if valid
code verification certificate handle was found, and proceeds to
malloc a 0-length buffer for a non-existent certificate.  This
caused OTA code verification to fail for OTAs relyng on certificate
located in aws_ota_codesigner_certificate.h.
This fix makes sure the prvGetCertificate checks if the certificate
handle is valid before mallocing memory for it, and implements a
check for a non-null certificate value in prvPAL_ReadAndAssumeCertificate.
Small updates to factory_image_generator.py script to make it agnostic of
Python version 2 or 3.
Description
-----------
Checklist:
----------
> Fix bug in OTA PALs for Microchip & ESP

- demos/common/include/aws_logging_task.h
- lib/include/aws_system_init.h
- lib/include/aws_tls.h
- lib/include/message_buffer.h
- lib/include/stream_buffer.h
In order to guarantee correct include order, FreeRTOS.h must be
included before FreeRTOS library headers that rely on FreeRTOS
kernel types and prototypes.  These changes add an error with
instructions to include the required header.
Resolves issue #93
Description
-----------
Checklist:
----------
> Add FreeRTOS.h include warning to library headers

- lib/pkcs11/mbedtls/aws_pkcs11_mbedtls.c
fix: Delete extra headers in aws_pkcs11_mbedtls.c.
Header files:
#include "FreeRTOSIPConfig.h"
#include "task.h"
#include "semphr.h"
Were not being used.
Checklist:
----------
> fix: Delete extra headers in aws_pkcs11_mbedtls.c.

- lib/FreeRTOS-Plus-TCP/source/FreeRTOS_IP.c
FreeRTOS+TCP should flush its ARP cache on network-down
Description
-----------
git issue #100
Checklist:
----------
> fix: FreeRTOS+TCP should flush its ARP cache on network-down

- demos/xilinx/microzed/common/config_files/aws_pkcs11_config.h
- tests/espressif/esp32_devkitc_esp_wrover_kit/common/config_files/aws_pkcs11_config.h
- tests/infineon/xmc4800_iotkit/common/config_files/aws_pkcs11_config.h
- tests/ti/cc3220_launchpad/common/config_files/aws_pkcs11_config.h
- tests/vendor/board/common/config_files/aws_pkcs11_config.h
- tests/xilinx/microzed/common/config_files/aws_pkcs11_config.h
In release 1.4.3, PKCS #11 objects switched from being
accessed by file name to being accessed by label name.
As a result, pkcs11configFILE_NAME_* configs are now a property
of the portable PAL layer and are unused in the config file.
Description
-----------
Checklist:
----------
> Remove unused configs from aws_pkcs11_config.h

- lib/include/bluetooth_low_energy/bt_hal_avsrc_profile.h
- lib/include/bluetooth_low_energy/bt_hal_gatt_client.h
- lib/include/bluetooth_low_energy/bt_hal_gatt_server.h
- lib/include/bluetooth_low_energy/bt_hal_gatt_types.h
- lib/include/bluetooth_low_energy/bt_hal_manager.h
- lib/include/bluetooth_low_energy/bt_hal_manager_adapter_ble.h
- lib/include/bluetooth_low_energy/bt_hal_manager_types.h
Removing old ACE name from the APIs
Description
-----------
This PR remove left over of the old ACE name
Checklist:
----------
> Fix:Removing old ACE name from the APIs

- tools/checks/style/hn_check/readme.md
- tools/checks/style/hn_check/src/hn_check.py
- tools/checks/style/hn_check/test/test_hn_check.py
PKCS #11 types may follow the format CK_TYPE_PTR or CK_TYPE_PTR_PTR.
This change updates the style checker to recognize _PTR and _PTR_PTR
line endings as pointer types.
This change also allows variables to start with a number.
Checklist:
----------
> Modify style checker for PKCS #11 types

- tests/common/ble/aws_test_ble.c
Bug in BLE automated tests
Description
-----------
This commit fix a bug in BLE automated test.
It would expect a mode 1 level 2 on a reconnect after bonding in mode 1 level 4 which is a mistake.
After bonding, a reconnect should re-establish the same level of security.
Also, fixed default secure connection enforcement in ESP32
Checklist:
----------
> Fix: Bug in BLE automated tests

- lib/bluetooth_low_energy/portable/espressif/aws_ble_hal_gap.c
Fix: Secure connection in HAL
Description
-----------
This commit fix secure connection that was not automatically activated in the lower layer.
This is a minor fixed as secure connection is enforced by upper layers.
Checklist:
----------
> Fix: Secure connection in HAL

- tools/ota_e2e_tests/aws_ota_test/aws_ota_test_runner.py
Only the TI CC3220SF LaunchpadXL needs the RootCA to connect to other internal Amazon development stage IoT Core MQTT endpoints.
Checklist:
----------
> Update specificity on which board needs the Root CA updated for MQTT connections on other development stage endpoints.

- lib/include/aws_appversion32.h
* #pragma pack(push, 1) and #pragma pack(pop) are not portable compiler directives.
The structure AppVersion32_t is extern'ed as xAppFirmwareVersion and used throughout the code only to access each of it's member individually. 
Amazon FreeRTOS reference bootloader was going to read the version from the image, but that was decided against and so it not the current behavior. These directives are residual from the development process.
OTA Happy-path tests were performed on all supported platforms. 
Checklist:
----------
- [] My code is Linted.
> fix: Remove pragma in aws_application32.h

- lib/FreeRTOS-Plus-POSIX/source/FreeRTOS_POSIX_pthread_mutex.c
- lib/include/FreeRTOS_POSIX/sys/types.h
Changed internal pthread_mutexattr_t allocation from dynamic to stack based.
This will reduce memory fragmentation and malloc/free overhead
Description
-----------
Checklist:
----------
- [ X] I have tested my changes. No regression in existing tests.
- [X ] My code is Linted.
> fix: updated pthread_mutexattr_t

- lib/FreeRTOS-Plus-POSIX/source/FreeRTOS_POSIX_clock.c
- lib/FreeRTOS-Plus-POSIX/source/FreeRTOS_POSIX_mqueue.c
- lib/FreeRTOS-Plus-POSIX/source/FreeRTOS_POSIX_pthread_cond.c
- lib/FreeRTOS-Plus-POSIX/source/FreeRTOS_POSIX_pthread_mutex.c
- lib/FreeRTOS-Plus-POSIX/source/FreeRTOS_POSIX_semaphore.c
- lib/FreeRTOS-Plus-POSIX/source/FreeRTOS_POSIX_timer.c
- lib/FreeRTOS-Plus-POSIX/source/FreeRTOS_POSIX_utils.c
- lib/include/FreeRTOS_POSIX/utils.h
- tests/common/posix/aws_test_posix_clock.c
- tests/common/posix/aws_test_posix_pthread.c
- tests/common/posix/aws_test_posix_timer.c
- tests/common/posix/aws_test_posix_utils.c
- tools/git/hooks/src/pre_commit.py
Fixed potential UTILS_TimespecSubtract overflow
Updated UTILS_AbsoluteTimespecToTicks to get rid of call to posix function
Added unit tests
Description
-----------
Checklist:
----------
> Fix: Posix utils timespec overflow

- lib/FreeRTOS-Plus-POSIX/source/FreeRTOS_POSIX_pthread_mutex.c
Added critical section protection to update owner and unlock atomically
Description
-----------
Checklist:
----------
> fix: pthread_mutex_unlock update owner atomically

- demos/ti/cc3220_launchpad/common/application_code/main.c
- tests/common/ota/aws_test_ota_pal.c
- tests/ti/cc3220_launchpad/common/application_code/main.c
* This is to help with debugging possible security alerts caused by testing that are not cleared. 
* Through experimentation the alert count would print only when the routine is placed after the WiFi connection is complete.
Checklist:
----------
> fix: Add printing of FS security alert count to the main.c of the TI CC3220SF

- demos/renesas/rx65n-rsk/e2studio/.cproject
- tests/renesas/rx65n-rsk/e2studio/.cproject
* As of today the latest version of CC-RX is 3.00.00. 
* e2 studio has a hard-coded dependency on the tool-chain version and it is not automatically updated in the project file for the version that may be available on your machine.
Checklist:
----------
> fix: Update the toolchain version for Renesas Rx65n rsk to the latest CC-RX v3.00.00.

- demos/nordic/nrf52840-dk/common/application_code/main.c
- demos/nordic/nrf52840-dk/common/config_files/sdk_config.h
Fix: ble reliability fix
Description
-----------
ble reliability fix.
UART interrupt was getting preempted cause system instabilities
Checklist:
----------
> Fix: Fixing instabilities due to UART

- lib/include/private/aws_ota_pal.h
* Specify that the entire flash partition designated for OTA image download must be completely erased in prvPAL_CreateFileForRx().
Checklist:
----------
- [n/a] I have tested my changes. No regression in existing tests.
> docs: Add OTA image download partition information to prvPAL_CreateFileForRx().

- tools/aws_config_quick_start/README.md
- tools/aws_config_quick_start/SetupAWS.py
- tools/aws_config_quick_start/configure.json
- For ease of use add the relative path to afr_source_dir in configure.json.
- Add support for the ~ relative home path in Unix systems. 
Tested ../.., ~, and absolute paths in Linux and Windows.
----------
> Updates to the Quick Start script given documention feedback

- tools/ota_e2e_tests/aws_ota_test/aws_ota_test_case.py
- tools/ota_e2e_tests/aws_ota_test/aws_ota_test_main.py
- tools/ota_e2e_tests/aws_ota_test/aws_ota_test_runner.py
When the program did not exit, this hogged the test machine indefinitely. 
When there was an exception in initializing AWS resources or the initial project build for a test case fails, then the program would not exit. This is because FlashSerialComm opened a separate thread that was still running. I have moved the initialization of the serial port reading thread last. I moved the test case setup, that may build a project, to a try catch block noting the exception as a failure. 
Checklist:
----------
> Exit the OTA E2E tests for build failures and AWS initialization errors

- tests/common/defender/aws_iot_tests_defender_api.c
Description
-----------
- not do test assert in MQTT callback; instead, copy the data and assert outside the callback
- remove "retry if reject" logic; instead, simply increase the sleep time
Checklist:
----------
> improve defender unit tests

- demos/common/devmode_key_provisioning/aws_dev_mode_key_provisioning.c
- lib/pkcs11/mbedtls/aws_pkcs11_mbedtls.c
Resolves issue #262
Description
-----------
Tested by running WinSim TCP, TLS, PKCS tests.
Checklist:
----------
> Protect PKCS Sign/Verify keys during multithreaded use

- lib/third_party/mcu_vendor/espressif/esp-idf/components/newlib/include/pthread.h
- lib/third_party/mcu_vendor/espressif/esp-idf/components/pthread/include/esp_pthread.h
- lib/third_party/mcu_vendor/espressif/esp-idf/components/pthread/pthread_cond_var.c
- tests/common/posix/aws_test_posix_pthread.c
* Added missing PTHREAD_COND_INITIALIZER provided by ESP developer
* Removed unit tests changes made to account for missing initializer
Description
-----------
Checklist:
----------
> feat: Added PTHREAD_COND_INITIALIZER for ESP

- lib/bluetooth_low_energy/aws_ble_gap.c
- lib/bluetooth_low_energy/aws_ble_gatt.c
- lib/include/aws_ble.h
- lib/include/iot_linear_containers.h
- lib/include/iot_metrics.h
- lib/include/private/aws_ble_internals.h
Changed GATT and GAPP service and event lists to the linked containers
Description
-----------
The containers in aws_ble_gatt.c and aws_ble_gap.c were using aws_doubly_linked_list.h
This change switches these containers over to the new iot_linear_containers.h 
Checklist:
----------
> Changed GATT and GAPP service and event lists to the linked containers

- demos/common/defender/aws_iot_demo_defender_v1.c
- demos/pc/windows/visual_studio/aws_demos.vcxproj
- demos/pc/windows/visual_studio/aws_demos.vcxproj.filters
- lib/defender/aws_iot_defender_collector.c
- lib/defender/aws_iot_defender_v1.c
- lib/include/aws_defender.h
- tests/common/defender/aws_iot_tests_defender_api_v1.c
- tests/common/include/aws_iot_config_common.h
- tests/common/test_runner/aws_test_runner.c
- tests/pc/windows/visual_studio/aws_tests.vcxproj
- tests/pc/windows/visual_studio/aws_tests.vcxproj.filters
Description
-----------
implement old defender library interfaces, including demo and tests. Only support one metrics: TCP connections count
Changes from original defender library:
- DefenderMetric_t is defined as enum, instead of pointer to internal metrics structure
- DEFENDER_ConnectionTimeoutSet function will do nothing but return success
- remove irrelevant tests
Checklist:
----------
> implement old defender library interfaces, including demo and tests

- lib/wifi/portable/nxp/lpc54018iotmodule/aws_wifi.c
- tests/common/wifi/aws_test_wifi.c
- tests/nxp/lpc54018iotmodule/common/application_code/main.c
Description
-----------
Updated the WiFi tests to put the status message in the task parameters for the multi-task test.
Updated the WiFi tests to retry the socket connection in the round trip test.
Updated the NXP WiFi port to return success when it was already successfully initialized and to fail the WiFi connection if the DHCP fails.
http://34.216.37.221/job/afr_test_custom/715/
Checklist:
----------
> AWS WiFi Test Stability Upates + NXP LPC54018 AWS WiFi port updates

- lib/shadow/aws_shadow.c
- lib/shadow/aws_shadow_json.c
Our Shadow client has an error message which reports a 'timeout' in reference to trying to acquire a semaphore handle. But that sounds a lot like a network timeout in the context of MQTT applications; we could be a bit clearer.
Description
-----------
Update the error message to clarify that the application appears to have encountered an error in the callback method which the application was waiting on, inferred from the fact that its callback never released its semaphore.
Checklist:
----------
> Update shadow error message in response to issue #304

- tests/common/secure_sockets/aws_test_tcp.c
Description
-----------
xEhoServerAddress was created on stack and some of the member variables
were not initialized. As a result those variables would end up having
garbage values - this did not create any problem because we did not use
those member variables. This commit initializes those member variables
to correct values.
Checklist:
----------
> fix: Fix uninitialized variable in TCP tests

- tools/ota_e2e_tests/aws_ota_test/aws_ota_test_runner.py
* Print exceptions that occur when cleaning up AWS resources.
We are deleting the serial thread first, so that when exceptions occur in cleaning up the AWS resources the program exits because there are no outstanding threads.
Checklist:
----------
> Delete the serial thread first in the test cleanup.

- lib/greengrass/aws_greengrass_discovery.c
Include the C runtime header for snprintf (stdio.h).
> Include C runtime header for snprintf.

- lib/include/aws_tls.h
- lib/pkcs11/portable/pc/windows/aws_pkcs11_pal.c
- lib/tls/aws_tls.c
- tests/common/secure_sockets/aws_test_tcp.c
TLS library states that it returns negative error codes, but PKCS #11
library returns positive error codes.  Some positive PKCS #11 error codes
were propogated out of TLS, breaking API contract and occasionally causing
error code to be interpreted as number of bytes sent or received.
This commit also fixes a threading bug in the Windows PKCS #11 PAL layer
when reading files, and cleans up formatting on an error print statement in
the sockets tests.
Description
-----------
Ran TLS & Sockets tests on WinSIm for testing.
Checklist:
----------
> Convert errors in TLS wrapper to negative error codes

- tools/aws_config_quick_start/SetupAWS.py
Description
-----------
- We cannot delete read-only file under Windows, need to change permission first.
- cert_id_file is open without being closed.
Checklist:
----------
> Fix some issues in quick start script under Windows

- lib/include/FreeRTOS_POSIX/sys/types.h
- lib/include/FreeRTOS_POSIX/unistd.h
I ran into a couple of small issues building FreeRTOS+POSIX into a project, and these changes seemed to fix them.
Description
-----------
* Add the 'off_t' file size/offset type, set to what looks like the POSIX standard of a long int.
* Add a 'sys/types.h' include to the 'unistd.h' header file to make sure that the 'useconds_t' type is defined.
I'm not sure if this is actually part of the POSIX standard, or just how POSIX says that the 'off_t' type should be dealt with in systems which implement it. But this seems like a fairly minor change, and it also seems good to avoid compile-time 'libc'-related errors where we can. See resources such as:
http://pubs.opengroup.org/onlinepubs/9699919799/basedefs/sys_types.h.html
Checklist:
----------
> Add the 'off_t' POSIX type and ensure that 'sys/types.h' is included in 'unistd.h' so that the 'useconds_t' type is known to be known.

- lib/mqtt/aws_mqtt_agent.c
- lib/tls/aws_tls.c
TLS_Send does not handle the error condition when space is not available on disk.
Related Issues: https://github.com/aws/amazon-freertos/issues/275
Description
-----------
mbedtls_write sends back pdFREERTOS_ERRNO_ENOSPC when the send buffer is full.
Checklist:
----------
> Why: TLS_Send does not handle the error condition when space is not available on disk.

- lib/FreeRTOS-Plus-TCP/source/FreeRTOS_TCP_WIN.c
Description
-----------
FreeRTOS_TCP_WIN.c accessed the container member of the list item
directly instead of using the provided accessor macro for the same. The
container variable name was changed from pvContainer to pxContainer
which resulted in build failure. To ensure backward compatibility,
pxContainer was replaced with pvContainer using preprocessor if
configENABLE_BACKWARD_COMPATIBILITY was set to 1.
This commit removes the direct access and replaces it with the provided
accessor macro. As a result, it is no longer needed to set
configENABLE_BACKWARD_COMPATIBILITY to 1.
Fix issue: https://github.com/aws/amazon-freertos/issues/366
Testing
----------
- Generated the preprocessed file and examined manually for both configENABLE_BACKWARD_COMPATIBILITY = 1 and …
> fix: Use accessor macro to access list member

- lib/FreeRTOS-Plus-TCP/source/portable/NetworkInterface/WinPCap/NetworkInterface.c
Description
-----------
In response to #372.
Removes incorrect selection of network interfaces.  Fixes spelling of `xConfigNetworkInterfaceToUse`.
Checklist:
----------
> fix: WinPCAP network interface selection

- lib/include/FreeRTOS.h
- lib/include/private/portable.h
Description
-----------
portHAS_STACK_OVERFLOW_CHECKING was getting defined too late before
being used in portable.h for the platforms that do not have stack
overflow checking registers. This commit ensures that it is defined
before it is used.
Checklist:
----------
> fix: Fix warning portHAS_STACK_OVERFLOW_CHECKING not defined

- lib/FreeRTOS-Plus-TCP/source/FreeRTOS_Sockets.c
Description
-----------
bug fix to "ARG FV Finding: FreeRTOS_setsockopt() returns wrong error codes".
ticket number: E039512548
Please check with current on-call for status update. 
Checklist:
----------
>  Fix FreeRTOS_setsockopt()

- demos/microchip/curiosity_pic32mzef/mplab/nbproject/configurations.xml
* Took rtos_hooks.c out of compilation in the demo project. This is already done in the test project.
This is the first fix for support of XC32 v2.15. Updating Harmony to v2.06 and the subsequent auto-generated system configuration files will be in a separate PR.
Requesting a review from all engineers involved in the original investigation.
Checklist:
----------
> fix: Fix duplicate defined FreeRTOS hooks in Microchip.

- lib/include/iot_linear_containers.h
Fix a potential build error caused by int type mismatch.
Description
-----------
Depending on how strict the compiler flags are, this can cause a build failure because the `IotListDouble_InsertSorted` function is called with an int*(...) for its last argument instead of an int32_t*(...) in the taskpool source files.
Another option would be to make the `_timerEventCompare(...)` method in `lib/common/iot_taskpool.c` return an int instead of an int32_t. But the method is marked as static, so it is unlikely to be used outside of the library file and the extra specificity shouldn't cause issues for users who choose to use generic 'int' types in their application code.
I also did not observe any issues with calls to `IotListDouble_InsertSorted` in other places with different int types. …
> Fix a compiler warning / potential error from an int/int32_t mismatch

- demos/common/mqtt/aws_subscribe_publish_loop.c
There was a warning generated on System Workbench of -Wunused-variable.
The reason being it falls under the preprocessor block of INCLUDE_uxTaskGetStackHighWaterMark.
Checklist:
----------
> fix: Remove the warning of unused variable xTaskStatus

- demos/pc/windows/common/application_code/aws_demo_logging.c
* printf and fflush are not scheduler safe operations.
* vLoggingPrint provides a variation of the WinSim console logger that omits timestamps.
This PR implements changes from: https://github.com/aws/amazon-freertos/pull/285
Checklist:
----------
> fix: Make vLoggingPrint() for WinSim scheduler safe.

- lib/FreeRTOS/portable/GCC/ARM_CM0/port.c
- lib/FreeRTOS/portable/RVDS/ARM_CM0/port.c
Description
-----------
Fix spelling of priority in comments. This was pointed out in the PR: https://github.com/aws/amazon-freertos/pull/320
Checklist:
----------
> docs: Fix spelling of priority in comments

- lib/FreeRTOS-Plus-TCP/source/portable/NetworkInterface/WinPCap/NetworkInterface.c
* I accidentally placed it within the if() of pcap_setfilter(). 
* pcap_freecode() needs to be called anytime pcap_compile succeeds.
Checklist:
----------
> fix: pcap_freecode() was in the wrong spot.

- README.md
The Windows Simulator sections is inconsistently styled from the other platform's sections and looks weird in the browser rendering. 
This pull request fixes that styling.
Checklist:
----------
> docs: Fix README.md style for Windows Simulator.

- demos/microchip/curiosity_pic32mzef/mplab/nbproject/configurations.xml
- tests/microchip/curiosity_pic32mzef/mplab/nbproject/configurations.xml
Description
-----------
The latest XC32 compiler (version 2.15) does not allow multiple
definitions while the previous versions allowed it. As a result, using
the latest compiler results in linker errors. We should remove
multiple definitions but allowing explicitly for now to fix the
build failure with the latest compiler.
Checklist:
----------
> fix: Fix link failure with latest XC32 compiler on Microchip

- lib/FreeRTOS-Plus-POSIX/source/FreeRTOS_POSIX_clock.c
- lib/FreeRTOS-Plus-POSIX/source/FreeRTOS_POSIX_mqueue.c
- lib/FreeRTOS-Plus-POSIX/source/FreeRTOS_POSIX_pthread.c
- lib/FreeRTOS-Plus-POSIX/source/FreeRTOS_POSIX_pthread_mutex.c
- lib/include/FreeRTOS_POSIX/pthread.h
- tests/common/posix/aws_test_posix_mqueue.c
POSIX compliance fix.
Description
-----------
This PR comes from staging repo feature/ble-beta branch commit SHA 4b4d61db72079236e307e9fcf48873f581575118.
This PR passes winsim test project, POSIX test suite. 
FreeRTOS_POSIX_clock.c -- clock_getcpuclockid(), Open Group "Upon successful completion, clock_getcpuclockid() shall return zero; otherwise, an error number shall be returned to indicate the error."
FreeRTOS_POSIX_clock.c -- clock_gettime(), Open Group does not require this branch, and returning -1 without errno set is confusing. Thus taking out tp null check.
FreeRTOS_POSIX_mqueue.c -- mq_open(), Open Group "[EINVAL]
O_CREAT was specified in oflag, the value of attr is not NULL, and either mq_maxmsg or mq_msgsize was less than or equal to zero." Additional args -- mode and attr are …
> POSIX compliance fix.

- lib/include/platform/iot_platform_types_afr.h
- tests/pc/windows/visual_studio/aws_tests.vcxproj
- tests/pc/windows/visual_studio/aws_tests.vcxproj.filters
Description
-----------
Windows Tests cannot be built:
- add stdbool.h to iot_platform_types_afr.h
- fix project file
Checklist:
----------
> fix platform types afr and project file

- tests/common/wifi/aws_test_wifi.c
Description
-----------
The WiFi test setup does not have protection, so if it crashes the setup fails and report that all the tests are passing. This change catches that scenario.
Checklist:
----------
> Add protection to wifi test setup

- lib/FreeRTOS-Plus-POSIX/include/FreeRTOS_POSIX_internal.h
- lib/FreeRTOS-Plus-POSIX/include/portable/FreeRTOS_POSIX_portable_default.h
- lib/FreeRTOS-Plus-POSIX/source/FreeRTOS_POSIX_pthread_barrier.c
- lib/FreeRTOS-Plus-POSIX/source/FreeRTOS_POSIX_pthread_cond.c
- lib/FreeRTOS-Plus-POSIX/source/FreeRTOS_POSIX_semaphore.c
- lib/common/iot_taskpool.c
- lib/include/atomic.h
- tests/pc/windows/visual_studio/aws_tests.vcxproj
- tests/pc/windows/visual_studio/aws_tests.vcxproj.filters
Atomic & POSIX with atomic.
Description
-----------
- ```atomic.h``` header. 
post previous review:
(1) added macro ```ATOMIC_COMPARE_AND_SWAP_SUCCESS```/```ATOMIC_COMPARE_AND_SWAP_FAILURE```.
(2) CAS API returns type uint32_t, which indicates swapped or not, instead of previous value. 
(3) if ```portmacro.h``` does not provide compiler specific force inline, don't inline. 
- POSIX barrier, pthread mutex condition, and semaphore are updated. (```pthread_cond_broadcast()``` and ```pthread_cond_signal()``` would be fun to review, CAS is involved. To see which mutexes are removed, ```FreeRTOS_POSIX_internal.h```)
- POSIX semaphore maximum allowed value got updated, since POSIX requires sem value to be int, and atomic is using uint32_t.
- Task pool maximum allowed semaphore value also got …
> Atomic & POSIX with atomic.

- lib/utils/platform/iot_threads_afr.c
- tests/nordic/nrf52840-dk/common/config_files/FreeRTOSConfig.h
- tests/nordic/nrf52840-dk/common/config_files/iot_test_config.h
Description
-----------
Fix MQTT "multithreaded subscription" test on Nordic.  Was running out of memory when creating threads.  Increased FreeRTOS heap size on Nordic by 15KB.
Checklist:
----------
> Fix multithreaded subscription test on Nordic

- lib/common/iot_common.c
- lib/include/private/aws_secure_sockets_wrapper_metrics.h
- lib/secure_sockets/aws_secure_sockets_wrapper_metrics.c
- lib/utils/aws_system_init.c
- tests/pc/windows/common/config_files/iot_test_config.h
Description
-----------
- remove metrics from IotCommon_Init
- map socket init to socket-metrics-init when metrics is enabled
- update aws_system_init.c to include aws_secure_socket header instead of linking extern function
Checklist:
----------
> init metrics library in socket init when enabled

- demos/common/include/iot_config_common.h
- lib/utils/platform/iot_network_afr.c
Description
-----------
Secure sockets is inconsistent and returns either 0 or `EWOULDBLOCK` on timeout, depending on the port.  Change the network layer to check for both values.
Checklist:
----------
> Check for EWOULDBLOCK on timeout

- demos/common/network_manager/aws_iot_network_manager.c
Fixing syntax error in network manager
Description
-----------
Fixing syntax error in network manager with WIFI provisioning disabled.
Tested with all the configurations.
Checklist:
----------
> Fixing syntax error ( Issue#482 )

- lib/wifi/portable/espressif/esp32_devkitc_esp_wrover_kit/aws_wifi.c
ESP WIFI_GetMac was calling esp_wifi_get_mac with wrong argument.
https://github.com/aws/amazon-freertos/issues/452
Description
-----------
Checklist:
----------
- [ X] I have tested my changes. No regression in existing tests.
> fix: ESP WIFI_GetMac returning wrong mac.

- tools/ota_e2e_tests/aws_ota_test/aws_ota_aws_agent.py
* The versioning enabling should happen when we create a bucket.
It was happening for every initialization previously and causing a potentional
for conflicting operations.
Checklist:
----------
> tools: Fix when we enable s3 bucket versioning.

- lib/ota/portable/README.md
Fix the Readme file in OTA pal.
Description
-----------
The readme file in OTA pal was still having a statement that OTA is in beta. This changes removes that line in readme as OTA is in GA.
Checklist:
----------
> docs: fix OTA pal readme file by removing line that OTA is beta.

- demos/common/demo_runner/iot_demo_afr.c
- lib/bluetooth_low_energy/services/wifi_provisioning/iot_ble_wifi_provisioning.c
- lib/include/iot_ble_wifi_provisioning.h
- lib/include/private/iot_ble_config_defaults.h
Use task pool for WiFi-Provisioning 
Description
-----------
Use task pool to avoid dynamic task creation.
Change names of variables/config.
Checklist:
----------
> Move wifi provisioning to taskpool

- lib/wifi/portable/espressif/esp32_devkitc_esp_wrover_kit/aws_wifi.c
- tests/common/include/iot_ble_wifi_prov_test_access_define.h
- tests/common/wifi_provisioning/aws_test_wifi_provisioning.c
Avoid Clearing STARTED_BIT in WIFI_Scan() API 
Description
-----------
STARTED_BIT should not be cleared from event group after WiFi driver has started successfully. This causes other APIs to block on the started bit.
Checklist:
----------
> [Issue #486] Avoid Clearing STARTED_BIT in WIFI_Scan()

- lib/FreeRTOS-Plus-TCP/source/FreeRTOS_DNS.c
prvProcessDNSCache() stops the search when pcName[0] is zero
pcName[0] is set to zero when cache entry is invalidated.
https://github.com/aws/amazon-freertos/issues/471
Description
-----------
Checklist:
----------
- [ X] I have tested my changes. No regression in existing tests.
> fix: DNS cache processing

- tools/cbmc/proofs/ParseDNSReply/Makefile.json
- tools/cbmc/proofs/ParseDNSReply/cbmc-batch.yaml
- tools/cbmc/proofs/make-common-makefile.py
Fix new loop unwinding issue in CBMC proof of ParseDSNReply
Description
-----------
The function prvProcessDNSCache includes a loop that needs to be unwound for the CBMC proof to be sound.  This pull request unwinds the loop 5 times which is sufficient for the proof to succeed.
Checklist:
----------
> Fix new loop unwinding issue in CBMC proof of ParseDSNReply

- modules/libraries/3rdparty/CMakeLists.txt
- modules/libraries/standard/serializer/CMakeLists.txt
- vendors/nxp/boards/lpc54018iotmodule/CMakeLists.txt
- vendors/nxp/boards/lpc54018iotmodule/aws_demos/common/application_code/main.c
- vendors/nxp/boards/lpc54018iotmodule/ports/secure_sockets/aws_secure_sockets.c
Description
-----------
- add CMakefile for nxp mcuxpresso
- exclude cborpretty.c because it includes a bad header "inttype.h"
- fix multi-definition problem in demo
Checklist:
----------
> add CMakefile for nxp and fix build problems

- vendors/espressif/boards/esp32/CMakeLists.txt
Fix CMAKE dependency for wifi connect task
Description
-----------
Wifi Connect task is a demo task and should only be included for demos when ble ( wifi provisioning is enabled).
Checklist:
----------
> Fix Cmake dependency for wifi connect task

- modules/ports/wifi/test/aws_test_wifi.c
- Made connection status and made task failures more clear in AFQP_WiFiSeperateTasksConnectingAndDisconnectingAtOnce.
Checklist:
----------
> tests: Add more feedback to wifi multitask test.

- tests/common/include/aws_test_wifi.h
- tests/common/wifi/aws_test_wifi.c
Description
-----------
refactor: Move the 2nd test WIFI AP to a header file
Checklist:
----------
> refactor: Move the 2nd test WIFI AP to a header file

- lib/FreeRTOS-Plus-TCP/source/FreeRTOS_Sockets.c
prvTCPSendCheck needs to handle eCLOSED, eCLOSE_WAIT, and eCLOSING as as a disconnected socket. See #566.
> Fix handling of disconnected socket states in prvTCPSendCheck.

- lib/FreeRTOS-Plus-TCP/include/FreeRTOS_IP_Private.h
- lib/FreeRTOS-Plus-TCP/source/FreeRTOS_TCP_IP.c
Report the correct WIN size
Description
-----------
A FreeRTOS+TCP user Wolfgang Schur, reported that under some rare circumstances, the reported value of WIN ( the available space in the TCP r4ecption window) is not correct.
In fact, it would be a bit behind: the last read from a socket would not be taken into account, so the reported WIN size sometimes wat too small.
The WIN size would be stored in the TCP socket field called `ulRxCurWinSize`.
In this patch, the field `ulRxCurWinSize` will be removed, and WIN will be calculated at the moment it must be send to the peer.
Under certain circumstances, this patch will make the communication a bit more efficient.
Checklist:
----------
> Report the correct WIN size

- lib/FreeRTOS-Plus-TCP/include/FreeRTOS_Sockets.h
- lib/FreeRTOS-Plus-TCP/source/FreeRTOS_Sockets.c
Make TCP low-water/high-water limits configurable with a socket option
Description
-----------
When receiving data on a TCP socket, there is a mechanism that controls the flow: when the reception stream buffer gets filled for more than 80%, a WIN update will be sent to the peer.
When the buffer drops below 20%, again a WIN update will be sent in order to resume transmission.
These 20/80 limits have been hard-coded up until now.
This patch allows to control the 2 limits per socket. It adds a new socket option:
`#define FREERTOS_SO_SET_LOW_HIGH_WATER	( 18 )`
and it should be called with a (pointer to a) parameter of this type:
`typedef struct xLOW_HIGH_WATER {`
`	/* Structure to pass for the 'FREERTOS_SO_SET_LOW_HIGH_WATER' option */`
`	size_t uxLittleSpace;	/* Send a STOP when buffer space …
> Make TCP low-water/high-water limits configurable with a socket option

- modules/ports/ble/include/private/iot_ble_internal.h
- modules/ports/ble/iot_ble_gap.c
- modules/ports/ble/iot_ble_gatt.c
Removing FreeRTOS from middleware
Description
-----------
Making middleware OS agnostic by using APIs from iot_threads.h
Checklist:
----------
> Removing FreeRTOS from middleware

- demos/common/ota/bootloader/utility/ota_image_generator.py
On some platforms, endAddress variable was rendered with the long "L"
designation at the end (ex 0x01234567L) which was not interpreted
properly by subsequent functions.  This commit uses the
format32BitHexStr to address all string formatting.
Description
-----------
Checklist:
----------
> Fix formatting of endAddress in ota_image_generator.py

- lib/FreeRTOS-Plus-TCP/source/FreeRTOS_DHCP.c
- tools/cbmc/proofs/ProcessDHCPReplies/Makefile.json
- tools/cbmc/proofs/ProcessDHCPReplies/cbmc-batch.yaml
- tools/cbmc/proofs/make-common-makefile.py
Fix handling of an option occurring at the end of a DHCP response packet. See #559.
> Fix handling of an option at the end of the DHCP response packet.

- cmake/vendors/espressif/esp32_devkitc_esp_wrover_kit/CMakeLists.txt
- cmake/vendors/espressif/esp32_devkitc_esp_wrover_kit/run_idf_monitor.cmake
List of changes:
* sdkconfig generation path now inside build folder
* sdkconfig is regenerated on running cmake
* support added for monitor target
> ESP IDF : CMake build system related changes

- tools/cbmc/proofs/ARP/ARPAgeCache/ARPAgeCache_harness.c
- tools/cbmc/proofs/ARP/ARPAgeCache/Makefile.json
- tools/cbmc/proofs/ARP/ARPAgeCache/cbmc-batch.yaml
- tools/cbmc/proofs/ARP/ARPGenerateRequestPacket/ARPGenerateRequestPacket_harness.c
- tools/cbmc/proofs/ARP/ARPGenerateRequestPacket/Makefile.json
- tools/cbmc/proofs/ARP/ARPGenerateRequestPacket/cbmc-batch.yaml
- tools/cbmc/proofs/ARP/ARPGetCacheEntry/ARPGetCacheEntry_harness.c
- tools/cbmc/proofs/ARP/ARPGetCacheEntry/Makefile.json
- tools/cbmc/proofs/ARP/ARPGetCacheEntry/cbmc-batch.yaml
- tools/cbmc/proofs/ARP/ARPProcessPacket/ARPProcessPacket_harness.c
- tools/cbmc/proofs/ARP/ARPProcessPacket/Makefile.json
- tools/cbmc/proofs/ARP/ARPProcessPacket/cbmc-batch.yaml
- tools/cbmc/proofs/ARP/ARPRefreshCacheEntry/ARPRefreshCacheEntry_harness.c
- tools/cbmc/proofs/ARP/ARPRefreshCacheEntry/Makefile.json
- tools/cbmc/proofs/ARP/ARPRefreshCacheEntry/cbmc-batch.yaml
- tools/cbmc/proofs/ARP/ARPSendGratuitous/ARPSendGratuitous_harness.c
- tools/cbmc/proofs/ARP/ARPSendGratuitous/Makefile.json
- tools/cbmc/proofs/ARP/ARPSendGratuitous/cbmc-batch.yaml
- tools/cbmc/proofs/ARP/ARP_FreeRTOS_ClearARP/ClearARP_harness.c
- tools/cbmc/proofs/ARP/ARP_FreeRTOS_ClearARP/Makefile.json
- tools/cbmc/proofs/ARP/ARP_FreeRTOS_ClearARP/cbmc-batch.yaml
- tools/cbmc/proofs/ARP/ARP_FreeRTOS_OutputARPRequest/Makefile.json
- tools/cbmc/proofs/ARP/ARP_FreeRTOS_OutputARPRequest/OutputARPRequest_harness.c
- tools/cbmc/proofs/ARP/ARP_FreeRTOS_OutputARPRequest/cbmc-batch.yaml
Description
-----------
Theses harnesses proof in general the memory safety of the ARP code base.
There are a few assumptions made about the code:
- pointer passed as an pointer to an ARPPacket_t are really pointing to a piece of memory of sizeof(ARPPacket_t)
- pxGetNetworkBufferWithDescriptor work correctly (There are proofs in the pipeline for this as well.)
- xNetworkInterfaceOutput is out of scope for this proofs and abstracted away.
- xSendEventToIPTask  is out of scope for this proofs and abstracted away.
The program is safe until the call of abstracted functions. There might be a memory problem inside the xNetworkInterfaceOutput or xSendEventToIPTask function, that is not catched in this call.
Checklist:
----------
- …
> CBMC harnesses for FreeRTOS_ARP.c

- cmake/vendors/espressif/esp32_devkitc_esp_wrover_kit/CMakeLists.txt
.elf suffix removed and target app directly depends on exe_target
> IDF CMake : Circular dependency fixed in ELF generation

- lib/FreeRTOS-Plus-TCP/source/FreeRTOS_TCP_IP.c
This fixes the ACK number check that ensures that inbound RST packets received during the SYN-SENT state. Per the TCP RFC, the ACK number should be one more than the current sequence number in our window state structure.
> Fix ACK number check for RST packet handling.

- demos/demo_runner/iot_demo_afr.c
- vendors/cypress/WICED_SDK/WICED/RTOS/FreeRTOS/FreeRTOS.mk
- vendors/cypress/boards/CYW943907AEVAL1F/aws_demos/common/application_code/main.c
- vendors/cypress/boards/CYW943907AEVAL1F/aws_demos/common/config_files/FreeRTOSConfig.h
- vendors/cypress/boards/CYW943907AEVAL1F/aws_tests/common/application_code/main.c
- vendors/cypress/boards/CYW943907AEVAL1F/aws_tests/common/config_files/FreeRTOSConfig.h
- vendors/cypress/boards/CYW943907AEVAL1F/aws_tests/common/config_files/aws_test_runner_config.h
- vendors/cypress/boards/CYW954907AEVAL1F/aws_demos/common/application_code/main.c
- vendors/cypress/boards/CYW954907AEVAL1F/aws_demos/common/config_files/FreeRTOSConfig.h
- vendors/cypress/boards/CYW954907AEVAL1F/aws_tests/common/application_code/main.c
- vendors/cypress/boards/CYW954907AEVAL1F/aws_tests/common/config_files/FreeRTOSConfig.h
- vendors/cypress/boards/CYW954907AEVAL1F/aws_tests/common/config_files/aws_test_runner_config.h
Changes:
1. Remove double intialization of wifi in main() by removing `prvWifiConnect()`
2. Move back to heap_3 as cypress was qualified with heap_3 and the reboot resolves
with switching back to heap_3
3. Remove the line `xPortGetMinimumEverFreeHeapSize` in iot_demo_afr.c as heap_3
doesn't have that function.
4. Change the test runner config to run the new defined tests.
Checklist:
----------
> fix: Reboot issue on cypress with release-1.5

- demos/common/defender/aws_defender_demo.c
- lib/defender/aws_defender.c
Per #219 the analogous fix to our Greengrass Discovery library was previously made. This fix allows the Defender client code to use Thing names that are determined at runtime rather than statically.
> Don't assume that Thing name is a static string define (see #219).

- tools/cbmc/README.md
- tools/cbmc/proofs/make-common-makefile.py
- tools/cbmc/proofs/make-configuration-directories.py
Description
-----------
The make-configuration-directories.py script takes a Configurations.json file and unfold the define section into a single proof directory per define set.
Checklist:
----------
> Add a configuration unfolding script for CBMC proof configurations.

- modules/libraries/aws/defender/test/aws_iot_tests_defender_api.c
- modules/libraries/standard/metrics/src/aws_secure_sockets_wrapper_metrics.c
- modules/ports/secure_sockets/freertos_plus_tcp/aws_secure_sockets.c
- modules/ports/secure_sockets/include/aws_secure_sockets_config_defaults.h
- modules/ports/secure_sockets/include/aws_secure_sockets_wrapper_metrics.h
- vendors/pc/boards/windows/aws_tests/common/config_files/aws_secure_sockets_config.h
Description
-----------
- move socket metrics configuration to socket header
Tests pass: https://amazon-freertos-ci.corp.amazon.com/view/5-CMake/job/afr_test_cmake/272/
Checklist:
----------
> enable metrics of secure socket in windows test

- vendors/cypress/WICED_SDK/WICED/network/LwIP/WICED/wiced_network.c
Description
-----------
Waiting for IPV6 address to be advertised causes reboot on Cypress boards. Commented out the code which only waits for IPv6 validation.
**This change needs further investigation. It is being tracked on :https://sim.amazon.com/issues/TS-7386** 
Checklist:
----------
> Fix reboot on cypress tests

- vendors/cypress/WICED_SDK/apps/test/aws_test/aws_test.mk
Description
-----------
Defender tests have a new dependency on secure sockets. Adding the `aws_secure_sockets_wrapper_metrics.c` file to the tests.
Removing double inclusion of `aws_test_tls.c`
Checklist:
----------
> Add secure sockets file for Defender tests

- tools/cbmc/proofs/Makefile.template
Description
-----------
This change adds the option for goto-instrument flags specification. These were not required until now, but the task pool code base is full of volatile variables whose behavior cannot be correctly modeled unless the flag `--nondet-volatile` is passed to goto-instrument.
Checklist:
----------
> Adds option for goto-instrument flags specification

- tools/cbmc/proofs/DNS/DNSHandlePacket/DNShandlePacket_harness.c
- tools/cbmc/proofs/DNS/DNSHandlePacket/Makefile.json
- tools/cbmc/proofs/DNS/DNSHandlePacket/cbmc-batch.yaml
Description
-----------
This PR includes the CBMC proof for memory safety of the DNShandlePacket function, which handles a DNS packet.
Checklist:
----------
> CBMC memory-safety proof for DNSHandlePacket

- tools/cbmc/proofs/DNS/DNSclear/DNSclear_harness.c
- tools/cbmc/proofs/DNS/DNSclear/Makefile.json
- tools/cbmc/proofs/DNS/DNSclear/cbmc-batch.yaml
Description
-----------
This PR includes the CBMC proof for memory safety of the DNSgetHostByName function, which removes entries from the DNS cache.
Checklist:
----------
> CBMC memory-safety proof for DNSclear

- libraries/c_sdk/standard/common/include/iot_taskpool.h
- libraries/c_sdk/standard/common/include/types/iot_taskpool_types.h
- libraries/c_sdk/standard/common/taskpool/iot_taskpool.c
Description
-----------
This commit also fixes a minor initialization issue where memset was not
being passed the correct size. Other than that all the changes are in
comments only.
Checklist:
----------
> Fix multiple spellings in TaskPool documentation.

- tools/cbmc/proofs/ARP/ARPGetCacheEntryByMac/ARPGetCacheEntryByMac_harness.c
- tools/cbmc/proofs/ARP/ARPGetCacheEntryByMac/Makefile.json
- tools/cbmc/proofs/ARP/ARPGetCacheEntryByMac/README.md
- tools/cbmc/proofs/ARP/ARP_FreeRTOS_PrintARPCache/FreeRTOS_PrintARPCache_harness.c
- tools/cbmc/proofs/ARP/ARP_FreeRTOS_PrintARPCache/Makefile.json
- tools/cbmc/proofs/ARP/ARP_FreeRTOS_PrintARPCache/README.md
Description
-----------
While eARPGetCacheEntryByMac and FreeRTOS_PrintARPCache are compiled out by default,
the provided proofs ensure that they are memory safe, if compiled in on occasion.
> Add CBMC harnesses for non default functions

- tools/ota_e2e_tests/aws_ota_test/aws_ota_test_case_back_to_back_downloads.py
- tools/ota_e2e_tests/aws_ota_test/aws_ota_test_case_corrupt_image_after_signing.py
- tools/ota_e2e_tests/aws_ota_test/aws_ota_test_case_corrupt_image_before_signing.py
- tools/ota_e2e_tests/aws_ota_test/aws_ota_test_case_corrupt_signature.py
- tools/ota_e2e_tests/aws_ota_test/aws_ota_test_case_dummy_test.py
- tools/ota_e2e_tests/aws_ota_test/aws_ota_test_case_factory.py
- tools/ota_e2e_tests/aws_ota_test/aws_ota_test_case_greater_version.py
- tools/ota_e2e_tests/aws_ota_test/aws_ota_test_case_incorrect_platform.py
- tools/ota_e2e_tests/aws_ota_test/aws_ota_test_case_incorrect_wifi_password.py
- tools/ota_e2e_tests/aws_ota_test/aws_ota_test_case_missing_filename.py
- tools/ota_e2e_tests/aws_ota_test/aws_ota_test_case_previous_version.py
- tools/ota_e2e_tests/aws_ota_test/aws_ota_test_case_same_version.py
- tools/ota_e2e_tests/aws_ota_test/aws_ota_test_case_single_byte_image.py
- tools/ota_e2e_tests/aws_ota_test/aws_ota_test_case_unsigned_image.py
- tools/ota_e2e_tests/aws_ota_test/aws_ota_test_case_untrusted_certificate.py
Remove duplicate getName method in specific test cases
Description
-----------
Remove duplicate getName method in specific test cases. Meanwhile, correct the test case name for OtaTestMissingFilename.
Checklist:
----------
> Remove duplicate getName method in specific test cases

- demos/demo_runner/iot_demo_afr.c
- demos/include/iot_config_common.h
Add unique identifier for device and generate metrics with device identifier
Description
-----------
Inorder to identify devices emitting metrics behind a proxy, a unique identifier for device needs to be emitted.
Identifier is generated using MD5 hash of device certificate and encoded as a 32 character hex string.
Sample output:
10 1033 [iot_thread] ?SDK=AmazonFreeRTOS&Version=4.0.0&Platform=WinSim&AFRDevID=8CC7EB90972FF50A4F17C459EBC5BCD2
Checklist:
----------
> Add device identifier and device metrics computation

- libraries/abstractions/ble_hal/test/aws_test_ble_hal.c
- tests/common/iot_tests_network.c
- vendors/espressif/boards/esp32/aws_tests/application_code/main.c
- vendors/nordic/boards/nrf52840-dk/aws_tests/application_code/main.c
Improving ble stack initialization sequence
Description
-----------
Before:
In the main during initialization, if BLE test were not being run, memory for BLE would be cleared.
That memory needs to be released to allow memory hungry test like last will and testament to succeed.
The issue with that approach is that is needs to check on flags in test_runner_config.h.
This conflict with our test system and IDT.
Now:
Only BT classic memory is released.
BLE stack is initialized when network is selected.
Checklist:
----------
> Improving ble stack initialization sequence

- libraries/freertos_plus/aws/ota/src/aws_iot_ota_agent.c
Description
-----------
This fix adds a filter for accepted data blocks before sending OTA job status update to service. This ensures that when duplicate data blocks are received we do not send any OTA job status thus reducing the overhead and number of MQTT messages.
Checklist:
----------
> Fix: Ignore duplicate data blocks when sending OTA status update to service

- tools/aws_config_quick_start/SetupAWS.py
Description
-----------
The quick start script uses configuration values supplied by the user in
configure.json file. The WiFi security value is not a free form string
and must be one of the following values: eWiFiSecurityOpen,
eWiFiSecurityWEP, eWiFiSecurityWPA, eWiFiSecurityWPA2. This change makes
sure that we terminate the script and provide a useful error message if
the user has supplied incorrect WiFi security value.
Checklist:
----------
> Add WiFi Security value check in quick start script

- freertos_kernel/include/FreeRTOS.h
- tools/cbmc/proofs/MakefileCommon.json
Description
-----------
I introduce `configPRECONDITION` which is resolved to `configASSERT` in the default case,
but allows finer control for dealing with an assertion in CBMC proofs.
There are a couple of implicit invariants, I will introduce as `configPRECONDTION` along with test harnesses to the code base.
Other invariants are explicit and kept as `configASSERT`.
The idea is to resolve `configPRECONDITION` to `__CPROVER_assume` for proofs and `configASSERT` to `__CPROVER_assert` for proofs.
Checklist:
----------
> Add configPRECONDITION to FreeRTOS.h

- tools/cbmc/proofs/MakefileCommon.json
Description
-----------
Set CBMC include path to absolute in MakefileCommon.json. The change is required for proofs grouped in subfolders that include `cbmc.h` (since the proof folder structure is not flat anymore).
Checklist:
----------
> Change CBMC include path to absolute

- libraries/c_sdk/aws/shadow/src/aws_shadow.c
Fix error with Delta Callback Registration
See issue #826 
Description
-----------
Delta callback was inadvertently being registered to update events due to
a function parameter issue.
Checklist:
----------
> Fix error with Delta Callback Registration

- libraries/freertos_plus/aws/ota/src/aws_iot_ota_agent.c
This change adds a check that if the prvProcessOTAJobMsg returns NULL
and the image state is still unknown, the OTA job is aborted with
a job parse error
Description
-----------
If "prvProcessOTAJobMsg" returns NULL, a test is made to see if the image state is in the "self_test" phase.  However "prvProcessOTAJobMsg" will also return NULL if there is an error in parsing the OTA job data.  
This changes checks for that condition by checking if the image state is still in the "unknown" state and if so, aborts the OTA job with a parse error.
Checklist:
----------
> Added a check for a failed process job message.

- vendors/espressif/boards/esp32/CMakeLists.txt
This should also fix support for adding extra components by setting IDF_EXTRA_COMPONENT_DIRS
Also corrected IDF_PATH supplied to `monitor` target
Here is a reference CMakeLists.txt of an external project outside the AFR source tree. Note that it is assumed the `amazon_freertos` root is a subdirectory of this project.
```
cmake_minimum_required(VERSION 3.13)
project(my_app)
add_executable(my_app main.c)
set(IDF_PROJECT_EXECUTABLE my_app)
get_filename_component(EXTRA_COMPONENT_DIRS
"components/hello_world" ABSOLUTE
)
set(IDF_EXTRA_COMPONENT_DIRS ${EXTRA_COMPONENT_DIRS})
set(AFR_BOARD espressif.esp32_devkitc CACHE INTERNAL "")
add_subdirectory(amazon-freertos)
target_link_libraries(my_app PRIVATE AFR::mqtt)
```
To build, flash an start the serial monitor, we need to call the following:
``` …
```
> cmake : Allow projects outside AFR source tree to link IDF component libs

- libraries/c_sdk/aws/shadow/test/aws_test_shadow.c
In response to #825 
Adds a (different) delta callback in the update callback test; this will ensure that the correct function is being set.
> Set delta callback in Shadow test

- CMakeLists.txt
- libraries/CMakeLists.txt
- vendors/espressif/boards/esp32/aws_demos/application_code/espressif_code/mbedtls/CMakeLists.txt
- vendors/espressif/boards/esp32/aws_tests/application_code/espressif_code/mbedtls/CMakeLists.txt
There are multiple changes in this PR. Apart from the correction in vendor/espressif specific cmake files, there are small changes in AFR library cmake files to have the 3rdparty libraries added prior to adding the vendor specific files. This allows adding vendor specific port sources and include files to be added to 3rdparty library targets.
List of changes:
* add 3rdparty libraries before adding vendor specific subdirectory
* IDF's mbedtls port files now added directly to the 3rdparty library
> cmake : Add mbedtls port files from IDF to 3rdparty/mbedtls library

- projects/microchip/curiosity_pic32mzef/mplab/aws_demos/nbproject/configurations.xml
- projects/microchip/curiosity_pic32mzef/mplab/aws_tests/nbproject/configurations.xml
- vendors/microchip/boards/curiosity_pic32mzef/CMakeLists.txt
- vendors/microchip/boards/curiosity_pic32mzef/aws_demos/config_files/aws_demo_config.h
- vendors/microchip/boards/curiosity_pic32mzef/aws_demos/config_files/aws_iot_network_config.h
- vendors/microchip/boards/curiosity_pic32mzef/aws_tests/config_files/FreeRTOSIPConfig.h
- vendors/microchip/boards/curiosity_pic32mzef/aws_tests/config_files/aws_iot_network_config.h
- vendors/microchip/boards/curiosity_pic32mzef/ports/wifi/iot_wifi.c
Update Microchip PIC32MZEF to use the Ethernet
Description
-----------
The heart of this PR is this commit: https://github.com/aws/amazon-freertos/pull/907/commits/0244112dc709505ba24e88a5302d0539a41c0ce8
- Added PIC32_USE_ETHERNET where it was missing in Microchip.
- Added NetworkInterface_eth.c to be compiled in CMAKE, and the MPLABX IDE projects.
- Updated the network manager configuration files to support Ethernet .
- Fixed a path to some OTA utility python scripts that was incorrect in vendors\microchip\boards\curiosity_pic32mzef\CMakeLists.txt
This addresses issue: https://github.com/aws/amazon-freertos/issues/831
To use Ethernet you define this preprocessor macro at the project level: PIC32_USE_ETHERNET
We are still working on integrating this into the internal testing framework. …
> Update Microchip PIC32MZEF to use the Ethernet

- vendors/cypress/WICED_SDK/Makefile
Debugger issue with Cypress port
Description
-----------
Openocd is looking for gdbinit in the same folder where .cproject is loaded from.
This patch re-locates .gdbinit to the right path so that de-bugging works correctly
Checklist:
----------
> Fixing Debugger issue with Cypress port

- libraries/c_sdk/aws/shadow/src/aws_shadow.c
- libraries/c_sdk/standard/mqtt/src/iot_mqtt_agent.c
The C-SDK refers to upcoming MQTT API as v4, but for Amazon FreeRTOS they are v2 of these libraries.
Fixing comment references between v4 and v2 in Amazon FreeRTOS-only files to use Amazon FreeRTOS
versioning syntax.
https://amazon-freertos-ci.corp.amazon.com/view/3-Nightly/job/dsl_nightly_cmake/71/
Description
-----------
Checklist:
----------
> Change references from v4 to v2

- libraries/freertos_plus/standard/freertos_plus_tcp/source/FreeRTOS_DNS.c
- tools/cbmc/proofs/DNS/DNSlookup/DNSlookup_harness.c
- tools/cbmc/proofs/DNS/DNSlookup/Makefile.json
Description
-----------
This PR includes the CBMC proof for memory safety of the DNSlookup function, which looks for the indicated host name in the DNS cache
Checklist:
----------
> CBMC memory-safety proof for DNSlookup

- tools/cbmc/proofs/parsing/ProcessIPPacket/Makefile.json
- tools/cbmc/proofs/parsing/ProcessIPPacket/ProcessIPPacket_harness.c
Description
-----------
This PR includes the CBMC proof for memory safety of the prvProcessIPPacket function.
Checklist:
----------
> Adding CBMC proof for Process IP header (Depends on pull requests #760 and #761)

- libraries/freertos_plus/standard/freertos_plus_tcp/source/FreeRTOS_IP.c
- libraries/freertos_plus/standard/freertos_plus_tcp/source/FreeRTOS_TCP_IP.c
- tools/cbmc/include/aws_freertos_ip_verification_access_ip_define.h
- tools/cbmc/include/aws_freertos_tcp_verification_access_tcp_define.h
Description
-----------
These headers files are required to access the static functions in FreeRTOS_TCP_IP and FreeRTOS_IP.
Checklist:
----------
> Header files to access static functions for IP header proof

- libraries/freertos_plus/standard/freertos_plus_tcp/source/FreeRTOS_UDP_IP.c
- tools/cbmc/proofs/parsing/ProcessReceivedUDPPacket/Makefile.json
- tools/cbmc/proofs/parsing/ProcessReceivedUDPPacket/ProcessReceivedUDPPacket_harness.c
Description
-----------
This PR includes the CBMC proof for memory safety of the xProcessReceivedUDPPacket function.
Checklist:
----------
> Adding CBMC proof for Process received UDP packet

- libraries/freertos_plus/standard/freertos_plus_tcp/source/FreeRTOS_TCP_IP.c
- tools/cbmc/proofs/parsing/ProcessReceivedTCPPacket/Makefile.json
- tools/cbmc/proofs/parsing/ProcessReceivedTCPPacket/ProcessReceivedTCPPacket_harness.c
Description
-----------
This PR includes the CBMC proof for memory safety of the xProcessReceivedTCPPacket function.
Checklist:
----------
>  Adding CBMC proof for Process received TCP packet (Depends on pull requests #760 and #761)

- libraries/freertos_plus/standard/freertos_plus_tcp/source/FreeRTOS_IP.c
Corrected length-check in usGenerateProtocolChecksum()
-----------
The 16-bit IPv4-field `usLength` is equal to the length of the IP-header, plus the protocol header plus the payload.
But it does not have knowledge about the Ethernet header that may precede it.
The the length check should be:
-	if( uxBufferLength < FreeRTOS_ntohs( pxIPPacket->xIPHeader.usLength )
+	if( uxBufferLength < FreeRTOS_ntohs( pxIPPacket->xIPHeader.usLength + ipSIZE_OF_ETH_HEADER )
I tested the above change by adding some logging, which shows that `uxBufferLength` is always 14 bytes bigger than what is indicated in `usLength`.
Checklist:
----------
> Length check in usGenerateProtocolChecksum()

- tools/ota_e2e_tests/aws_ota_test/aws_ota_project.py
- tools/ota_e2e_tests/aws_ota_test/aws_ota_test_case.py
- tools/ota_e2e_tests/aws_ota_test/aws_ota_test_case_factory.py
- tools/ota_e2e_tests/aws_ota_test/aws_ota_test_case_greater_version_max_block_config.py
- tools/ota_e2e_tests/aws_ota_test/aws_ota_test_case_greater_version_min_block_config.py
Added two new precor test cases for OTA E2E.
Description
-----------
Added two new precor test cases for OTA E2E. One with min block size of 1U and one with max block size of 128U.
Checklist:
----------
> Added two new precor test cases for OTA E2E.

- libraries/freertos_plus/standard/freertos_plus_tcp/source/FreeRTOS_DNS.c
DNS calculates protocol-checksum with wrong length
-----------
When the IP-task must calculate checksums:
#define ipconfigDRIVER_INCLUDED_TX_IP_CHECKSUM   0
the function `prvReplyDNSMessage()` passes the length of the UDP-payload, in stead of the length of the entire Ethernet packet to `usGenerateProtocolChecksum()`.
-	usGenerateProtocolChecksum( ( uint8_t* ) pxUDPPacket, lNetLength, pdTRUE );
+	usGenerateProtocolChecksum( ( uint8_t* ) pxUDPPacket, pxNetworkBuffer->xDataLength, pdTRUE );
As a result, the unit was not able to reply to LLMNR or NBNS requests.
I tested it by doing a ping to my device, by name. Ping uses the LLMNR protocol to find the IP-address.
Checklist:
----------
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this …
> DNS calculates protocol checksum with wrong length

- libraries/freertos_plus/aws/ota/src/aws_iot_ota_agent.c
Added starting of the request timer even when the prvPublishMmessage returns a failure.
This is a fix for [Issue#897](https://github.com/aws/amazon-freertos/issues/897)
Description
-----------
Added the starting of the request timer even if the "prvPublishMessage" returns a failure.
Checklist:
----------
> Fix for issue#897.

- tools/cbmc/proofs/parsing/ProcessIPPacket/Makefile.json
- tools/cbmc/proofs/parsing/ProcessIPPacket/ProcessIPPacket_harness.c
Description
-----------
This PR changes the name of the flag in the proof for ProcessIPHeader in order to access the verification headers.
--------
Checklist:
----------
> Name change in ProcessIPHeader proof

- libraries/c_sdk/standard/mqtt/src/iot_mqtt_network.c
Description
-----------
In response to #940
- Adds a log message on malloc failure (note that this log message may not print because logging requires malloc too).
- Flush a partial MQTT packet from the incoming data stream on malloc failure.
Checklist:
----------
> Flush MQTT packets on receive malloc failure

- tools/cbmc/proofs/DNS/DNSgetHostByName_cancel/DNSgetHostByName_cancel_harness.c
- tools/cbmc/proofs/DNS/DNSgetHostByName_cancel/Makefile.json
Description
-----------
This PR includes the CBMC proof for memory safety of the DNSgetHostByName_cancel function.
Checklist:
----------
> CBMC memory-safety proof for DNSgetHostByName_cancel

- projects/st/stm32l475_discovery/ac6/aws_demos/.project
- projects/st/stm32l475_discovery/ac6/aws_tests/.project
- vendors/st/boards/stm32l475_discovery/aws_demos/application_code/st_code/cmsis_os.c
- vendors/st/boards/stm32l475_discovery/aws_demos/application_code/st_code/cmsis_os.h
- vendors/st/boards/stm32l475_discovery/aws_demos/application_code/st_code/es_wifi_conf.h
- vendors/st/boards/stm32l475_discovery/aws_demos/application_code/st_code/es_wifi_io.c
- vendors/st/boards/stm32l475_discovery/aws_demos/config_files/FreeRTOSConfig.h
- vendors/st/boards/stm32l475_discovery/aws_tests/application_code/st_code/cmsis_os.c
- vendors/st/boards/stm32l475_discovery/aws_tests/application_code/st_code/cmsis_os.h
- vendors/st/boards/stm32l475_discovery/aws_tests/application_code/st_code/es_wifi_conf.h
- vendors/st/boards/stm32l475_discovery/aws_tests/application_code/st_code/es_wifi_io.c
- vendors/st/boards/stm32l475_discovery/aws_tests/config_files/FreeRTOSConfig.h
- vendors/st/stm32l475_discovery/BSP/Components/es_wifi/es_wifi.c
Description
-----------
The driver for the Inventek WiFi module provided by ST had support for
interrupts but it was written for CMSIS-RTOS. So far we were using the
driver in the polling mode thereby wasting unnecessary CPU cycles while
the module was busy working.
This change uses the CMSIS wrapper for FreeRTOS provided by ST to enable
the interrupt mode of the driver. As a result, we no longer will waste
any unnecessary CPU cycles while the module is busy working.
Checklist:
----------
> Make the driver for Inventek WiFi module interrupt driven

- libraries/freertos_plus/standard/freertos_plus_tcp/source/FreeRTOS_DNS.c
- tools/cbmc/proofs/DNS/DNSgetHostByName_a/DNSgetHostByName_a_harness.c
- tools/cbmc/proofs/DNS/DNSgetHostByName_a/Makefile.json
Description
-----------
This PR includes the CBMC proof for memory safety of the DNSgetHostByName_a function, which prepares and sends a message to a DNS server along with callback.
Checklist:
----------
> CBMC memory-safety proof for DNSgetHostByName_a

- libraries/freertos_plus/standard/freertos_plus_tcp/source/FreeRTOS_DNS.c
- tools/cbmc/proofs/DNS/DNSgetHostByName/DNSgetHostByName_harness.c
- tools/cbmc/proofs/DNS/DNSgetHostByName/Makefile.json
Description
-----------
This PR includes the CBMC proof for memory safety of the DNSgetHostByName function, which prepares and sends a message to a DNS server.
Checklist:
----------
> CBMC memory-safety proof for DNSgetHostByName

- libraries/c_sdk/standard/mqtt/src/iot_mqtt_operation.c
Description
-----------
Fix a log message in MQTT keep alive job printing the wrong value.
Checklist:
----------
> Fix log message in MQTT keep-alive

- libraries/c_sdk/standard/ble/include/iot_ble_config_defaults.h
- libraries/c_sdk/standard/ble/src/iot_ble_gap.c
- libraries/c_sdk/standard/ble/src/services/mqtt_ble/iot_ble_data_transfer.c
In response to https://github.com/aws/amazon-freertos/issues/950
Description
-----------
The PR adds config to enable or disable all FreeRTOS GATT services or selectively enable/disable each  of them.
By default, Device Information Service and Data Transfer Services are enabled by in FreeRTOS. 
To disable them, set :
``` #define IOT_BLE_ENABLE_FREERTOS_GATT_SERVICES ( 0 ) ``` in ```iot_ble_config.h```
Checklist:
----------
Tested all configurations against Nordic and ESP.
> Enable/disable BLE gatt services through config

- vendors/cypress/WICED_SDK/apps/test/aws_test/aws_test.mk
Add missing file iot_device_metrics.c to cypress tests
Description
-----------
iot_device_metrics.c was only added to demos make file but not the tests
Checklist:
----------
> Fix build error in cypress tests

- tools/cmake/toolchains/arm-ti.cmake
Corrects the syntax for specifying a response file to the TI
toolchain.
This resolves an issue when CMake attempted to build aws_tests.out on
Windows where, due to command line length limits, a response file was
being created and referenced incorrectly.
Signed-off-by: Chris Ring <cring@ti.com>
Checklist:
----------
> Fix TI CMake response file syntax

- tools/cbmc/proofs/HTTP/IotHttpsClient_Connect/IotHttpsClient_Connect_harness.c
- tools/cbmc/proofs/HTTP/IotHttpsClient_Connect/Makefile.json
- tools/cbmc/proofs/HTTP/IotHttpsClient_ReadContentLength/IotHttpsClient_ReadContentLength_harness.c
- tools/cbmc/proofs/HTTP/IotHttpsClient_ReadContentLength/Makefile.json
- tools/cbmc/proofs/HTTP/IotHttpsClient_ReadHeader/IotHttpsClient_ReadHeader_harness.c
- tools/cbmc/proofs/HTTP/IotHttpsClient_ReadHeader/Makefile.json
- tools/cbmc/proofs/HTTP/IotHttpsClient_ReadResponseStatus/IotHttpsClient_ReadResponseStatus_harness.c
- tools/cbmc/proofs/HTTP/IotHttpsClient_ReadResponseStatus/Makefile.json
- tools/cbmc/proofs/HTTP/global_state_HTTP.c
- tools/cbmc/proofs/MakefileCommon.json
Description
-----------
This PR contains CBMC proof for IotHttpsClient_Connect, IotHttpsClient_ReadContentLength, IotHttpsClient_ReadHeader, IotHttpsClient_ReadResponseStatus. The initialization of global data structures and memory allocation for pointers are done in global_state_HTTP.c.
Checklist:
----------
> Adding CBMC proof for HTTP

- tools/cbmc/proofs/HTTP/IotHttpsClient_Disconnect/IotHttpsClient_Disconnect_harness.c
- tools/cbmc/proofs/HTTP/IotHttpsClient_Disconnect/Makefile.json
Description
-----------
This PR contains cbmc proof for IotHttpsClient_Disconnect. The proof uses global_state_HTTP.c file added in PR #966.
Checklist:
----------
> CBMC proof for IotHttpsClient_Disconnect (depends on PR #966)

- tools/cbmc/proofs/HTTP/IotHttpsClient_SendSync/HttpsClient_SendSync_harness.c
- tools/cbmc/proofs/HTTP/IotHttpsClient_SendSync/Makefile.json
Description
-----------
This PR contains cbmc proof for IotHttpsClient_SendSync. The proof uses global_state_HTTP.c file added in PR #966.
Checklist:
----------
> CBMC proof for IotHttpsClient_SendSync (depends on PR #966)

- tools/git/hooks/src/pre_commit.py
Description
-----------
pre-commit script runs some code style checks including uncrustify
before a commit is made. This commit adds 2 options to the script to
allow users to use the same script to uncrustify files:
1. ```python tools/git/hooks/src/pre_commit.py --uncrustify```
2. ```python tools/git/hooks/src/pre_commit.py --uncrustify-all-files```
The first one uncrustifies the modified files by the user while the
second one uncrustifies all the files in the repo.
Checklist:
----------
> Add option to run uncrustify to the pre-commit script

- vendors/espressif/boards/esp32/CMakeLists.txt
List of changes:
* Revert `sdkconfig` generation logic, i.e. changes in sdkconfig.defaults are only reflected on fresh build
* Allow external projects to specify `IDF_SDKCONFIG_DEFAULTS`
> IDF : Allow external projects to override defaults

- demos/demo_runner/iot_demo_freertos.c
Description
-----------
runDemoTask is created using Iot_CreateDetachedThread API and the
threads created using this API must not call vTaskDelete as it is
automatically called when the thread routine returns. Explicitly calling
vTaskDelete results in a memory leak as the internally allocated
threadInfo_t does not get freed.
This was reported here:
https://github.com/aws/amazon-freertos/issues/989
Checklist:
----------
> Remove call to vTaskDelete from runDemoTask

- vendors/nuvoton/boards/numaker_iot_m487_wifi/aws_tests/config_files/iot_test_pkcs11_config.h
- vendors/nuvoton/boards/numaker_iot_m487_wifi/ports/pkcs11/iot_pkcs11_pal.c
Description
-----------
PKCS11 tests failed on Nuvoton due to memory corruption on stack. This is to fix the bug in Nuvoton pkcs11 porting code.
Checklist:
----------
> fix bug in Nuvoton pkcs11 porting code

- CHANGELOG.md
- demos/include/iot_demo_runner.h
- vendors/cypress/boards/CYW943907AEVAL1F/aws_demos/config_files/aws_demo_config.h
- vendors/cypress/boards/CYW954907AEVAL1F/aws_demos/config_files/aws_demo_config.h
- vendors/espressif/boards/esp32/aws_demos/config_files/aws_demo_config.h
- vendors/espressif/boards/esp32/aws_tests/config_files/aws_demo_config.h
- vendors/infineon/boards/xmc4800_iotkit/aws_demos/config_files/aws_demo_config.h
- vendors/marvell/boards/mw300_rd/aws_demos/config_files/aws_demo_config.h
- vendors/marvell/boards/mw300_rd/aws_tests/config_files/aws_demo_config.h
- vendors/mediatek/boards/mt7697hx-dev-kit/aws_demos/config_files/aws_demo_config.h
- vendors/microchip/boards/curiosity_pic32mzef/aws_demos/config_files/aws_demo_config.h
- vendors/nordic/boards/nrf52840-dk/aws_demos/config_files/aws_demo_config.h
- vendors/nxp/boards/lpc54018iotmodule/aws_demos/config_files/aws_demo_config.h
- vendors/pc/boards/windows/aws_demos/config_files/aws_demo_config.h
- vendors/renesas/boards/rx65n-rsk/aws_demos/config_files/aws_demo_config.h
- vendors/renesas/boards/rx65n-rsk/aws_tests/config_files/aws_demo_config.h
- vendors/st/boards/stm32l475_discovery/aws_demos/config_files/aws_demo_config.h
- vendors/ti/boards/cc3220_launchpad/aws_demos/config_files/aws_demo_config.h
- vendors/vendor/boards/board/aws_demos/config_files/aws_demo_config.h
- vendors/xilinx/boards/microzed/aws_demos/config_files/aws_demo_config.h
Updated stack sizes and priorities to be demo specific.
Description
-----------
Release 1.5 changed demos to use  default stack size from aws_demo_config.h .  Some demos do need higher stack size. iot_demo_runner.h, defines entry function for each demo, the same file can be used define demo specific stack size if it is required. This change makes sure that if demo specific stack size and priority is defined, then it is used, otherwise default sizes are used. 
Other changes include cleaning up defines that are no longer used (related to SUB PUB demo) and uncrustify.
Checklist:
----------
- [] I have tested my changes. No regression in existing tests.
- [X ] My code is Linted.
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, …
> fix: demo stack sizes and priorities

- vendors/espressif/boards/esp32/CMakeLists.txt
Fix ESP CMakefile to support multiple BLE stacks
Description
-----------
With recent changes for adding multiple BLE  HAL implementations, CMakefile also needs to be include them as header files instead of source. 
Checklist:
----------
Ran successfully BLE tests on ESP
> Fix ESP cmakefile 

- vendors/cypress/WICED_SDK/apps/test/aws_test/aws_test.mk
Fix MQTT unit test group build failure for cypress
Description
-----------
MQTT unit tests for metrics build was failing as the test source file was not added to make file.
Checklist:
----------
Ran successfully the MQTT test group for Cypress54
> Fix test group build failure  for cypress

- vendors/cypress/WICED_SDK/apps/test/aws_test/aws_test.mk
Fix MQTT unit test group build failure for cypress
Description
-----------
MQTT unit tests for metrics build was failing as the test source file was not added to make file.
Checklist:
----------
Ran successfully the MQTT test group for Cypress54
> Fix test group build failure for cypress

- tools/cbmc/include/queue_init.h
- tools/cbmc/include/tasksStubs.h
- tools/cbmc/proofs/CBMCStubLibrary/tasksStubs.c
CBMC Stub Library
Description
-----------
While working on the proofs for linear containers,
I figured out that there are a couple of stubs and function models I have to reuse in different harnesses. Therefore, I started a CBMC Stub library for keeping a single model for each of these stubs.
This library is still work in progress but I appreciate some early feedback on my assumptions.
Checklist:
----------
> Add CBMC Stub Library and queue proof infrastructure

- libraries/freertos_plus/standard/freertos_plus_tcp/include/NetworkBufferManagement.h
- libraries/freertos_plus/standard/freertos_plus_tcp/source/FreeRTOS_IP.c
FreeRTOS_IP.c three small changes
-----------
In order to save time and energy, I would like to combine 3 small changes to `FreeRTOS_IP.c` in a single PR:
1. Check if `ipINITIALISATION_RETRY_DELAY` is already defined from outside
2. In function `pxDuplicateNetworkBufferWithDescriptor()`: give length parameter `size_t` type
3. Only check the validity of the gateway address if it is defined ( i.e. non-zero ).
Ad 1.
the function `xNetworkInterfaceInitialise()` is called repeatedly until it returns `pdPASS`. It shall return `pdPASS` once the PHY Link Status is high ( or once WiFi is connected ). The time between these calls ( polls ) is now fixed at 3 seconds.
FreeRTOS+TCP has a few macro's that are not exactly public, but that may be defined from outside. I would like to do the same here:
/* …
> FreeRTOS_IP.c three small changes

- libraries/c_sdk/standard/https/src/iot_https_client.c
There is a buffer overflow in header generation if the lengths of
the header name or value are large enough to induce an integer overflow
in the header length calculation.  This patch bounds these lengths to
UINT32_MAX>>2.
Description
-----------
Checklist:
----------
> Bound name and value lengths so header length does not overflow.

- vendors/nxp/boards/lpc54018iotmodule/aws_demos/config_files/aws_demo_config.h
Per #1024, this change increases the stack size for the above from 360 words to 990.
> Provide enough stack for the MQTT Echo Demo connection task (see #1024).

- tools/cbmc/proofs/MakefileCommon.json
- tools/cbmc/proofs/make_cbmc_batch_files.py
CBMC proofs do not currently run on a Windows PC due to changes to the build infrastructure over summer. (CBMC proofs still run fine in CI). This patchset Windows proof run issues.
> Windows fixes for CBMC local runs

- libraries/freertos_plus/standard/tls/src/iot_tls.c
TLS_Recv was returning an mbedtls error instead of the valid number of bytes read.
Description
-----------
Please consider the following scenario:
The server sends 300 valid bytes then immediately closes the connection. Such is the case with a non-persistent HTTP request.
My buffer to receive is 500 bytes. I cannot know large the HTTP response is so I ask the network receive function for 500 bytes.
In the original code mbedtls_ssl_read will return 300 bytes in the first iteration, but since that is less than the 500 bytes requested, the code loops again.
In the second iteration a negative error code is returned indicating that the server closed the connection. This error code would be returned replacing the 300 bytes read.
The correct way to handle this is to simply return the bytes read …
> Update TLS_Recv to return bytes read immediately.

- vendors/cypress/boards/CYW943907AEVAL1F/aws_demos/config_files/aws_demo_config.h
- vendors/cypress/boards/CYW954907AEVAL1F/aws_demos/config_files/aws_demo_config.h
- vendors/espressif/boards/esp32/aws_tests/config_files/aws_demo_config.h
- vendors/infineon/boards/xmc4800_iotkit/aws_demos/config_files/aws_demo_config.h
- vendors/marvell/boards/mw300_rd/aws_demos/config_files/aws_demo_config.h
- vendors/mediatek/boards/mt7697hx-dev-kit/aws_demos/config_files/aws_demo_config.h
- vendors/microchip/boards/curiosity_pic32mzef/aws_demos/config_files/aws_demo_config.h
- vendors/nuvoton/boards/numaker_iot_m487_wifi/aws_demos/config_files/aws_demo_config.h
- vendors/pc/boards/windows/aws_demos/config_files/aws_demo_config.h
- vendors/renesas/boards/rx65n-rsk/aws_demos/config_files/aws_demo_config.h
- vendors/renesas/boards/rx65n-rsk/aws_tests/config_files/aws_demo_config.h
- vendors/st/boards/stm32l475_discovery/aws_demos/config_files/aws_demo_config.h
- vendors/ti/boards/cc3220_launchpad/aws_demos/config_files/aws_demo_config.h
- vendors/xilinx/boards/microzed/aws_demos/config_files/aws_demo_config.h
Make MQTT demo to use default stack size.
MQTT demo has been updated and updates to other components like PKCS may
require the demo to use larger stack size. Specific stack size defined
for MQTT was smaller than the default stack size. This PR removes specific
stack size #define for MQTT so that it will use the default stack size.
Description
-----------
Checklist:
----------
- [ X] My code is Linted.
> fix: Use default stack size for MQTT demo.

- tools/cbmc/proofs/HTTP/IotHttpsClient_AddHeader/IotHttpsClient_AddHeader_harness.c
- tools/cbmc/proofs/HTTP/IotHttpsClient_AddHeader/Makefile.json
- tools/cbmc/proofs/HTTP/IotHttpsClient_Connect/IotHttpsClient_Connect_harness.c
- tools/cbmc/proofs/HTTP/IotHttpsClient_Connect/Makefile.json
- tools/cbmc/proofs/HTTP/IotHttpsClient_Disconnect/IotHttpsClient_Disconnect_harness.c
- tools/cbmc/proofs/HTTP/IotHttpsClient_Disconnect/Makefile.json
- tools/cbmc/proofs/HTTP/IotHttpsClient_ReadContentLength/Makefile.json
- tools/cbmc/proofs/HTTP/IotHttpsClient_ReadHeader/Makefile.json
- tools/cbmc/proofs/HTTP/IotHttpsClient_ReadResponseStatus/Makefile.json
- tools/cbmc/proofs/HTTP/IotHttpsClient_SendSync/HttpsClient_SendSync_harness.c
- tools/cbmc/proofs/HTTP/IotHttpsClient_SendSync/Makefile.json
- tools/cbmc/proofs/HTTP/global_state_HTTP.c
Strengthen HTTP proofs.
Check for all built-in checks that come with cbmc:
--bounds-check
--pointer-check
--div-by-zero-check
--float-overflow-check
--nan-check
--pointer-overflow-check
--undefined-shift-check
--signed-overflow-check
--unsigned-overflow-check
Use --nondet-static to allow uninitialized global variable to start
with arbitrary values.
Clean up test harnesses (move defines from c files to makefiles)
Checklist:
----------
> Http cleanup (depends on 1030)

- vendors/espressif/boards/esp32/CMakeLists.txt
- vendors/espressif/boards/esp32/ports/ble/nimble/iot_ble_hal_gap.c
Fix cmake for OCW
Description
-----------
Fix cmake for OCW: Added nimble port source files as include files in cmake so they get picked up by OCW.
Also fixed 2 warnings for functions stubs
Checklist:
----------
> Fix cmake for OCW  and warnings

- tools/cbmc/patches/patches_constants.py
Description
-----------
This PR adds the path to `portmacro.h` to the directories scanned when computing automatic patches. This is required for some proofs in TaskPool where macros in `portmacro.h` must be redefined (e.g., TaskSwitchContext).
Checklist:
----------
> Add MSVC-MingW folder to patchable paths

- tools/cbmc/patches/compute_patch.py
Description
-----------
This PR adds support for multiline definitions in patch computing. This is required for some proofs in TaskPool where macros must be redefined (e.g., TaskSwitchContext).
Checklist:
----------
> Add support for multiline definitions in patch computing

- libraries/freertos_plus/aws/ota/test/aws_test_ota_agent.c
This change fixes the OTA agent prvParseJSONbyModel_Errors test initialization.
Description
-----------
Checklist:
----------
> Fix: OTA Agent prvParseJSONbyModel_Errors Tests

- vendors/pc/boards/windows/aws_demos/config_files/FreeRTOSConfig.h
This is a two-line modification of a core FreeRTOS include file that makes it easy for us to test all configASSERTs in FreeRTOS (and HTTP) code.
This patch just encloses the definition of configASSERT within #ifndef ... #endif so
it can be redefined from the command line during CBMC proof checking
to invoke __CPROVER_assert to check the assertions with CBMC.
> Escape configASSERT in FreeRTOSConfig.h for CBMC proof checking

- tools/cbmc/proofs/Makefile.template
Description
-----------
This flag enforces that goto-cc compiles all data structures assuming 32 bits.
Checklist:
----------
> Update CFLAGS to always include -m32

- tools/cbmc/proofs/Makefile.template
Description
-----------
The cbmc-viewer --srcexclude arguments in Makefile.common allow to exclude directories in the coverage report. Excluding `./tools` here causes the report to not generate reports for the harness and any other files included in the proof directory. Therefore, this PR avoids excluding `./tools` from report generation.
Checklist:
----------
> Remove `./tools` from cbmc-viewer srcexclude args

- tools/cbmc/proofs/HTTP/IotHttpsClient_AddHeader/IotHttpsClient_AddHeader_harness.c
- tools/cbmc/proofs/HTTP/IotHttpsClient_Connect/IotHttpsClient_Connect_harness.c
- tools/cbmc/proofs/HTTP/IotHttpsClient_Connect/Makefile.json
- tools/cbmc/proofs/HTTP/IotHttpsClient_Disconnect/IotHttpsClient_Disconnect_harness.c
- tools/cbmc/proofs/HTTP/IotHttpsClient_Disconnect/Makefile.json
- tools/cbmc/proofs/HTTP/IotHttpsClient_ReadContentLength/IotHttpsClient_ReadContentLength_harness.c
- tools/cbmc/proofs/HTTP/IotHttpsClient_ReadContentLength/Makefile.json
- tools/cbmc/proofs/HTTP/IotHttpsClient_ReadHeader/IotHttpsClient_ReadHeader_harness.c
- tools/cbmc/proofs/HTTP/IotHttpsClient_ReadHeader/Makefile.json
- tools/cbmc/proofs/HTTP/IotHttpsClient_ReadResponseStatus/IotHttpsClient_ReadResponseStatus_harness.c
- tools/cbmc/proofs/HTTP/IotHttpsClient_ReadResponseStatus/Makefile.json
- tools/cbmc/proofs/HTTP/IotHttpsClient_SendSync/HttpsClient_SendSync_harness.c
- tools/cbmc/proofs/HTTP/IotHttpsClient_SendSync/Makefile.json
- tools/cbmc/proofs/HTTP/global_state_HTTP.c
This is a recreation of PR 1040 that has been closed to produce this PR that should be cleaner to merge into the http branch.  https://github.com/aws/amazon-freertos/pull/1040 
This is a sequence of changes to the HTTP proofs intended to clean up the proofs in general, refactor the constructors in global_state_HTTP.c into allocators that do nothing but malloc memory and is_valid predicates that encode all of the assumptions we are making about the type (eg, that the malloc succeeded and the pointer is valid). This refactoring has the advantage of recording all assumptions explicitly in the test harness itself, but the process of writing the is_valid predicates and testing that each of the remaining conjuncts was necessary led to weakening the assumptions (and thus strengthening the …
> CBMC HTTP proof cleanup (recreation)

- vendors/nxp/boards/lpc54018iotmodule/aws_demos/config_files/aws_demo_config.h
Description
-----------
Shadow, Defender, HTTPS_SYNC demos are stuck on TLS connection. Increasing stack size can fix the problem
Checklist:
----------
> increase stack size of nxp demos

- demos/https/CMakeLists.txt
Add metadata for http demos for OCW
Description
-----------
This change is to add metadata for OCW for http demos
> Add metadata for http demos for OCW

- libraries/c_sdk/standard/https/src/iot_https_client.c
Patch an integer underflow in IotHttpsClient_ReadHeader when called with valueLen=0 and later compare the length readHeaderValueLength with valueLen-1.
> Avoid integer underflow in IotHttpsClient_ReadHeader

- tools/cbmc/proofs/HTTP/IotHttpsClient_Disconnect/IotHttpsClient_Disconnect_harness.c
- tools/cbmc/proofs/HTTP/IotHttpsClient_ReadContentLength/IotHttpsClient_ReadContentLength_harness.c
- tools/cbmc/proofs/HTTP/IotHttpsClient_ReadHeader/IotHttpsClient_ReadHeader_harness.c
- tools/cbmc/proofs/HTTP/global_state_HTTP.c
The only uncovered lines are blocks of code guarded by a test for the
asynchronous case, plus one line in the cleanup code for SendSync.
> Improve CBMC coverage on HTTP synchronous proofs to all but one line.

- vendors/mediatek/boards/mt7697hx-dev-kit/aws_tests/config_files/FreeRTOSConfig.h
- vendors/mediatek/boards/mt7697hx-dev-kit/aws_tests/config_files/iot_config.h
Description
-----------
The default number of Tx/Rx task pairs for ```MQTT_Agent_MultiTaskTest``` is 2
which means that we try to establish two simultaneous connections to the
AWS IoT broker. This results in test failure as we do not have enough
RAM to do two simultaneous TLS handshakes. This change limits the number
of Tx/Rx task pairs to 1 for Mediatek.
This change also sets ```configUSE_MALLOC_FAILED_HOOK``` to 1 which makes memory
failure debugging a lot easier.
Checklist:
----------
> Limit Tx/Rx task pairs to 1 for MQTT_Agent_MultiTaskTest on Mediatek

- libraries/freertos_plus/aws/ota/src/aws_iot_ota_agent.c
- libraries/freertos_plus/aws/ota/src/aws_ota_cbor.c
- libraries/freertos_plus/aws/ota/src/aws_ota_cbor.h
- libraries/freertos_plus/aws/ota/src/aws_ota_cbor_internal.h
- libraries/freertos_plus/aws/ota/test/aws_test_ota_cbor.c
- vendors/cypress/boards/CYW943907AEVAL1F/aws_demos/config_files/aws_ota_agent_config.h
- vendors/cypress/boards/CYW943907AEVAL1F/aws_tests/config_files/aws_ota_agent_config.h
- vendors/cypress/boards/CYW954907AEVAL1F/aws_demos/config_files/aws_ota_agent_config.h
- vendors/cypress/boards/CYW954907AEVAL1F/aws_tests/config_files/aws_ota_agent_config.h
- vendors/espressif/boards/esp32/aws_demos/config_files/aws_ota_agent_config.h
- vendors/espressif/boards/esp32/aws_tests/config_files/aws_ota_agent_config.h
- vendors/infineon/boards/xmc4800_iotkit/aws_demos/config_files/aws_ota_agent_config.h
- vendors/infineon/boards/xmc4800_iotkit/aws_tests/config_files/aws_ota_agent_config.h
- vendors/marvell/boards/mw300_rd/aws_demos/config_files/aws_ota_agent_config.h
- vendors/marvell/boards/mw300_rd/aws_tests/config_files/aws_ota_agent_config.h
- vendors/microchip/boards/curiosity_pic32mzef/aws_demos/config_files/aws_ota_agent_config.h
- vendors/microchip/boards/curiosity_pic32mzef/aws_tests/config_files/aws_ota_agent_config.h
- vendors/nordic/boards/nrf52840-dk/aws_demos/config_files/aws_ota_agent_config.h
- vendors/nordic/boards/nrf52840-dk/aws_tests/config_files/aws_ota_agent_config.h
- vendors/pc/boards/windows/aws_demos/config_files/aws_demo_config.h
- vendors/pc/boards/windows/aws_demos/config_files/aws_ota_agent_config.h
- vendors/pc/boards/windows/aws_tests/config_files/aws_ota_agent_config.h
- vendors/renesas/boards/rx65n-rsk/aws_demos/config_files/aws_ota_agent_config.h
- vendors/renesas/boards/rx65n-rsk/aws_tests/config_files/aws_ota_agent_config.h
- vendors/ti/boards/cc3220_launchpad/aws_demos/config_files/aws_ota_agent_config.h
- vendors/ti/boards/cc3220_launchpad/aws_tests/config_files/aws_ota_agent_config.h
- vendors/vendor/boards/board/aws_demos/config_files/aws_ota_agent_config.h
- vendors/vendor/boards/board/aws_tests/config_files/aws_ota_agent_config.h
Add support in OTA agent for controlling number of data blocks requested from streaming service.
Description
-----------
This change adds support in OTA agent for controlling number of data blocks requested from streaming service. A new parameter representing number of data blocks is added as a config that is sent with every data block request. For example if this parameter is set as 16 then OTA streaming service will send 16 Data Blocks in response.
This change also restarts the timer as soon as the requested number of data blocks are received instead of waiting for the request timer timeout. This helps in speeding up the OTA process by avoiding unnecessary wait for timer to expire.
Checklist:
----------
By submitting this pull request, I confirm that you can use, modify, copy, and …
> Feat: Add support for sending number of blocks with OTA data request.

- libraries/abstractions/platform/freertos/iot_network_freertos.c
Fix IotNetworkAfr_ReceiveUpto() to return the number of bytes recieved.
This has been tested with the HTTPS demo and tests that utilize the network.
Checklist:
----------
> Fix IotNetworkAfr_ReceiveUpto() to return the number of bytes recieved.

- demos/https/CMakeLists.txt
- demos/https/iot_demo_https_s3_download_async.c
- demos/https/iot_demo_https_s3_download_sync.c
Update the configuration metadata to enable the HTTPS Client synchronous download demo
Users can read the HTTPS Client docs and enable the asynchronous download demo.
Update logging in demos to demote which type of demo is currently running.
Checklist:
----------
> Update the configuration metadata to enable the synchronous download demo

- CHANGELOG.md
- doc/lib/https.txt
* Doxygen update for the HTTPS Client library moves the demo usage instructions to their own page. This supports linkage to page and easy finding from AWS Getting Started pages.
* Change Log update introduces the first version of the HTTPS Client library to Amazon FreeRTOS.
* Change log update for Nuvoton NuMaker-IoT-M487 release.
Checklist:
----------
> Change log update for HTTPS Client V1.0.0 and doxygen update.

- doc/config/common
- doc/guidance.md
Fixed broken Doxygen link. Fixed inconsistent custom command.
Description
-----------
Current Doxygen link in guidance.md 403's. An alias was using less arguments than the argument number specified.
Checklist:
----------
> Minor Doxygen Fixes

- demos/https/iot_demo_https_s3_download_async.c
- demos/https/iot_demo_https_s3_download_sync.c
- doc/lib/https.txt
Sometimes the boards experience transient network issues in connection to some servers. This reduces the likely-hood the demo fails for those errors.
A connection is only attempted again if IOT_HTTPS_CONNECTION_ERROR is returned from IotHttpsClient_Connect(). This indicates an error in the network layer. To view logging for network errors update IOT_LOG_LEVEL_NETWORK to IOT_LOG_ERROR in iot_config.h.
Checklist:
----------
> Add connection retries to the HTTPS Client demos.

- libraries/abstractions/platform/freertos/iot_network_freertos.c
Description
-----------
An incorrect error log message would have been printed if bufferSize was 1.
Checklist:
----------
> Fix log message in ReceiveUpto

- vendors/mediatek/boards/mt7697hx-dev-kit/aws_demos/application_code/main.c
- vendors/mediatek/boards/mt7697hx-dev-kit/aws_tests/application_code/main.c
Description
-----------
Each of the Greengrass test calls ```IotSdk_Init``` in the setup and
```IotSdk_Cleanup``` in the teardown. ```IotSdk_Init``` creates the system task pool
which consists of 2 tasks of 2K stack size each. ```IotSdk_Cleanup``` deletes
those tasks by calling ```vTaskDelete```.``` vTaskDelete``` only marks a task for
deletion and the actual deletion happens in the idle task. The test
runner task for Mediatek was running at ```tskIDLE_PRIORITY + 1``` and was not
allowing the Idle task to run between test runs. As a result, the heap
space allocated for system pool tasks' stack and TCB was not getting
freed. This was resulting in memory allocation failures leading to test
failures. This change lowers the priority of the test runner task to
```tskIDLE_PRIORITY``` to ensure …
> Fix Greengrass test and add debugging support

- tools/cmake/afr_module.cmake
- vendors/nordic/boards/nrf52840-dk/CMakeLists.txt
Description
-----------
Nordic does not have WiFi/Ethernet and so the HTTP library should not be
supported for it. This change adds the support for explicitly disabling
AFR public modules in our cmake framework and then explicitly disables
HTTP for Nordic.
Checklist:
----------
> Remove HTTP from the supported libraries for Nordic

- demos/https/iot_demo_https_s3_download_async.c
- demos/https/iot_demo_https_s3_download_sync.c
* Update comments about input demo parameters.
* Async demo was always passing even if there were failures during response callback. This was
updated to check for a file size downloaded successfully at the end of the demo.
* Fix logic to destroy the semaphores if was created.
Tested on Windows Simulator and Espressif ESP32.
Description
-----------
Checklist:
----------
> Fix memory leak in the HTTPS Client Async download demo.

- vendors/microchip/boards/curiosity_pic32mzef/aws_demos/config_files/FreeRTOSIPConfig.h
- vendors/microchip/boards/curiosity_pic32mzef/aws_tests/config_files/FreeRTOSIPConfig.h
Description
-----------
Checklist:
----------
> Fix parenthesis in default define for MCHP FreeRTOS_debug_printf

- vendors/mediatek/boards/mt7697hx-dev-kit/aws_demos/config_files/aws_demo_config.h
Increase Greegrass demo stack size for Mediatek board
Description
-----------
Checklist:
----------
- [] My code is Linted.
> fix: Greengrass demo stack size for Mediatek

- libraries/freertos_plus/standard/freertos_plus_tcp_multi/include/FreeRTOSIPConfigDefaults.h
- libraries/freertos_plus/standard/freertos_plus_tcp_multi/include/FreeRTOS_DNS.h
- libraries/freertos_plus/standard/freertos_plus_tcp_multi/include/FreeRTOS_IP.h
- libraries/freertos_plus/standard/freertos_plus_tcp_multi/include/FreeRTOS_IP_Private.h
- libraries/freertos_plus/standard/freertos_plus_tcp_multi/include/FreeRTOS_Sockets.h
- libraries/freertos_plus/standard/freertos_plus_tcp_multi/source/FreeRTOS_ARP.c
- libraries/freertos_plus/standard/freertos_plus_tcp_multi/source/FreeRTOS_DNS.c
- libraries/freertos_plus/standard/freertos_plus_tcp_multi/source/FreeRTOS_IP.c
- libraries/freertos_plus/standard/freertos_plus_tcp_multi/source/FreeRTOS_ND.c
- libraries/freertos_plus/standard/freertos_plus_tcp_multi/source/FreeRTOS_Routing.c
- libraries/freertos_plus/standard/freertos_plus_tcp_multi/source/FreeRTOS_Sockets.c
- libraries/freertos_plus/standard/freertos_plus_tcp_multi/source/FreeRTOS_TCP_IP.c
- libraries/freertos_plus/standard/freertos_plus_tcp_multi/source/checksum.ipv6.c
- libraries/freertos_plus/standard/freertos_plus_tcp_multi/source/portable/NetworkInterface/STM32Fxx/NetworkInterface.c
- libraries/freertos_plus/standard/freertos_plus_tcp_multi/source/protocols/FTP/FreeRTOS_FTP_server.c
August 20, adapted and tested FreeRTOS_DNS to use IPv6
Description
-----------
FreeRTOS_DNS.c :
Applied PC-LINT.
Checked the asynchronous lookup ( `FreeRTOS_getaddrinfo_a()`, `FreeRTOS_gethostbyname_a()` ) with both IPv4/v6.
The declaration of the application-hook had to change:
~~~c
#if( ipconfigUSE_IPv6 != 0 )
typedef void (* FOnDNSEvent ) ( const char * /* pcName */, void * /* pvSearchID */, struct freertos_sockaddr6 * /* pxAddress6 */ );
#else
typedef void (* FOnDNSEvent ) ( const char * /* pcName */, void * /* pvSearchID */, uint32_t /* ulIPAddress */ );
#endif
~~~
Further developed and tested the new `FreeRTOS_getaddrinfo()` functions.
FreeRTOS_Socket.c
Applied PC-LINT.
Added socket options for low- and high water. Merged from the existing IPv4-only release.
Merged …
> August 20, adapted and tested FreeRTOS_DNS to use IPv6

- vendors/mediatek/boards/mt7697hx-dev-kit/ports/wifi/iot_wifi.c
- vendors/mediatek/sdk/middleware/MTK/dhcpd/src/dhcpd.c
Description
-----------
Mediatek DHCP code creates a DCHP task in ```dhcpd_start``` function which
creates a LWIP socket and listens on it. ```dhcpd_stop``` function deletes
the DHCP task and then closes the socket. When the socket is closed,
LWIP makes sure that if any task is waiting for the data to be received
on the socket, it gets unblocked. The following piece of code from LWIP
does that:
```c
while( xTask != NULL )
{
xTaskAbortDelay( xTask );
taskYIELD();
xTask = pxMailBox->xTask;
}
```
```dhcpd_stop``` function first deletes the DHCP task and then closes the
LWIP socket. This creates a race condition –
- DHCP task calls ```recv_from``` on the socket and gets blocked waiting for
the data on the socket.
- User task (test runner in our case) calls ```dhcpd_stop``` which deletes
the …
> Fix WiFi test failures/hangs for Mediatek

- vendors/nordic/boards/nrf52840-dk/aws_demos/application_code/main.c
The build combination tests for the "Amazon FreeRTOS Device Software" configuration page in AWS IoT Core were improved. When the user to selects just the BLE library from the Nordic NRF52840 DK, then MQTT library and all of it's source and header files are stripped away. 
This header in main.c is deleted so that the build will pass for the scenario mentioned and also because it is unused anyways in the file. 
I have built the package downloaded from "Amazon FreeRTOS Device Software" for Nordic with only the BLE library selected. I have built this amazon-freertos source with the change.
Checklist:
----------
> Delete unused include of MQTT headers in Nordic's main.c

- libraries/freertos_plus/aws/ota/src/aws_iot_ota_agent.c
Fix Bug in OTA
Description
-----------
Since we are using QOS1, the broker can potentially send a job message while it is performing a stream.
In that case the stream get's interrupted and OTA fails.
This fix will discard job message while OTA is performing streaming operations.
Checklist:
----------
> Fix Bug in OTA

- libraries/abstractions/ble_hal/test/include/iot_test_ble_hal_afqp.h
- libraries/abstractions/ble_hal/test/include/iot_test_ble_hal_common.h
- libraries/abstractions/ble_hal/test/include/iot_test_ble_hal_integration.h
- libraries/abstractions/ble_hal/test/include/iot_test_ble_hal_kpi.h
- libraries/abstractions/ble_hal/test/include/iot_test_ble_hal_stress_test.h
- libraries/abstractions/ble_hal/test/src/iot_test_ble_hal_afqp.c
- libraries/abstractions/ble_hal/test/src/iot_test_ble_hal_integration.c
- libraries/abstractions/ble_hal/test/src/iot_test_ble_hal_kpi.c
- libraries/abstractions/ble_hal/test/src/iot_test_ble_hal_stress_test.c
- tests/bleTestsScripts/startTests_integration.py
- tests/bleTestsScripts/startTests_kpi.py
- tests/bleTestsScripts/startTests_stress.py
- tests/bleTestsScripts/testClass.py
New integration test, stress test and KPI test
Description
-----------
-Add stress tests
-init/deinit
-enable/disable
-restart service
-reconnect
-Add KPI tests
-between scan begin and advertisement received
-between scan begin and connection created
-Add integration tests
-Crash if calling pxEnable twice (MTK)
-Callback timeout
-Advertisement issue with NULL properties
-Hal API(pxEnable) doesn't implemented as expected
-Wrong Adv Interval
-Callback timeout
-MTK stack doesn't check data size
you can refer to this link for more details:
https://wiki.labcollab.net/confluence/pages/viewpage.action?pageId=629941320
Issues: On Nordic pxBleAdapterInit() fails when BLE stack enable more than once.
Checklist:
----------
- [x ] My …
> New integration test, stress test and KPI test in Iot Tester

- libraries/freertos_plus/standard/freertos_plus_tcp_multi/include/FreeRTOSIPConfigDefaults.h
- libraries/freertos_plus/standard/freertos_plus_tcp_multi/include/FreeRTOS_IP_Private.h
- libraries/freertos_plus/standard/freertos_plus_tcp_multi/include/FreeRTOS_ND.h
- libraries/freertos_plus/standard/freertos_plus_tcp_multi/include/FreeRTOS_Routing.h
- libraries/freertos_plus/standard/freertos_plus_tcp_multi/include/FreeRTOS_errno_TCP.h
- libraries/freertos_plus/standard/freertos_plus_tcp_multi/include/IPTraceMacroDefaults.h
- libraries/freertos_plus/standard/freertos_plus_tcp_multi/source/FreeRTOS_DHCP.c
- libraries/freertos_plus/standard/freertos_plus_tcp_multi/source/FreeRTOS_IP.c
- libraries/freertos_plus/standard/freertos_plus_tcp_multi/source/FreeRTOS_ND.c
- libraries/freertos_plus/standard/freertos_plus_tcp_multi/source/FreeRTOS_Routing.c
- libraries/freertos_plus/standard/freertos_plus_tcp_multi/source/FreeRTOS_TCP_IP.c
- libraries/freertos_plus/standard/freertos_plus_tcp_multi/source/FreeRTOS_UDP_IP.c
Description
-----------
Until now, IPv6 end-points had to be configured statically.
This PR makes it possible to solicit for a Router Advertisement, which may provide the following parameters:
- Network prefix
- Prefix length
- Address of a IPv6 gateway
When these parameters are known, the device will choose a **random IP-address that uses the prefix and prefix-length**.
It will be tested if the IP-address already exists by issuing a few neighbour solicitations, and wait for replies.
When no other device replies, the address will be taken and the end-point will go UP. When there are replies, a new one will be chosen, and the procedure is repeated.
These are the default configuration macro's that control the entire process:
~~~c
/* Ask for a Router Advertisement at most 3 times. */
#define …
> August 28, Added Router Advertisement/SLAAC

- freertos_kernel/portable/Renesas/RX100/port.c
Description
-----------
Checklist:
----------
> Add missing _VECT to #pragma interrupt  in RX100/port.c

- demos/defender/aws_iot_demo_defender.c
- demos/greengrass_connectivity/aws_greengrass_discovery_demo.c
Description
-----------
All the demos run in the task named ```runDemoTask``` which is created using
```Iot_CreateDetachedThread```. The use of this API requires that the task
must not call ```vTaskDelete``` to delete itself which will result in a memory leak. Also, the
demo status string and the demo end marker string which are printed in
the ```runDemoTask``` function will not get printed if the ```runDemoTask``` is
deleted pre-maturely by calling ```vTaskDelete```. This change removes the
```vTaskDelete``` calls from greengrass and defender demos to ensure that the
```runDemoTask``` is not deleted pre-maturely.
Also, the defender demo was not propagating the errors from APIs which
could result in a false success code from the defender demo. This change
fixes the demo to propagate the …
> Remove vTaskDelete calls from demos

- tools/cmake/afr_module.cmake
- vendors/nordic/boards/nrf52840-dk/CMakeLists.txt
Description
-----------
AFR public modules are the modules which are selectable by the user in
the FreeRTOS console (OCW). We need to disable some public modules for
some hardware platforms - for example, the Nordic board cannot support
HTTPS library because it does not have WiFi/Ethernet. We added a
function, namely ```afr_disable_public_modules```, to disable public modules
for a hardware platform. Later we realized that this function is not
needed and a module (regardless of whether it is public or not) can be
disabled by just calling ```set(AFR_MODULE_<module> 0 CACHE INTERNAL "")``` in
the board's CMakeLists.txt.
This change removes the function ```afr_disable_public_modules``` and instead
uses ```set(AFR_MODULE_https 0 CACHE INTERNAL "")``` to disable HTTPS module
for the Nordic …
> Simplify disabling public modules for a hardware platform

- tools/certificate_configuration/PEMfileToCString.html
This matches the format now expected by aws_clientcredential_keys.h
Description
-----------
Checklist:
----------
> Update PEMfileToCString.html to add \ line joiners and remove semicolon

- libraries/c_sdk/standard/https/src/iot_https_client.c
Fix an integer overflow in pointer arithmetic.
> Fix integer overflow in HTTP _addHeaders buffer offset calculations.

- tools/cbmc/proofs/HTTP/IotHttpsClient_AddHeader/IotHttpsClient_AddHeader_harness.c
- tools/cbmc/proofs/HTTP/IotHttpsClient_AddHeader/Makefile.json
- tools/cbmc/proofs/HTTP/IotHttpsClient_Connect/Makefile.json
- tools/cbmc/proofs/HTTP/IotHttpsClient_Disconnect/Makefile.json
- tools/cbmc/proofs/HTTP/IotHttpsClient_ReadContentLength/Makefile.json
- tools/cbmc/proofs/HTTP/IotHttpsClient_ReadHeader/Makefile.json
- tools/cbmc/proofs/HTTP/IotHttpsClient_ReadResponseStatus/Makefile.json
- tools/cbmc/proofs/HTTP/IotHttpsClient_SendSync/Makefile.json
- tools/cbmc/proofs/HTTP/global_state_HTTP.c
Fix integer overflow in CBMC proofs caused by choosing buffer lengths longer than the 
maximum object size allowed by CBMC.
In CBMC, a pointer is an object id followed by an offset into the object.  The number of bits of the pointer used for the object id limits the number of bits remaining for the offset, and hence limits the size of the object.  If the top 7 bits are used for the object id, then offsets into the object must fit into the bottom 32-7 bits.
> Fix integer overflow in CBMC proofs caused by long buffer lengths.

- tools/cbmc/patches/compute_patch.py
This pull request causes CBMC to skip the generation of patch files that would be zero-length patch files.
The patch command complains when it is invoked with a zero-length patch file.
CBMC proofs check the memory safety of some functions in multiple build configurations.  CBMC does this by patching header files to make it easy to configure a build from the command line with build invocations of the form "make -Dconfigvar1=val1 -Dconfigvar2=var2".  CBMC generates the patch files, then applies the patch files, then builds the desired configurations.  This pull request suppresses complaints by patch during the patch file application.
This pull request has been tested by running the CBMC proofs.
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this …
> Stop CBMC patch generation from generating 0-length patches.

- demos/demo_runner/iot_demo_freertos.c
Description
-----------
The test framework flashes the binary to a board and then opens the
serial  port for reading output. The code on the MCU starts running
after it is flashed and as a result it is possible that the test
framework may not see the ```DEMO STARTING``` tag. To address this, this
change adds delay before starting the demo and this delay is only added
if ```INSERT_DELAY_BEFORE_DEMO``` is defined - This ensures that no one else
sees this delay.
Checklist:
----------
> Add delay before starting a demo

- libraries/abstractions/pkcs11/mbedtls/iot_pkcs11_mbedtls.c
- libraries/abstractions/pkcs11/test/iot_test_pkcs11.c
- libraries/freertos_plus/standard/pkcs11/include/iot_pkcs11.h
- tests/common/aws_test_runner.c
This is an example of the additional test output log lines:
4 6729 [TestRunner] The PKCS #11 module supports RSA signing.
5 6729 [TestRunner] The PKCS #11 module supports ECDSA.
6 6729 [TestRunner] The PKCS #11 module supports elliptic-curve key generation.
TEST(Full_PKCS11_Capabilities, AFQP_Capabilities) PASS
> Implement and test PKCS#11 C_GetMechanismInfo

- libraries/c_sdk/standard/https/include/iot_https_client.h
Description
-----------
All doxygen commands must use @ and not backslash.
Checklist:
----------
> Changed the meager occurences of \code to @code in HTTP Client lib doxygen docs.

- vendors/espressif/boards/esp32/ports/ble/nimble/iot_ble_hal_common_gap.c
- vendors/espressif/esp-idf/components/nimble/nimble/nimble/host/include/host/ble_gap.h
- vendors/espressif/esp-idf/components/nimble/nimble/nimble/host/src/ble_gap.c
- vendors/espressif/esp-idf/components/nimble/nimble/nimble/host/src/ble_sm.c
- Additional check added to confirm the `max_enc_key_size` in pairing request is not less than 16
Bytes in case of secure connection only mode.
Description
-----------
1. Modifies `iot_ble_hal_common_gap.c` to reject pairing request if the max encryption key size is less than 16 Bytes with reason `BLE_SM_ERR_ENC_KEY_SZ`.
2. Adds `max_enc_key_size` to structure `ble_gap_pairing_req`, so that can be used while handling GAP pairing request event.
Checklist:
----------
> AFR NimBLE: Fix pairing request GAP event handling for SC only mode

- doc/lib/https.txt
- libraries/c_sdk/standard/https/include/iot_https_client.h
- libraries/c_sdk/standard/https/src/iot_https_client.c
- libraries/c_sdk/standard/https/test/system/iot_tests_https_system.c
The application provides a header buffer and and a body buffer for a response.
The steps internal to the library for receiving a response are:
1. Set the **bufferProcessingState** to PROCESSING_STATE_FILLING_HEADER_BUFFER
1. Fill the header buffer with network data.
1. Parse the header buffer (increments points denoting end of HTTP headers)
1. Set the bufferProcessingState to PROCESSING_STATE_FILLING_BODY_BUFFER
1. Fill the body buffer with network data.
1. Parse the body buffer (increments pointers denoting start and end of HTTP body)
1. Set the bufferProcessingState to PROCESSING_STATE_FINISHED
1. Fill the flush buffer with network data.
1. Parse the flush buffer (since bufferProcessingState == PROCESSING_STATE_FINISHED, no pointers updated only the state of the parser inside of the …
> Fixed to ALWAYS stop parsing for a head request in the HTTPS Client library.

- libraries/abstractions/common_io/test/test_iot_uart.c
Added Test Protects to UART test code to fix cascading failures.
Description
-----------
Added Test Protects to UART test code to fix cascading failures.
Checklist:
----------
> Added Test Protects to UART test code to fix cascading failures.

- libraries/freertos_plus/standard/tls/test/iot_test_tls.c
There are currently two calls to the same test case: connecting to a test server with supplied elliptic-curve client credentials. This change preserves one of the calls, in order to balance code coverage with test suite execution time.
> Remove redundant elliptic-curve TLS test execution.

- libraries/abstractions/secure_sockets/test/iot_test_tcp.c
The same-socket/different-tasks TCP group test executes the same four variations in a loop four times consecutively. The architecture of the test is such that the sending and receiving threads are synchronized at the end of each loop. On some embedded boards with Wi-Fi connectivity, a single iteration can take several minutes to complete. A reasonable compromise would seem to be to run each variation once.
> Remove redundant loops from the same-socket/different-tasks test.

- demos/https/iot_demo_https_s3_download_async.c
- demos/https/iot_demo_https_s3_download_sync.c
- demos/https/iot_demo_https_s3_upload_async.c
- demos/https/iot_demo_https_s3_upload_sync.c
- libraries/c_sdk/standard/https/include/types/iot_https_types.h
- libraries/c_sdk/standard/https/src/iot_https_client.c
A post commit to master code review finds the "p" missing from char arrays and char pointer variables, in the HTTPS Client synchronous and asynchronous download demos.
This PR also elaborates on the difference between the path in IotHttpsRequest_t and returned from IotHttpsClient_GetUrlPath().
IotHttpsClient_GetUrlPath() returns the path length without a query.
The path with a query is defined to be the \"abs_path\" according to the HTTP/1.1 RFC and this is the path needed in IotHttpsRequest_t. This path is the one in the Request-Line.
Checklist:
----------
> Fix coding style for HTTPS Client Sync and Async demos

- libraries/abstractions/platform/test/iot_test_platform_threads.c
- libraries/c_sdk/standard/ble/test/iot_ble_wifi_prov_test_access_declare.h
- libraries/c_sdk/standard/ble/test/iot_test_ble_end_to_end.c
- libraries/c_sdk/standard/ble/test/iot_test_wifi_provisioning.c
- libraries/freertos_plus/aws/ota/test/aws_test_ota_agent.c
- tests/common/iot_tests_network.c
Fix BLE testcase setup and teardown
Description
-----------
Miscellaneous fixes for testcases encountered during testing with ESP-IDF FreeRTOS. Check return values, initialize BLE as needed, and use some older APIs during assertions.
Checklist:
----------
- [ X] I have tested my changes. No regression in existing tests.
- [ X] My code is Linted.
> Fix BLE testcase setup and teardown

- libraries/abstractions/common_io/test/test_iot_i2c.c
Description
-----------
Improve I2C behavior by following the I2C design wiki:
- call ioctl to get bytes of RX or TX
- handle global handle in test setup
- make multiple read/write call instead of one
- new test for get bus state and combined transaction
- no cascade test failure to following tests
Checklist:
----------
> Add more I2C test cases and verification

- vendors/espressif/boards/esp32/ports/ble/nimble/iot_ble_hal_gatt_server.c
NimBLE AFR: Fix Notification/Indication tx handling
Description
-----------
The handling of notifications/indications is done in BLE_GAP_EVENT_NOTIFY_TX where the appropriate status is returned. So, it is not required in prvBTSendIndication
Checklist:
----------
> NimBLE AFR: Fix Notification/Indication tx handling

- doc/config/https
- doc/config/main
- doc/guidance.md
- doc/tag/README.md
Sometime in the past few weeks, the doxygen configurations were updated to not use the doc/tag folder and https was neglected in the update. 
This update fixes the HTTPS Client doxygen documentation to generated appropriately with the rest of libraries.
Checklist:
----------
> Fix the HTTPS Client doxygen configuration.

- libraries/abstractions/secure_sockets/test/iot_test_tcp.c
Mistake in TCP tests calling
TEST_ASSERT_LESS_THAN_UINT32( 0, xResult ) where negative
number is interpreted as positive.
Update in unity fixed a bug that caused this to go unnoticed
previously :)
Description
-----------
Checklist:
----------
> Fix comparison of 0 > UINT macro use in TCP tests

- vendors/espressif/boards/esp32/ports/ble/bluedroid/iot_ble_hal_gap.c
- vendors/espressif/esp-idf/components/bt/bluedroid/api/include/api/esp_gap_ble_api.h
- vendors/espressif/esp-idf/components/bt/bluedroid/bta/dm/bta_dm_co.c
- vendors/espressif/esp-idf/components/bt/bluedroid/bta/include/bta/bta_dm_co.h
- vendors/espressif/esp-idf/components/bt/bluedroid/btc/profile/std/gap/btc_gap_ble.c
- vendors/espressif/esp-idf/components/bt/bluedroid/common/include/common/bte_appl.h
- vendors/espressif/esp-idf/components/bt/bluedroid/stack/smp/smp_utils.c
- Helps in fixing `Key Negotiations issue` by which Encryption Key size could be brought
down to 7 Bytes from 16 Bytes in `Secure Connection only` mode as well.
Description
-----------
- Modifies `esp_ble_gap_set_security_param` API to set Minimum Encryption Key size requirement.
- Modifies `iot_ble_hal_gap.c`, to set `ESP_BLE_SM_MIN_KEY_SIZE` to 16 Bytes.
- Additional check in `smp_utils.c` to reject pairing request in case peer device's key size is less than `ble_min_key_size` requirement set by application.
- Helps in mitigating `Key Negotiation attack`, by which the peer device can bring down `Encryption key size` to 7 Bytes from 16 Bytes in `secure connections`.
Checklist:
----------
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this …
> AFR Bluedroid: Add support to set minimum Encryption key size requirement

- tools/cbmc/proofs/HTTP/IotHttpsClient_AddHeader/Makefile.json
- tools/cbmc/proofs/HTTP/IotHttpsClient_Connect/Makefile.json
- tools/cbmc/proofs/HTTP/IotHttpsClient_Disconnect/Makefile.json
- tools/cbmc/proofs/HTTP/IotHttpsClient_ReadContentLength/Makefile.json
- tools/cbmc/proofs/HTTP/IotHttpsClient_ReadHeader/Makefile.json
- tools/cbmc/proofs/HTTP/IotHttpsClient_ReadResponseStatus/Makefile.json
- tools/cbmc/proofs/HTTP/IotHttpsClient_SendSync/Makefile.json
- tools/cbmc/proofs/HTTP/global_state_HTTP.c
This pull request removes buffer length assumptions from HTTP proofs.  
This pull request changes a lot of files.  It is easier to read one commit at a time.
The key insight to removing buffer length assumptions is that the code accesses all buffers via pointers in the message headers, the code does not depend on the fact that buffers follow the message headers in memory (there is no pointer arithmetic to access the start of the buffers).
This also repairs the CBMC proof of HTTP AddHeaders method until there is a fix to https://github.com/diffblue/cbmc/issues/5096.
> Remove all buffer length assumptions from HTTP proofs.

- freertos_kernel/include/atomic.h
Description
-----------
```include/atomic.h``` provides a generic implementation. Compiler/architecture dependent implementation of atomic.h is to be provided under each port directory.
Once this PR is merged into GitHub, ```include/atomic.h``` will be copied over to SVN. 
Checklist:
----------
> Removing compiler/architecture specific implementation.  

- demos/tcp/aws_tcp_echo_client_single_task.c
aws_tcp_echo_client_single_task.c : a time-out is not fatal (second version)
Description
-----------
The earlier PR #354 had too many conflicts, this one will replace it.
When the reception of data times out, and at least 1 byte has been received, an ASSERT will be thrown because the contents does not match.
When the number of bytes received is less than expected, it would be nicer to just consider this as a failure. The link may have failed, the remote party is too slow, etc.
Only when the expected number of bytes was received, but the received string does not match, this should be a fatal error ( calling configASSERT() ).
Also I replaced a few tabs with spaces, to make it confirm Crustify.cfg.
Checklist:
----------
By submitting this pull request, I confirm that you can use, modify, …
> aws_tcp_echo_client_single_task.c : a time-out is not fatal (second version)

- libraries/c_sdk/standard/https/src/iot_https_client.c
Preface HTTPS clean up code in _networkReceiveCallback to disconnect
and simply return in the event that an out-of-order response was
received with no matching request.
This issue was discovered by Nathan Chong while writing a CBMC proof.
> Disconnect and return in the event of an out-of-order HTTP response.

- vendors/nordic/boards/nrf52840-dk/CMakeLists.txt
Description
-----------
```portable/GCC/nrf52840-dk/``` was moved to ```portable/ThirdParty/GCC/nrf52840-dk/```. This is a followup PR for https://github.com/aws/amazon-freertos/pull/1260. 
Checklist:
----------
> Updating CMake for nordic port. 

- libraries/abstractions/common_io/include/iot_power.h
Add power ioctl support to overwrite rtc wakeup time set in power imp…lementation
The reason is we want to add feature if a product want to sleep for a longer period in some idle case
This will be a onetime overwrite
Description
-----------
Checklist:
----------
> Add power ioctl support to overwrite rtc wakeup time set in power implementation

- tools/cmake/toolchains/arm-segger.cmake
- vendors/nordic/boards/nrf52840-dk/CMakeLists.txt
- vendors/nordic/boards/nrf52840-dk/flash_placement.xml
Make Cmake for Nordic working.
Description
-----------
Following changes are done:
* Include all Nordic SDK files
* Override the default compiler and assembler commands to have SES specific compiling and assembler steps.
* Fixes compiler/linker path and options in CMakefile
* Include compiler specific libc libraries under linker libraries.
Checklist:
----------
> Fix: CMake for Nordic

- libraries/freertos_plus/standard/tls/include/iot_tls.h
- libraries/freertos_plus/standard/tls/src/iot_tls.c
Add error codes for missing client credentials.
https://amazon-freertos-ci.corp.amazon.com/job/master/job/custom/job/pc/job/windows-ide/10/
Checklist:
----------
> Fix iot_tls.c - check for errors before retrieving P11 objects

- libraries/freertos_plus/standard/tls/test/iot_test_tls.c
This change improves TLS test group compatibility with secure element-equipped boards by respecting capability configuration settings for key import, ECDSA, and RSA.
> Make TLS test group aware of key import and type capabilities.

- vendors/renesas/boards/rx65n-rsk/ports/pkcs11/iot_pkcs11_pal.c
Happy-path prints are overwhelming the print queue and causing occasional
failure to print test results.  Modifying happy-path print statements to
be controlled through a debug print statement so that they may be turned
off for testing.  Disabling this print by default.
Tests w/ debug printf enabled: https://amazon-freertos-ci.corp.amazon.com/job/master/job/custom/job/renesas/job/rx65n-rsk-ide/6/
Tests w/ debug printf commented out: https://amazon-freertos-ci.corp.amazon.com/job/master/job/custom/job/renesas/job/rx65n-rsk-ide/10/console
Resolves TS-9109
Checklist:
----------
> Exchange happy-path prints with a debug print in Renesas PKCS PAL

- libraries/abstractions/platform/freertos/iot_network_freertos.c
- The network interface send() function only gives feedback about the bytes sent.
- This gives debugging feeback about the network layer error returned.
- The function plugged into receive() gives this feedback.
Checklist:
----------
- [ n/a ] My code is Linted.
> Update IotNetworkAfr_Send() to give error feedback.

- projects/infineon/xmc4800_plus_optiga_trust_x/dave4/aws_demos/.cproject
- projects/infineon/xmc4800_plus_optiga_trust_x/dave4/aws_demos/.project
- projects/infineon/xmc4800_plus_optiga_trust_x/dave4/aws_tests/.cproject
- projects/infineon/xmc4800_plus_optiga_trust_x/dave4/aws_tests/.project
The purpose of this change is to update the aws_demos and aws_tests projects for the OPTIGA Trust X board to handle the recent 3rd http_parser folder name change.
> Update 3rd party libaries path for http_parser folder name change.

- vendors/infineon/secure_elements/optiga_trust_x/optiga/dtls/AlertProtocol.c
- vendors/infineon/secure_elements/optiga_trust_x/optiga/dtls/DtlsHandshakeProtocol.c
- vendors/infineon/secure_elements/optiga_trust_x/optiga/dtls/OCPConfig.c
This change fixes Linux cmake builds for the Infineon OPTIGA Trust X board.
> Build fix for the OPTIGA Trust X board for Linux cmake

- libraries/abstractions/common_io/include/iot_i2c.h
Description
-----------
clarify unsupported functions in i2c
Checklist:
----------
> clarify unsupported functions in i2c

- CMakeLists.txt
- libraries/abstractions/ble_hal/CMakeLists.txt
- tools/cmake/afr.cmake
- vendors/espressif/boards/esp32/CMakeLists.txt
- vendors/marvell/boards/mw300_rd/CMakeLists.txt
- vendors/microchip/boards/curiosity_pic32mzef/CMakeLists.txt
- vendors/nxp/boards/lpc54018iotmodule/CMakeLists.txt
- vendors/ti/boards/cc3220_launchpad/CMakeLists.txt
Description
-----------
This PR addresses issues in #832 and #1131,
- Use `include` for vendor CMake file instead of `add_subdirectory`.
- BLE hal layer is now defined as static library.
Some use cases require vendor to set some custom settings at source file level. Specifically in issue #1131, some source files in BLE hal porting layer needs to be treated as header files. However, CMake does not support passing these settings outside of current directory scope. `add_subdirectory` will create a new scope which makes this impossible. So we need to use `include` which do not create a new scope.
Test results are pending at this moment.
Checklist:
----------
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your …
> Fix cmake scope issue for source file properties

- libraries/abstractions/ble_hal/test/src/iot_test_ble_hal_afqp.c
- tests/bleTestsScripts/startTests_kpi.py
- tests/bleTestsScripts/startTests_stress.py
- tests/bleTestsScripts/testClass.py
BLE_HAL testing removing unnecessary Cb's
Description
-----------
Removing BondedCb and in the Reconnect Test case, remove status change
Removed trailing white spaces from python scripts
Checklist:
----------
> BLE_HAL testing removing unnecessary Cb Testing's

- vendors/infineon/boards/xmc4800_iotkit/CMakeLists.txt
- vendors/infineon/boards/xmc4800_plus_optiga_trust_x/CMakeLists.txt
Infineon has requested updates to the display string metadata of its two Amazon FreeRTOS qualified boards.
> Update board metadata per silicon partner request.

- libraries/c_sdk/standard/ble/src/services/wifi_provisioning/iot_ble_wifi_provisioning.c
Description
-----------
Fix for issue #1277 
list_network never sends a response if the wifi scan completes successfully but finds 0 APs.
This change checks how many networks were found and at least returns a status response, so the mobile app (or, more generally, BLE Central) can handle the situation instead of hanging.
Checklist:
----------
> iot_ble_wifi_provisioning: list_networks sends a response even if no wifi APs are found

- tools/cbmc/include/cbmc.h
Description
-----------
Added pvPortMalloc, pvFree functions stubs to CBMC header, these will be used across several proofs in the future. Added macro that asserts if zero-allocation is allowed.
Checklist:
----------
> Add common stubs to CBMC header

- tools/cbmc/patches/0005-Remove-volatile-qualifier-from-tasks-variables.patch
Description
-----------
The proposed patch removes the volatile qualifier from a few static global variables declared in the tasks.c file. This patch will be necessary for the majority of the incoming task pool management proofs.
> Add CBMC patch to remove volatile qualifier from some variables

- CHANGELOG.md
The purpose of the SoftHSMv2 port is to allow ad hoc interoperability testing with an independent implementation of the PKCS #11 standard.
> Add SoftHSMv2 port for PKCS #11 to the change log.

- libraries/freertos_plus/standard/tls/test/iot_test_tls.c
It's defined for all ports, but some ports define to 0.
Fix for EC and BYOCCredential test stability.
Test run: https://amazon-freertos-ci.corp.amazon.com/job/master/job/custom_ide/130/
Checklist:
----------
> Fix TLS tests to check for EC support defined to 1

- libraries/freertos_plus/standard/tls/test/iot_test_tls.c
It's defined for all ports, but some ports define to 0.
Resolves TS-9313
Cherry picks PR #1329 which was already merged to master.
Description
-----------
Checklist:
----------
> Fix TLS tests to check for EC support defined to 1 (#1329)

- tools/cbmc/proofs/prepare.py
This patch modifies the prepare.py script used to prepare the source tree for CBMC proofs.  The script now applies the normal patch files, and then modifies header files in place so that CBMC proofs can modify defines in the header files from the build command line.  CBMC does this, among other reasons, to test various build configurations.
> Modify prepare.py to apply patch files and modify headers in place.

- tools/cbmc/proofs/IP/SendEventToIPTask/Makefile.json
- tools/cbmc/proofs/IP/SendEventToIPTask/README.md
- tools/cbmc/proofs/IP/SendEventToIPTask/SendEventToIPTask_harness.c
Add CBMC memory safety proof for SendEventToIPTask originally written by Adrian Palacios and now rebased against the current master branch.
I have verified that the proofs work against the current master.
> Add IP memory safety proofs

- tools/cbmc/proofs/DHCP/DHCPProcess/DHCPProcess_harness.c
- tools/cbmc/proofs/DHCP/DHCPProcess/Makefile.json
- tools/cbmc/proofs/DHCP/DHCPProcess/README.md
- tools/cbmc/proofs/DHCP/IsDHCPSocket/IsDHCPSocket_harness.c
- tools/cbmc/proofs/DHCP/IsDHCPSocket/Makefile.json
- tools/cbmc/proofs/DHCP/IsDHCPSocket/README.md
Add DHCP memory safety proofs originally written by Adrian Palacios and now rebased against the current master branch.
Review this request one commit at a time. This pull request changes a lot of files, but each commit introduces a single proof at a time. I have verified that the proofs work against the current master.
> Add DHCP memory safety proofs

- tools/cbmc/proofs/TCP/prvTCPHandleState/Makefile.json
- tools/cbmc/proofs/TCP/prvTCPHandleState/README.md
- tools/cbmc/proofs/TCP/prvTCPHandleState/TCPHandleState_harness.c
- tools/cbmc/proofs/TCP/prvTCPPrepareSend/Makefile.json
- tools/cbmc/proofs/TCP/prvTCPPrepareSend/README.md
- tools/cbmc/proofs/TCP/prvTCPPrepareSend/TCPPrepareSend_harness.c
- tools/cbmc/proofs/TCP/prvTCPReturnPacket/Makefile.json
- tools/cbmc/proofs/TCP/prvTCPReturnPacket/README.md
- tools/cbmc/proofs/TCP/prvTCPReturnPacket/TCPReturnPacket_harness.c
- tools/cbmc/proofs/utility/memory_assignments.c
Add TCP memory safety proofs originally written by Debasmita Lohar and now rebased against the current master branch.  
Review this request one commit at a time.  This pull request changes a lot of files, but each commit introduces a single proof at a time.   I have verified that the proofs work against the current master.
> Add TCP memory safety proofs

- tools/cbmc/proofs/ProcessDHCPReplies/Makefile.json
The Makefile.json was building DNS and not DHCP, so ProcessDHCPReplies
was not being tested.  This error was probably introduced during the
transition to the Makefile.json build flow.
> Fix CBMC memory safety proof for ProcessDHCPReplies.

- tools/cbmc/proofs/make_type_header_files.py
Make CBMC script make_type_header_files.py run under Python 3.5
The script is used to prepare the source tree for CBMC proofs of the
queue API.  The script was written using the text keyword argument to
subprocess.run which was added in Python 3.7 "as a more understandable
alias of universal_newlines."  CBMC CI uses Python 3.5.  This patch just uses 
the original keyword argument.
>  Make CBMC script make_type_header_files.py run under Python 3.5

- libraries/abstractions/common_io/include/iot_battery.h
- libraries/abstractions/common_io/include/iot_hw.h
iot_battery_temp() API needs to return signed, not unsigned value
Why:  Most of this is documentation changes, but there is one API
change.  While reviewing the API's, I found that iot_battery_temp()
was originally returning an unsigned value.  This needs to be
signed since temperatures can be below 0.
Checklist:
----------
> fix: iot_battery_temp() needs to return signed value

- vendors/espressif/boards/esp32/aws_demos/application_code/espressif_code/amazon-freertos-common/component.mk
- vendors/espressif/boards/esp32/aws_tests/application_code/espressif_code/amazon-freertos-tests/component.mk
Description
-----------
Fix http_parser link in esp32 project file. #1263 
https://amazon-freertos-ci.corp.amazon.com/job/master/job/custom/job/espressif/job/esp32_devkitc-ide/45/console
Checklist:
----------
> Fixed esp32 project link to http_parser

- demos/defender/aws_iot_demo_defender.c
- demos/include/iot_demo_runner.h
- libraries/c_sdk/aws/defender/include/aws_iot_defender.h
- libraries/c_sdk/aws/defender/src/aws_iot_defender_api.c
- libraries/c_sdk/aws/defender/src/aws_iot_defender_collector.c
- libraries/c_sdk/aws/defender/src/aws_iot_defender_mqtt.c
- libraries/c_sdk/aws/defender/src/aws_iot_defender_v1.c
- libraries/c_sdk/aws/defender/src/private/aws_iot_defender_internal.h
- libraries/c_sdk/aws/defender/test/aws_iot_tests_defender_api.c
Use shared MQTT connection and remove sync call from taskpool.
Before this change, Defender library created and maintained its own
MQTT connection. Use of shared MQTT connection will save memory and
processing time.
Defender library used taskpool task which made blocking calls to
MQTT library. Because MQTT library also uses taskpool, blocking calls
may cause deadlock if limited number of taskpool tasks are available.
This change removes blocking calls from taskpool context.
Description
-----------
Checklist:
----------
> fix: Re-architect Defender Library.

- libraries/abstractions/pkcs11/test/iot_test_pkcs11.c
- projects/infineon/xmc4800_plus_optiga_trust_x/dave4/aws_demos/.cproject
- projects/infineon/xmc4800_plus_optiga_trust_x/dave4/aws_tests/.cproject
- vendors/infineon/boards/xmc4800_plus_optiga_trust_x/CMakeLists.txt
- vendors/infineon/boards/xmc4800_plus_optiga_trust_x/aws_tests/config_files/iot_test_pkcs11_config.h
The purpose of this change is to ensure that the Infineon OPTIGA projects, including IDE and cmake, set key import policy via the same configuration headers.
> Consistent key import policy handling for OPTIGA

- vendors/infineon/boards/xmc4800_iotkit/CMakeLists.txt
- vendors/infineon/boards/xmc4800_plus_optiga_trust_x/CMakeLists.txt
- vendors/nxp/boards/lpc54018iotmodule/CMakeLists.txt
add missing metadata "IS_ACTIVE" required by console for the following boards.
infineon:
xmc4800_plus_optiga_trust_x
xmc4800_iotkit
nxp:
lpc54018iotmodule
Description
-----------
Checklist:
----------
> add missing console metadata

- libraries/abstractions/common_io/include/iot_perfcounter.h
- libraries/abstractions/common_io/include/iot_pwm.h
- libraries/abstractions/common_io/include/iot_reset.h
Improve documentation in PerfCounter, PWM, and Reset header files
Why:  Need to clarify return values of all of the APIs, as well as
improve overall documentation to make usage clearer.
Checklist:
----------
> docs: Improve documentation in iot header files

- vendors/microchip/boards/curiosity_pic32mzef/aws_demos/application_code/microchip_code/NetworkConfig.h
- vendors/microchip/boards/curiosity_pic32mzef/aws_demos/config_files/FreeRTOSIPConfig.h
- vendors/microchip/boards/curiosity_pic32mzef/aws_tests/application_code/microchip_code/NetworkConfig.h
- vendors/microchip/boards/curiosity_pic32mzef/aws_tests/config_files/FreeRTOSIPConfig.h
- vendors/microchip/harmony/v2.05/framework/tcpip/src/tcpip_packet.c
Description
-----------
The FreeRTOS+TCP [IPv6 branch](https://github.com/aws/amazon-freertos/tree/hein/tcpipv6) is being developed with the assumption that the IP-type (v4/v6) can be stored in the Network Buffers, a few bytes before the actual packet data.
However, the Microchip Ethernet driver for the Curiosity board is using the same space to store a pointer to a `TCPIP_MAC_PACKET`.
In C language:
~~~c
struct
{
NetworkBufferDescriptor_t * pxDescriptor;   /* 0 + 4 =  4 */
uint32_t ulIPv6Info;                        /* 4 + 4 =  8 */
uint16_t usFiller;                          /* 8 + 2 = 10 */
char pcEthernetHeader[ 14 ];                /* The Ethernet header and the rest */
};
~~~
The driver would overwrite the value in `ulIPv6Info` to store its own information.
In order to let the …
> Prepare Microchip/Curiosity driver for IPv6

- demos/demo_runner/iot_demo_freertos.c
- demos/dev_mode_key_provisioning/src/aws_dev_mode_key_provisioning.c
- demos/https/iot_demo_https_s3_download_async.c
- libraries/abstractions/pkcs11/mbedtls/iot_pkcs11_mbedtls.c
- libraries/c_sdk/standard/common/iot_device_metrics.c
- libraries/freertos_plus/standard/crypto/src/iot_crypto.c
Fix compiler warnings and add mbedtls configuration to FreeRTOS IoT file.
Description
-----------
- The first commit addresses issue #1366 
I have done a grep of #include "mbedtls/config" and iot_crypo.c is the ONLY file where this is present in Amazon FreeRTOS.
- The second commit addresses issue #1367 + other build warnings found when compiling MCUExpresso, UVision, and IAR.
Checklist:
----------
> Fix compiler warnings and add mbedtls configuration to FreeRTOS IoT file.

- vendors/marvell/boards/mw300_rd/aws_demos/config_files/FreeRTOSConfig.h
- vendors/marvell/boards/mw300_rd/aws_tests/config_files/FreeRTOSConfig.h
Description
-----------
PR #1163 has incorrectly reverted timer task priority fix, and we are seeing hard fault in task pool test group. (When timer task priority is lower than task pool priority, timer deletion and timer triggering are executed in wrong order.) Reapplying previous fix. 
After this PR is merged to master, will cherry pick it into release candidate.
Checklist:
----------
> Fixing timer task priority on Marvell

- libraries/c_sdk/standard/common/CMakeLists.txt
- vendors/microchip/boards/secure_element/CMakeLists.txt
- vendors/microchip/boards/secure_element/secure_element.cmake
- vendors/microchip/manifest.cmake
Description
-----------
This PR has a working CMake file for the ECC608+WinSim port. Since the naming is not decided, this is to be merged to mchp/ecc608, not master.
Checklist:
----------
> Working CMake for ECC608 (with current folder structure)

- demos/demo_runner/iot_demo_freertos.c
- demos/demo_runner/iot_demo_runner.c
- vendors/pc/boards/windows/aws_demos/config_files/aws_demo_config.h
- vendors/st/boards/stm32l475_discovery/aws_demos/config_files/aws_demo_config.h
- vendors/ti/boards/cc3220_launchpad/aws_demos/config_files/aws_demo_config.h
Added Heap and stack analysis to AFR demos.
Description
-----------
This is my proposal for a demo agnostic and port agnostic heap and stack usage collection. This has been tested on ST port and Windows Simulator. This is to be tested on CI to ensure it works for all demo and board combinations.
TODO: Test on CI
TODO: Add more granular analysis to individual demos. (Eg. Some demos use more than one task.) 
Checklist:
----------
> Added Heap and stack analysis to AFR demos.

- libraries/abstractions/common_io/include/iot_efuse.h
Remove unused return error code and fix documentation in EFUSE
Why: Some of the return errors were not used and need to be removed.
Also come documentation style were not inline with the standards.
Checklist:
----------
> docs:Documentation error in EFUSE

- libraries/abstractions/common_io/test/test_iot_rtc.c
Fixing spelling error on IotRtcStatus_t enum.
Why:  because alarm was spelled wrong.
This is related to PR 1391
@lundinc2 @qiutongs 
Checklist:
----------
> style: Fixing spelling error on IotRtcStatus_t enum.

- libraries/abstractions/ble_hal/test/include/iot_test_ble_hal_common.h
- libraries/abstractions/ble_hal/test/src/iot_test_ble_hal_afqp.c
- libraries/abstractions/ble_hal/test/src/iot_test_ble_hal_common.c
Clear events from the previous test case
Description
-----------
Some test cases don't check for all ble events in the queue. These pending ble events can cause the following test cases to fail.
Added a helper to clear the event queue before running the test case.
Checklist:
----------
> Ble Hal tests: Clear events from previous test case

- libraries/abstractions/common_io/include/iot_i2s.h
Fixing typo and style issue in comments of iot_i2s.h
Why:  nit fixes
Checklist:
----------
> style: Fix typo and alignment issue is iot_i2s.h

- libraries/freertos_plus/standard/tls/test/iot_test_tls.c
Description
-----------
#include "iot_pkcs11_config.h" must be included before #include "iot_pkcs11.h"
Checklist:
----------
> Fix missing header in TLS tests

- libraries/freertos_plus/standard/freertos_plus_tcp/include/FreeRTOS_Stream_Buffer.h
- libraries/freertos_plus/standard/freertos_plus_tcp/source/portable/NetworkInterface/RX/NetworkInterface.c
Description
-----------
The FreeRTOS+TCP library has its own implementation of a stream buffer in `FreeRTOS_Stream_Buffer.c`.
Its implementation differs in some ways from the kernel library `stream_buffer.c`.
Two helper functions are defined in both modules: `xStreamBufferIsFull()` and `xStreamBufferIsEmpty()`.
In many projects, this went unnoticed because the FreeRTOS+TCP versions are never used in any of the sources.
I propose to remove the two unused declarations from `FreeRTOS_Stream_Buffer.c` :
~~~c
static portINLINE BaseType_t xStreamBufferIsEmpty( const StreamBuffer_t *pxBuffer );
static portINLINE BaseType_t xStreamBufferIsFull( const StreamBuffer_t *pxBuffer );
~~~
The [Renesas Network Interface](https://github.com/aws/amazon-freertos/blob/master/libraries/freertos_plus/standard/f …
> Remove 2 unused functions from +TCP stream buffer

- libraries/abstractions/platform/freertos/iot_network_freertos.c
Update IotNetworkAfr_Create() to give error feedback on connection.
This helpful for example to know that FreeRTOS+TCP timed out with a -116 error.
Checklist:
----------
> Update IotNetworkAfr_Create() to give error feedback on connection.

- vendors/espressif/boards/esp32/aws_demos/config_files/FreeRTOSIPConfig.h
- vendors/espressif/boards/esp32/aws_tests/config_files/FreeRTOSIPConfig.h
- This was mapping to c std rand() and therefore the same numbers were being output each board reset.
- ulRand() defined in the secure sockets port for FreeRTOS+TCP maps to the ESP32 hardware entropy logic.
This fixes issue #1357 
Checklist:
----------
> Fix FreeRTOS+TCP rand32 mapping in ESP32.

- libraries/c_sdk/standard/https/include/iot_https_client.h
- libraries/c_sdk/standard/https/include/types/iot_https_types.h
Fix a few notable missing reference tags in https client doxygen docs.
These are just the ones in the header files.
When the HTTPS Client moves to the CSDK, doxygen generation will be able to get the acquire the tags desired.
Checklist:
----------
> Fix missing reference tags in https client doxygen docs.

- demos/demo_runner/iot_demo_freertos.c
Description
-----------
disable network in demo cleanup code so that demo can be re-run
Related issue: https://github.com/aws/amazon-freertos/issues/1380
Checklist:
----------
> disable network in demo cleanup code so that demo can be re-run

- libraries/freertos_plus/standard/freertos_plus_tcp/source/FreeRTOS_DHCP.c
- libraries/freertos_plus/standard/freertos_plus_tcp/source/portable/BufferManagement/BufferAllocation_1.c
Link Local Fallback and UDP Verbosity Fixes
Description
-----------
- FreeRTOS_DHCP can crash when trying to close a NULL socket
- TCP window debugging messages cause compile problems when TCP is unused
Checklist:
----------
> Link Local Fallback and UDP Verbosity Fixes

- vendors/espressif/boards/esp32/aws_demos/config_files/FreeRTOSIPConfig.h
- vendors/espressif/boards/esp32/aws_tests/config_files/FreeRTOSIPConfig.h
This PR is a copy into release-candidate of: https://github.com/aws/amazon-freertos/pull/1413
- This was mapping to c std rand() and therefore the same numbers were being output each board reset.
- ulRand() defined in the secure sockets port for FreeRTOS+TCP maps to the ESP32 hardware entropy logic.
- This fixes issue #1357
Checklist:
----------
> Release-Candidate Copy: Fix FreeRTOS+TCP rand32 mapping in ESP32. 

- libraries/freertos_plus/standard/freertos_plus_tcp/include/FreeRTOS_IP_Private.h
- libraries/freertos_plus/standard/freertos_plus_tcp/source/FreeRTOS_ARP.c
- libraries/freertos_plus/standard/freertos_plus_tcp/source/FreeRTOS_IP.c
Description
-----------
The function `FreeRTOS_OutputARPRequest()` was developed to be used by both the IP-task, as well as the application. However, when the application calls it, `xNetworkInterfaceOutput()` may land in a `configASSERT()`, because only the IP-task is allowed to call that (non re-entrant) function.
Solution:
~~~c
if( xIsCallingFromIPTask() != 0 )
{
/* Only the IP-task is allowed to call this function directly. */
xNetworkInterfaceOutput( pxNetworkBuffer, pdTRUE );
}
else
{
/* Let the IP-task send the packet. */
}
~~~
A new event-type is added: `eNetworkTxEvent`, which is sent as:
~~~c
IPStackEvent_t xSendEvent;
xSendEvent.eEventType = eNetworkTxEvent;
xSendEvent.pvData = ( void * ) pxNetworkBuffer;
xSendEventStructToIPTask( &xSendEvent, ( TickType_t ) portMAX_DELAY );
~~~ …
> Make FreeRTOS_OutputARPRequest() available for application code

- projects/microchip/ecc608a_plus_winsim/visual_studio/aws_demos/aws_demos.vcxproj
- projects/microchip/ecc608a_plus_winsim/visual_studio/aws_demos/aws_demos.vcxproj.filters
- projects/microchip/ecc608a_plus_winsim/visual_studio/aws_tests/aws_tests.vcxproj
- projects/microchip/ecc608a_plus_winsim/visual_studio/aws_tests/aws_tests.vcxproj.filters
- vendors/microchip/boards/ecc608a_plus_winsim/CMakeLists.txt
Description
-----------
This also has a fix for CMakefiles where vendors/microchip/boards/ecc608a_plus_winsim/secure_elements/lib/atca_cfgs.c should not be included in the project. 
cfg_ateccx08a_kithid_default is re-declared in: vendors/microchip/boards/ecc608a_plus_winsim/ports/pkcs11/iot_pkcs11_secure_element.c
Checklist:
----------
> Add ECC608A to IDE Generator and generate project files

- libraries/abstractions/ble_hal/test/src/iot_test_ble_hal_integration.c
- vendors/espressif/boards/esp32/aws_demos/application_code/main.c
- vendors/espressif/boards/esp32/aws_tests/application_code/main.c
- vendors/espressif/boards/esp32/ports/ble/bluedroid/iot_ble_hal_common_gap.c
- vendors/espressif/boards/esp32/ports/ble/nimble/iot_ble_hal_common_gap.c
Refactor ESP init/deint/disable/enable functions
Description
-----------
* Move memory teardown functions outside.
* Have init/deinit enable/disable show consistent behavior.
Checklist:
----------
> [BLE] Refactor ESP init/deint/disable/enable functions

- libraries/abstractions/pkcs11/mbedtls/iot_pkcs11_mbedtls.c
- libraries/abstractions/pkcs11/test/iot_test_pkcs11.c
Description
-----------
Adds test that RSA and EC private keys cannot be extracted.
Updates C_GetAttributeValue to return the correct error code when RSA private key is queried. (Previously returned CKR_ATTRIBUTE_TYPE_INVALID).
Checklist:
----------
https://amazon-freertos-ci.corp.amazon.com/job/master/job/custom_ide/268/console
> Add test that private keys are not extractable

- libraries/c_sdk/standard/ble/CMakeLists.txt
- tests/common/aws_test_runner.c
- tests/common/iot_tests_network.c
- vendors/nordic/boards/nrf52840-dk/CMakeLists.txt
- vendors/nordic/boards/nrf52840-dk/aws_demos/bootloader/asn1utility.c
- vendors/nordic/boards/nrf52840-dk/aws_demos/bootloader/asn1utility.h
- vendors/nordic/boards/nrf52840-dk/aws_tests/bootloader/asn1utility.c
- vendors/nordic/boards/nrf52840-dk/aws_tests/bootloader/asn1utility.h
- vendors/nordic/boards/nrf52840-dk/bootloader.cmake
- vendors/nordic/boards/nrf52840-dk/bootloader_flash_placement.xml
Add bootloader project to nordic cmake
Description
-----------
Nordic has separate bootloader project which needs to be built along with demos and test projects
* Added bootloader CMakefile and include it from demos and test projects.
* Ran Nordic tests with CMake.
* Separated BLE WiFi provisioning test files  from BLE  CMake to not get included for Nordic.
* Fix header file dependencies in Nordic application code
* Move MQTT serializer tests for BLE under BLE end-to-end group.
Checklist:
----------
> Add bootloader project to Nordic CMake

- libraries/abstractions/common_io/test/test_iot_cli.c
- libraries/abstractions/common_io/test/test_iot_i2s.c
- libraries/abstractions/common_io/test/test_iot_internal.h
Adding unit tests for the iot_i2s APIs
Why:  We need to have unit tests for the iot_i2s APIs so that
we can validate proper functionality.
This completes the addition of the tests added in PR 1426
Description
-----------
Checklist:
----------
> test: Adding unit tests for iot_i2s APIs

- libraries/freertos_plus/aws/ota/test/aws_test_ota_pal.c
- vendors/nordic/boards/nrf52840-dk/CMakeLists.txt
Fix OTA PAL test for Nordic
Description
-----------
Nordic doesn't have a PKCS11 port implementation yet, so the test for importing code signer certificate using PKCS11 should be disabled for Nordic. The test was guarded with config `otatestpalREAD_CERTIFICATE_FROM_NVM_WITH_PKCS11 `  but not the private function. 
Added guard to the private function as well.
Checklist:
----------
> Fix OTA PAL test for Nordic

- vendors/renesas/amazon_freertos_common/entropy_hardware_poll.c
When data requested is not a multiple of 4 bytes,
mbedtls_hardware_poll could have overflowed the output
buffer.
Tests
https://amazon-freertos-ci.corp.amazon.com/job/master/job/custom_ide/262/console
Rebuild after PR feedback:
https://amazon-freertos-ci.corp.amazon.com/job/master/job/custom_ide/274/console (all tests pass)
Checklist:
----------
> Prevent overflow of Renesas RNG buffer

- CHANGELOG.md
- libraries/3rdparty/lwip/src/include/lwip/sys.h
- libraries/3rdparty/lwip/src/portable/arch/lwipopts_freertos.h
- libraries/3rdparty/lwip/src/portable/arch/sys_arch.c
- libraries/3rdparty/lwip/src/portable/arch/sys_arch.h
These changes implement the minimum functionality necessary to enable lwIP's "full duplex" mode.  This mode "enables code that allows reading from one thread, writing from a 2nd thread and closing from a 3rd thread at the same time."
To keep the implementation self-contained, the per-task semaphore lookup function does the allocation on first use by a given task, and the semaphore is never freed.  This is compatible with the standard persistent task model.
This work is the companion of the code committed in https://github.com/aws/amazon-freertos/pull/1017/commits/e6dee5a266a2bbf01c1aef47ea40b55935c607b3 .
The TCP regression suite passes, including:
TEST(Full_TCP, AFQP_SOCKETS_Threadsafe_SameSocketDifferentTasks) PASS
TEST(Full_TCP, AFQP_SOCKETS_Threadsafe_DifferentSocketsDifferentTasks) …
> Implement LWIP_NETCONN_SEM_PER_THREAD and LWIP_NETCONN_FULLDUPLEX

- libraries/abstractions/pkcs11/mbedtls/iot_pkcs11_mbedtls.c
- libraries/abstractions/pkcs11/test/iot_test_pkcs11.c
- vendors/st/boards/stm32l475_discovery/aws_tests/config_files/iot_pkcs11_config.h
- vendors/st/boards/stm32l475_discovery/aws_tests/config_files/iot_test_pkcs11_config.h
If ECDSA support has been disabled via static configuration, the PKCS #11 test module should completely skip test cases that involve that cryptosystem.
> Don't check for ECDSA support if it's disabled in static configuration.

- libraries/abstractions/pkcs11/mbedtls/iot_pkcs11_mbedtls.c
- libraries/abstractions/pkcs11/test/iot_test_pkcs11.c
- vendors/renesas/amazon_freertos_common/entropy_hardware_poll.c
- vendors/st/boards/stm32l475_discovery/aws_tests/config_files/iot_pkcs11_config.h
- vendors/st/boards/stm32l475_discovery/aws_tests/config_files/iot_test_pkcs11_config.h
Add test that private keys are not extract-able. Prevent overflow of Renesas RNG buffer.  Don't check for ECDSA support if it's disabled in static configuration.
> Renesas RNG and private key policy fixes

- vendors/nordic/boards/nrf52840-dk/CMakeLists.txt
- vendors/nordic/boards/nrf52840-dk/bootloader.cmake
Miscellaneous fixes to Nordic cmake
Description
-----------
* Nordic SDK includes crypto modules by referencing them from flash program data section.
CMAKE was not including crypto files as there was no direct dependency from Nordic SDK.
Fix - Added SDK source files directly to target to get them linked.
* Change thumb_crt0.s file for bootloader
Checklist:
----------
> Miscellaneous fixes to Nordic cmake

- vendors/microchip/secure_elements/lib/pkcs11/pkcs11_key.c
CKA_VALUE was missing from certificate template, causing GetAttributeValue
calls on private keys to return CKR_ATTRIBUTE_TYPE_INVALID instead of
CKR_ATTRIBUTE_SENSITIVE.  Adding this attribute to the template triggers
the CKR_ATTRIBUTE_SENSITIVE return value instead.
Description
-----------
Checklist:
----------
> Add CKA_VALUE with NULL retrieval function to private key template

- libraries/freertos_plus/standard/freertos_plus_tcp/source/portable/NetworkInterface/mw300_rd/NetworkInterface.c
- vendors/marvell/boards/mw300_rd/aws_demos/config_files/FreeRTOSConfig.h
- vendors/marvell/boards/mw300_rd/aws_tests/config_files/FreeRTOSConfig.h
Description
-----------
```IP-task``` is created before ```wifi_driver``` and ```wlcmgr``` task. Right after entering IP task, network down event is sent to the queue in the same task to initialize local MAC address. Due to the condition ```if ( xInterfaceState == INTERFACE_UP )```, the code skips reading MAC address from NVM and fails updating IP stack local MAC address properly. 
The fix is proposed given reading MAC address does not need WiFi layer to be ready prior. 
Checklist:
----------
> BUGFIX: Marvell MAC address was not properly initialized in TCP stack

- demos/include/iot_config_common.h
- tests/include/iot_config_common.h
Description
-----------
When using quotes, the compiler searches first in the same directory containing the current file. With this behavior, there's no way to specify another include path and tell compiler to search that first. One of the use cases is customer may want to set up our library as a submodule, and specify another include path for our config files that takes precedence over our default config directory. This commit fixes some immediate issues that are blocking this use case. Further discussions are needed for all other #include
Checklist:
----------
> Use angle brackets for some include

- libraries/c_sdk/standard/mqtt/test/system/iot_tests_mqtt_system.c
- tests/include/iot_config_common.h
Add exponential retry logic to all MQTT System tests.
Description
-----------
To reduce the probability of failures in MQTT connect because of transient network issues, we add exponential retries to all IotMqtt_Connect() calls in all MQTT_System tests.
This change once approved will be repeated in the CSDK. 
Checklist:
----------
> Add exponential retry logic to all MQTT System tests.

- demos/greengrass_connectivity/aws_greengrass_discovery_demo.c
- libraries/freertos_plus/aws/greengrass/include/aws_greengrass_discovery.h
- libraries/freertos_plus/aws/greengrass/src/aws_greengrass_discovery.c
- libraries/freertos_plus/aws/greengrass/test/aws_test_greengrass_discovery.c
Description
-----------
Removed demo includes from aws_clientcredential.h in greengrass library code.
Updated greengrass demo to use v2 MQTT APIs instead of v1.
Checklist:
----------
> Remove client credential from greengrass discovery

- libraries/c_sdk/standard/mqtt/test/system/iot_tests_mqtt_system.c
Accidentally left `retryCount <= IOT_TEST_MQTT_CONNECT_RETRY_COUNT`. This needs to be `retryCount < IOT_TEST_MQTT_CONNECT_RETRY_COUNT`, otherwise for a IOT_TEST_MQTT_CONNECT_RETRY_COUNT of 1, we will try to connect twice. 
Checklist:
----------
> Fix bug in the MQTT system tests with retry count.

- vendors/nordic/boards/nrf52840-dk/CMakeLists.txt
Description
-----------
- Throw an error if arm-none-eabi-size is not found
- Use the compiler location to search objcopy and arm-none-eabi-size
Checklist:
----------
> Fix an issue in nordic CMake file

- vendors/espressif/boards/esp32/ports/ble/nimble/iot_ble_hal_gap.c
NimBLE - Correct the HCI disconnect reason 
Checklist:
----------
> AFR: NimBLE - Correct the HCI disconnect reason

- libraries/abstractions/common_io/test/test_iot_i2c.c
Description
-----------
fix i2c tests by sending not stop condition after write
Checklist:
----------
> fix i2c tests by sending not stop condition after write

- libraries/3rdparty/lwip/src/api/api_msg.c
The uninitialized element leads to non-deterministic behavior when full duplex mode is enabled.
> Fix uninitialized element in connection struct

- libraries/abstractions/common_io/test/test_iot_tsensor.c
Changing the upper and lower limit for tsensor test
Why:  The tests were failing in pre-CI because the DUT is running
in a closed environment with no air circulation or a/c.  This is
causing it to run hotter than expected room temperature.
----------
> test: Changing thresholds for tsensor test

- libraries/abstractions/common_io/include/iot_usb_device.h
- libraries/abstractions/common_io/test/test_iot_usb_device.c
Documentation and correcting return codes for LL-Hal iot_usb_devices
Why:  While going through and improving the overall documentation of
iot_usb_devices header file, we discovered that there were some
duplicate return codes, as well as some API's that were returning
mis-leading return codes.  We've cleaned that up.
Description
-----------
Checklist:
----------
> fix: Documentation and correcting return codes for iot_usb_devices

- libraries/abstractions/ble_hal/test/ble_test_scipts/startTests_afqp.py
- libraries/abstractions/ble_hal/test/ble_test_scipts/testClass.py
- libraries/abstractions/ble_hal/test/include/iot_test_ble_hal_common.h
- libraries/abstractions/ble_hal/test/include/iot_test_ble_hal_config_defaults.h
- libraries/abstractions/ble_hal/test/src/iot_test_ble_hal_afqp.c
- libraries/abstractions/ble_hal/test/src/iot_test_ble_hal_integration.c
- projects/nordic/nrf52840-dk/ses/aws_tests/aws_tests.emProject
Description
-----------
- Add read long value test
- rewrite BLE_Write_Notification_Size_Greater_Than_MTU_3 test case
Checklist:
----------
> Add read long value test

- libraries/abstractions/common_io/include/iot_i2s.h
- libraries/abstractions/common_io/test/test_iot_i2s.c
Adding ioctl for GetTxNoOfBytes/GetRxNoOfBytes
Why:  While reviewing tests for I2S, we discovered that we were
missing the ability to get the number of tx/rx bytes sent in the
previous calls to read/write.
So, we've added the ioctl, along with appropriate tests.
Checklist:
----------
> feat: Add Get TX/RX Num bytes for I2S operations

- libraries/abstractions/ble_hal/test/ble_test_scipts/bleAdapter.py
- libraries/abstractions/ble_hal/test/ble_test_scipts/runPI.sh
- libraries/abstractions/ble_hal/test/ble_test_scipts/startTests_afqp.py
- libraries/abstractions/ble_hal/test/ble_test_scipts/testClass.py
- libraries/abstractions/ble_hal/test/src/iot_test_ble_hal_afqp.c
Make RPI BLE tests more robust
Description
-----------
* Add wait with a timeout for disconnected, paired and service discovery events. This removes flakiness if there is a delay in receiving events.
* Add test for disconnect from peripheral
Checklist:
----------
> Make RPI BLE tests more robust

- libraries/abstractions/secure_sockets/freertos_plus_tcp/iot_secure_sockets.c
- libraries/freertos_plus/standard/freertos_plus_tcp/include/FreeRTOS_IP.h
- libraries/freertos_plus/standard/freertos_plus_tcp/source/FreeRTOS_DHCP.c
- libraries/freertos_plus/standard/freertos_plus_tcp/source/FreeRTOS_DNS.c
- libraries/freertos_plus/standard/freertos_plus_tcp/source/FreeRTOS_Sockets.c
- libraries/freertos_plus/standard/freertos_plus_tcp/source/portable/NetworkInterface/WinPCap/FaultInjection.c
- vendors/infineon/boards/xmc4800_plus_optiga_trust_x/ports/secure_sockets/iot_secure_sockets.c
- vendors/vendor/boards/board/ports/secure_sockets/iot_secure_sockets.c
Replace the ipconfigRAND32 macro with a function
-----------
Summary:
Any TCP/IP stack has a need for random numbers. Think of random port numbers and initial sequence numbers in a TCP connection. But also ID's when contacting a DNS server.
Until now, there was a macro `ipconfigRAND32()` that was usually defined as:
~~~c
extern uint32_t ulRand();
#define ipconfigRAND32()    ulRand()
~~~
When a random number is obtained from a peripheral, things may go wrong because of a hardware failure. We introduced the rule that a random value '0' stands for a failure.
However, the number 0 is a valid random number.
I propose a new function that delivers a random number, and that indicates if the operation was successful:
~~~c
/* xApplicationGetRandomNumber() will set *pulNumber to a random number,
and …
> Replace the ipconfigRAND32 macro with a function

- libraries/abstractions/secure_sockets/lwip/iot_secure_sockets.c
- vendors/cypress/boards/CYW943907AEVAL1F/aws_demos/config_files/aws_secure_sockets_config.h
- vendors/cypress/boards/CYW943907AEVAL1F/aws_tests/config_files/aws_secure_sockets_config.h
- vendors/cypress/boards/CYW954907AEVAL1F/aws_demos/config_files/aws_secure_sockets_config.h
- vendors/cypress/boards/CYW954907AEVAL1F/aws_tests/config_files/aws_secure_sockets_config.h
- vendors/mediatek/boards/mt7697hx-dev-kit/aws_demos/config_files/aws_secure_sockets_config.h
- vendors/mediatek/boards/mt7697hx-dev-kit/aws_tests/config_files/aws_secure_sockets_config.h
- vendors/nuvoton/boards/numaker_iot_m487_wifi/aws_demos/config_files/aws_secure_sockets_config.h
- vendors/nuvoton/boards/numaker_iot_m487_wifi/aws_tests/config_files/aws_secure_sockets_config.h
This change makes the stack size for receive callbacks configurable.  Also a bad return after vTaskDelete() is removed.
TCP tests pass
* https://amazon-freertos-ci.corp.amazon.com/job/master/job/custom/job/cypress/job/cypress54-ide/99/
* https://amazon-freertos-ci.corp.amazon.com/job/master/job/custom/job/mediatek/job/mt7697hx-dev-kit-ide/130/
MQTT demo passes
* https://amazon-freertos-ci.corp.amazon.com/job/master/job/custom/job/cypress/job/cypress54-ide/100/
* https://amazon-freertos-ci.corp.amazon.com/job/master/job/custom/job/mediatek/job/mt7697hx-dev-kit-ide/131/
> Configuration of the stack depth for the lwip receive callback task.

- libraries/abstractions/secure_sockets/test/iot_test_tcp.c
- vendors/espressif/boards/esp32/aws_tests/config_files/aws_test_tcp_config.h
- vendors/marvell/boards/mw300_rd/aws_tests/config_files/aws_test_tcp_config.h
- vendors/microchip/boards/curiosity_pic32mzef/aws_tests/config_files/aws_test_tcp_config.h
- vendors/microchip/boards/ecc608a_plus_winsim/aws_tests/config_files/aws_test_tcp_config.h
- vendors/pc/boards/windows/aws_tests/config_files/aws_test_tcp_config.h
- vendors/renesas/boards/rx65n-rsk/aws_tests/config_files/aws_test_tcp_config.h
- vendors/vendor/boards/board/aws_tests/config_files/aws_test_tcp_config.h
- vendors/xilinx/boards/microzed/aws_tests/config_files/aws_test_tcp_config.h
The old test returned pdPASS if integrationtestportableMAX_NUM_UNSECURE_SOCKETS sockets were created and pdFAIL for fewer or more sockets.  Some ports are limited only by free memory.  The test would return pdFAIL for those ports.  To work around this an exclusion list was added via preprocessor directive.
This PR removes the exclusion list, and returns pdFAIL only if fewer sockets were created.  The define directive is removed from ports without a hard limit. For those ports, the test looks for a reasonable number of sockets to be created.
https://amazon-freertos-ci.corp.amazon.com/job/master/job/custom_ide/439/
> Change TooManySockets test to a concurrent count test

- libraries/abstractions/ble_hal/test/src/iot_test_ble_hal_integration.c
Description
-----------
Checklist:
----------
> add unsubscribe to BLE_Send_Data_After_Disconnected

- libraries/abstractions/ble_hal/test/src/iot_test_ble_hal_integration.c
In `BLE_Write_Notification_Size_Greater_Than_MTU_3` (integration tests), test should wait for `eBLEHALEventIndicateCb` event after sending notification.   
Description
-----------
After sending notification, stack sends GAP event `BLE_GAP_EVENT_NOTIFY_TX` to tell the application that notification transmission was attempted. This is followed by calling callback `prvIndicationSentCb`, where event  `eBLEHALEventIndicateCb` is pushed to queue. Since test does not wait for event to become available in current implementation, it gives invalid results e.g. if followed with `BLE_Send_Data_After_Disconnected` test, where after disconnection sending notification should be unsuccessful but results in success. 
Checklist:
----------
By submitting this pull request, I confirm that you can use, modify, …
> AFR NimBLE: Wait for eBLEHALEventIndicateCb event in BLE_Write_Notification_Size_Greater_Than_MTU_3

- vendors/espressif/boards/esp32/aws_demos/application_code/main.c
- vendors/espressif/boards/esp32/aws_tests/application_code/main.c
- vendors/espressif/boards/esp32/ports/ble/nimble/iot_ble_hal_common_gap.c
- vendors/espressif/boards/esp32/ports/ble/nimble/iot_ble_hal_gatt_server.c
- vendors/espressif/boards/esp32/ports/ble/nimble/iot_ble_hal_internals.h
Helps in fixing the integration test:TEST( Full_BLE_Integration_Test_Connection, BLE_Send_Data_After_Disconected )​ getting stuck in middle.
Description
-----------
- Fix return code in `prvBTSendResponse`.
- Changes `prvValidGattRequest` to handle valid/invalid gatt request properly.
- Introduce `prvGattGiveSemaphore` API inline with `prvGattGetSemaphore`.
- Remove redundant `esp_bt_controller_mem_release( ESP_BT_MODE_BTDM )` from **application_code** of **aws_tests** and **aws_demos** as `ESP_BT_MODE_CLASSIC_BT` memory is already released at the start. 
Checklist:
----------
> AFR NimBLE: Misc fixes in prvBTSendResponse, prvValidGattRequest and application code (aws_demos & aws_tests)

- libraries/abstractions/pkcs11/mbedtls/iot_pkcs11_mbedtls.c
- libraries/abstractions/pkcs11/test/iot_test_pkcs11.c
- libraries/freertos_plus/standard/pkcs11/src/iot_pkcs11.c
- vendors/cypress/boards/CYW943907AEVAL1F/ports/pkcs11/iot_pkcs11_pal.c
- vendors/cypress/boards/CYW954907AEVAL1F/ports/pkcs11/iot_pkcs11_pal.c
- vendors/nxp/boards/lpc54018iotmodule/ports/pkcs11/iot_pkcs11_pal.c
In #1498 https://github.com/aws/amazon-freertos/commit/6d86aab2383e730c08a81d66acb8d533eada9d2b
a bug was fixed in xFindObjectWithLabelAndClass.
xFindObjectWithLabelAndClass calls a sequence of operations, C_FindObjectInit, C_FindObject, C_FindObjectFinal.   Previously, the error code from C_FindObject was overwritten by the error code in C_FindObjectFinal.  After the fix, the error from C_FindObject is propagated properly, exposing an issue in several PAL layers where PKCS11_PAL_FindObject returned a valid object handle when non exists.
This fix cleans up some logic in the use of FindObject and corrects these PALs.
Description --> Fixes regression in NXP and Cypress PKCS #11 tests.
-----------
Cypress: https://amazon-freertos-ci.corp.amazon.com/job/master/job/custom/job/cypress/job/cypres …
> Clean up PKCS #11 FindObject if error occurs

- libraries/3rdparty/CMakeLists.txt
- libraries/3rdparty/tracealyzer_recorder/streamports/TCPIP/trcStreamingPort.c
- libraries/abstractions/lwip_osal/include/arch/cc.h
- libraries/abstractions/secure_sockets/lwip/iot_secure_sockets.c
- tools/cmake/toolchains/arm-armclang.cmake
Fix compilation issues with ARM and IAR compilers
Description
-----------
- Add CMake toolchain file for ARM Compiler 6
- arm-armclang.cmake is based on arm-keil.cmake
- CMake 3.15 or newer is required to detect ARMClang
- CMake requires the CMAKE_SYSTEM_PROCESSOR variable to be configured
in order to detect ARMClang
- LwIP: ARM Compiler does not provide sys/time.h
- LwIP: Allow overriding LwIP's errno declaration
- cc.h no longer defines LWIP_PROVIDE_ERRNO when
LWIP_ERRNO_STDINCLUDE or LWIP_ERRNO_INCLUDE is defined
- Remove libraries/3rdparty/lwip/src/include/lwip from the include
path because LwIP's errno.h conflicts with the standard library's
errno.h
- Update source files that contained unqualified paths to LwIP 
header files
- LwIP: Fix incorrect struct packing with IAR EWARM
- When …
> Fix compilation issues with ARM and IAR compilers

- demos/demo_runner/iot_demo_freertos.c
- demos/demo_runner/iot_demo_runner.c
- vendors/espressif/boards/esp32/aws_demos/config_files/aws_demo_config.h
- vendors/pc/boards/windows/aws_demos/config_files/aws_demo_config.h
- vendors/st/boards/stm32l475_discovery/aws_demos/config_files/aws_demo_config.h
- vendors/ti/boards/cc3220_launchpad/aws_demos/config_files/aws_demo_config.h
Added stack and heap metrics logging to ESP32 demos. Abstracted data type of stack size as on ESP32 it is bytes, but FreeRTOS implementation is usually stack words. Changed variable prefixes from demo to democonfig as per convention.
Description
-----------
Checklist:
----------
> Heap and Stack metrics for ESP32. Plus naming changes.

- libraries/freertos_plus/standard/freertos_plus_tcp/source/portable/NetworkInterface/RX/NetworkInterface.c
- libraries/freertos_plus/standard/freertos_plus_tcp/source/portable/NetworkInterface/RX/ether_callback.c
- vendors/renesas/FIT/RDP_v1.15_modified/r_ether_rx/src/r_ether_rx.c
- vendors/renesas/boards/rx65n-rsk/aws_demos/application_code/main.c
- vendors/renesas/boards/rx65n-rsk/aws_demos/config_files/FreeRTOSConfig.h
- vendors/renesas/boards/rx65n-rsk/aws_demos/config_files/FreeRTOSIPConfig.h
- vendors/renesas/boards/rx65n-rsk/aws_demos/src/smc_gen/r_config/r_ether_rx_config.h
- vendors/renesas/boards/rx65n-rsk/aws_tests/application_code/main.c
- vendors/renesas/boards/rx65n-rsk/aws_tests/config_files/FreeRTOSIPConfig.h
Description
-----------
The NetworkInterface driver for Renesas' RX65N works fine to do a demo and some tests.
In order to make it ready for a real-life application, I would like to propose some changes:
- The detection of the PHY Link Status should be repaired, the code contains a few typo's.
~~~c
if (ETHER_SUCCESS == ret)
{
if ((NULL != cb_func.pcb_func) && (FIT_NO_FUNC != cb_func.pcb_func))
{
cb_arg.channel = channel;
cb_arg.event_id = ETHER_CB_EVENT_ID_LINK_ON;
(*cb_func.pcb_func)((void *) &cb_arg);
}
+        lchng_flag[channel] = ETHER_FLAG_ON_LINK_ON;
}
else
{
/* When PHY auto-negotiation is not completed */
transfer_enable_flag[channel] = ETHER_FLAG_OFF;
-        lchng_flag[channel] = ETHER_FLAG_ON_LINK_ON;
+        lchng_flag[channel] = ETHER_FLAG_ON_LINK_OFF;
}
~~~
This code …
> FreeRTOS+TCP: Revisiting the network interface for Renesas RX65N

- libraries/abstractions/ble_hal/test/src/iot_test_ble_hal_afqp.c
- vendors/espressif/boards/esp32/ports/ble/bluedroid/iot_ble_hal_common_gap.c
- vendors/espressif/boards/esp32/ports/ble/nimble/iot_ble_hal_common_gap.c
- vendors/nordic/boards/nrf52840-dk/ports/ble/iot_ble_hal_common_gap.c
Fix BLE porting layer get bonded devices property
Description
-----------
The API was returning the number of elements in the array of bonded devices, instead of length of the array (as per the API definition). Changed to use length and have number of elements derived from it.
Checklist:
----------
> Fix BLE porting layer get bonded devices property

- libraries/abstractions/ble_hal/include/bt_hal_manager_adapter_ble.h
- libraries/c_sdk/standard/ble/src/iot_ble_gap.c
Set connection interval range only for scan response
Description
-----------
Advertisement payload allows only 31 bytes of data. With connection interval included in advertisement it exceeds by 3 bytes.
Skipping connection interval in advertisement and instead setting in scan response data.
Checklist:
----------
> Set connection interval range only for scan response

- libraries/freertos_plus/standard/freertos_plus_tcp/source/FreeRTOS_ARP.c
- libraries/freertos_plus/standard/freertos_plus_tcp/source/FreeRTOS_DNS.c
- libraries/freertos_plus/standard/freertos_plus_tcp/source/FreeRTOS_IP.c
- libraries/freertos_plus/standard/freertos_plus_tcp/source/FreeRTOS_Sockets.c
- libraries/freertos_plus/standard/freertos_plus_tcp/source/FreeRTOS_UDP_IP.c
Description
-----------
A network buffer (`NetworkBufferDescriptor_t`) has a field `xDataLength`. This is the total length of the buffer. It includes the 14-byte Ethernet header and everything after that.
Just recently, @aggarg  wanted to add a length check in the function `vARPGenerateRequestPacket()`, something like:
~~~c
configASSERT( pxNetworkBuffer->xDataLength >= sizeof(ARPPacket_t) )
~~~
This function failed because there are two cases in which `xDataLength` has a different meaning.
- In an outgoing ICMP/ping packet, it means the number of bytes to send plus the size of an ICMP header.
- In an outgoing UDP packet, it is the payload size ( without the UDP header ).
In order to avoid confusion, I'd like to correct that: `xDataLength` will always contain the total number of bytes. …
> FreeRTOS+TCP: Let xDataLength always mean "total number of bytes"

- libraries/abstractions/common_io/test/test_iot_uart.c
Description
-----------
1. Remove test case: AFQP_IotUARTWriteSyncReadAsyncLoopbackTest
This test works with a loopback wiring setup. When it does a sync write, all the bytes will go to Rx register and cause an overrun error. This test only works if there is a hardware FIFO buffer on the UART. 
2. AFQP_IotUARTWriteReadAsyncWithCallback is fixed for similar reason above.
3. Removed some local unused variable.
Checklist:
----------
> fix UART non-assisted tests

- libraries/abstractions/secure_sockets/test/iot_test_tcp.c
Description
-----------
The function ```prvTcpSocketHelper``` called by ```prvConnectHelperWithRetry``` returns error code, if Socket cannot be allocated and the error code is stored in variable ```xResult```.
Previously this variable was never addressed after an error is received. Thus, the code runs in an infinite loop(which is not expected). This is the reason for failure of ```AFQP_SOCKETS_Threadsafe_DifferentSocketsDifferentTasks``` test-case.
The expected behaviour is; the function should retry obtaining a socket repetitively after a specific delay.
In prvConnectHelperWithRetry, check is added to retry until valid socket is received.
Checklist:
----------
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of …
> Fix for prvConnectHelperWithRetry function in iot_test_tcp.c

- vendors/espressif/boards/esp32/CMakeLists.txt
Description
-----------
- esp-idf CMakefile checks for python dependencies before
configuring, which breaks metadata upload step in OCW
- This commit marks python dependencies as checked if
AFR_METADATA_MODE is enabled.
Checklist:
----------
> Fix AFR_METADATA_MODE on espressif

- vendors/espressif/boards/esp32/ports/pkcs11/iot_pkcs11_pal.c
Description:
In the PAL layer(iot_pkcs_pal.c) adding the handling for fetching the JITP certificate from NVS.
Description
-----------
Handled the JITP Certificate operations in the PAL layer for Espressif. Previously they were unhandled.
Also, added some verbose prints before erasing the nvs_partition if nvs_partition_initialization fails due to some reason.
Checklist:
----------
- [*] I have tested my changes. No regression in existing tests.
- [*] My code is Linted.
> feat/espressif_jitp_cert_fix: Fixes the handline of JITP certs

- demos/https/iot_demo_https_common.c
- demos/https/iot_demo_https_s3_download_async.c
- demos/https/iot_demo_https_s3_download_sync.c
- demos/https/iot_demo_https_s3_upload_async.c
- demos/https/iot_demo_https_s3_upload_sync.c
- doc/generate_doc.sh
- libraries/c_sdk/standard/https/include/iot_https_client.h
- libraries/c_sdk/standard/https/include/types/iot_https_types.h
- libraries/c_sdk/standard/https/src/iot_https_client.c
- libraries/c_sdk/standard/https/src/private/iot_https_internal.h
Description
-----------
* Fix `_requestPool.pRequestDatas->scheduled = true;` to `_requestPool.pRequestContexts[ reqIndex ].scheduled = true;` as found by third-party static analysis tool.
* Changed all "requestDatas" to "requestContexts" this is because the "datas" is weird as data is already plural. "Context" postfixed to a variable name is vague to use, but better than postfixing "Data". These variables have a collection of information that get updated during the callbacks, so they are essentially "callbackContexts". 
* Fix spellings of words in all HTTPS Client library and demo files.
* Add more debug logging to the HTTPS Client library code and the async download demo.
Checklist:
----------
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute …
> Fix bad pointer de-reference in HTTPS Client demo

- vendors/espressif/boards/esp32/ports/ble/bluedroid/iot_ble_hal_gap.c
- vendors/espressif/boards/esp32/ports/ble/nimble/iot_ble_hal_gap.c
Modify the default 128 bit Service UUID to 16 bit Service UUID in Service Data.
Description
-----------
In `iot_ble_hal_gap.c`, use 16 bit Service UUID inside the Service Data as a default while setting advertisement data with `prvSetAdvData`. 
Checklist:
----------
> BLE AFR: Make 16 bit Service UUID as default while advertising with Service Data (Bluedroid & NimBLE port)

- libraries/abstractions/common_io/test/test_iot_spi.c
Description
-----------
Forget to protect some of this api call with the macro. The api is not implemented by all of the platform, which will cause build failure.
Checklist:
----------
> Add conditional build for all of the iot_spi_slave_slecet call.

- vendors/infineon/secure_elements/pkcs11/iot_pkcs11_trustx.c
- In FindObject, return CKR_OK & count=0 when object not found
- In GetAttributeValue when buffer provided is too small,
supply required buffer size.
Description
-----------
https://amazon-freertos-ci.corp.amazon.com/job/im_master/job/tests_ide/job/infineon/job/xmc4800_plus_optiga_trust_x-ide/12/console
Checklist:
----------
> Fixes to Optiga Trust X PKCS #11 implementation

- tools/cbmc/patches/.gitattributes
CBMC proofs start by patching the code with a few patch files to prepare the code for proof.  We apply the patch files using "git apply foo.patch".  It seems that the Windows git supplied by Visual Studio on Windows does not like crlf line endings in the patch files.  
This patch added a .gitattributes to the tools/cbmc/patches directory that forces eol=lf for the patch files in that directory.  We should probably be adding this to the top-level .gitattributes, but we keep it local to the patches directory to limit the blast radius of unintended consequences.
This has been test on macos, linux, and windows with the equivalent of the script
```
git clone https://github.com/markrtuttle/amazon-freertos.git debug
cd debug
git checkout preserve-patch-line-endings
git submodule update --init
cd …
```
> Preserve patch line endings for cbmc patch files.

- tools/cbmc/proofs/HTTP/IotHttpsClient_Disconnect/Makefile.json
IotDeQueue_Count added to debugging code in commit a62c57fe caused a loop unwinding assertion to fail.  This commit just unrolls the loop.
> Repair CBMC proof of IotHttpsClient_Disconnect.

- tools/cbmc/proofs/Makefile.template
- tools/cbmc/proofs/MakefileCommon.json
- tools/cbmc/proofs/make_proof_makefiles.py
One of the commits in this PR improves the performance of cbmc-viewer on windows by actually excluding the correct directories. The other fixes the common Makefile used by CBMC proofs so that it can also be used on Windows.
> CBMC Windows fixes

- tools/cbmc/proofs/make_proof_makefiles.py
This commit fixes the make_proof_makefiles.py script, which uses a class that was removed from the standard library in python 3.8. The script now detects which python version it's running on, and uses the correct class either way.
>  Ensure make_proof_makefiles.py runs on python 3.8 f4f947b 

- tools/cbmc/proofs/Makefile.template
This commit fixes a build rule in the CBMC Makefile.common, where
multiple source files are passed to the goto-cl compiler. While this is
acceptable on Linux, the cl compiler errors out when given more than one
source file in /c mode.
> Pass a single input file to goto-cl

- vendors/espressif/boards/esp32/components/freertos_tcpip/esp_http_server/CMakeLists.txt
- vendors/espressif/boards/esp32/components/freertos_tcpip/esp_http_server/component.mk
- vendors/espressif/esp-idf/components/driver/uart.c
- vendors/espressif/esp-idf/components/esp_http_server/CMakeLists.txt
- vendors/espressif/esp-idf/components/esp_http_server/Kconfig
- vendors/espressif/esp-idf/components/esp_http_server/component.mk
- vendors/espressif/esp-idf/components/esp_http_server/include/esp_http_server.h
- vendors/espressif/esp-idf/components/esp_http_server/include/http_server.h
- vendors/espressif/esp-idf/components/esp_http_server/src/esp_httpd_priv.h
- vendors/espressif/esp-idf/components/esp_http_server/src/httpd_main.c
- vendors/espressif/esp-idf/components/esp_http_server/src/httpd_parse.c
- vendors/espressif/esp-idf/components/esp_http_server/src/httpd_sess.c
- vendors/espressif/esp-idf/components/esp_http_server/src/httpd_txrx.c
- vendors/espressif/esp-idf/components/esp_http_server/src/httpd_uri.c
- vendors/espressif/esp-idf/components/esp_http_server/src/port/esp32/osal.h
- vendors/espressif/esp-idf/components/esp_http_server/src/util/ctrl_sock.c
- vendors/espressif/esp-idf/components/esp_http_server/src/util/ctrl_sock.h
- vendors/espressif/esp-idf/components/esp_http_server/test/CMakeLists.txt
- vendors/espressif/esp-idf/components/esp_http_server/test/component.mk
- vendors/espressif/esp-idf/components/esp_http_server/test/test_http_server.c
Description
-----------
Now that `LwIP` stack is supported for ESP32 (which in turn provides `posix` API), web server can also be supported. This PR pulls in required component. In addition also fixes minor issue in UART driver to correct critical section API.
Steps to use
---------------
```cmake -DVENDOR=espressif -DBOARD=esp32_wrover_kit -DCOMPILER=xtensa-esp32 -S . -B build  -DAFR_ESP_LWIP=1```
<Call `esp_http_server` APIs in application>
Checklist:
----------
> Web server support for ESP32

- demos/dev_mode_key_provisioning/src/aws_dev_mode_key_provisioning.c
- libraries/freertos_plus/standard/pkcs11/src/iot_pkcs11.c
- vendors/infineon/secure_elements/pkcs11/iot_pkcs11_trustx.c
Fix the PKCS11 Find Object loop in order to handle a certificate object that was previously in storage but subsequently deleted. Also fix code formatting and typographical errors.
> Fix PKCS11 FindObject behavior for deleted certificate scenario

- libraries/c_sdk/standard/ble/src/iot_ble_gap.c
Fix Infinite loop in BLE disconnect
Description
-----------
Shadow demo and MQTT demo on Nordic were not completing on Nordic.
The root cause was that the demo was completing but it was ending up in
an infinite loop in BLE disconnect logic and thus blocking the lower
priority logging task . This prevented logs of demo completion to be not
printed.
Solution is done by exiting the infinite loop in a condition when there
is error.
Checklist:
----------
- [ x] I have tested my changes.
> Fix Infinite loop in BLE disconnect

- libraries/freertos_plus/standard/freertos_plus_tcp/source/FreeRTOS_DNS.c
Detect integer overflow in `ulDNSHandlePacket()`.
-----------
This PR fixes an integer overflow case introduced in [an earlier commit](https://github.com/aws/amazon-freertos/commit/93c0aba73fe69cd3b067941d83d3d5d4dfebaabd#diff-ab35dd7e800d6d3ecb19dfa767aeacd4R1615) and detected by a failing [`ulDNSHandlePacket()`](https://github.com/aws/amazon-freertos/blob/master/libraries/freertos_plus/standard/freertos_plus_tcp/test/iot_test_freertos_tcp.c#L291) test.  See [here](https://github.com/aws/amazon-freertos/blob/release-candidate/libraries/freertos_plus/standard/freertos_plus_tcp/source/FreeRTOS_IP.c#L1615) for another example of this overflow detection logic.
Checklist:
----------
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, …
> ulDNSHandlePacket() - check length before calculating payload size

- libraries/freertos_plus/aws/ota/src/aws_iot_ota_agent.c
Description
-----------
OTA shutdown so that OTA demo can reconnect when maximum retries are completed.
Checklist:
----------
> fIX: Shutdown OTA agent so that it reconnects after max errors

- libraries/c_sdk/standard/serializer/src/json/iot_serializer_json_encoder.c
The length of "null" element isn't included into container's offset calculation logic.
> Fix for IOT_SERIALIZER_SCALAR_NULL datatype.

- libraries/c_sdk/standard/ble/CMakeLists.txt
- libraries/freertos_plus/aws/ota/CMakeLists.txt
- vendors/espressif/boards/esp32/CMakeLists.txt
- vendors/microchip/boards/curiosity_pic32mzef/CMakeLists.txt
- vendors/microchip/boards/ecc608a_plus_winsim/CMakeLists.txt
- vendors/nordic/boards/nrf52840-dk/CMakeLists.txt
- vendors/pc/boards/windows/CMakeLists.txt
- vendors/ti/boards/cc3220_launchpad/CMakeLists.txt
- vendors/vendor/boards/board/CMakeLists.txt
Description
-----------
We cannot automatically figure out which backend to enable in OTA. This PR refactors the OTA CMake file to let vendor choose which one to enable.
Checklist:
----------
> Let vendor choose which OTA backend to enable

- vendors/nxp/boards/lpc54018iotmodule/aws_demos/config_files/FreeRTOSConfig.h
- vendors/nxp/boards/lpc54018iotmodule/aws_demos/config_files/aws_ota_agent_config.h
- vendors/nxp/boards/lpc54018iotmodule/aws_tests/config_files/aws_ota_agent_config.h
Tune number of buffers.
Same as https://github.com/aws/amazon-freertos/pull/1620 but for release-candidate.
> Avoid "Error: No OTA data buffers available" on LPC54018

- vendors/espressif/boards/esp32/aws_demos/config_files/iot_pkcs11_config.h
- vendors/espressif/boards/esp32/aws_tests/config_files/iot_pkcs11_config.h
- vendors/espressif/boards/esp32/ports/pkcs11/iot_pkcs11_pal.c
ESP32 PKCS11 PAL: make NVS partition and namespace configurable
Description
-----------
This allows the common manufacturing pattern where per-device credentials are flashed as a separate read-only partition. This pattern allows the per-device credentials to be decoupled from user data, and simplifies the implementation of "factory reset" functionality (the user partition can just be reinitialised, leaving credentials intact)
Currently this requires patching AFR manually.
This PR addresses #1566 
Checklist:
----------
> ESP32 PKCS11 PAL: make NVS partition and namespace configurable

- libraries/abstractions/wifi/include/iot_wifi.h
- vendors/espressif/boards/esp32/ports/wifi/iot_wifi.c
Description
-----------
This commit adds eWiFiSecurityWPA2_ent into WIFISecurity structure to
let vendor be able to support Wi-Fi WPA2 enterprise security in the
future.
Since we have a pending release, the original PR is moved to release-candidate branch to run integration tests.
https://github.com/aws/amazon-freertos/pull/1595
Checklist:
----------
> Add eWiFiSecurityWPA2_ent into Wi-Fi Security types

- libraries/freertos_plus/standard/freertos_plus_tcp/source/portable/NetworkInterface/RX/NetworkInterface.c
- vendors/renesas/FIT/RDP_v1.15_modified/r_ether_rx/src/r_ether_rx.c
Description
-----------
In an earlier PR #1533, I made a change to:
vendors\renesas\FIT\RDP_v1.15_modified\r_ether_rx\src\r_ether_rx.c
In this patch I revert that change. Apparently I was mistaken about the exact meaning of `ETHER_FLAG_ON_LINK_ON`/`OFF`. I communicated with the Renesas FIT-team about this.
In fact, the effect of this change is not noticeable: the Link Status detection remains the same.
I retested the demo application. Also I connected and disconnected the RX65N to a network switch while running. And finally: I started without a LAN, and only connected it after a while. That all worked as expected.
Within `NetworkInterface.c`, logging will be suppressed for errors in the link status:
~~~c
if( xBytesReceived == ETHER_ERR_LINK )
{
/* Auto-negotiation is not completed, and …
> Renesas network interface: reverted change to FIT module

- demos/greengrass_connectivity/aws_greengrass_discovery_demo.c
Description
-----------
The Greengrass demo enabled ALPN by default, but this causes the demo to error on boards where ALPN has not been implemented. ALPN is not needed by Greengrass, and is not used in other demos.
Checklist:
----------
> fix: Disable ALPN for GGD demo

- libraries/abstractions/common_io/test/test_iot_i2s.c
This change provide commonly used I2S paramerts for this IOCTL
configuration test that we can assume it's safely going to be supported
by any I2S.
Why:
This is needed by MTK as the used parameters currently are not supported
by their chip.
Description
-----------
Checklist:
----------
> test: Change I2S IOCTL test parameters

- libraries/abstractions/common_io/include/iot_uart.h
- libraries/abstractions/common_io/test/test_iot_uart.c
Need to differentiate read/write complete status
Description
-----------
For console application which calling iot_uart, it's possible that console application will need to differentiate write and read complete status.
Checklist:
----------
> Need to differentiate read/write complete status

- tools/cmake/afr_module.cmake
Description
-----------
Fix a bug introduced in #1161, address issue #1652. See details in commit message.
Checklist:
----------
> Fix a dependency parsing bug in CMake from #1161

- libraries/abstractions/common_io/test/test_scripts/adc/test_iot_adc_test.py
- libraries/abstractions/common_io/test/test_scripts/adc/test_iot_runonPI_adc.sh
- libraries/abstractions/common_io/test/test_scripts/gpio/test_iot_gpio_test.py
- libraries/abstractions/common_io/test/test_scripts/gpio/test_iot_runonPI_gpio.sh
- libraries/abstractions/common_io/test/test_scripts/pwm/test_iot_pwm_test.py
- libraries/abstractions/common_io/test/test_scripts/pwm/test_iot_runonPI_pwm.sh
- libraries/abstractions/common_io/test/test_scripts/spi_master/test_iot_spi_master_test.py
- libraries/abstractions/common_io/test/test_scripts/test_iot_test_template.py
- libraries/abstractions/common_io/test/test_scripts/tsensor/test_iot_runonPI_tsensor.sh
- libraries/abstractions/common_io/test/test_scripts/tsensor/test_iot_tsensor_test.py
- libraries/abstractions/common_io/test/test_scripts/uart/test_iot_runonPI_uart.sh
- libraries/abstractions/common_io/test/test_scripts/uart/test_iot_uart_test.py
- libraries/abstractions/common_io/test/test_scripts/usb_device/test_iot_usb_device_test.py
Description
-----------
Convert all paths to be absolute so the tests do not have to be run in the specific folder.
Checklist:
----------
> Convert all paths to be absolute so the tests do not have to be run in the specific folder.

- demos/demo_runner/iot_demo_freertos.c
- demos/network_manager/aws_iot_network_manager.c
- libraries/c_sdk/standard/ble/include/iot_ble_data_transfer.h
- libraries/c_sdk/standard/ble/include/iot_ble_device_information.h
- libraries/c_sdk/standard/ble/src/iot_ble_gap.c
- libraries/c_sdk/standard/ble/src/iot_ble_gatt.c
- libraries/c_sdk/standard/ble/src/services/device_information/iot_ble_device_information.c
- libraries/c_sdk/standard/ble/src/services/mqtt_ble/iot_ble_data_transfer.c
- libraries/c_sdk/standard/ble/test/iot_test_wifi_provisioning.c
- tests/common/iot_tests_network.c
- vendors/espressif/boards/esp32/aws_demos/application_code/main.c
- vendors/espressif/boards/esp32/ports/ble/nimble/iot_ble_hal_common_gap.c
- vendors/espressif/boards/esp32/ports/ble/nimble/iot_ble_hal_gap.c
- vendors/espressif/boards/esp32/ports/ble/nimble/iot_ble_hal_gatt_server.c
- vendors/nordic/boards/nrf52840-dk/aws_demos/application_code/main.c
- vendors/nordic/boards/nrf52840-dk/aws_tests/application_code/main.c
- vendors/nordic/boards/nrf52840-dk/ports/ble/iot_ble_hal_common_gap.c
- vendors/nordic/boards/nrf52840-dk/ports/ble/iot_ble_hal_gap.c
- vendors/nordic/boards/nrf52840-dk/ports/ble/iot_ble_hal_gatt_server.c
Fix enable/disable sequence in BLE to support disabling and re-enabling stack at runtime.
Description
-----------
* Refactor IotBle_On() and IotBle_Off() functions to be symmetrical - enable/teardown GATT services and BLE stack.
* Example usage in demo runner to disable non-used networks for demo . (Disable BLE stack to save power and reclaim RAM after WiFi provisioning when WiFi is connected).
* Tested on ESP32 and Nordic.
PR also fixes #1576
Checklist:
----------
> Fix BLE enable disable sequence

- libraries/abstractions/common_io/test/test_iot_spi.c
Description
-----------
Declaring variables in the "for loop" is not allowed by TI-gcc compiler.
Checklist:
----------
> declare variables outside "for loop" in spi tests

- libraries/freertos_plus/standard/freertos_plus_tcp/source/FreeRTOS_UDP_IP.c
Description
-----------
Recently, it was decided to let `NetworkBufferDescriptor::xDataLength` always mean: the total size of the network packet. Before that, it could also mean: "payload size", depending on the location in the code. That was confusing.
This was changed in [PR #1513](https://github.com/aws/amazon-freertos/pull/1513).
However, by mistake, I hadn't tested the `ipconfigUSE_CALLBACKS` option with UDP after the PR.
In `xProcessReceivedUDPPacket()`, the value of `xDataLength` should have been corrected with `ipUDP_PAYLOAD_OFFSET_IPv4`:
~~~
+    /* The value of 'xDataLength' was proven to be at least the size of a
+    UDP packet in prvProcessIPPacket(). */
if( xHandler( ( Socket_t ) pxSocket,
( void* ) pcData,
-                  ( size_t ) pxNetworkBuffer->xDataLength,
+ …
> FreeRTOS+TCP : pass payload length when calling UDP callback

- libraries/abstractions/secure_sockets/lwip/iot_secure_sockets.c
Potential Segfault - Validate socket handle before dereferencing
Description
-----------
Validating the socket before dereferencing it
Checklist:
----------
> Fix: Potential Segfault - Validate socket handle before dereferencing

- libraries/abstractions/secure_sockets/lwip/iot_secure_sockets.c
check whether socket is connected before attempting to send
Description
-----------
Perform a check similar to the read one to make sure the socket is connected before calling lwip_send
Checklist:
----------
> Fix: check whether socket is connected before attempting to send

- libraries/abstractions/common_io/test/test_iot_i2c.c
Description
-----------
- remove unnecessary NO_STOP in test AFQP_IotI2CReadAsyncFailReadTwice
- move iot_i2c_set_callback after iot_i2c_write_sync in test AFQP_IotI2CCancelReadSuccess
- add configurable IOT_TEST_COMMON_IO_I2C_MAX_WRITE_LENGTH to limit the length of write buffer; this causes fault on TI
- provide a default value for IOT_TEST_COMMON_IO_I2C_MAX_WRITE_LENGTH 
- vendor can override it in "test_iot_config"
Checklist:
----------
> Fix several issues in I2C tests after testing on TI board

- libraries/freertos_plus/aws/greengrass/include/aws_greengrass_discovery.h
- libraries/freertos_plus/aws/greengrass/src/aws_greengrass_discovery.c
- libraries/freertos_plus/aws/greengrass/test/aws_test_greengrass_discovery.c
Description
-----------
GGD_JSONRequestGetFile() would not receive the entire file
in one call on some boards. This adds a loop to receive the
file in chunks if the request was not completed.
Checklist:
----------
> Fix: GGD Test failures on ST

- libraries/freertos_plus/standard/pkcs11/src/iot_pkcs11.c
- Always call C_FindObjectsFinal() after C_FindObjects()
- Invalidate object handle if object not found
Description
-----------
PR #1498 introduced a regression in which PKCS #11 object lookups are not terminated according
to the [specification](http://docs.oasis-open.org/pkcs11/pkcs11-base/v2.40/os/pkcs11-base-v2.40-os.html#_Toc416959743), and object handles are not invalidated as required by [`iot_tls.c:prvInitializeClientCredential()`](https://github.com/aws/amazon-freertos/blob/master/libraries/freertos_plus/standard/tls/src/iot_tls.c#L628).  This PR reverts these changes.
Checklist:
----------
> Fix PKCS #11 object lookup logic.

- vendors/espressif/esp-idf/components/bootloader_support/CMakeLists.txt
Fix bug where verification key was not embedded in app when Secure Boot is enable
Description
-----------
While building app with CMake, when secured boot is enabled, verification key is not embedded in the app. This leads to build failure.
This PR fixes the issue https://github.com/espressif/esp-idf/issues/4419
Checklist:
----------
> CMake bugfix when Secure Boot is enable

- libraries/abstractions/pkcs11/test/iot_test_pkcs11.c
PKCS#11 C_Sign. Added testcase to verify that if a NULL signature buffer is passed to C_Sign, the signature length required is returned.
Description
-----------
Checklist:
----------
> PKCS#11 Test case

- vendors/cypress/manifest.cmake
Description
-----------
Add board directory mapping to cypress. We can remove the hard coding from test infra with this fix.
Checklist:
----------
> Add board dir for cypress in CMake

- libraries/abstractions/secure_sockets/lwip/iot_secure_sockets.c
freeing memory that failed to be allocated, since it is not set to null
Description
-----------
SOCKETS_SetSockOpt option SOCKETS_SO_ALPN_PROTOCOLS
if the second malloc fails, all the remaining memory after the corresponding memory is not set to NULL.
When SOCKETS_Close is called, it is freeing the memory after the failed one, which results in a segmentation violation
Checklist:
----------
> Fix potential segfault: freeing memory that failed to be allocated, since it is not set to null

- vendors/nordic/boards/nrf52840-dk/ports/ble/iot_ble_hal_gap.c
Fix advertising slave connection interval in Nordic
Description
-----------
Nordic port was not including slave connection interval range in advertisement.
PR fixes this.
Checklist:
----------
> Fix advertising slave connection interval in Nordic

- libraries/abstractions/common_io/include/iot_uart.h
- libraries/abstractions/common_io/test/test_iot_i2c.c
- libraries/abstractions/common_io/test/test_iot_spi.c
Description
-----------
Address comments in this PR: https://github.com/aws/amazon-freertos/pull/1682
- refactored SPI tests code by putting the code of constructing assisted test message into one helper function
- minor update of UART data type in the comment
- formatting the iot_uart.h
Checklist:
----------
> Address comments of Common IO in PR 1682

- libraries/freertos_plus/standard/freertos_plus_tcp/source/portable/NetworkInterface/esp32/NetworkInterface.c
- vendors/espressif/boards/esp32/aws_demos/config_files/FreeRTOSIPConfig.h
- vendors/espressif/boards/esp32/aws_tests/config_files/FreeRTOSIPConfig.h
Description
-----------
While reviewing all major FreeRTOS+TCP network interfaces, ESP32 doesn't seem to need many changes, at most a bit of configuring.
It has a very basic NetworkInterface.c which can do initialisation, send and receive. It does not start its own task, a "deferred interrupt handler". In stead, the "wifi" task handles the reception and it will call `wlanif_input()` to forward a network packet to the IP-task.
The IP/task calls `xNetworkInterfaceOutput()` to send out a packet, as in any other implementation.
I thought I had found an "issue": during a performance test, many packets got lost. The IP-stack responded with selective ACK's, because packets were missing.
Normally, the following resources must be checked, beside the available heap:
1) The number of free network …
> FreeRTOS+TCP : Espressif ESP32 NetworkInterface

- libraries/freertos_plus/standard/freertos_plus_tcp/source/FreeRTOS_DHCP.c
Description
-----------
DHCP option 61 i.e. `Client-Identifier` consist of type-value pairs. In FreeRTOS TCP stack, value is assigned, while the type is missing.
Hence, type is added in Client-identifier option, which has value 0x1. `0x1` corresponds to `Ethernet`.
Checklist:
----------
> Fix DHCP option Client-identifier

- vendors/pc/boards/windows/ports/ota/aws_ota_pal.c
Description
-----------
Allow winsim to also use the compiled code signing cert from `aws_ota_codesigner_certificate.h` as a fallback option.
Checklist:
----------
> Fallback to compiled code signing cert on winsim

- tools/ota_e2e_tests/aws_ota_test/aws_ota_aws_agent.py
Description
-----------
Fix a bug in OTA E2E script when it's called with non-prod stage.
Sanity check: https://amazon-freertos-ci.corp.amazon.com/job/esp-ota-e2e-release-1.5/610/testReport/esp32_wrover_kit/OTAEndToEndTests/
Checklist:
----------
> Fix CLI command for non-prod stage in OTA E2E

- libraries/freertos_plus/standard/freertos_plus_tcp/source/portable/NetworkInterface/Common/phyHandling.c
- libraries/freertos_plus/standard/freertos_plus_tcp/source/portable/NetworkInterface/STM32Fxx/NetworkInterface.c
- libraries/freertos_plus/standard/freertos_plus_tcp/source/portable/NetworkInterface/STM32Fxx/readme.txt
- libraries/freertos_plus/standard/freertos_plus_tcp/source/portable/NetworkInterface/STM32Fxx/stm32f2xx_hal_eth.h
- libraries/freertos_plus/standard/freertos_plus_tcp/source/portable/NetworkInterface/STM32Fxx/stm32f4xx_hal_eth.h
- libraries/freertos_plus/standard/freertos_plus_tcp/source/portable/NetworkInterface/STM32Fxx/stm32f7xx_hal_eth.h
- libraries/freertos_plus/standard/freertos_plus_tcp/source/portable/NetworkInterface/STM32Fxx/stm32fxx_hal_eth.c
- libraries/freertos_plus/standard/freertos_plus_tcp/source/portable/NetworkInterface/STM32Fxx/stm32fxx_hal_eth.h
- libraries/freertos_plus/standard/freertos_plus_tcp/source/portable/NetworkInterface/include/phyHandling.h
Description
-----------
Source file `networkInterface.c` :
- `ipconfigZERO_COPY_TX_DRIVER` : The driver was supposed to work for both the zero-copy and the copy-implementation. However, the copy-version was never fully implemented. In this version, both copy and zero-copy can be used..
- `ipconfigDRIVER_INCLUDED_RX_IP_CHECKSUM` / `ipconfigDRIVER_INCLUDED_TX_IP_CHECKSUM` : both enabled and disabled can be used int the new release.
Normally one will enable the automatic offloading of checksums because it helps the performance. Only for testing purposes, it can be handy to change this.
- PHY handling: the handling of the connected PHY is now done in a separate module: `Common/phyHandler.c`. It recognises the attached PHY automatically and starts auto negotiation. Also it can poll for the PHY …
> FreeRTOS+TCP : STM32Fxx network interface Updated

- tools/cbmc/proofs/ninja.py
This patch adds a python script that generates a ninja build file for cbmc proofs.  The build file makes it easy to check a collection of proofs concurrently using the concurrency of a ninja build.  The list of proofs to check can be specified in the command line, in a json file, or simply found in the local filesystem.
> Add python script to run cbmc proofs concurrently with ninja.

- libraries/abstractions/common_io/test/test_iot_flash.c
None
None
Description
-----------
Checklist:
----------
> Fix Flash test code to not overflow the size of flash.

- tools/ota_e2e_tests/aws_ota_test/aws_ota_test_runner.py
Description
-----------
For OTA Jobs, dots are not accepted. If a dot is provided, we will replace it to an underscore in the script for IoT Core related actions.
Checklist:
----------
> OTA e2e scripts: Replace dots with underscores

- libraries/abstractions/common_io/test/iot_test_common_io.c
- libraries/abstractions/common_io/test/test_iot_adc.c
- libraries/abstractions/common_io/test/test_iot_efuse.c
- libraries/abstractions/common_io/test/test_iot_i2c.c
- libraries/abstractions/common_io/test/test_iot_internal.h
- libraries/abstractions/common_io/test/test_iot_pwm.c
- libraries/abstractions/common_io/test/test_iot_uart.c
This change provide:
1- Using macros to enable/diable running tests for peripherals
2- Default the macros to "enable", to avoid forgetting about setting it
for a test
3- Unify the macro used to enable the test or not with the old macro
that would set the number of tests to run.
3- Collect all variables that can be changed by the peripheral
configuration function into one header.
Why:
- Simplifying the header exposed to the vendors
- Reduce macros needed for each peripheral
Description
-----------
Checklist:
----------
> test: Expand on how we enable/disable peripheral tests

- libraries/abstractions/common_io/test/test_iot_battery.c
Fix Test group name used in BATTERY test code
Description
-----------
Changing seemingly typo in the battery test group name, from TEST_IOT_RTC to TEST_IOT_BATTERY.
Checklist:
----------
> Fix Test group name used in BATTERY test code

- libraries/abstractions/common_io/test/test_iot_timer.c
Wait for 1ms before getting the timer count. Timer count may still be zero
Description
-----------
Wait for 1ms before getting the timer count. Timer count may still be zero
Checklist:
----------
> Fix timer test code to wait before trying to get the count

- .gitmodules
- tools/cmake/afr_module.cmake
- tools/ota_e2e_tests/aws_ota_test/aws_ota_aws_agent.py
- tools/ota_e2e_tests/aws_ota_test/aws_ota_test_runner.py
- tools/ota_e2e_tests/poetry.lock
- tools/ota_e2e_tests/pyproject.toml
- vendors/cypress/manifest.cmake
Update FreeRTOS-Kernel submodule branch to release-candidate
Description
-----------
Update FreeRTOS-Kernel submodule branch from V10.2.1-convergence-FreeRTOS-Source
to release-candidate_10.3.0_rc3
commit id: d7550ef1a0560ceddac7c0b8bc0148272ac641a6
Checklist:
----------
> Bringing changes for AFR Release 202002.00

- libraries/3rdparty/tracealyzer_recorder/Include/trcKernelPort.h
Description
-----------
Due to the kernel version bump, Tracealyzer also needs to be updated. This is to fix the build failure on Windows and Microchip in this PR -- https://github.com/aws/amazon-freertos/pull/1723
Checklist:
----------
> Variable name change from uxPendedTicks to xPendedTicks.

- demos/dev_mode_key_provisioning/src/aws_dev_mode_key_provisioning.c
xProvisionDevice checks for NULL certs and keys, but a path existed that caused it to try and provision a NULL private key.
This caused a hard fault on ST and TI when credentials were NULL.
Description
-----------
Checklist:
----------
> Fixed hard fault on ST and TI Caused By Call To xProvisionDevice

- .gitmodules
Description
-----------
Update FreeRTOS-Kernel submodule branch from release-candidate_10.3.0_rc3 to V10.3.0-kernel-only
commit id: 210b1ffcc87bcff93871a37fbf0ad2033870ecaf
Checklist:
----------
> Update FreeRTOS-Kernel submodule to V10.3.0-kernel-only

- libraries/c_sdk/standard/https/test/system/iot_tests_https_system.c
Description
-----------
HTTPS_Client_System test Group is fails for TI when connecting to
'httpbin.org'. Connect to 'postman-echo.com' to solve this issue.
Checklist:
----------
> change http echo server from 'httpbin.org' to 'postman-echo.com'

- projects/microchip/curiosity_pic32mzef/mplab/aws_demos/nbproject/configurations.xml
- projects/microchip/curiosity_pic32mzef/mplab/aws_tests/nbproject/configurations.xml
- vendors/microchip/boards/curiosity_pic32mzef/CMakeLists.txt
- vendors/microchip/boards/curiosity_pic32mzef/aws_demos/config_files/FreeRTOSConfig.h
- vendors/microchip/boards/curiosity_pic32mzef/aws_tests/config_files/FreeRTOSConfig.h
This change is necessary because FreeRTOS based projects should not use the C runtime heap. Instead
they should use the FreeRTOS managed Heap. I have changed the C runtime heap allocation from
170KB to 10KB, and in turn increased the FreeRTOS heap size by 160KB.
Description
-----------
Checklist:
----------
> Reduce Microchip C Runtime Heap Size and Increase FreeRTOS Heap Size

- projects/cypress/CYW943907AEVAL1F/wicedstudio/aws_demos/.project
- projects/cypress/CYW943907AEVAL1F/wicedstudio/aws_tests/.project
- projects/cypress/CYW954907AEVAL1F/wicedstudio/aws_demos/.project
- projects/cypress/CYW954907AEVAL1F/wicedstudio/aws_tests/.project
- vendors/cypress/WICED_SDK/WICED/RTOS/FreeRTOS/FreeRTOS.mk
- vendors/cypress/freertos_thirdparty_port/GCC/Wiced_CY/port.c
- vendors/cypress/freertos_thirdparty_port/GCC/Wiced_CY/portASM.S
- vendors/cypress/freertos_thirdparty_port/GCC/Wiced_CY/portmacro.h
Description
-----------
In previous releases, we "accidentally" committed a kernel port in kernel third party directory. This is unnecessary since third party port is essentially the same as ```GCC/ARM_CRx_No_GIC```. In this kernel release, we removed the redundant third party ports. We attempted to switch over to ```GCC/ARM_CRx_No_GIC``` in https://github.com/aws/amazon-freertos/pull/1746. Given - we don't know whether this MCU indeed supports floating point (data sheet did not mention) and we are having issue with tool chain flashing, I'm temporarily making a copy to unblock. 
Moving forward, we should reach out Cypress to get some context on FPU. Also, IDE debug needs to work and getting started guide should be updated. 
Checklist:
----------
By submitting this pull request, I confirm …
> Cypress kernel dependency workaround

- libraries/freertos_plus/standard/freertos_plus_tcp/source/portable/NetworkInterface/STM32Fxx/NetworkInterface.c
- libraries/freertos_plus/standard/freertos_plus_tcp/source/portable/NetworkInterface/STM32Fxx/readme.txt
Network Interface for STM32F, follow-up
Description
-----------
This PR is a follow on the earlier [#1638](https://github.com/aws/amazon-freertos/pull/1638)
It clarifies the use of a linker section `.first_data`, see discussion with Gary [here](https://github.com/aws/amazon-freertos/pull/1638#discussion_r370922182)
Checklist:
----------
> FreeRTOS+TCP : STM32Fxx network interface Updated, after Gary's comments

- vendors/renesas/boards/rx65n-rsk/aws_demos/config_files/FreeRTOSIPConfig.h
- vendors/renesas/boards/rx65n-rsk/aws_tests/config_files/FreeRTOSIPConfig.h
Temporary Change required to get the Renesas tests/demos running
Description
-----------
There is an issue with the implementation of the FreeRTOS_gethostbyname. (FreeRTOS_DNS.c)
It is supposed to return the ipaddress converted long integer if the input is an IP address. The logic is there but there is a flag checking around the logic: if (ipconfigINCLUDE_FULL_INET_ADDR == 1).
Renesas happens to have that flag set to 0 in FreeRTOSIPConfig.h
So the GG Core address was correctly retrieved from the gg core json file, but was never able to connect. (The ip address was converted to 0).
As a short term fix, the #define ipconfigINCLUDE_FULL_INET_ADDR was changed from 0 to 1 in FreeRTOSIPConfig.h for Renesas. 
For long run, the issue with FreeRTOS_gethostbyname should be fixed. (including …
> Release candidate

- libraries/abstractions/common_io/test/test_iot_i2c.c
- libraries/abstractions/common_io/test/test_iot_internal.h
- libraries/abstractions/common_io/test/test_scripts/i2c_master/test_iot_i2c_master_rp3.py
- libraries/abstractions/common_io/test/test_scripts/i2c_master/test_iot_i2c_master_test.py
- libraries/abstractions/common_io/test/test_scripts/i2c_master/test_iot_runonPI_i2c_master.sh
Description
-----------
Created iot test, scripts for dut, host and rpi respectively. For the i2c write test, 15 bytes are generated randomly by dut and sent to rpi. The host compares the read bytes by rpi and write bytes by dut. For the i2c read test, 16 bytes are generated randomly by rpi and sent to dut. The dut has to read twice to mitigate the limitation of rpi. The host compares the second read of dut with the first write of rpi.
Run test script in the i2c_master folder
$ ./test_iot_i2c_master_test.py -i <ip> -l <login> -s <pwd> -p <serial>
Output result
tests start
2020-01-24 17:13:51.903284 [INFO] test_IotI2CWriteSyncAssisted 0  PASS  :  test_IotI2CWriteSyncAssisted Passed
2020-01-24 17:13:55.546245 [INFO] test_IotI2CWriteAsyncAssisted 0  PASS  :  test_IotI2CWriteAsyncAssisted …
> Check in assisted tests for I2C master

- tools/cbmc/patches/0005-Remove-volatile-qualifier-from-tasks-variables.patch
- tools/cbmc/patches/0006-Remove-static-from-prvNotifyQueueSetContainer.patch
- tools/cbmc/proofs/Queue/QueueGenericSend/QueueGenericSend_harness.c
- tools/cbmc/proofs/TaskPool/TaskDelay/README.md
- tools/cbmc/proofs/TaskPool/TaskDelay/tasks_test_access_functions.h
- tools/cbmc/proofs/TaskPool/TaskIncrementTick/tasks_test_access_functions.h
- tools/cbmc/proofs/TaskPool/TaskResumeAll/README.md
- tools/cbmc/proofs/TaskPool/TaskResumeAll/tasks_test_access_functions.h
This ensures that CBMC proofs are able to build after the name-change in
commit 23839bb.
> Change uxPendedTicks to xPendedTicks in all proofs

- libraries/abstractions/common_io/test/test_iot_spi.c
Description
-----------
Why: The byte count in the no of bytes assertion is incorrect.
Checklist:
----------
> Test: Fix wrong no of bytes assert in spi assisted tests

- libraries/c_sdk/standard/ble/include/iot_ble_data_transfer.h
- libraries/c_sdk/standard/ble/src/services/mqtt_ble/iot_ble_data_transfer.c
Description
-----------
callback for control gatt characteristic was sending responses even for eBLEWriteNoResponse.
If the client didn't request/expect a response, don't waste the cycles
Checklist:
----------
> Remove unrequested responses and avoid potential NULL deref

- vendors/nordic/boards/nrf52840-dk/ports/ota/aws_ota_pal.c
Fix Nordic OTA PAL Tests
Description
-----------
OTA PAL for Nordic assumes soft device task to always post events, for flash APIS, for which the soft device task needs to be enabled beforehand.
As part of the commit# 893f09ee40f0f6ec46d0763dcb4e4c577b1405ba  enable soft device has been postponed to when BLE is enabled. 
Also, as per the [documentation](https://github.com/aws/amazon-freertos/blob/f33863740032c59307b1849629c736a416ea2687/vendors/nordic/nRF5_SDK_15.2.0/components/softdevice/s112/headers/nrf_soc.h#L830),  flash Apis for Nordic does not require soft device to be running.
Fix: Adding a check if soft device is enabled before waiting for events from soft device task.
Checklist:
----------
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute …
> Fix Nordic OTA PAL Tests

- libraries/abstractions/secure_sockets/lwip/iot_secure_sockets.c
remove unreachable path from secure sockets
Description
-----------
The Check "if( ctx->ip_socket )" will always evaluate to true as long as the Socket_t is a valid pointer
Checklist:
----------
> Fix: remove uncecessary conditions

- libraries/abstractions/common_io/test/test_iot_uart.c
Description
-----------
Fix async test by separating read and write semaphore.
Test case AFQP_IotUARTWriteReadAsyncWithCallback failed on ST board because it waits for write to complete before making a read call. That incurred UART overrun error. 
So the right way is to start async write and async read at the same time and verify each of them completes. I solve this problem by separating it to two semaphores.
Checklist:
----------
> Fix async test by separating read and write semaphore

- libraries/freertos_plus/standard/freertos_plus_posix/source/FreeRTOS_POSIX_timer.c
- vendors/microchip/boards/curiosity_pic32mzef/aws_demos/config_files/FreeRTOSConfig.h
- vendors/microchip/boards/curiosity_pic32mzef/aws_tests/config_files/FreeRTOSConfig.h
Microchip Specific changes to remove possible bugs
Description
-----------
`#define configENABLE_BACKWARD_COMPATIBILITY` flag was enabling a `#define xTimerHandle TimerHandle_t`. This was causing an issue in the functions `timer_delete`, `timer_settime` and `timer_gettime` defined in `FreeRTOS_POSIX_timer.c` since these functions were using variables named `xTimerHandle`.
The timer_t type when expanded results in an unsigned long (since the compiler uses its own version of POSIX library which is included in its toolchain and we cannot change that) in some Microchip compilers. The compiler does an implicit typecast (which is also bad) which we cannot get around, thus to suppress the warnings, we explicitly typecast the unsigned long to TimerHandle_t. TimerHandle_t is a struct pointer.
- …
> Microchip Specific changes to remove possible bugs

- libraries/abstractions/ble_hal/include/bt_hal_avsrc_profile.h
- libraries/abstractions/ble_hal/include/bt_hal_gatt_client.h
- libraries/abstractions/ble_hal/include/bt_hal_gatt_server.h
- libraries/abstractions/ble_hal/include/bt_hal_gatt_types.h
- libraries/abstractions/ble_hal/include/bt_hal_manager.h
- libraries/abstractions/ble_hal/include/bt_hal_manager_adapter_ble.h
- libraries/abstractions/ble_hal/include/bt_hal_manager_adapter_classic.h
- libraries/abstractions/ble_hal/include/bt_hal_manager_types.h
Update BLE HAL
Description
-----------
* Update BTGattStatus_t to match BT 5.0
* Change BTStatus_t to BTGattStatus_t for GATT Client callbacks
* Add pxMultiAdvSetInstRawData in bt_hal_manager_adapter_ble
* Add back pxBondedCb and ucTimeout and mark as deprecated
Checklist:
----------
> Update BLE HAL

- libraries/abstractions/common_io/test/test_iot_internal.h
- libraries/abstractions/common_io/test/test_iot_pwm.c
- libraries/abstractions/common_io/test/test_scripts/pwm/test_iot_pwm_rp3.py
Description
-----------
Why: The pwm input pin is also used by gpio test on the rpi before. It is better to separate from each other.
Checklist:
----------
> test: decouple pins for pwm test with gpio test

- vendors/st/boards/stm32l475_discovery/ports/common_io/iot_i2c.c
Description
-----------
Fix ST I2C bug by adding break in switch block
Checklist:
----------
> Fix ST I2C bug by adding break in switch block

- vendors/pc/boards/windows/aws_demos/config_files/aws_ota_agent_config.h
- vendors/pc/boards/windows/aws_tests/config_files/aws_ota_agent_config.h
WinSim OTA e2e test had issue to keep the file transfer connection open.  
Changed the request to 1 block at a time.  The block size will remain as 4K.
Checklist:
----------
> Changes in WinSim OTA config to use 1block/request

- libraries/freertos_plus/standard/freertos_plus_tcp/source/portable/NetworkInterface/ksz8851snl/ksz8851snl.c
- libraries/freertos_plus/standard/freertos_plus_tcp/source/portable/NetworkInterface/ksz8851snl/ksz8851snl.h
- libraries/freertos_plus/standard/freertos_plus_tcp/source/portable/NetworkInterface/ksz8851snl/ksz8851snl_reg.h
Added files necessary for the network interface
Description
-----------
The files listed below were missing (as pointed out by Hein in his email on 6th March morning 12:36AM):
portable/NetworkInterface/ksz8851snl/ksz8851snl.c
portable/NetworkInterface/ksz8851snl/ksz8851snl.h
portable/NetworkInterface/ksz8851snl/ksz8851snl_reg.h
Copied from GitHub/freertos repo. [ https://github.com/FreeRTOS/FreeRTOS/tree/master/FreeRTOS-Plus/Source/FreeRTOS-Plus-TCP/portable/NetworkInterface/ksz8851snl ]
Checklist:
----------
> Added files necessary for the ksz8851snl network interface

- libraries/abstractions/ble_hal/include/bt_hal_avsrc_profile.h
- libraries/abstractions/ble_hal/include/bt_hal_gatt_client.h
- libraries/abstractions/ble_hal/include/bt_hal_gatt_server.h
- libraries/abstractions/ble_hal/include/bt_hal_gatt_types.h
- libraries/abstractions/ble_hal/include/bt_hal_manager.h
- libraries/abstractions/ble_hal/include/bt_hal_manager_adapter_ble.h
- libraries/abstractions/ble_hal/include/bt_hal_manager_adapter_classic.h
- libraries/abstractions/ble_hal/include/bt_hal_manager_types.h
Add back stddef.h
Description
-----------
* Need to add back stddef.h in bt_hal_avsrc_profile.h
Checklist:
----------
> Add back stddef.h

- libraries/freertos_plus/standard/tls/src/iot_tls.c
Description
-----------
`TLS_Cleanup()` was not calling `prvFreeContext()` for unsuccessful TLS handshakes.  This can cause a memory leak if the necessary credentials [can't be loaded](https://github.com/aws/amazon-freertos/blob/master/libraries/freertos_plus/standard/tls/src/iot_tls.c#L553).  This change ensures that mbedtls resources are freed on `TLS_Cleanup()` even if the handshake didn't complete.  Note that PKCS11 resources are freed independently in the case where [`C_OpenSession()` fails](https://github.com/aws/amazon-freertos/blob/master/libraries/abstractions/pkcs11/mbedtls/iot_pkcs11_mbedtls.c#L1028).
Checklist:
----------
> Free mbedtls resources in TLS_Cleanup().

- vendors/nordic/nRF5_SDK_15.2.0/external/nrf_cc310/common/integration_test_ssi_defs.h
Description
-----------
Note that some macros are wrong, lucky is nobody uses them now, 
so fixed them to avoid more errors in the future:
SHARED_SECRET_MAX_LENGHT ->  SHARED_SECRET_MAX_LENGTH    
ECC_KEY_MAX_LENGHT ->  ECC_KEY_MAX_LENGTH    
AES_KEY_MAX_LENGHT_IN_BYTES -> AES_KEY_MAX_LENGTH_IN_BYTES
Checklist:
----------
> Fixed macro error

- demos/include/aws_demo.h
Description
-----------
Remove unused function prototype vApplicationInit in aws_demo.h. This was brought to our attention by a customer through github issues. https://github.com/aws/amazon-freertos/issues/1821
Checklist:
----------
> Remove unused function prototype vApplicationInit

- libraries/freertos_plus/standard/freertos_plus_tcp/source/portable/NetworkInterface/esp32/NetworkInterface.c
- vendors/pc/boards/windows/aws_tests/config_files/FreeRTOSIPConfig.h
Logging function use cleaned up
Description
-----------
The logging function was being guarded by multiple #ifs all over the code. Instead of doing that at every single place, a #define was used to guard the declaration and definition itself. It makes the code look cleaner and might help future users avoid mistakes.
Code tests:
- Custom Cmake (#define ipconfigHAS_PRINTF = 1). The tests show that shadow did not pass, but since that doesn't have anything to do with this change I have assumed that the code works. (Also other tests passed)
- Custom Cmake (#define ipconfigHAS_PRINTF = 0). The tests show that OTA did not pass, but since that doesn't have anything to do with this change I have assumed that the code works. (Also other tests passed)
Checklist:
----------
By submitting this pull …
> Logging function use cleaned up

- libraries/abstractions/pkcs11/mbedtls/iot_pkcs11_mbedtls.c
- vendors/infineon/secure_elements/pkcs11/iot_pkcs11_trustx.c
These two struct members, xFindObjectInit, and xFindObjectComplete, are undocumented and unused. There is no reference in the code to xFindObjectInit being used.
xFindObjectComplete is actually used, but the code path it is used in is either impossible, or a bug. Since the P11SessionPtr_t struct is memset to 0
immediately after being malloc'd the line of code using xFindObjectComplete will always evaluate to false, as it is comparing it to CK_TRUE,
as CK_TRUE is equal to 1, and xFindObjectComplete is never explicitly set to 1.
Description
-----------
Checklist:
----------
> Removed Unused Struct Members Related to Find_Objects.

- libraries/c_sdk/standard/ble/include/iot_ble.h
- libraries/c_sdk/standard/ble/include/iot_ble_config_defaults.h
- libraries/c_sdk/standard/ble/src/iot_ble_gap.c
- libraries/c_sdk/standard/ble/test/iot_test_ble_end_to_end.c
- tests/common/aws_test_runner.c
- tests/common/iot_tests_network.c
- vendors/espressif/boards/esp32/ports/ble/bluedroid/iot_ble_hal_common_gap.c
- vendors/espressif/boards/esp32/ports/ble/bluedroid/iot_ble_hal_gap.c
- vendors/espressif/boards/esp32/ports/ble/bluedroid/iot_ble_hal_internals.h
Add set device name API 
Description
-----------
Add a new API to set device name for BLE at run time. This facilitates reading the device name from a storage example flash and configuring different names for different devices without changing code.
Minor - Replaced some static variables (used only once) to functions to save RAM.
Checklist:
----------
> [BLE] Add set device name API

- tools/cbmc/proofs/HTTP/global_state_HTTP.c
This commit attempts to preserve the functionality of the memory checks
in is_valid_IotResponseHandle until the issue in
https://github.com/diffblue/cbmc/issues/5194 is sorted out. This commit
is needed because is_valid_IotResponseHandle uses the __CPROVER_r_ok and
__CPROVER_w_ok macros, and is_valid_IotResponseHandle itself is used
inside an assume statement, triggering the issue mentioned in that bug.
> Remove {r,w}_ok from is_valid_IotResponseHandle

- vendors/espressif/boards/esp32/ports/ota/aws_ota_pal.c
Description
-----------
When SPIRAM is enabled, available heap is enough to support OTA data over HTTP along with BLE.
Hence, memory constraints should be checked only when SPIRAM is disabled.
Checklist:
----------
> Support OTA data over HTTP together with BLE on ESP32 when SPIRAM is enabled

- vendors/pc/boards/windows/aws_tests/config_files/FreeRTOSConfig.h
Currently the winsim test project is configured to network adapter 3. If this adapter is incorrect for your windows PC, the project will seemingly
get stuck after successfully opening the network port. This issue is very hard to debug, as the project appears to just be frozen. If we configure this
network port to 0, the test project will be unable to open the network adapter, and print a helpful error message that helps the user configure it to the right
network adapter.
Description
-----------
Checklist:
----------
> Change Default Winsim Test Port to 0

- libraries/c_sdk/aws/shadow/test/aws_test_shadow.c
- tests/common/aws_test_runner.c
Description
-----------
Creates a new unit test group for the Shadow `ClientCreateDelete` test, which is part of the old Shadow API. The tests were kept in the same file to follow the same pattern as [MQTT](https://github.com/aws/amazon-freertos/blob/master/libraries/c_sdk/standard/mqtt/test/iot_test_mqtt_agent.c), where all test groups for the v1 API are in a single file. The `Shadow_Unit_` prefix was not used for the test groups to avoid confusion with the v4 Shadow API, which uses those group names.
Checklist:
----------
> Separate old shadow unit test

- demos/defender/aws_iot_demo_defender.c
- demos/https/iot_demo_https_s3_download_async.c
- demos/mqtt/iot_demo_mqtt.c
- demos/network_manager/aws_iot_network_manager.c
- libraries/c_sdk/aws/shadow/src/aws_iot_shadow_api.c
- libraries/c_sdk/aws/shadow/src/aws_iot_shadow_operation.c
- libraries/c_sdk/aws/shadow/src/aws_iot_shadow_parser.c
- libraries/c_sdk/standard/ble/src/services/wifi_provisioning/iot_ble_wifi_provisioning.c
- libraries/c_sdk/standard/common/include/iot_logging_setup.h
- libraries/c_sdk/standard/https/src/iot_https_client.c
- libraries/c_sdk/standard/mqtt/src/iot_ble_mqtt_serialize.c
- libraries/c_sdk/standard/mqtt/src/iot_mqtt_operation.c
Fix Format specifier warnings
Allow logging override for log library.
Description
-----------
This PR contains changes enable overriding IotLog macro with a custom logging function by defining it in `iot_config.h`.
Also the PR aims to fix format specifier warnings like:
- Incorrect number of arguments to logger.
- Incorrect format specifier types
Checklist:
----------
> Enable IotLog override and fix format specifier warnings.

- libraries/c_sdk/standard/ble/src/services/mqtt_ble/iot_ble_data_transfer.c
- libraries/c_sdk/standard/ble/utest/iot_ble_data_transfer_utest.c
Remove read permission on RX char.
PR Fixes #1845 
Description
-----------
Read permission is not required for RX characteristics as its used to write data to the device.
Added unit tests to catch this behavior.
Checklist:
----------
> BLE data transfer: Remove read permission on RX char

- projects/pc/windows/visual_studio/aws_tests/aws_tests.vcxproj
Description
-----------
Line initially put in #1854.
Specifying WindowsTargetPlatformVersion in the project file makes it specific to an SDK version which fails to build in our tests. 
After fix: https://amazon-freertos-ci.corp.amazon.com/job/im_v1_master/job/custom_ide/job/pc/job/windows-ide/768/console
Checklist:
----------
> Remove specific target platform version from VS project file

- libraries/abstractions/common_io/test/test_iot_adc.c
Description
-----------
Refactored tests to perform open/close during setup/tear-down phases.
This is part of the work related to the following issue: https://github.com/aws/amazon-freertos/issues/1859
Checklist:
----------
> common-io: Refactoring ADC test cases

- libraries/c_sdk/aws/defender/test/system/aws_iot_tests_defender_system.c
Description
-----------
This PR re-includes Metrics_TCP_connections_all_are_published_multiple_sockets as a system test. 
This test was last included [here](https://github.com/aws/amazon-freertos/blob/a6a459b5e498f92db5ab16d6bf69f8d449d8c8e9/libraries/c_sdk/aws/defender/test/aws_iot_tests_defender_api.c) but was removed after transferring tests from C SDK: #1854 
Note that _verifyTcpConnections( int total ) is not changed back to _verifyTcpConnections( int total, ... ) due to lack of platform-specific tests.
Checklist:
----------
> Reinclude multiple-sockets metrics test from pre-separation as a system test

- libraries/abstractions/common_io/test/test_iot_uart.c
Description
-----------
Refactored open/close to be done in setup/tear-down stages. 
Updated word length defines to number of bits.
Added checks for optional features such as flow-control support. 
Refactored loopback tests to perform read->write instead of write->read.
This is part of the work related to the following issue:
https://github.com/aws/amazon-freertos/issues/1859
Checklist:
----------
> common-io: Refactoring and updates to UART test cases

- .gitmodules
- libraries/3rdparty/mbedtls_config/aws_mbedtls_config.h
This PR updated the mbedTLS to point to v2.16.5
Description
-----------
Here is the change log between mbedTLS v2.16.0 (Current version) and v2.16.5
Features
(2.16, 2.7) Add MBEDTLS_REMOVE_3DES_CIPHERSUITES to allow removing 3DES ciphersuites from the default list (enabled by default). See https://sweet32.info/SWEET32_CCS16.pdf.
Bugfix
(2.16) Fix a compilation issue with mbedtls_ecp_restart_ctx not being defined when MBEDTLS_ECP_ALT is defined. Reported by jwhui. Fixes #2242.
(2.16, 2.7) Run the AD too long test only if MBEDTLS_CCM_ALT is not defined. Raised as a comment in #1996.
(2.16) Reduce the stack consumption of mbedtls_mpi_fill_random() which could previously lead to a stack overflow on constrained targets.
(2.16) Add MBEDTLS_SELF_TEST for the mbedtls_self_test functions in the …
> Update mbedTLS to v2.16.5

- libraries/abstractions/common_io/test/test_iot_gpio.c
Description
-----------
* Refactor tests to use TEST_PROTECT sections. 
* Added checks for some functions that could be unsupported by the HW. 
* Added use of pull-up in read-back test for open-drain output
* Removed setup-phase code as setting GPIO functionality might not be supported as per API description. 
Checklist:
----------
> common-io: Refactoring GPIO test cases

- libraries/freertos_plus/aws/ota/test/aws_test_ota_agent.c
Description
-----------
MQTT connect in the OTA agent tests did not have retries before and could easily fail. This PR addresses the problem.
Checklist:
----------
> Add retries to MQTT connect in OTA agent tests

- libraries/3rdparty/mbedtls_utils/README.md
- libraries/abstractions/pkcs11/mbedtls/iot_pkcs11_mbedtls.c
Fix documentation typos in `iot_pkcs11_mbetls.c`
Description
-----------
Resolves documentation typos pointed in #1875 
Update `mbedtls_utils/README.md` about the new `mbedtls_strerror_highlevel` and `mbedtls_strerror_lowlevel` utilities
Checklist:
----------
> Fix doc typos

- libraries/abstractions/common_io/test/test_iot_i2c.c
Description
-----------
Remove port specific portYIELD_FROM_ISR in I2C tests.
I2C tests is supposed to be platform independent. I didn't realize portYIELD_FROM_ISR is port-specific until the implementation of ESP: https://github.com/aws/amazon-freertos/pull/1850/files
After second thought, portYIELD_FROM_ISR should not be strictly required in Common IO tests. 
Checklist:
----------
> Remove port specific portYIELD_FROM_ISR in I2C tests

- .gitmodules
Description
-----------
Security
* Fix side channel in ECC code that allowed an adversary with access to
precise enough timing and memory access information (typically an
untrusted operating system attacking a secure enclave) to fully recover
an ECDSA private key. Found and reported by Alejandro Cabrera Aldaya,
Billy Brumley and Cesar Pereida Garcia. CVE-2020-10932
* Fix a potentially remotely exploitable buffer overread in a
DTLS client when parsing the Hello Verify Request message.
Bugfix
* Fix compilation failure when both MBEDTLS_SSL_PROTO_DTLS and
MBEDTLS_SSL_HW_RECORD_ACCEL are enabled.
* Fix a function name in a debug message. Contributed by Ercan Ozturk in
#3013.
Checklist:
----------
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this …
> Set mbedTLS version to 2.16.6

- projects/cypress/CY8CKIT_064S0S2_4343W/mtb/aws_demos/afr.mk
- projects/cypress/CY8CKIT_064S0S2_4343W/mtb/ota/afr.mk
- projects/cypress/CY8CKIT_064S0S2_4343W/mtb/wifi_scanner/afr.mk
ModusToolbox: Fix MTB builds
Description
-----------
Exclude freertos_thirdparty_port from being built in the projects.
Checklist:
----------
> ModusToolbox: Fix MTB builds

- CMakeLists.txt
The Linux unit test was broken, because a library target was referenced before the unit test conditional statement.
Description
-----------
Checklist:
----------
> Fix Linux Unit Test build

- libraries/abstractions/common_io/test/test_iot_spi.c
- libraries/abstractions/common_io/test/test_iot_uart.c
Description
-----------
Remove port specific code in SPI and UART tests
Common IO tests is supposed to be platform independent. I didn't realize portYIELD_FROM_ISR is port-specific until the implementation of ESP: https://github.com/aws/amazon-freertos/pull/1850/files
After second thought, portYIELD_FROM_ISR should not be strictly required in Common IO tests.
Checklist:
----------
> Remove port specific code in SPI and UART tests

- vendors/microchip/boards/ecc608a_plus_winsim/aws_tests/config_files/aws_test_ota_config.h
- vendors/pc/boards/windows/aws_tests/config_files/aws_test_ota_config.h
Description
-----------
Winsim now fallback to use the signing cert from the header file if it's not found on file system. This will resolve the OTA pal tests failures in our regression tests.
Checklist:
----------
> Fix OTA pal tests on windows simulator

- CMakeLists.txt
- PreLoad.cmake
Description
-----------
Per IDT request, this PR allows user(usually vendor partners) to specify an arbitrary location for vendor code using the `AFR_BOARD_PATH` variable. Example,
- `cmake -DAFR_BOARD_PATH='../tmp/afr-esp/boards/esp32' -DCOMPILER=xtensa-esp32 -S . -B build -GNinja`
- `cmake -DAFR_BOARD_PATH='../tmp/afr-st/boards/stm32l475_discovery' -DCOMPILER=arm-gcc -S . -B build -GNinja`
Checklist:
----------
> Allow loading vendor code from a custom location

- vendors/nxp/boards/lpc54018iotmodule/aws_demos/config_files/aws_wifi_config.h
- vendors/nxp/boards/lpc54018iotmodule/aws_tests/config_files/aws_secure_sockets_config.h
- vendors/nxp/boards/lpc54018iotmodule/ports/secure_sockets/iot_secure_sockets.c
- vendors/nxp/boards/lpc54018iotmodule/ports/wifi/iot_wifi.c
The NXP port changes done in PR #1778 have not improved reliability in
the Full_TCP test suite.  This change backs them out.
Description
-----------
Checklist:
----------
> Revert NXP port changes from PR #1778

- demos/demo_runner/iot_demo_freertos.c
- demos/dev_mode_key_provisioning/src/aws_dev_mode_key_provisioning.c
- demos/https/iot_demo_https_s3_download_async.c
- libraries/abstractions/pkcs11/mbedtls/iot_pkcs11_mbedtls.c
- libraries/c_sdk/aws/defender/src/aws_iot_defender_api.c
- libraries/c_sdk/standard/common/logging/iot_logging_task_dynamic_buffers.c
- libraries/c_sdk/standard/https/src/iot_https_client.c
- libraries/c_sdk/standard/https/src/private/iot_https_internal.h
Description
-----------
Address some warnings flagged by ARM GCC from `-Wall -Wextra` build configuration
Checklist:
----------
> Remove warnings from PKCS11 and Defender files

- libraries/c_sdk/standard/serializer/src/json/iot_serializer_json_encoder.c
Description
-----------
Fix -Wstringop-truncation warning in JSON encoder
Serializer tests pass.
Checklist:
----------
> Fix -Wstringop-truncation warning in JSON encoder

- libraries/c_sdk/standard/ble/test/iot_test_ble_end_to_end.c
Remove waitAfterDisconnect test from BLE
Description
-----------
waitAfterDisconnect test was made a unit test in #1844 . Removing this test from BLE system test as well.
Checklist:
----------
> Move waitAfterDisconnect to unit test in BLE

- libraries/abstractions/secure_sockets/utest/secure_sockets_utest.c
- tests/unit_test/linux/CMakeLists.txt
- tests/unit_test/linux/utils/task_control.c
- tools/cmock/create_test.cmake
- vendors/pc/boards/linux/CMakeLists.txt
Fix Race Condition In Unit Test
Description
-----------
A race condition could occur in UT where a thread frees a shared variable, then it is used by the main thread which could cause a core dump
Checklist:
----------
> TEST: fix race condition in Unit test

- libraries/freertos_plus/aws/greengrass/src/aws_greengrass_discovery.c
- libraries/freertos_plus/aws/greengrass/test/aws_test_ggd_system.c
Description
-----------
GGD_JSONRequestStart method creates a connection to a specified host and port by using the Sockets API. If that connection fails, then the test completely fails. This PR addresses this issue by wrapping the method around RETRY_EXPONENTIAL, which retries the method with exponential backoff if the expected status is not returned. 
Also considered retries for the library function instead but this masks the problem that really needs to be handled in the network layer.
Checklist:
----------
> Retry using exponential backoff upon connection failure with GGD system tests

- libraries/c_sdk/standard/mqtt/test/system/iot_tests_mqtt_system.c
- tests/include/iot_config_common.h
Because we are now using periodMs throughout all system tests, it makes sense to make it a config macro in iot_config_common.h. 
Description
-----------
Checklist:
----------
> Make periodMs a config macro

- libraries/abstractions/common_io/test/test_iot_pwm.c
Description
-----------
* Added "TEST_PROTECT" sections where needed
* Removed stale includes, variables and code
* Added in "AFQP_IotPwm_StartFuzzing" and "AFQP_IotPwmAccuracy" test cases in the group.
* Removed "AFQP_IotPwmOpenFailure" as it was testing the same as "AFQP_IotPwmOpenFuzzing" 
* Refactored "AFQP_IotPwmAccuracy" and "AFQP_IotPwmAccuracyAssisted", moving common code out to shared private function. 
Checklist:
----------
> common-io: Refactoring and updates to PWM test cases

- libraries/c_sdk/aws/defender/test/system/aws_iot_tests_defender_system.c
- vendors/cypress/WICED_SDK/apps/demo/aws_demo/aws_demo.mk
- vendors/cypress/WICED_SDK/apps/test/aws_test/aws_test.mk
- vendors/espressif/boards/esp32/aws_tests/application_code/espressif_code/amazon-freertos-tests/component.mk
- vendors/espressif/boards/esp32/aws_tests/config_files/aws_test_runner_config.h
- vendors/marvell/boards/mw300_rd/aws_tests/config_files/aws_test_runner_config.h
This PR fixes defender test failures on multiple platfroms.
**Cypress:** A file in tinybor which was not compiled for Cypress resulted in linker error.
**Esp32:** Defender test files were not getting built in the make files. 
**Marvell:** Marvell passes `-ffreestanding` flag to the compiler which results in `__STDC_HOSTED__` being defined to 0. In this case the function used for printing a cbor value `cbor_value_to_pretty`
is not available and this results in a linker error. 
Signed-off-by: Gaurav Aggarwal <aggarg@amazon.com>
> Fix defeneder test build failure on multiple platforms

- tools/cmake/afr.cmake
Description
-----------
Export the json compile commands file from CMake. This will generate a `compile_commands.json` file under the build directory, which contains the compiler flags for each file.
**Note: this only works for non-IDE generators like makefile and ninja. It doesn't work for IDE generators since they typically hide the compiler commands.**
Checklist:
----------
> Export the compile commands in CMake

- tools/cbmc/proofs/DNS/DNSgetHostByName_a/Makefile.json
- tools/cbmc/proofs/DNS/DNSgetHostByName_cancel/Makefile.json
- tools/cbmc/proofs/ReadNameField/Makefile.json
Fix the breaking CBMC proof for DNSgetHostByName_a & DNSgetHostByName_cancel & ReadNameField.
Description
-----------
Added a #define in all three Makefile.json to declare an essential macro ipconfigDNS_CACHE_NAME_LENGTH used in CBMC proofs which is not defined if (ipconfigUSE_DNS_CACHE == 0).
Previous PR https://github.com/aws/amazon-freertos/pull/1928 disabled the use of DNS cache which broke the proofs.
Checklist:
----------
> Fix breaking CBMC proof for DNSgetHostByName_a/_cancel & ReadNameField

- libraries/abstractions/common_io/test/iot_test_common_io_internal.h
- libraries/abstractions/common_io/test/test_iot_i2c.c
Description
-----------
Removed reference to global handles and closing them during setup. This based on the assumption that other tests using the I2C and possibly these handles should me responsible for cleaning up.
Updated to use variable directly in code instead of a define replacement, this to align with how other tests look. 
Added a TEST_PROTECT section to AFQP_IotI2COpenCloseFail.
Checklist:
----------
> common-io: Updates to I2C test cases

- vendors/ti/boards/cc3220_launchpad/ccs.cmake
Description
-----------
The Ninja generator combines linker and post build commands using '&&' which results in a long string. Windows has a limit of 8191 characters on the command line string length. We were hitting that limit for TI and were getting "command string too long" error.
This commit updates the cmake files to force Ninja to use response files which is a feature implemented for exactly this purpose and results in a much smaller command string.
Signed-off-by: Gaurav Aggarwal <aggarg@amazon.com>
> Fix build failure for TI tests for cmake

- tools/cmake/afr_metadata.cmake
Add mbedtls_config and mbedtls_utils to the source list for console
metadata.
Add mbedtls_config and mbedtls_utils folders to the CMake Metadata output for the FreeRTOS Console.
Description
-----------
Add an explicit case in the Metadata module to include the above directories.
Checklist:
----------
> Add mbedtls_config and mbedtls_utils to metadata.

- libraries/abstractions/pkcs11/mbedtls/iot_pkcs11_mbedtls.c
Description
-----------
Checklist:
----------
> Return memory failure if PKCS #11 stack fails to initialize a mutex.

- vendors/nuvoton/boards/numaker_iot_m487_wifi/CMakeLists.txt
Description
-----------
Incorrect compiler flags in the cmake build were causing tests in CI to fail due to stack overflow. This change aligns the cmake build's flags with those of the IDE build and fixes the problem.
Checklist:
----------
> Align Nuvoton cmake compiler flags with IDE build.

- demos/dev_mode_key_provisioning/src/aws_dev_mode_key_provisioning.c
All of the warnings were due to https://docs.microsoft.com/en-us/cpp/error-messages/compiler-warnings/compiler-warning-level-4-c4221?view=vs-2019.
This warning means that you cannot use an auto allocated variable's address when initializing a struct. Therefore it is necessary to initialize a struct, and then initialize it's members.
Description
-----------
Checklist:
----------
> Fix compiler warnings on msvc in aws_dev_mode_key_provisioning.c.

- demos/dev_mode_key_provisioning/src/aws_dev_mode_key_provisioning.c
- libraries/abstractions/pkcs11/mbedtls/iot_pkcs11_mbedtls.c
- libraries/abstractions/pkcs11/test/iot_test_pkcs11.c
* Fix memory leak in AFQP_Capabilities due to pxSlotId not being freed.
* Fix memory leak in prvGetProvisionedState due to pxSlotId not being freed.
* Added NULL check in call to semaphore delete.
* Fixed strcmp logic to determine if a device was a secure element.
Description
-----------
Checklist:
----------
> PKCS #11 Memory Leak Fixes and Provisioning Memory Leak Fix

- tools/cbmc/proofs/HTTP/global_state_HTTP.c
- tools/cbmc/proofs/ParseDNSReply/ParseDNSReply_harness.c
Use __CPROVER_havoc_object instead of __CPROVER_array_copy
Description
-----------
1. Use `__CPROVER_havoc_object` instead of `__CPROVER_array_copy`. This is self-documenting.
1. Remove unnecessary havoc of already unconstrained value.
Checklist:
----------
> Use __CPROVER_havoc_object instead of __CPROVER_array_copy

- libraries/abstractions/pkcs11/mbedtls/iot_pkcs11_mbedtls.c
- vendors/infineon/secure_elements/pkcs11/iot_pkcs11_trustx.c
Description
-----------
iot_pkcs11_mbedtls.c has a function xIsObjectWithNoNvmStorage which is currently not used anywhere in the code. It's purpose is to check whether a PKCS #11 object was stored in NVM or in a header file. 
It is desirearable to remove this function because
1. It is unused / dead code.
2. We can remove aws_clientcredential.h, aws_clientcredential_keys.h, iot_default_root_certificates.h from our dependencies.
Checklist:
----------
> Removed unused function and credential includes in iot_pkcs11_mbedtls.c

- vendors/nuvoton/boards/numaker_iot_m487_wifi/CMakeLists.txt
Description
-----------
Nuvoton's cmake build is failing because of a regression introduced in #1957. Our PR checks didn't catch this because it's not including the Nuvoton CMake build, I've talked to them to address this issue.
Checklist:
----------
> Fix nuvoton's cmake build

- libraries/c_sdk/standard/https/test/system/iot_tests_https_system.c
- libraries/c_sdk/standard/https/test/unit/iot_tests_https_async.c
- libraries/c_sdk/standard/https/test/unit/iot_tests_https_client.c
Remove (ARM) GCC warnings from HTTP tests
Description
-----------
Checklist:
----------
> Resolve HTTP tests warnings

- libraries/abstractions/pkcs11/utest/iot_pkcs11_mbedtls_utest.c
Removed malloc use in RSA and EC test cases. Added happy paths for C_Sign, C_SignInit, C_GetAttributeValue, C_FindObjects, C_FindObjectsInit, C_FindObjectsFinal, C_DigestUpdate, PKCS11_PAL_DestroyObject, C_VerifyInit, C_CreateObject RSA Pub key, x509 Certificate, EC Pub key.
Description
-----------
Checklist:
----------
> PKCS11 Unit Tests

- libraries/c_sdk/aws/shadow/test/system/aws_iot_tests_shadow_system.c
Description
-----------
If IotMqtt_Connect connection fails, then the test completely fails. This PR addresses this issue by wrapping the method around RETRY_EXPONENTIAL, which retries the method with exponential backoff if the expected status is not returned.
Checklist:
----------
> Retry using exponential backoff upon connection failure with Shadow system tests 

- libraries/c_sdk/aws/defender/test/system/aws_iot_tests_defender_system.c
- libraries/c_sdk/aws/shadow/test/system/aws_iot_tests_shadow_system.c
If IotMqtt_Connect connection fails, then the test completely fails. This PR addresses this issue by wrapping the method around RETRY_EXPONENTIAL, which retries the method with exponential backoff if the expected status is not returned.
Description
-----------
Checklist:
----------
> Retry using exponential backoff upon connection failure with Defender system tests

- libraries/abstractions/pkcs11/mbedtls/iot_pkcs11_mbedtls.c
Fix MISRA violations in pkcs11_mbetls, impossible paths, dead code. Fix a memory leak when a RSA ctx is not freed. Fix some error logging. Reduce logic complexity.
Description
-----------
Checklist:
----------
> PKCS11 Refactor

- libraries/abstractions/common_io/test/test_iot_i2c.c
- libraries/abstractions/common_io/test/test_iot_spi.c
- libraries/abstractions/common_io/test/test_iot_uart.c
- libraries/abstractions/wifi/test/iot_test_wifi.c
Description
-----------
Fix compile warnings in common io and wifi tests
Checklist:
----------
> Fix compile warnings in common io and wifi tests

- libraries/abstractions/pkcs11/utest/iot_pkcs11_mbedtls_utest.c
Description
-----------
* Now at 85% line coverage
* 100% function coverage
* Added unit tests for:
* C_GetAttributeValue
* PKCS11_PAL_DESTROY_OBJECT
* C_Verify
* C_GenerateKeyPair
* C_GenerateRandom
Checklist:
----------
> PKCS #11 Unit Tests

- libraries/abstractions/pkcs11/mbedtls/iot_pkcs11_mbedtls.c
PKCS #11 GNU Complexity Refactoring
Description
-----------
Functions that were bloated and need to be refactored to lower their GNU complexity due to switch statements being nested in loops, as well as having a lot of branches in the switch statement are refactored into multiple smaller functions in this PR.
Code is also reused between public and private EC keys to move towards the DRY principle.
* Functions refactored to be at an acceptable GNU complexity level:
* prvCreateCertificate
* prvCreatePublicEcKey
* prvCreatePrivateEcKey
* prvCreatePrivateKey
* prvCreateRsaPrivateKey
Checklist:
----------
> PKCS #11 GNU Complexity Refactor

- libraries/abstractions/wifi/test/iot_test_wifi.c
Add exact error messages to failing tests
Description
-----------
Currently tests only display true or false whether the test passed or failed
This Commit will display the exact error code received from the underlying Wifi implementation
Checklist
----------
> Test: display error codes when a test fails

- vendors/cypress/boards/CY8CKIT_064S0S2_4343W/ports/wifi/iot_wifi.c
Ensure cyobjstore is initialized
Description
-----------
cyobjstore may be called before it is initialized. This patch makes sure cyobjstore is initialized.
Checklist:
----------
> Ensure cyobjstore is initialized

- libraries/freertos_plus/standard/freertos_plus_tcp/source/FreeRTOS_TCP_IP.c
The TCP flags are not of proper width according to the header in the TCP protocol.
Description
-----------
The TCP flags are not of proper width according to the header in the TCP protocol. In absence of a cast, this value is downcasted from `uin16_t` to `uint8_t` to assign value to the 8 bit width `xTCP_HEADER.ucTCPFlags`.
These flags are designed to fit in a 6-bit wide value according to [RFC 793](https://tools.ietf.org/html/rfc793#section-3.1). The other bits are experimental and are defined in various RFCs. They are not used as of now in the +TCP stack except for the purposes of debugging.
The issue that triggered this PR:
Visual Studio build (v142) yields 2 warnings for `FreeRTOS_TCP_IP.c` file, both of which are `cast truncates constant value`.
``` …
```
> Make Flags of proper width

- libraries/abstractions/common_io/test/test_iot_flash.c
- libraries/abstractions/pkcs11/ecc608a/atca_cert_chain.h
Description
-----------
This pull request is rather large (sorry for this), the main contributions is the following:
* Refactored flash test cases to use TEST_PROTECT sections to guard against cascading failures.
* Refactored flash test cases, moving common code for writing, reading, verifying dummy data out of each test case into global privates. This should simplify maintaining the tests as.
* Updated AFQP_IotFlashReadInfo to allow block >= sector >= page >= flash (in other words, moved from "greater than" to "greater than or equal") as this is a valid scenario. 
Checklist:
----------
> common-io: Refactoring FLASH test cases

- libraries/abstractions/common_io/test/test_iot_timer.c
Description
-----------
* Refactored flash test cases to use TEST_PROTECT sections to guard against cascading failures.
* Updated the thresholds used in AFWP_IotTimer_Running and AFWP_IotTimer_Stop. This as the worst case scenario could be an 2ms offset (+-1ms per vTaskDelay). Also added the factor "5" as this was missing.
* Updated return value checks for iot_timer_delay() to also check for IOT_TIMER_NOT_RUNNING based on API description. 
Checklist:
----------
> common-io: Refactoring Timer test cases

- libraries/abstractions/common_io/include/iot_flash.h
Description
-----------
Add flash id component to IotFlashInfo struct
Checklist:
----------
> Add flash id component to IotFlashInfo struct

- tools/ota_e2e_tests/aws_ota_test/aws_ota_test_case_disconnect_cancel_update.py
- tools/ota_e2e_tests/aws_ota_test/aws_ota_test_case_disconnect_resume.py
Description
-----------
Wait time is too short in OTA suspend and resume E2E tests. This PR replace the hardcode 3 mins with the timeout value from configuration.
Checklist:
----------
> Update wait time in OTA suspend and resume E2E tests

- libraries/abstractions/common_io/include/iot_rtc.h
- libraries/abstractions/common_io/test/test_iot_rtc.c
Description
-----------
* Added TEST_PROTECT sections to test cases
* Removed global handle as the usage of the RTC is always open -> close which means the handle would be closed after the first test had run (often without setting it to NULL again).
* Added "Week day" to the date/time structure for each test so that the whole structure is in a known state when performing the tests.
* Changed semaphore timeouts to not be "eternal".
* Added global variable that can be used to configure which RTC instance to open (test was hard-coded to 0)
* Updated/added expected return value to the top-level API header file based on how the test cases was setup (please feedback on this as the test and API description was not aligned).
Checklist:
----------
By submitting this pull request, I confirm that …
> common-io: Refactoring and updates to RTC test cases and top-level header file

- libraries/abstractions/common_io/test/test_iot_tsensor.c
* Added TEST_PROTECT sections
* Removed AFQP_IotTsensorCalibrationNullInputFuzz as the test was not valid according the API description stating that this request will not return invalid status on NULL buffer.
* Updated AFQP_IotTsensorCalibrationSuccess to test for status when passing in NULL buffer
* Reworked AFQP_IotTsensorTriggerMinThreshold and AFQP_IotTsensorTriggerMaxThreshold. 
* Updated expected return values based on what is defined by the API header file
Description
-----------
Checklist:
----------
> common-io: Refactoring and updates to Temp Sensor test cases

- demos/demo_runner/iot_demo_freertos.c
- vendors/nordic/nRF5_SDK_15.2.0/components/libraries/timer/app_timer_freertos.c
Fix freertos timer create function for Nordic
Description
-----------
Nordic has an implementation for app timer APIs using FreeRTOS timers. `app_timer_create` API is expected to re-create a new timer with a new handler (note: there is no API to delete a timer). Currently the API returns an error if a timer already exists. With this PR, API ensures if timer is inactive, then delete and create a new timer with the new handler.
Also added a check in demo runner to handle user initiated network disable transition in network manager callback.
Checklist:
----------
> Fix nordic freertos timer create

- libraries/freertos_plus/aws/ota/src/aws_iot_ota_agent.c
The change add a private function to free buffers for unexpected job and data events. The change also fixes file close when OTA resumes.
Description
-----------
Checklist:
----------
> OTA - Add private function to free buffers for unhandled events

- tests/unit_test/linux/README.md
Unit Testing on boarding readme
Description
-----------
Steps to follow to onboard unit testing with cmake, cmock and unity
Checklist:
----------
> Unit Testing on boarding readme

- libraries/freertos_plus/standard/freertos_plus_tcp/source/FreeRTOS_TCP_IP.c
- tools/cbmc/patches/remove-static-in-freertos-tcp-ip.patch
Make compilation of `prvReadSackOption()` dependent on `ipconfigUSE_TCP_WIN`
Description
-----------
Since the function `prvCheckOptions()` was split-up into smaller parts, the function `prvReadSackOption()` was compiled unconditionally.
Checklist:
----------
> Only compile prvReadSackOption() when TCP sliding windows are used

- tools/uncrustify.cfg
Revert uncrustify change from PR #2015 
Description
-----------
Some changes to uncrustify came with #2015. The new change added a space to every *, this reverts this change.
Checklist:
----------
> Revert uncrustify change from PR #2015

- vendors/espressif/boards/esp32/aws_tests/application_code/espressif_code/amazon-freertos-tests/component.mk
Description
-----------
aws_tests project shouldn't add demos/include to the include paths, this is causing OTA PAL tests to use wrong header file and failing.
Checklist:
----------
> Fix an include path issue in esp32 makefile

- vendors/xilinx/boards/microzed/aws_demos/application_code/main.c
Description
-----------
This change increases the logging queue size so that the demo finished message prints for the CI to know that the demo finished successfully.
There have been changes that increased the amount of logging messages in this board. These include increased memory monitoring logging. 
Checklist:
----------
> Xilinx Demo Finish Message Print Issue: Increased logging queue size

- libraries/abstractions/common_io/test/test_iot_flash.c
- libraries/abstractions/common_io/test/test_iot_gpio.c
Description
-----------
TEST_MESSAGE() requires Unity 2.4.4, currently the latest released.  Comment out these message to avoid requirement to uplevel Unity.
Checklist:
----------
> Comment out calls to TEST_MESSAGE

- libraries/abstractions/common_io/test/test_iot_gpio.c
Moved global semaphore creation to TEST_SETUP().
Added code to delete semaphore in TEST_TEAR_DOWN().
Fixed TEST_ASSERT_GREATER_THAN() in AFQP_IotGpioSpeed.
Description
-----------
Checklist:
----------
> Fixes to test_iot_gpio.c

- libraries/abstractions/common_io/test/test_iot_i2c.c
* The there are two eI2CSendNoStopFlag calls, one for the write and one for the read
both are needed.
Description
-----------
Checklist:
----------
> Revert removal of sending second eI2CSendNoStopFlag iot_i2c_ioctl call

- libraries/c_sdk/standard/mqtt/src/iot_mqtt_api.c
- libraries/c_sdk/standard/mqtt/src/iot_mqtt_operation.c
- libraries/c_sdk/standard/mqtt/src/iot_mqtt_validate.c
- libraries/c_sdk/standard/mqtt/src/private/iot_mqtt_internal.h
Description
-----------
Fixes a keep alive bug in MQTT when IOT_MQTT_RESPONSE_WAIT_MS is a significant fraction of keepAliveMs
Checklist:
----------
> Fix: MQTT Keep Alive scheduling

- vendors/microchip/boards/ecc608a_plus_winsim/aws_demos/config_files/FreeRTOSConfig.h
- vendors/microchip/boards/ecc608a_plus_winsim/aws_tests/config_files/FreeRTOSConfig.h
winsim+ecc608a network adapter fix
Description
-----------
Default the selected adapter to 0 so the user gets a helpful message when setting up the winsim+ecc608a project.
Checklist:
----------
> winsim+ecc608a network adapter fix

- libraries/c_sdk/standard/mqtt/src/iot_mqtt_operation.c
- libraries/c_sdk/standard/mqtt/test/unit/iot_tests_mqtt_api.c
Description
-----------
Fixes an MQTT KeepAlivePeriodic unit test failure introduced by #2064. The KeepAlivePeriodic Test had triggered an assert since the keep alive time used by the test was lower than the minimum IOT_MQTT_RESPONSE_WAIT_MS allowed. This increases the keep alive time used by the test to be within acceptable bounds.
Checklist:
----------
> fix: MQTT test failure from #2064

- vendors/cypress/boards/CY8CKIT_064S0S2_4343W/aws_demos/application_code/cy_code/CY8CKIT-064S0S2-4343W.mk
- vendors/cypress/boards/CY8CKIT_064S0S2_4343W/aws_tests/application_code/cy_code/CY8CKIT-064S0S2-4343W.mk
make qprogram - skips the build step and programs the board
Signed-off-by: Andrei Narkevitch <ainh@cypress.com>
Description
-----------
Checklist:
----------
> PSoC64: add missing qprogram make target

- libraries/c_sdk/standard/https/test/system/iot_tests_https_system.c
Fix HTTPS failures on Nuvoton, TI and Infineon by running tests against an HTTPS server owned by the Lab Infra Team
Description
-----------
Changed code to use https echo server running on CI EC2 instance. 
Checklist:
----------
> Change https echo server domain

- vendors/nxp/boards/lpc54018iotmodule/ports/pkcs11/iot_pkcs11_pal.c
Fixed regression in PKCS #11 NXP due to logic error in PAL refactor.
Description
-----------
The  logic for a successful initialization in the NXP PAL was accidentally refactored to be the opposite of the intention.
Checklist:
----------
> Fixed regression in PKCS #11 nxp due to logic error in PAL refactor.

- vendors/nuvoton/boards/numaker_iot_m487_wifi/aws_tests/config_files/FreeRTOSConfig.h
Fix Nuvoton build for HTTPS Client Async Tests
Description
-----------
Free up some RAM by reducing the HEAP.
Checklist:
----------
> Fix Nuvoton build for HTTPS Client Async Tests

- libraries/c_sdk/standard/https/src/iot_https_client.c
Fix `-Wunused-but-set-variable` warnings when building with (ARM) GCC using `-Wall -Wextra` flags
Description
---------------
The variables flagged are used only for logging; the warnings are raised when logging is disabled.
> Suppress -Wunused-but-set-variable warnings

- vendors/cypress/WICED_SDK/apps/demo/aws_demo/aws_demo.mk
- vendors/cypress/WICED_SDK/apps/test/aws_test/aws_test.mk
- vendors/cypress/WICED_SDK/libraries/aws/aws.mk
Fix Cypress makefile include paths and defines
Description
-----------
The AFQP_Verify was failing on both of the cypress boards. The root issue was that it was using the default MbedTLS config file instead of the "aws_mbedtls_config.h" file. 
Changes I made to fix this:
* Fixed the way that the include paths and defines are added in aws.mk. 
* Added the path to the aws_mbedtls_config.h file to the aws_demo.mk and aws_test.mk files for consistency.  
Checklist:
----------
> Fix Cypress makefile include paths and defines

- libraries/abstractions/common_io/test/test_iot_uart.c
* Needed for definition of IOT_TEST_COMMON_IO_UART_SUPPORTED_CANCEL
Description
-----------
Checklist:
----------
> Added #include "iot_test_common_io_internal.h" to test_iot_uart.c

- vendors/cypress/WICED_SDK/apps/demo/aws_demo/aws_demo.mk
- vendors/cypress/WICED_SDK/apps/test/aws_test/aws_test.mk
- vendors/cypress/WICED_SDK/libraries/aws/aws.mk
Fix Cypress makefile include paths and defines
Description
-----------
The AFQP_Verify test was failing on both of the cypress boards. The root issue was that it was using the default MbedTLS config file instead of the "aws_mbedtls_config.h" file.
Changes I made to fix this:
- Fixed the way that the include paths and defines are added in aws.mk.
- Added the path to the aws_mbedtls_config.h file to the aws_demo.mk and aws_test.mk files for consistency.
Checklist:
----------
> Fix Cypress makefiles include paths and defines (#2070)

- libraries/freertos_plus/aws/ota/src/aws_iot_ota_agent.c
This fix starts the self-test timer before it receives the OTA job document.
Description
-----------
The fix helps in handling conditions where the OTA job is forced cancelled after it is started to allow device to reset and rollback.
Checklist:
----------
> OTA/ Start self test timer before job doc is requested.

- libraries/c_sdk/standard/https/src/iot_https_client.c
Port the warning suppression change made in #2084 to `release-candidate`
> Port changes for warnings reduction in #2084 to RC

- vendors/cypress/boards/CY8CKIT_064S0S2_4343W/aws_demos/config_files/iot_config.h
- ARM CLang and IAR linkers have issues when
external demoGetMqttSerializer symbol is declared and
not defined (i.e. TCP_ECHO_CLIENT_DEMO application)
Signed-off-by: Andrei Narkevitch <ainh@cypress.com>
Description
-----------
Checklist:
----------
> TCP_ECHO_CLIENT_DEMO app fix for CLang/IAR builds

- vendors/mediatek/boards/mt7697hx-dev-kit/ports/wifi/iot_wifi.c
Allow Ping to succeed on Mediatek if >= 0 pings
Description
-----------
Allow Ping to succeed on Mediatek if >= 0 pings have succeeded
Checklist:
----------
> Fix: Allow Ping to succeed on Mediatek if >= 0 pings

- libraries/abstractions/pkcs11/mbedtls/iot_pkcs11_mbedtls.c
- libraries/freertos_plus/standard/pkcs11/src/iot_pkcs11.c
- libraries/freertos_plus/standard/utils/src/iot_pki_utils.c
Enforce PKCS 11 80 char column limit
Description
-----------
As per the FreeRTOS coding standard, enforce an 80 character column limit.
Checklist:
----------
> Enforce PKCS 11 80 char column limit

- vendors/nuvoton/boards/numaker_iot_m487_wifi/aws_demos/config_files/FreeRTOSConfig.h
Fix Nuvoton HTTPS demo build
Description
-----------
Reduce heap size to increase the available RAM to fix the HTTPS demobuild.
Checklist:
----------
> Fix Nuvoton HTTPS demo build

- tools/echo_server/echo_server.go
- tools/echo_server/readme.md
Only use TLS cipher suite's supported by AWS IoT Core
Description
-----------
Explicitly only allow the use of the cipher suite's AWS IoT Core uses.
Checklist:
----------
> Go Echo Server TLS 

- CHANGELOG.md
Add the `202006.00` release version section header missed in #2098
> Add the 202006.00 release version section header

- libraries/abstractions/pkcs11/mbedtls/iot_pkcs11_mbedtls.c
Fix remaining warnings from (ARM) GCC in `iot_pkcs11_mbedtls.c` file when building with `-Wall -Wextra` flags
Checklist:
----------
> Resolve remaining warnings in PKCS 11 file

- libraries/3rdparty/mbedtls_config/aws_mbedtls_config.h
Remove CBC from mbedTLS
Description
-----------
Disable some algorithms unsupported by IOT Core. Namely ones using CBC. Alongside this, other features that only work with CBC have been disabled, as well as some features that are currently not being used, such as the self-test and version APIs.
Checklist:
----------
> Remove CBC from mbed TLS

- libraries/abstractions/pkcs11/include/iot_pkcs11_pal.h
- libraries/abstractions/pkcs11/mbedtls/iot_pkcs11_mbedtls.c
- vendors/cypress/boards/CY8CKIT_064S0S2_4343W/ports/pkcs11/iot_pkcs11_pal.c
- vendors/cypress/boards/CYW943907AEVAL1F/ports/pkcs11/iot_pkcs11_pal.c
- vendors/cypress/boards/CYW954907AEVAL1F/ports/pkcs11/iot_pkcs11_pal.c
- vendors/espressif/boards/esp32/aws_demos/config_files/default_pkcs11_config/iot_pkcs11_config.h
- vendors/espressif/boards/esp32/ports/pkcs11/iot_pkcs11_pal.c
- vendors/infineon/boards/xmc4800_iotkit/ports/pkcs11/iot_pkcs11_pal.c
- vendors/infineon/secure_elements/pkcs11/iot_pkcs11_trustx.c
- vendors/marvell/boards/mw300_rd/ports/pkcs11/iot_pkcs11_pal.c
- vendors/mediatek/boards/mt7697hx-dev-kit/ports/pkcs11/iot_pkcs11_pal.c
- vendors/microchip/boards/curiosity_pic32mzef/ports/pkcs11/iot_pkcs11_pal.c
- vendors/nuvoton/boards/numaker_iot_m487_wifi/ports/pkcs11/iot_pkcs11_pal.c
- vendors/nxp/boards/lpc54018iotmodule/ports/pkcs11/iot_pkcs11_pal.c
- vendors/pc/boards/windows/ports/pkcs11/iot_pkcs11_pal.c
- vendors/renesas/boards/rx65n-rsk/ports/pkcs11/iot_pkcs11_pal.c
- vendors/st/boards/stm32l475_discovery/ports/pkcs11/iot_pkcs11_pal.c
- vendors/ti/boards/cc3220_launchpad/ports/pkcs11/iot_pkcs11_pal.c
- vendors/vendor/boards/board/ports/pkcs11/iot_pkcs11_pal.c
- vendors/xilinx/boards/microzed/ports/pkcs11/iot_pkcs11_pal.c
PKCS #11 PAL MISRA Update
Description
-----------
This commit fixes some of the MISRA errors caused by the PKCS #11 PAL API. It makes most functions use the PKCS #11 data types, as well as reduces the amount of casting being done in the PKCS #11 stack by as much as possible.
Checklist:
----------
> PKCS #11 PAL MISRA Fix

- libraries/abstractions/pkcs11/mbedtls/iot_pkcs11_mbedtls.c
- libraries/freertos_plus/standard/crypto/src/iot_crypto.c
- libraries/freertos_plus/standard/tls/src/iot_tls.c
- vendors/infineon/secure_elements/pkcs11/iot_pkcs11_trustx.c
- vendors/pc/boards/windows/ports/pkcs11/iot_pkcs11_pal.c
Use configPRINTF instead of directly using logging API
Description
-----------
Use configPRINTF instead of directly using logging API. This allows using a logging mechanism that is configurable, as well as removing the dependency on vLoggingPrintf.
Checklist:
----------
> Use configPRINTF instead of directly using logging API

- libraries/freertos_plus/standard/freertos_plus_tcp/source/FreeRTOS_TCP_IP.c
Description
-----------
Since the big PR #2015, it can happen that the TCP checksum for an outgoing packet is not set correctly, because it sees a length error. I just found this out while testing with the WinSim projects.
The function `usGenerateProtocolChecksum()` has recently become stricter: it also checks the the total length is at least the sum of the Ethernet header, plus the length field found in the IPv4 header (see code below ).
I propose the following change, symbolically in `FreeRTOS_TCP_IP.c`:
~~~c
+    pxNetworkBuffer->xDataLength = ulLen + ipSIZE_OF_ETH_HEADER;
/* calculate the TCP checksum for an outgoing packet. */
usGenerateProtocolChecksum( pxTCPPacket, pxNetworkBuffer->xDataLength, pdTRUE );
-    pxNetworkBuffer->xDataLength = ulLen + ipSIZE_OF_ETH_HEADER;
~~~
The …
> FreeRTOS+TCP Set xDataLength before calculating checksum

- vendors/st/stm32l475_discovery/BSP/Components/es_wifi/es_wifi.c
Description
-----------
The Inventek module returns one of the following as ping response:
```
Success - \r\nIP0.IP1.IP2.IP3,RTT\r\nOK\r\n>
Timeout - \r\nIP0.IP1.IP2.IP3,Timeout\r\nOK\r\n>
```
Where IP0..IP3 are the octacts of the IP address pinged and RTT is the round trip time.
```
Example success response - \r\n8.8.8.8,48\r\nOK\r\n>
Example timeout response - \r\n192.168.1.1,Timeout\r\nOK\r\n>
```
Earlier the function just relied on the presence of `\r\nOK\r\n>` to detect success which is present in both the success and the timeout response. As a result, it incorrectly detected timeout as success.
This change adds additional parsing to ensure that success and timeout responses are differentiated correctly.
Testing
--------
* Tested pinging Google DNS server (8.8.8.8) and `ES_WIFI_Ping` …
> Fix ES_WIFI_Ping to correctly differentiate Ping Success and Timeout

- vendors/cypress/MTB/psoc6/cmake/cy_kit_utils.cmake
- vendors/cypress/boards/CY8CKIT_064S0S2_4343W/aws_tests/application_code/main.c
Description
-----------
1. Remove the cypress tools from dependency when AFR_METADATA_MODE is enabled.
2. Add 20s delay to the start of test program, so that the board have enough time to establish a serial connection to our test infra PC before the test program starts to output data to serial port. 
Checklist:
----------
> Fix: psoc64 metadata mode fix & Add a delay to psoc64 test project

- vendors/espressif/boards/esp32/aws_demos/config_files/aws_wifi_config.h
- vendors/espressif/boards/esp32/aws_tests/application_code/main.c
- vendors/espressif/boards/esp32/aws_tests/config_files/aws_wifi_config.h
- vendors/espressif/boards/esp32/ports/wifi/iot_wifi.c
Description
-----------
strlcpy sets last byte to NULL. Hence, length of SSID to be copied should be (max length + 1).
Using `sizeof` operator to calculate string length also counts NULL termination character. Hence, use strlen to calculate length of SSID and Passphrase.
Fixes issue https://github.com/aws/amazon-freertos/issues/2067
Checklist:
----------
> Fix issue related to WiFi scan and configure AP with SSID of maximum length on ESP32

- vendors/st/boards/stm32l475_discovery/ports/common_io/iot_spi.c
Description
-----------
Baud fix: The low level LL_SPI_SetBaudRatePrescaler requires a prescaler parameter instead of the raw frequency. So we need to calculate the prescaler based on the system clock and desired frequency.
Default config fix: when open, the frequency should be calculated to the default one which is system clock divided by the default prescaler - 2.
Checklist:
----------
> Fix SPI baud change and default config on ST

- libraries/3rdparty/mbedtls_config/aws_mbedtls_config.h
Renable CBC for connecting to Greengrass.
Description
-----------
Since we only enable TLS 1.2 there was no overlapping cipher suites supported by the client and the Greengrass core.
Checklist:
----------
> Re-enable CBC for connecting to Greengrass.

- libraries/abstractions/pkcs11/mbedtls/iot_pkcs11_mbedtls.c
Fix PKCS 11 Warning and Recent Regression
Description
-----------
Fixes a recent regression caused by using the wrong label for the private key when cleaning up objects.
Checklist:
----------
> Fix PKCS 11 Warning and Recent Regression

- libraries/abstractions/pkcs11/utest/iot_pkcs11_mbedtls_utest.c
- libraries/abstractions/pkcs11/utest/project.yml
PKCS 11 Unit Tests
Description
-----------
Sync up unit tests with latest PKCS #11 changes. Add last 0.4% of line coverage. The main changes getting synced here are the data type changes in the PKCS #11 PAL.
Checklist:
----------
> PKCS 11 Unit Tests

- .gitmodules
Add PKCS #11 to PSA shim as a submodule.
Description
-----------
Add PKCS #11 to PSA shim as a submodule. Note it is not yet in the build system or tested.
Checklist:
----------
> Add PKCS #11 to PSA shim as a submodule.

- vendors/st/boards/stm32l475_discovery/aws_demos/application_code/st_code/stm32l4xx_hal_msp.c
Description
-----------
Add SPI and UART initialization code on ST board. The code is copied from test folder to demo.
Link: https://github.com/aws/amazon-freertos/blob/master/vendors/st/boards/stm32l475_discovery/aws_tests/application_code/st_code/stm32l4xx_hal_msp.c
Checklist:
----------
> Add SPI and UART initialization code on ST board

- libraries/abstractions/pkcs11/mbedtls/iot_pkcs11_mbedtls.c
Add check for token to be true when generating a public key.
Description
-----------
This fixes a regression that occurred when refactoring. This adds a check for the token property of a generated public key.
Checklist:
----------
> Add check for token to be true when generating a public key.

- libraries/abstractions/pkcs11/utest/iot_pkcs11_mbedtls_utest.c
Add a testcase for token property of a public key template when generating a key pair
Description
-----------
This is a testcase for catching an error that was made when refactoring the pkcs mbedtls layer. The API says that if specified, a public key's CKA_TOKEN type should have a value of "True" but this check was accidentally removed.
Checklist:
----------
> Add a testcase for token property of a public key template when generating a key pair

- libraries/freertos_plus/aws/ota/src/aws_iot_ota_agent.c
- libraries/freertos_plus/aws/ota/src/aws_iot_ota_agent_internal.h
Description
-----------
The change handles the situation when OTA Agent is suspended , existing job is cancelled and new job is queued and the OTA Agent resumes. The existing job is aborted and new job execution is initiated. 
Checklist:
----------
> OTA: Handle new job document after resuming 

- libraries/freertos_plus/standard/freertos_plus_tcp/include/FreeRTOS_IP.h
- libraries/freertos_plus/standard/freertos_plus_tcp/source/FreeRTOS_IP.c
- libraries/freertos_plus/standard/freertos_plus_tcp/source/portable/NetworkInterface/RX/NetworkInterface.c
- libraries/freertos_plus/standard/freertos_plus_tcp/source/portable/NetworkInterface/STM32Fxx/NetworkInterface.c
- libraries/freertos_plus/standard/freertos_plus_tcp/source/portable/NetworkInterface/Zynq/NetworkInterface.c
- libraries/freertos_plus/standard/freertos_plus_tcp/source/portable/NetworkInterface/esp32/NetworkInterface.c
Description
-----------
In some of the network interfaces for FreeRTOS+TCP, there is static function `prvMonitorResources()` that produces warnings as soon as these resources drop:
- The amount of heap available
- The number of network buffers
- The free space in the IP-task queue
This method of logging would produce too much information.
In this PR I added a global function `vPrintResourceStats()` to `FreeRTOS_IP.c`, so it can be used by any FreeRTOS+TCP project.
Changes compared to the earlier `prvMonitorResources()`:
- There won't be logging about the amount of heap as long as there is plenty (`ipMONITOR_MAX_HEAP`, default 1 MByte)
- There will only be logging about the heap as soon as the amount has dropped at least 10% (configurable).
Checklist:
----------
By submitting this pull …
> FreeRTOS+TCP : print resource statistics routine

- demos/tcp/aws_tcp_echo_client_single_task.c
Description
-----------
Thanks to the issue: https://github.com/aws/amazon-freertos/issues/2172, a race condition in tasks (parent and child) was found in TCP_Echo_Single demo.
As the issue points out, the parent task finishes before the child (echo) task(s) and therefore the demo finishes even before the echo-client has a chance to connect to the echo server.
This PR rectifies the aforementioned race condition by making the parent task wait using Semaphores.
+ The child (echo) tasks were designed as a `for( ; ; )` and were not getting cleaned up after the demo. This PR addresses that as well. The iterations are limited by a certain amount and the parent task cleans up the child tasks after their completion.
Checklist:
----------
By submitting this pull request, I confirm that you can …
> Sync Single Echo Client demo tasks

- libraries/3rdparty/mbedtls_config/aws_mbedtls_config.h
Re-enable encrypt then MAC for CBC now that CBC is re-enabled.
Description
-----------
Re-enable encrypt then MAC for CBC now that CBC is re-enabled. 
CBC was re-enabled in https://github.com/aws/amazon-freertos/pull/2153 for Greengrass, which needed this algorithm for TLS 1.2.
Checklist:
----------
> Re-enable encrypt then MAC for CBC now that CBC is re-enabled.

- libraries/3rdparty/mbedtls_config/aws_mbedtls_config.h
- libraries/abstractions/pkcs11/mbedtls/iot_pkcs11_mbedtls.c
Cherry-pick mbed TLS config fix and PKCS #11 fix
Description
-----------
Cherry-picking these into release-candidate
Checklist:
----------
> Cherry-pick mbed TLS config fix and PKCS #11 fix

- tools/ota_e2e_tests/aws_ota_test/aws_ota_test_case_disconnect_cancel_update.py
Description
-----------
We should prepare the image at the beginning and immediately create another update after cancel the current one to make sure device is getting the new job doc after it resumes.
Checklist:
----------
> Fix OTA disconnect and cancel E2E test

- vendors/cypress/MTB/psoc6/cmake/cy_kit_utils.cmake
Description
-----------
BLE was explicitly excluded from build if the compiler is not arm-gcc (the psoc64 BLE port currently only works with arm-gcc). This cause a problem when generating the build combinations / metadata. AFR_METADATA_MODE only runs the cmake in configuration stage without compilier definded. 
Checklist:
----------
> Fix: PSoC64 Cmake file for AFR_METADATA_MODE

- tests/unit_test/linux/config_files/portmacro.h
Bump version of `portmacro.h` file under `tests/` missed in #2183 
> Bump version of portmacro. h

- CHANGELOG.md
- README.md
**Re-brand the repository product from `FreeRTOS` to `FreeRTOS AWS Reference Integrations`**
The **FreeRTOS** product brand will be represented by the [FreeRTOS/FreeRTOS](github.com/FreeRTOS/FreeRTOS) repository and freertos.org website.
> Re-name FreeRTOS with FreeRTOS AWS Reference Integrations

- CHANGELOG.md
Add Cypress 64 board qualification text to **CHANGELOG.md** which is in scope for the **202007.00** release
> Add text for Cypress64 board qualification to ChangeLog

- libraries/abstractions/pkcs11/utest/CMakeLists.txt
- libraries/abstractions/pkcs11/utest/iot_pkcs11_mbedtls_utest.c
Update PKCS #11 unit tests
Description
-----------
Update PKCS #11 unit tests to account for x509 parsing in C_GetAttributeValue.
Checklist:
----------
> Update PKCS #11 unit tests

- libraries/abstractions/pkcs11/mbedtls/iot_pkcs11_mbedtls.c
- libraries/abstractions/pkcs11/test/iot_test_pkcs11.c
Refactor Key Size Macros
Description
-----------
Fix TODO for writing a key to DER.
Added size specific macros for the keys currently supported by the stack.
Use smallest possible buffer for converting keys to DER.
Checklist:
----------
> Refactor Key Size Macros

- libraries/freertos_plus/standard/freertos_plus_tcp/include/FreeRTOS_IP.h
- libraries/freertos_plus/standard/freertos_plus_tcp/source/FreeRTOS_IP.c
- libraries/freertos_plus/standard/freertos_plus_tcp/source/portable/NetworkInterface/RX/NetworkInterface.c
- libraries/freertos_plus/standard/freertos_plus_tcp/source/portable/NetworkInterface/STM32Fxx/NetworkInterface.c
- libraries/freertos_plus/standard/freertos_plus_tcp/source/portable/NetworkInterface/Zynq/NetworkInterface.c
- libraries/freertos_plus/standard/freertos_plus_tcp/source/portable/NetworkInterface/esp32/NetworkInterface.c
Port #2164 logging frequency of FreeRTOS+TCP stack to `release-candidate`
Description
-----------
Too much logging from network stack was inhibiting logging messages of demos to be printed, causing CI to detect false failures.
> FreeRTOS+TCP : print resource statistics routine (#2164)

- projects/cypress/CY8CKIT_064S0S2_4343W/mtb/aws_demos/Makefile
Description
-----------
To fix BLE_GATT_SERVER demo build error in build combination test.
https://amazon-freertos-ci.corp.amazon.com/view/5-Build_Combinations/job/Build_Combinations/job/Build_All_Combinations/437/
Checklist:
----------
> Fix: Enable BLE in Cypress PSoC64 MTB demo project.

- libraries/freertos_plus/aws/ota/include/aws_iot_ota_agent.h
- libraries/freertos_plus/aws/ota/src/aws_iot_ota_agent.c
- libraries/freertos_plus/aws/ota/src/aws_iot_ota_agent_internal.h
Description
-----------
This change adds supports for handling force cancellation of an in-progress OTA job from the service. This will abort the existing download and fetches the next job document from service and begins processing if available.
This change also includes getting the timestamp from job document and identifying a job document received does not have any execution data.
Checklist:
----------
> OTA: Support force cancellation of in progress Job

- tools/ota_e2e_tests/aws_ota_test/aws_ota_test_case_2_updates_cancel_1st.py
- tools/ota_e2e_tests/aws_ota_test/aws_ota_test_case_cancel_then_update.py
Description
-----------
Add 2 OTA E2E tests for handling cancel and abort.
Checklist:
----------
> Add 2 OTA E2E tests for handling cancel and abort

- libraries/freertos_plus/standard/freertos_plus_tcp/source/FreeRTOS_DNS.c
This is a copy of my earlier [PR #2048](https://github.com/aws/amazon-freertos/pull/2048). Resubmitting it to get a clean PR that is in tune with the master repo.
-----------
Checklist:
----------
> DNS lookup: warn if ipconfigDNS_CACHE_NAME_LENGTH is too small (v2)

- tools/cbmc/proofs/make_configuration_directories.py
Some CBMC proofs are built in several different 'configurations'. Prior
to this commit, the name of each of these configurations was the same as
the name of the original proof. This meant that CI would sometimes write
the proof artifacts of each of these configurations on top of each
other, since the artifacts are saved under a folder whose name is based
on the name of the proof.
This commit fixes this so that each configuration of each proof has a
unique name, formed by joining the name of the configuration to the name
of the proof with a double underscore---for example,
TaskIncrementTick__config_default.
> Make each config of a CBMC proof have unique name

- libraries/3rdparty/mbedtls_config/aws_mbedtls_config.h
Update aws_mbedtls_config.h header file
Description
-----------
* Removed statement saying that the file was part of the mbed tls library
* Added clarification on what license is being used
Checklist:
----------
> Update aws_mbedtls_config.h header file

- vendors/xilinx/boards/microzed/aws_demos/application_code/main.c
- vendors/xilinx/boards/microzed/aws_demos/config_files/FreeRTOSIPConfig.h
Description
-----------
I have tested locally that increasing the logging to 100 does not help the "Demo completed successfully" message to print, but increasing it to 128 does. Increasing the queue greater may cause issues with demos as memory is depleted. 
Every demo passes and run. 
https://amazon-freertos-ci.corp.amazon.com/job/im_v2_master/job/nightly_custom_job/63/
https://amazon-freertos-ci.corp.amazon.com/job/im_v2_master/job/nightly_custom_job/65/ - Shadow rerun
This change was needed in addition to the decrease in network statistic logs that were reduced by @htibosch a few weeks ago.
Checklist:
----------
> Increase the logging size for Xilinx Microzed

- libraries/abstractions/pkcs11/mbedtls/iot_pkcs11_mbedtls.c
PKCS #11 TODOs
Description
-----------
This commit address the last of the TODOs in iot_pkcs11_mbedtls.c
* Removed a TODO refactor comment as it was vague.
* Added a variable to track whether the sign and verify key is the same as the last operation, saving key parse operations.
Checklist:
----------
> PKCS #11 TODOs

- libraries/freertos_plus/standard/freertos_plus_tcp/include/FreeRTOSIPConfigDefaults.h
- libraries/freertos_plus/standard/freertos_plus_tcp/source/FreeRTOS_IP.c
UDP: Add ipconfigUDP_PASS_ZERO_CHECKSUM_PACKETS compile time constant
-----------
Description
-----------
In compliance with the UDP protocol specification the FreeRTOS+TCP stack currently processes UDP packets that have their checksum field set to 0.  This update introduces a new compile time constant `ipconfigUDP_PASS_ZERO_CHECKSUM_PACKETS` that defaults to 0.  The TCP/IP stack will drop UDP packets that have their checksum field set to zero unless that constant is set to 1.
Checklist:
----------
> UDP: Add ipconfigUDP_PASS_ZERO_CHECKSUM_PACKETS compile time constant

- projects/nuvoton/numaker_iot_m487_wifi/uvision/aws_demos_eth/aws_demos_eth.uvproj
Fix **Nuvoton Ethernet Build failure** by updating path to `tinycbor` files in project file
> Fix Nuvoton Ethernet Build by updating tinycbor path in project file

- libraries/freertos_plus/standard/freertos_plus_tcp/source/FreeRTOS_DNS.c
Correct DNS resolution logic
Description
-----------
The DNS resolution logic should only count A records (which are stored) when determining whether or not to stop processing records.  Previously the logic was counting all records (e.g. CNAME) in this logic.
Checklist:
----------
> Count only A records in DNS resolution logic

- libraries/freertos_plus/aws/greengrass/src/aws_helper_secure_connect.c
- vendors/nuvoton/boards/numaker_iot_m487_wifi/aws_demos/config_files/FreeRTOSConfig.h
- vendors/nuvoton/boards/numaker_iot_m487_wifi/aws_demos/config_files/FreeRTOSIPConfig.h
- vendors/nuvoton/boards/numaker_iot_m487_wifi/aws_tests/config_files/FreeRTOSIPConfig.h
A logging task is present to serialize calls to `printf` to ensure that messages from different tasks are not mangled. This requires that all the messages are printed using `vLoggingPrint` and `vLoggingPrintf` which will pass all the messages serially to the logging task. An incorrectly defined `configPRINTF` was causing `printf` to be called directly from multiple tasks resulting in mangled messages. This PR address it by defining  `configPRINTF` to  `vLoggingPrintf`.
`FreeRTOS_debug_printf` macro is called with double parentheses from the codebase and the expectation is that one set of parentheses will be removed when defining it to `vLoggingPrintf`:
```c
#define FreeRTOS_debug_printf( x ) vLoggingPrintf x
```
It was incorrectly defined to `vLoggingPrintf(x)` resulting in build errors …
> Fix GreenGrass Discovery demo failure in Nuvoton Ethernet board

- libraries/freertos_plus/aws/greengrass/src/aws_helper_secure_connect.c
- vendors/nuvoton/boards/numaker_iot_m487_wifi/aws_demos/config_files/FreeRTOSConfig.h
- vendors/nuvoton/boards/numaker_iot_m487_wifi/aws_demos/config_files/FreeRTOSIPConfig.h
- vendors/nuvoton/boards/numaker_iot_m487_wifi/aws_tests/config_files/FreeRTOSIPConfig.h
Port #2242 for Nuvoton Ethernet Project configuration fixes to `master` branch
> Fix GreenGrass Discovery demo failure in Nuvoton Ethernet board (#2242)

- CHANGELOG.md
Update **FreeRTOS+TCP** section in ChangeLog for **202007.00** release
> Update ChangeLog for FreeRTOS+TCP version and security improvement text

- libraries/freertos_plus/aws/ota/src/aws_iot_ota_agent.c
Description
-----------
This changes handles the condition where a job in self-test is forced cancelled and a new job is created before the device reboots in self-test. The device after detecting this condition now resets to rollback to previous image.
Checklist:
----------
> OTA: Self-test rollback in case the job in self-test is forced cancelled

- libraries/freertos_plus/aws/ota/src/aws_iot_ota_agent.c
Description
-----------
This change uses the platform image state function instead of OTA image state. 
Checklist:
----------
> OTA: Use platform get state function in processjobhandler

- libraries/freertos_plus/standard/freertos_plus_tcp/include/FreeRTOSIPConfigDefaults.h
* Remove duplication of default config definition for `ipconfigIP_PASS_PACKETS_WITH_IP_OPTIONS` and `ipconfigUDP_PASS_ZERO_CHECKSUM_PACKETS`
* Add helpful documentation for explaining utility of macros
> Hygiene changes for new macros in FreeRTOS+TCP config defaults

- demos/tcp/aws_tcp_echo_client_single_task.c
Description
-----------
The TCP echo demo erroneously reported success even when the connection had failed. This PR rectifies the error with the demo returning success/failure depending on the actual statistics of the connections.
The user can choose the threshold for the number of failures before the demo will be deemed to have failed.
Checklist:
----------
> Correct error reporting in demo

- CHANGELOG.md
- README.md
- vendors/cypress/MTB/ota/README.md
Updates to various docs for the release.
Description
-----------
1. Update top-level ReadMe to include the PSoC64 (several links are not live yet)
2. Update top-level Changelog to call out FreeRTOS AWS Reference Integrations and removed the release date, to be replaced with release month instead.  
3. Added the Cypress OTA ReadMe - (several links are not live yet)
> Updates to Changelog/ReadMe

- libraries/freertos_plus/standard/freertos_plus_tcp/include/FreeRTOSIPConfigDefaults.h
* Remove duplication of code and add documentation for new macros in FreeRTOSIPConfigDefaults.h
> Hygiene changes for new macros in FreeRTOS+TCP config defaults (#2267)

- libraries/abstractions/common_io/test/test_iot_flash.c
Update flash offset align check
Description
-----------
There is flash start offset align check condition in unit test case of test_iot_flash.c 
I think it assumes the flash start offset is less than block size. 
If the flash start offset is set to the even multiple of the block size, the block size alignment check fails. 
For example, 
- pxFlashInfo->ulBlockSize = 0x10000 (64K) 
- ultestIotFlashStartOffset = 2 * pxFlashInfo->ulBlockSize
- Then the alignment check fails. 
This update extends the alignment check condition to support the flash start offset larger than the block size. 
Checklist:
----------
> Update flash offset align check

- libraries/freertos_plus/standard/tls/src/iot_tls.c
TLS Shim Layer DRBG
Description
-----------
Use PKCS #11 to seed a DRBG instead of calling PKCS #11 for all random numbers needed by TLS.
This reduces the load on secure elements significantly when creating many random numbers.
Checklist:
----------
> TLS Shim Layer DRBG

- libraries/abstractions/pkcs11/mbedtls/iot_pkcs11_mbedtls.c
- libraries/abstractions/pkcs11/utest/iot_pkcs11_mbedtls_utest.c
Address some PKCS #11 TODOs
Description
-----------
* Added check to see if the parsed buffer was a certificate.
* Added macro for magic number for the EC point used in EC public keys.
* Determined byte size of an EC signature on the prime256v1 curve.
Checklist:
----------
> Address some PKCS #11 TODOs

- libraries/freertos_plus/aws/ota/include/aws_iot_ota_agent.h
Fix precompiler if should be ifdef in ota agent
Description
-----------
Just very minor change, this fails with stricter compilation settings otherwise:
```
aws_iot_ota_agent.h:408:13: error: "WIN32" is not defined, evaluates to 0 [-Werror=undef]
#if WIN32
^~~~~
cc1: all warnings being treated as errors
```
Checklist:
----------
- [  ] I have tested my changes. No regression in existing tests.
- [  ] My code is Linted.
(didn't take the effort, i assume very much both are still true, also couldn't find doc to quickly run tests and lint, should be some cmake targets? pointers appreciated if necessary :/ ) 
> Fix precompiler if should be ifdef in ota agent

- libraries/abstractions/pkcs11/mbedtls/iot_pkcs11_mbedtls.c
Fix memory leak in pkcs11 implementation.
Description
-----------
The x509 certificate context used to parse an object to determine if it was an x509 certificate was never free'd after use.
Checklist:
----------
> Fix memory leak in pkcs11 implementation.

- vendors/espressif/boards/esp32/CMakeLists.txt
Espressif CMake ENV Variables
Description
-----------
Add warning message to help user debug environment variable related build issues with Espressif CMake. If IDF_PATH is defined as an Environment variable when trying to generate a build folder, the error messages are unclear and hard to debug.
Checklist:
----------
> Espressif CMake ENV Variables

- vendors/renesas/manifest.cmake
Fix CMake Board Path's Command
Description
-----------
The Renesas manifest file is not in the root of the vendor directory, and causes an error when earching for vendor paths.
To reproduce:
Before merging this commit
` cmake -P tools/cmake/afr_board_paths.cmake`
Expected Output:
cmake_supported_boards.yml created
Actual Output:
CMake Error at tools/cmake/afr_board_paths.cmake:19 (include):
include could not find load file:
/Users/lundinc/Documents/amazon-freertos/vendors/renesas/manifest.cmake
Checklist:
----------
> Fix CMake Board Path's Command

- projects/nxp/lpc54018iotmodule/iar/bootloader/spifi_bootloader.ewp
Add Mbed TLS macros to the LPC54018 bootloader project
Description
-----------
* Add the MBEDTLS_CONFIG_FILE and CONFIG_MEDTLS_USE_AFR_MEMORY macros
* Add the directory of the AWS Mbed TLS config file to the include path
* Add the Mbed TLS utility directory to the include path
Checklist:
----------
> Add Mbed TLS macros to the LPC54018 bootloader project

- vendors/renesas/rx_mcu_boards/boards/rx65n-rsk/CMakeLists.txt
Update the rx65n-rsk CMake file to include the ota port
Description
-----------
Added a reference to the preexisting aws_ota_pal.c file in the rx65n-rsk CMake File
Checklist:
----------
> Add OTA port for rx65n-rsk to CMake files

- libraries/abstractions/common_io/include/iot_battery.h
PR for iot_battery.h fix
Description
-----------
Some type definition in iot_battery.h cannot hold real battery info well.
Corrected them to proper type definition to meet real battery info requirement.
Checklist:
----------
> Correct some type defination of battery info and comments

- libraries/abstractions/common_io/CMakeLists.txt
- libraries/abstractions/common_io/test/iot_test_common_io.c
Add all common-io peripherals to CMake build system
Description
-----------
Since the CMake now only tries to link supported peripheral symbols, all the tests and header files can be added to the build.
Checklist:
----------
> Add all common-io peripherals to CMake build system

- vendors/renesas/rx_mcu_boards/boards/rx65n-rsk/CMakeLists.txt
Update rx65n CMake file to match folder structure
Description
-----------
Previous commits changed and moved files in the renesas vendor
directory. The paths in the CMakeLists.txt file for renesas was
not updated alongside the file shuffle. This aligns the CMake file
with the current folder structure so that the metadata can build.
Checklist:
----------
> Update rx65n CMake file to match folder structure

- vendors/espressif/boards/esp32/ports/ble/nimble/iot_ble_hal_gap.c
Description
-----------
- Have added if-check to avoid filling `FLAGS` field in scan response data.
- Previous to this PR, `FLAGS` were potentially getting set twice. Once in advertisement data and second time in scan response data. To avoid duplication, added this check.   
Checklist:
----------
> NimBLE AFR: Set flags field only in advertisement data and not in scan response

- libraries/abstractions/pkcs11/mbedtls/iot_pkcs11_mbedtls.c
Minor PKCS #11 Refactoring
Description
-----------
Removed unnecessary check now that prvMbedTLS_Initialize has a static scope. Added additional guard to prevent freeing the sha256 mbedtls context if an operation was never initialized.
Checklist:
----------
> Minor PKCS #11 Refactoring

- libraries/abstractions/pkcs11/mbedtls/iot_pkcs11_mbedtls.c
Fix non-conformance to mbed TLS pk.h API when hashing a signature.
Description
-----------
The mbed TLS specifies that when using RSA, one should use no hashing algorithm and when using ECDSA one should use a hashing algorithm.
Checklist:
----------
> Fix non-conformance to mbed TLS pk.h API when hashing a signature.

- libraries/freertos_plus/aws/ota/src/aws_iot_ota_agent.c
- libraries/freertos_plus/aws/ota/src/aws_iot_ota_interface.c
- libraries/freertos_plus/aws/ota/src/aws_iot_ota_interface.h
- libraries/freertos_plus/aws/ota/src/http/aws_iot_ota_http.c
- libraries/freertos_plus/aws/ota/src/http/aws_iot_ota_http.h
- libraries/freertos_plus/aws/ota/src/mqtt/aws_iot_ota_mqtt.c
- libraries/freertos_plus/aws/ota/src/mqtt/aws_iot_ota_mqtt.h
Description
-----------
Address 2 issues:
- Separate data plane and control plane cleanup. We don't want to unsubscribe from job notification topic after OTA data transfer complete.
- Check if the stream name is null when unsubscribe from stream topic in MQTT data plane.
test is now passing: https://amazon-freertos-ci.corp.amazon.com/job/im_v2_master/job/ota_tests_ide/job/espressif/job/esp32_devkitc-make/68/console
Checklist:
----------
> OTA bug fix

- libraries/abstractions/wifi/test/iot_test_wifi.c
- tests/common/aws_test_runner.c
Quarantine part of WiFi tests to a different group
Description
-----------
Some of the WiFi tests are not adding value today: they don't test the result of API being qualified, or fails intermittently without enough error information for debugging.
Quarantine those tests for now to a `Quarantine_WiFi` group until they are fixed and restored.
Checklist:
----------
> Quarantine part of WiFi tests

- vendors/microchip/harmony/v2.05/framework/driver/wifi/wilc1000/wireless_driver_extension/wdrvext_wilc1000.c
PICMZEF MQTT demo project reset issue
Description
-----------
MQTT Demo completes and after a few seconds later a reset is observed from the console logs 
Checklist:
----------
> solve the reset issue by return error if the WINC driver is closed

- libraries/abstractions/pkcs11/mbedtls/iot_pkcs11_mbedtls.c
- libraries/abstractions/pkcs11/test/MBT_C_GenerateKeyPair.c
- libraries/abstractions/pkcs11/test/MBT_C_GetAttributeValue.c
- libraries/abstractions/pkcs11/test/MBT_C_Sign.c
- libraries/abstractions/pkcs11/test/MBT_C_SignInit.c
- libraries/abstractions/pkcs11/test/MBT_C_VerifyInit.c
- libraries/abstractions/pkcs11/test/MBT_ObjectMachine.c
- libraries/abstractions/pkcs11/test/MBT_SignMachine.c
- libraries/abstractions/pkcs11/test/MBT_VerifyMachine.c
- libraries/abstractions/pkcs11/test/iot_test_pkcs11.c
- libraries/abstractions/pkcs11/test/iot_test_pkcs11_globals.h
- libraries/freertos_plus/standard/utils/src/iot_pki_utils.c
PKCS 11 Multi Acc Auth
Description
-----------
Refactor PKCS #11 tests for boards that cannot create new credentials. Eg. for multi-acc registration.
Removed stdio includes
Clean up some MISRA regressions
Checklist:
----------
>  PKCS 11 Multi Acc Auth

- projects/microchip/curiosity_pic32mzef/mplab/aws_demos/nbproject/configurations.xml
- projects/microchip/curiosity_pic32mzef/mplab/aws_tests/nbproject/configurations.xml
- projects/microchip/curiosity_pic32mzef/mplab/bootloader/nbproject/configurations.xml
Update configurations.xml to fix build errors for MPLABX 5.40
Description
-----------
In the latest release of amazon-freertos (2020007.0):
MPLABX 5.40 DOES NOT work with XC compiler version 2.41, 2.40, and 2.30 on both my Windows and Mac environment.
However, MPLABX 5.35 works with XC compiler version 2.41, 2.40, and 2.30 on both my Windows and Mac environment.
I believe CI is using MPLABX 5.35, and both XC compiler versions 2.40 and 2.30.
The error in MPLABX 5.40 of amazon-freertos 2020007.0 stems from passing a string literal as a preprocessor macro in `configurations.xml`:
```xml
<property key="preprocessor-macros" value="MBEDTLS_CONFIG_FILE=\\\&quot;aws_mbedtls_config.h\\\&quot;;
```
This ends up giving the following error in MPLABX 5.40:
```
In file included from …
```
> Update configurations.xml to fix build errors for MPLABX 5.40

- demos/include/iot_demo_runner.h
- demos/mqtt_transport/CMakeLists.txt
- demos/mqtt_transport/demo_config.h
- demos/mqtt_transport/mqtt_config.h
- demos/mqtt_transport/mqtt_demo_transport.c
- libraries/c_sdk/standard/ble/CMakeLists.txt
- libraries/c_sdk/standard/ble/include/iot_ble_mqtt_serialize.h
- libraries/c_sdk/standard/ble/include/iot_ble_mqtt_transport.h
- libraries/c_sdk/standard/ble/include/iot_ble_mqtt_transport_config.h
- libraries/c_sdk/standard/ble/src/iot_ble_mqtt_serialize.c
- libraries/c_sdk/standard/ble/src/iot_ble_mqtt_transport.c
- libraries/c_sdk/standard/mqtt/CMakeLists.txt
- vendors/espressif/boards/esp32/aws_demos/config_files/aws_demo_config.h
- vendors/espressif/boards/esp32/aws_demos/config_files/mqtt_config.h
Transport code implementation and demo
Description
-----------
New transport layer for MQTT over BLE
New demo to show how transport layer works
Fixed CMakeFile issues
Fixed issue in old MQTT wrapper function
Added transport config file
Changed existing serializer code to use argument's packet identifier
Made packet identifier the responsibility of the application
Uncrustify and Coverity checks
Addressing comments from previous PR
Note: This is a new iteration of an old PR, old PR is https://github.com/aws/amazon-freertos/pull/2318
Checklist:
----------
> Transport code implementation + demo

- libraries/abstractions/common_io/test/test_iot_adc.c
Description
-----------
Checklist:
----------
> Change ioctl test case for ADC to use greater than equal.

- vendors/microchip/harmony/v2.05/framework/driver/wifi/wilc1000/include/wdrv_wilc1000_stub.h
This PR addresses the issue by defining `WDRV_STUB_Print` to be `configPRINTF` rather than `SYS_CONSOLE_PRINT`. 
Checklist:
----------
> Fix logging issue that is causing mangled start markers in Microchip boards

- libraries/abstractions/secure_sockets/lwip/iot_secure_sockets.c
Description
-----------
Checklist:
----------
[Issue #2307](https://github.com/aws/amazon-freertos/issues/2307) points out that there is a wifi dependency in the lwip implementation of the Secure Sockets API.  This Pull Request eliminates that dependency.  Has been tested on espressif & mediatek boards with Full_TCP, HTTPS_Client_System, and MQTT_System tests.
> Remove wifi dependency from lwip Secure Sockets implementation

- libraries/abstractions/ble_hal/include/bt_hal_manager_adapter_ble.h
Adding Advertise Tx Power defines
Description
-----------
* Tx Power defines which would be an index to Advertising Power values (in dBm) to be set by platforms.
Checklist:
----------
(Only defines)
> Adding Advertise Tx Power defines

- libraries/abstractions/platform/freertos/iot_threads_freertos.c
Update IotThreads_Free and IotThreads_Malloc default values
Description
-----------
The current default values for IotThreads_Free and IotThreads_Malloc in iot_threads_freertos.c are set to the standard library free and malloc functions. These functions are not thread-safe and can likely lead to issues. There are no current issues because they can be overridden, but they make for poor defaults.
Checklist:
----------
> Update IotThreads_Free and IotThreads_Malloc default values

- libraries/abstractions/pkcs11/test/iot_test_pkcs11.c
- vendors/infineon/boards/xmc4800_plus_optiga_trust_x/aws_tests/config_files/iot_test_pkcs11_config.h
- vendors/infineon/secure_elements/pkcs11/iot_pkcs11_trustx.c
Fix public key deletion and PKCS #11 tests on Optiga X.
Description
-----------
The newly refactored tests were overwriting and deleting the public key stored on the device. Need to do further tests to ensure this is the correct solution, but this will fix the "real" public key being deleted, as well as making the PKCS #11 tests pass.
Checklist:
----------
> Fix public key deletion and PKCS #11 tests on Optiga X.

- vendors/mediatek/boards/mt7697hx-dev-kit/ports/wifi/iot_wifi.c
Mediatek Wifi_ping fail on zero
Description
-----------
if no pings are received fail wifi ping, as other errors could lie behind which are not reported due to driver code
Checklist:
----------
> Fix: Mediatek wifi_ping fail on zero

- libraries/freertos_plus/aws/ota/include/aws_iot_ota_agent.h
Update OTA_AgentShutdown function comment
Description
-----------
OTA_AgentShutdown was referring to a non-existent state. I updated this to be
the "eOTA_AgentState_Stopped" state. 
Addressing issue #2370.
Checklist:
----------
> Update OTA_AgentShutdown function comment

- demos/demo_runner/iot_demo_freertos.c
Improve demo comment related to IotSdk_Init
Description
-----------
Improve comment in iot_demo_freertos.c to clearly state the requirement of
calling the IotSdk_Init function before any other C-SDK related functions.
This is PR is to address to issue #2369 
Checklist:
----------
> Improve demo comment related to IotSdk_Init

- libraries/abstractions/wifi/include/iot_wifi.h
Add WPA3 Security mode enum for wifi to run FullWiFi IDT tests
Description
-----------
WiFi Supports WPA3 Security mode and this enum is required to qualify WPA3 security mode  in Amazon FreeRTOS.
We are able to verify FullWiFi IDT test using WPA3 Security mode for Cypress kits with change required in userdata_schema.json for IDT version 3.1.0. Below change is required in devicetester package 
-  eWiFiSecurityWPA3 in clientWifiConfig ==> wifiSecurityType 
-  eWiFiSecurityWPA3 in testWifiConfig ==> wifiSecurityType 
This enum needs to be updated in aws documentation and IDTv3.1.0 onwards
Checklist:
----------
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under …
> Add WPA3 Security Mode enum for WiFi

- vendors/nuvoton/boards/numaker_iot_m487_wifi/aws_tests/config_files/FreeRTOSConfig.h
- vendors/nuvoton/boards/numaker_iot_m487_wifi/aws_tests/config_files/aws_wifi_config.h
Description
-----------
MQTT_System tests are failing because of allocation failure. This change increase the heap size to address the failure.
Checklist:
----------
> Increase heap size for Nuvoton tests project

- vendors/espressif/boards/esp32/ports/ble/nimble/iot_ble_hal_gatt_server.c
Characteristic descriptors are internally added by NimBLE stack, so to avoid duplication we avoid adding descriptors (16 bit UUID = 0x2902) to GATT database. The problem may come when the caller to `prvAddServiceBlob` provides CCCD with 128bit UUID type and standard base UUID. Ideally this should be avoided, but to avoid duplication this PR intends to accommodate 128 bit UUID comparison as well.
Description
-----------
- Add `BLE_GATT_DSC_CLT_CFG_UUID128` macro to convert 16 bit CCCD UUID (`0x2902`) to 128 bit UUID.
- Compare characteristic descriptor UUID with `BLE_GATT_DSC_CLT_CFG_UUID128`.
Checklist:
----------
> NimBLE AFR: Accommodate 128bit UUID type for comparison with standard CCCD(0x2902)

- demos/demo_runner/iot_demo_freertos.c
Description
-----------
This delay give the logging task a chance to drain the logging queue. This increases the probability of demo status and demo finished messages used by the test framework not getting dropped.
Checklist:
----------
> Add a delay before logging demo finished messages

- libraries/abstractions/pkcs11/mbedtls/iot_pkcs11_mbedtls.c
- libraries/abstractions/pkcs11/utest/iot_pkcs11_mbedtls_utest.c
Added the last 0.4% of PKCS #11 test coverage.
Description
-----------
Added an array that can be memcmp'd to see if it's a valid key. Removed impossible code path.
Checklist:
----------
> PKCS  Unit Tests

- tools/cbmc/README.md
These instructions are outdated and only ever worked for a single proof.
> Remove CMake instructions for building CBMC proofs

- vendors/infineon/secure_elements/optiga_trust_x/optiga/cmd/CommandLib.c
https://github.com/Infineon/optiga-trust-x/pull/42
Sync with the OPTIGA Trust X repo.
These important security relevant changes are recommended for all new designes
-----------
With this PR Incoming hash and hash context are now protected from beining manipulated on the i2c line without being recognised.
Checklist:
----------
- [+ ] I have tested my changes. No regression in existing tests.
- [ +] My code is Linted.
> Sync with the OPTIGA Trust X PR 42

- vendors/espressif/boards/esp32/ports/wifi/iot_wifi.c
Description
-----------
Semaphore is not released in esp32 WIFI_StartAP. Address issue #2415.
Checklist:
----------
> Fix WIFI_StartAP in esp32 port

- .gitmodules
Update Mbed TLS to v2.16.8 from v2.16.7
Description
-----------
Updated the Mbed TLS submodule to point to v2.16.8 instead of v2.16.7. 
Checklist:
----------
> Update Mbed TLS to v2.16.8 from v2.16.7

- libraries/abstractions/ble_hal/test/src/iot_test_ble_hal_common.c
Fix Remove all bonds test in BLE HAL qualification test
Description
-----------
Remove all bonds test was only copying  one bond (the first element of array), which causes it to fail if there are more than one bonds.
Fixed to copy the full array of bonds.
Checklist:
----------
> Fix Remove all bonds test in BLE HAL

- libraries/abstractions/common_io/include/iot_adc.h
- libraries/abstractions/common_io/test/test_iot_adc.c
- libraries/abstractions/common_io/test/test_iot_flash.c
- libraries/abstractions/common_io/test/test_iot_gpio.c
- libraries/abstractions/common_io/test/test_iot_i2s.c
- libraries/abstractions/common_io/test/test_iot_timer.c
- libraries/abstractions/common_io/test/test_iot_watchdog.c
Remove portYIELD_FROM_ISR calls in common-io tests.
Description
-----------
This change removes calls to portYIELD_FROM_ISR as the function prototype is not consistent between kernel ports. 
Checklist:
----------
> Remove portYIELD_FROM_ISR Calls in common-io Tests

- libraries/abstractions/pkcs11/mbedtls/iot_pkcs11_mbedtls.c
- libraries/abstractions/pkcs11/test/iot_test_pkcs11.c
- vendors/st/boards/stm32l475_discovery/aws_tests/config_files/FreeRTOSConfig.h
- vendors/st/boards/stm32l475_discovery/aws_tests/config_files/iot_test_pkcs11_config.h
- vendors/st/boards/stm32l475_discovery/ports/pkcs11/iot_pkcs11_pal.c
Description
-----------
This is needed for PKCS11 EC tests to pass when TLS is done on the host itself as opposed to offloading to the WiFi module. In addition to these changes, the following config changes are also needed to run EC tests:
- Set `pkcs11testEC_KEY_SUPPORT` to 1 in iot_test_pkcs11_config.h.
- Set `pkcs11testGENERATE_KEYPAIR_SUPPORT` to 1 in iot_test_pkcs11_config.h.
- Set `pkcs11configSUPPRESS_ECDSA_MECHANISM` to 0 in iot_pkcs11_config.h.
This commit also fixes a bug in the iot_pkcs11_mbedtls.c where incorrect label (public key/private key) was used to find the corresponding object.
Testing
-----------
All the PKCS11 tests pass locally.
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your …
> Add public key support in the PKCS11 PAL for ST

- libraries/abstractions/platform/freertos/iot_network_freertos.c
Update IotNetworkAfr_Send to call Sockets_Send while there are remaining bytes
Description
-----------
This fixes issue #2336. Depending on the size of the write buffer, `Sockets_Send` may return a number of bytes that is less than the message length. In which case, we must continually call `Sockets_Send` until all bytes remaining are sent.
Checklist:
----------
> Update IotNetworkAfr_Send to call Sockets_Send while there are bytes remaining

- libraries/c_sdk/aws/defender/src/aws_iot_defender_collector.c
Description
-----------
`aws_iot_defender_collector` defines a helper function named `_serialize`. Functions prefixed with underscores are reserved for the compiler, and compiling with MSVC on Visual Studio 2019, version 16.7.2, gives me the error `'_serialize': intrinsic function, cannot be defined`. This renames the function so the code can compile for the Windows simulator.
Checklist:
----------
> Rename underscored function for MSVC

- libraries/abstractions/pkcs11/test/iot_test_pkcs11.c
- libraries/abstractions/secure_sockets/test/iot_test_tcp.c
Tests: SecureSockets: Enable SNI when connecting to IoT Core 
Description
-----------
When connecting to IoT Core, always try to use SNI to enable device's relying on Multi Account Registration.
Checklist:
----------
> Tests: SecureSockets: Enable SNI when connecting to IoT Core 

- vendors/espressif/boards/esp32/CMakeLists.txt
- vendors/espressif/boards/esp32/aws_tests/config_files/aws_test_runner_config.h
- vendors/espressif/boards/esp32/aws_tests/config_files/iot_test_common_io_config.h
- vendors/espressif/boards/esp32/ports/common_io/component.mk
- vendors/espressif/boards/esp32/ports/common_io/include/iot_board_gpio.h
- vendors/espressif/boards/esp32/ports/common_io/iot_i2c.c
- vendors/espressif/boards/esp32/ports/common_io/iot_spi.c
- vendors/espressif/boards/esp32/ports/common_io/iot_test_common_io_internal.c
- vendors/espressif/boards/esp32/ports/common_io/iot_uart.c
Description
-----------
This PR intends to add support for UART, SPI and I2C modules in Common I/O
Checklist:
----------
> Add support for Common I/O (UART, SPI and I2C) on ESP32

- libraries/abstractions/common_io/test/test_iot_uart.c
Use semaphore in loopback test.
Description
-----------
The call to vTaskDelay is after the call to the ioctl. Instead it should be before, to allow the UART to transmit it's message. Instead we will use semaphores to release the test task once the write and read interrupts have fired.
Checklist:
----------
> Use semaphore in common-io UART loopback test

- projects/cypress/CY8CKIT_064S0S2_4343W/mtb/aws_demos/afr.mk
- projects/cypress/CY8CKIT_064S0S2_4343W/mtb/aws_tests/afr.mk
CY8CKIT_064S0S2_4343W: Correct PKCS#11 build
Description
-----------
Errors in afr.mk that is causing MTB Windows builds to fail.
Signed-off-by: Raymond Ngun <raymond.ngun@cypress.com>
Checklist:
----------
> CY8CKIT_064S0S2_4343W: Correct PKCS#11 build

- libraries/abstractions/platform/freertos/iot_network_freertos.c
This fix according to commit 63856c1626f71fc1de2519839757d4ded25c7737. Chunk size of bytesRemaining must be sent in current iteration instead of full messageLength.
> Update IotNetworkAfr_Send to fix chunk size while sending remaining bytes.

- vendors/espressif/boards/esp32/ports/ble/nimble/iot_ble_hal_common_gap.c
Nimble: Disable RPA feature before BLE disable
Description
-----------
Disable RPA feature as a stale timer from RPA causes NIMBLE port to crash 15 mins (RPA timeout) after BLE shutdown.
Checklist:
----------
> Nimble: Disable RPA feature before BLE disable

- libraries/c_sdk/standard/https/test/unit/iot_tests_https_common.h
- projects/st/stm32l475_discovery/ac6/aws_tests/.project
- vendors/st/boards/stm32l475_discovery/CMakeLists.txt
- vendors/st/boards/stm32l475_discovery/aws_tests/STM32L475VGTx_FLASH.ld
- vendors/st/boards/stm32l475_discovery/aws_tests/application_code/main.c
- vendors/st/boards/stm32l475_discovery/aws_tests/config_files/FreeRTOSConfig.h
The tests require that the amount of headers in the response fit at a minimum the following string (69 characters):
```
HTTP/1.1 200 OK\r\nContent-Length: <bodyLengthStr>\r\nheader0: value0\r\n\r\n
```
The tests require that HTTPS_TEST_RESP_BODY_BUFFER_SIZE + HTTPS_TEST_RESP_HEADER_BUFFER_LENGTH < HTTPS_TEST_RESPONSE_MESSAGE_LENGTH.
We have also updated the ST tests to use heap5 to save more memory. 
All HTTPS Client tests passing on windows and ST:
https://amazon-freertos-ci.corp.amazon.com/job/im_v2_master/job/nightly_custom_job/583/
All HTTP tests passing on all boards (except transient not passing in infineon and microchip with reruns below):
https://amazon-freertos-ci.corp.amazon.com/job/im_v2_master/job/nightly_custom_job/584/
HTTP tests passing on Infineon: …
> Decrease memory used in the HTTPS Client unit tests

- demos/ble/aws_ble_gatt_server_demo.c
- libraries/c_sdk/standard/ble/include/iot_ble.h
Move all related code related to IOT_BLE_ADD_CUSTOM_SERVICES to within if defined blocks.
This fixes warnings in the build as seen when building esp32.
All this PR does is move these functions:
- vCounterUpdateTaskFunction()
- vGattDemoSvcHook()
- _connectionCallback()
To within this if preprocessor block for IOT_BLE_ADD_CUSTOM_SERVICES :
```
#if ( IOT_BLE_ADD_CUSTOM_SERVICES == 1 )
...
#endif
```
Oh and I fixed some comments in iot_ble.h for vGattDemoSvcHook() and another close by.
Checklist:
----------
> Fix warnings in BLE demo build

- .gitmodules
Add submodule reference to `v1.0.0` tag of [coreMQTT](https://github.com/FreeRTOS/coreMQTT) repository
> Add submodule to coreMQTT repository

- tools/certificate_configuration/CertificateConfigurator.html
Fix html doc for wrong path for demos/include directory
Description
-----------
The path in CertificateConfigurator.html for the include directory is wrong (./demos/common/include)
fixing to (./demos/include)
issue #2478 
> Docs: Fix html doc for wrong path for demos/include directory

- libraries/abstractions/secure_sockets/freertos_plus_tcp/iot_secure_sockets.c
- libraries/abstractions/secure_sockets/include/iot_secure_sockets.h
- libraries/abstractions/secure_sockets/lwip/iot_secure_sockets.c
Secure Socket changes  to enable TCP keep-alive
Description
-----------
Added TCP Keep-alive option to enable and configure values via SOCKETS_SetSockOpt for LWIP and these options are not supported for FreeRTOS Plus TCP.
Checklist:
----------
> Secure Socket changes to enable TCP keep-alive

- vendors/espressif/boards/esp32/ports/ble/nimble/iot_ble_hal_gatt_server.c
Fix `prvBTStartService` in NimBLE port. This change also assumes that `prvAddServiceBlob` was called before calling `prvBTStartService`.
Description
-----------
- Previous to this PR, `eBTStatusUnsupported` was returned.
- Check if the input handle matches with the one populated in `prvAddServiceBlob`.
- Call `pxServiceStartedCb` callback if not NULL.
Checklist:
----------
> NimBLE AFR: Check if the handle is valid for prvBTStartService

- vendors/st/boards/stm32l475_discovery/aws_demos/STM32L475VGTx_FLASH.ld
- vendors/st/boards/stm32l475_discovery/aws_tests/STM32L475VGTx_FLASH.ld
Description
-----------
Linker script verifies that there is enough space for the MSP stack in the RAM. The MSP was placed in the RAM1 while the check was being done on RAM2 leaving the check useless and leaving a possibility that RAM1 does not have enough space for MSP. This commit moves the check to RAM1.
Checklist:
----------
> Fix MSP stack check in ST linker scripts

- vendors/renesas/boards/rx65n-rsk/aws_tests/config_files/iot_test_pkcs11_config.h
Fix PKCS #11 Capabilities Test Failures on Renesas.
Description
-----------
The PKCS #11 config was mis-configured and causing failures to to inconsistencies with the run time capabilities of the stack.
Checklist:
----------
> Fix PKCS #11 Capabilities Test Failures on Renesas.

- tools/cbmc/proofs/ARP/ARPAgeCache/ARPAgeCache_harness.c
- tools/cbmc/proofs/ARP/ARPGenerateRequestPacket/ARPGenerateRequestPacket_harness.c
- tools/cbmc/proofs/ARP/ARP_FreeRTOS_OutputARPRequest/OutputARPRequest_harness.c
- tools/cbmc/proofs/ARP/ARP_OutputARPRequest_buffer_alloc1/OutputARPRequest_harness.c
- tools/cbmc/proofs/ARP/ARP_OutputARPRequest_buffer_alloc2/OutputARPRequest_harness.c
- tools/cbmc/proofs/CheckOptions/CheckOptions_harness.c
- tools/cbmc/proofs/CheckOptionsInner/CheckOptionsInner_harness.c
- tools/cbmc/proofs/CheckOptionsOuter/CheckOptionsOuter_harness.c
- tools/cbmc/proofs/HTTP/global_state_HTTP.c
- tools/cbmc/proofs/TCP/prvTCPPrepareSend/TCPPrepareSend_harness.c
- tools/cbmc/proofs/parsing/ProcessIPPacket/ProcessIPPacket_harness.c
- tools/cbmc/stubs/freertos_api.c
Some proofs assume that some pointers returned by malloc are not
NULL. This patch modifies those proofs to make these assumptions
explicit with `__CPROVER_assume(pointer != NULL)` for all such
pointers.
> Modify CBMC proofs to make assumptions about malloc explicit.

- libraries/abstractions/common_io/CMakeLists.txt
- vendors/st/boards/stm32l475_discovery/CMakeLists.txt
Update `AFR::common_io` module to be built as a library so that application can link against it.
Currently, the module is configured as an `INTERFACE` which makes it as a non-independent library target. By removing the `INTERFACE` configuration, CMake will expose `afr_common_io` as a library target which can be linked against with `target_link_libraries`.
> Make common_io as a library target

- libraries/abstractions/transport/secure_sockets/transport_secure_sockets.c
- tests/integration_test/core_mqtt_system_test.c
Remove instances of NULL check with SOCKETS_INVALID_SOCKET in `transport_secure_sockets.c` and `core_mqtt_system.c` implementation
> Fix transport_secure_sockets implementation

- vendors/st/boards/stm32l475_discovery/aws_tests/application_code/main.c
- vendors/st/boards/stm32l475_discovery/aws_tests/config_files/FreeRTOSConfig.h
Description
-----------
Move 2KB heap from RAM1 to RAM2. This fixes GGD tests that are failing to build because of RAM overflow.
Checklist:
----------
> Fix GGD tests build failure for ST

- vendors/microchip/boards/ecc608a_plus_winsim/ports/ota/aws_ota_pal.c
Description
-----------
Use OTA code signing cert from header for winsim ecc608. This changes was made in regular winsim before, but ecc608 was left out. This PR syncs the change from winsim and now their OTA pal are the same.
Checklist:
----------
> Use OTA code signing cert from header for winsim ecc608

- tests/integration_test/core_mqtt_system_test.c
Description
-----------
AWS IoT Core takes some time before resending an unack'd PUBLISH, so a delay is added before resuming the persistent session.
Checklist:
----------
> Wait for republish in MQTT integration tests for AWS IoT Core

- vendors/mediatek/boards/mt7697hx-dev-kit/aws_demos/config_files/FreeRTOSConfig.h
- vendors/mediatek/boards/mt7697hx-dev-kit/aws_tests/config_files/FreeRTOSConfig.h
- vendors/nxp/boards/lpc54018iotmodule/aws_demos/config_files/FreeRTOSConfig.h
- vendors/nxp/boards/lpc54018iotmodule/aws_tests/config_files/FreeRTOSConfig.h
Add CLI config to mediatek and nxp boards
Description
-----------
Boards were missing the config for CLI library.
Checklist:
----------
> Add CLI config to mediatek and nxp boards

- libraries/abstractions/secure_sockets/include/iot_secure_sockets.h
- libraries/abstractions/secure_sockets/lwip/iot_secure_sockets.c
- libraries/abstractions/secure_sockets/utest/secure_sockets_utest.c
Secure Socket changes to support socket bind API
Description
-----------
Add Secure Socket bind API to LWIP stack.
As per discussion with Amazon team on 10/2/2020, Amazon team has agreed for socket bind API support.
The original PR  https://github.com/aws/amazon-freertos/pull/2392 is closed, opening a new PR with the latest code from master branch
All the review comments are captured in PR https://github.com/aws/amazon-freertos/pull/2392
Checklist:
----------
> Add socket bind API to LWIP

- libraries/c_sdk/standard/common/include/logging_stack.h
Update `logging_stack.h` file to support filename extraction from `__FILE__` macro for Windows platform.
> Improve logging on Windows

- tests/unit_test/linux/config_files/FreeRTOSConfig.h
- tests/unit_test/linux/config_files/trcConfig.h
- tests/unit_test/linux/utils/wait_for_event.c
Add new trace definitions to unit tests configs
Description
-----------
Unit tests are failing to build after upgrading the new version of tracalayzer which uses new defines, adding those defines to the config files.
Checklist:
----------
> Test: Add new trace definitions to unit tests configs

- tests/integration_test/core_mqtt_system_test.c
Parallel MQTT integration jobs against the same broker interfere with each other because of using the same set of MQTT topics per job.
Add uniqueness in MQTT topics by prefixing the configurable client ID
> Use unique MQTT topics in integration tests

- demos/defender/aws_iot_demo_defender.c
The CI currently checks for the string "Metrics report was accepted by defender service." to note if the Defender demo passes.
This string is printed in the current Device Defender library and then passes the AWS_IOT_DEFENDER_METRICS_ACCEPTED event to the demo's registered callback.
The demo currently always returns EXIT_SUCCESS for the Defender library starting successfully, even if AWS IoT did not accept the metrics.
This change registers a boolean context to the callback to catch the AWS_IOT_DEFENDER_METRICS_ACCEPTED event.
With this change, the demo will return EXIT_FAILURE if the AWS_IOT_DEFENDER_METRICS_ACCEPTED event is not reached. 
Checklist:
----------
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms …
> Report the success of the defender metrics to the demo for CI.

- libraries/abstractions/ble_hal/test/ble_test_scipts/startTests_afqp.py
- libraries/abstractions/ble_hal/test/ble_test_scipts/testClass.py
- libraries/abstractions/ble_hal/test/src/iot_test_ble_hal_afqp.c
- libraries/abstractions/ble_hal/test/src/iot_test_ble_hal_common.c
- vendors/nordic/boards/nrf52840-dk/ports/ble/iot_ble_hal_common_gap.c
- vendors/nordic/boards/nrf52840-dk/ports/ble/iot_ble_hal_gatt_server.c
BLE AFQP test update
Description
-----------
1. Make Pairing request callback with Consent as optional requirement to pass qualification tests.
2. Fix the MTU callback handling in Nordic BLE port, to pass the qualification tests. 
Checklist:
----------
> BLE AFQP test update

- demos/mqtt/CMakeLists.txt
Remove metadata configuration of old MQTT demos in `demos/mqtt` to favor new MQTT demos in `demos/coreMQTT`
> Disable metadata configuration of old MQTT demos

- vendors/cypress/MTB/psoc6/common/FreeRTOS-openocd.c
- vendors/espressif/boards/esp32/CMakeLists.txt
- vendors/espressif/boards/esp32/components/freertos/CMakeLists.txt
Kernel update
Description
-----------    
Fix Espressif ESP32 build when targeting IDF v3.3. The new FreeRTOS kernel supports both Espressif's IDF v3.3 and v4.2. Due to this the cmake build must be updated to target v3.3, until Amazon FreeRTOS has updated to IDF v4.2.
Checklist:
----------
> Kernel update

- libraries/c_sdk/standard/mqtt/src/iot_mqtt_api.c
OTA e2e test fix for ESP32.
Description
-----------
OTA e2e test fix for ESP32.
Issue: The return of 0 from Network interface was an error. However, it was interpreted as a timeout in transport interface.
Fix: Handle Network interface failure in transport send.
Checklist:
----------
> OTA e2e test fix for ESP32

- libraries/c_sdk/standard/mqtt/CMakeLists.txt
Follow-up PR from #2554. It additionally removes metadata information of the old MQTT library (present in `libraries/c_sdk/standard/mqtt`) to favor the new MQTT library (present at `libraries/coreMQTT`)
> Remove metadata of old MQTT library

- libraries/CMakeLists.txt
- libraries/core_mqtt.cmake
Fix metadata module name generated by `AFR_METADATA_MODE` flag from `core_mqtt_module` to `core_mqtt`
With the file name as `core_mqtt_module.cmake`, the generated metadata is:
```
core_mqtt_module###ID:::core_mqtt
core_mqtt_module###DESCRIPTION:::This library implements the MQTT protocol that enables communication with AWS IoT. MQTT is an ISO standard publish-subscribe-based messaging protocol.
core_mqtt_module###DISPLAY_NAME:::Core MQTT
core_mqtt_module###CATEGORY:::Connectivity
core_mqtt_module###VERSION:::1.0.0
core_mqtt_module###IS_VISIBLE:::tru
```
With this PR's change (of renaming the file), the correctly generated metadata is:
```
core_mqtt###ID:::core_mqtt
core_mqtt###DESCRIPTION:::This library implements the MQTT protocol that enables communication with AWS IoT. MQTT is an ISO …
```
> Fix metadata configuration issue for coreMQTT

- demos/coreMQTT/mqtt_demo_keep_alive.c
- demos/coreMQTT/mqtt_demo_mutual_auth.c
- demos/coreMQTT/mqtt_demo_plaintext.c
- demos/coreMQTT/mqtt_demo_serializer.c
Cypress CYW943907AEVAL1F and CYW954907AEVAL1F do not have xPortGetFreeHeapSize() defined because it uses heap_3. 
Another reason to remove this statistic is because the demos in this repo already print out memory statistics for the platform, if supported, after the demo completes: https://github.com/aws/amazon-freertos/blob/master/demos/demo_runner/iot_demo_freertos.c#L323
Checklist:
----------
> CORE MQTT Demos: Some boards do not have xPortGetFreeHeapSize() available.

- vendors/cypress/boards/CY8CKIT_064S0S2_4343W/aws_tests/config_files/core_mqtt_config.h
- vendors/cypress/boards/CYW943907AEVAL1F/aws_tests/config_files/core_mqtt_config.h
- vendors/cypress/boards/CYW954907AEVAL1F/aws_tests/config_files/core_mqtt_config.h
- vendors/espressif/boards/esp32/aws_tests/config_files/core_mqtt_config.h
- vendors/infineon/boards/xmc4800_iotkit/aws_tests/config_files/core_mqtt_config.h
- vendors/infineon/boards/xmc4800_plus_optiga_trust_x/aws_tests/config_files/core_mqtt_config.h
- vendors/marvell/boards/mw300_rd/aws_tests/config_files/core_mqtt_config.h
- vendors/mediatek/boards/mt7697hx-dev-kit/aws_tests/config_files/core_mqtt_config.h
- vendors/microchip/boards/curiosity_pic32mzef/aws_tests/config_files/core_mqtt_config.h
- vendors/microchip/boards/ecc608a_plus_winsim/aws_tests/config_files/core_mqtt_config.h
- vendors/nordic/boards/nrf52840-dk/aws_tests/config_files/core_mqtt_config.h
- vendors/nuvoton/boards/numaker_iot_m487_wifi/aws_tests/config_files/core_mqtt_config.h
- vendors/nxp/boards/lpc54018iotmodule/aws_tests/config_files/core_mqtt_config.h
- vendors/pc/boards/windows/aws_tests/config_files/core_mqtt_config.h
- vendors/renesas/boards/rx65n-rsk/aws_tests/config_files/core_mqtt_config.h
- vendors/st/boards/stm32l475_discovery/aws_tests/config_files/core_mqtt_config.h
- vendors/ti/boards/cc3220_launchpad/aws_tests/config_files/core_mqtt_config.h
- vendors/vendor/boards/board/aws_tests/config_files/core_mqtt_config.h
- vendors/xilinx/boards/microzed/aws_tests/config_files/core_mqtt_config.h
Positives of this change:  
- Most of the MQTT unit tests perform errors cases and there are too many logs. This was causing the test FAIL and PASS logs to not print.
- With no library logging, the Unity PASS or FAIL for a test case will always print. The CI reads these logs to determine if a test was successful. 
Negatives of this change:  
- If a new change breaks the CSDK v4_beta IoT MQTT unit test, then developers will need to create a new branch with logging turned on. Then they will need to run a custom job in CI to see the failure.
Please see the infineon unit tests below:
```
18:05:59 Executing command: rm C:\i_m\xmc4800_plus_optiga_trust_x-8\amazon-freertos/flash.jlink
18:05:59 Flashing of the board finished.
18:05:59 
18:05:59 …
```
> Disable logging in the coreMQTT library for all aws_test projects.

- vendors/nuvoton/boards/numaker_iot_m487_wifi/aws_tests/application_code/main.c
- vendors/nuvoton/boards/numaker_iot_m487_wifi/aws_tests/config_files/iot_config.h
Fix MQTT and Shadow integration test failures on Nuvoton
Description
-----------
Fix MQTT and Shadow integration test failures on Nuvoton
Issues fixed.
1. Network receive task was having higher task priority than the test runner task. This was causing the ack packets for MQTT to be received before the data structure updates are completed after a successful sent from test runner task. By making sure the priority of the test runner task is higher than that of the Network receive task, this issue can be avoided.
2. Last will and testament test was failing due to a lack of memory. Network receive task and the taskpool task were using higher than required stack size for the tests and was causing the memory issues. Reduced it and verified the tests.
Checklist:
----------
By submitting this pull …
> Fix MQTT and Shadow integration test failures on Nuvoton

- libraries/CMakeLists.txt
- libraries/abstractions/retry_utils/CMakeLists.txt
- libraries/abstractions/transport/CMakeLists.txt
- libraries/core_mqtt.cmake
- libraries/logging/CMakeLists.txt
The FreeRTOS Device Software console requires that the CMake metadata provide header files path, so that they are included in the downloaded ZIP. Thus, update the `core_mqtt`, `logging`, `retry_utils` and `transport_interface_secure_sockets` CMake targets to include header files in their **source** list
> Update CMake configuration of new libraries

- vendors/nuvoton/boards/numaker_iot_m487_wifi/aws_demos/config_files/aws_demo_config.h
Nuvoton MQTT demo fix
Description
-----------
Nuvoton MQTT demo fix.
Issues fixed.
Network receive task was having higher task priority than the MQTT demo task. This was causing the ack packets for MQTT to be received before the data structure updates are completed after a successful sent from MQTT demo task. Increasing the priority of the MQTT demo task, this issue can be resolved.
Checklist:
----------
> Nuvoton MQTT demo fix

- libraries/c_sdk/standard/mqtt/test/unit/iot_tests_mqtt_api.c
This PR reduces the logs printed in the MQTT_Unit_API test.
The **KeepAlivePeriodic** test case starts a thread that simulates PINGRESPs. The test used multiple calls to `UnityPrint` function to print the status about every PINGRESP's sent. In this repo, UnityPrint is mapped to configPRINTF(), which serializes logs via logging queue. As a result, multiple `UnityPrint` calls added 11 messages to the logging queue increasing the chances of dropped messages because of the logging queue being full.
This change combines the multiple `UnityPrint` calls into one by first formatting the log message in a buffer.  The result is just one message added to the logging queue for every PINGRESP sent.
The logs below are from Cypress CY8CKIT_064S0S2_4343W but the change this applies to all boards. …
> Fix KeepAlivePeriodic testing logs printed in the MQTT_Unit_API test group

- libraries/abstractions/retry_utils/CMakeLists.txt
- libraries/abstractions/transport/CMakeLists.txt
Remove metadata of `retry_utils` and `transport_interface_secure_sockets` as they are not FreeRTOS console facing libraries
> Remove metadata of internal libraries

- demos/coreMQTT/mqtt_demo_basic_tls.c
- demos/coreMQTT/mqtt_demo_keep_alive.c
- demos/coreMQTT/mqtt_demo_mutual_auth.c
- demos/coreMQTT/mqtt_demo_plaintext.c
- demos/coreMQTT/mqtt_demo_serializer.c
Description
-----------
In most of the demos, `xFailedSubscribeToTopic` is not reset in each iteration of the `while` loop of the subscribe-retry flow. Therefore, if the initial subscribe fails, and a subsequent one succeeds, then the demo would enter an infinite loop as neither `xFailedSubscribeToTopic` nor `xRetryUtilsStatus` are being updated.
* Also fixed some format specifiers and a typo.
Checklist:
----------
> Fix demo bug allowing infinite subscribe loop

- libraries/c_sdk/standard/ble/CMakeLists.txt
- libraries/c_sdk/standard/ble/test/iot_mqtt_ble_system_test.c
- projects/cypress/CY8CKIT_064S0S2_4343W/mtb/aws_tests/afr.mk
- projects/nordic/nrf52840-dk/ses/aws_tests/aws_tests.emProject
- tests/common/aws_test_runner.c
Adds integration test for BLE transport interface for MQTT
Description
-----------
Adds integration test for BLE transport interface for MQTT.
Tested on BLE boards, Nordic NRF52, ESP32
Checklist:
----------
> Add integration test for BLE transport interface

- libraries/freertos_plus/standard/tls/src/iot_tls.c
Configure TLS extension max fragment length
Description
-----------
The TLS extension for max fragment length was statically enabled, but never configured at runtime. With this
patch, if the feature is enabled in mbed TLS, it is also configured at runtime.
Checklist:
----------
> Configure TLS max fragment length extension.

- vendors/infineon/boards/xmc4800_plus_optiga_trust_x/CMakeLists.txt
Cmake configuration (`cmake .. -DVENDOR=infineon -DBOARD=xmc4800_plus_optiga_trust_x  -DCOMPILER=arm-gcc`)
fails for the **Infineon Optiga Trust** board due to incorrect file name change made at `vendors/infineon/boards/xmc4800_plus_optiga_trust_x/CMakeLists.txt` for PKCS11 file in #2563
> Fix CMake build failure of Infineon Optiga Trust

- libraries/CMakeLists.txt
- libraries/abstractions/transport/transport_interface_secure_sockets.cmake
Fix missing `libraries/abstractions/transport/CMakeLists.txt` file by renaming it to `libraries/abstractions/transport/transport_interface_secure_sockets.cmake`
> Fix missing transport Cmake file in FreeRTOS console

- projects/nxp/lpc54018iotmodule/mcuxpresso/aws_tests/.project
Fix NXP test project.
Description
-----------
Core PKI utils was mistakenly placed inside of another item in the test project.
Checklist:
----------
> Fix NXP test project.

- demos/ble/CMakeLists.txt
- demos/cli/CMakeLists.txt
- demos/coreMQTT/CMakeLists.txt
- demos/device_shadow_for_aws_iot_embedded_sdk/CMakeLists.txt
- demos/shadow/CMakeLists.txt
- libraries/c_sdk/aws/shadow/CMakeLists.txt
- libraries/core_json.cmake
- libraries/core_mqtt_demo_dependencies.cmake
- libraries/freertos_plus/standard/freertos_plus_posix/CMakeLists.txt
- tests/integration_test/CMakeLists.txt
- vendors/espressif/boards/esp32/CMakeLists.txt
- vendors/marvell/boards/mw300_rd/CMakeLists.txt
Fixes for FreeRTOS console project download build failures, and improvements for FreeRTOS Console UI workflow.
Description
-----------
Changes include:
* Removal of metadata of old Shadow library and demo.
* Removal of metadata of CLI demo and core JSON library, which are not going to be shown on FreeRTOS console.
* Addition of header files in source list of Espressif and Marvell CMakeLists.txt for fixing missing files issue.
* Add conditional dependency on `AFR::wifi` of `AFR::core_mqtt_demo_dependencies` so that the WiFi library is _auto-included_ when the coreMQTT library is selected on FreeRTOS console.
* Add dependency on `AFR::core_mqtt_demo_dependencies` for MQTT over BLE demo so that the demo isn't shown when coreMQTT is not selected on FreeRTOS console.
By submitting this pull …
> Hygiene and fixes in CMake metadata for FreeRTOS console

- demos/device_shadow_for_aws_iot_embedded_sdk/CMakeLists.txt
- libraries/core_json.cmake
- tests/integration_test/CMakeLists.txt
Fix missing `core_json.cmake` file in FreeRTOS console download when Device Shadow library is selected
> Fix missing core_json.cmake file in FreeRTOS console

- demos/coreMQTT/mqtt_demo_serializer.c
- libraries/abstractions/platform/include/platform/transport_interface.h
- libraries/abstractions/transport/secure_sockets/transport_secure_sockets.c
- libraries/abstractions/transport/secure_sockets/transport_secure_sockets.h
- libraries/c_sdk/aws/shadow/test/unit/aws_iot_tests_shadow_api.c
- libraries/c_sdk/standard/ble/include/iot_ble_mqtt_transport.h
- libraries/c_sdk/standard/ble/src/services/mqtt_ble/iot_ble_mqtt_transport.c
- libraries/c_sdk/standard/mqtt/src/iot_mqtt_api.c
- libraries/c_sdk/standard/mqtt/test/mock/iot_tests_mqtt_mock.c
- libraries/c_sdk/standard/mqtt/test/unit/iot_tests_mqtt_api.c
- libraries/c_sdk/standard/mqtt/test/unit/iot_tests_mqtt_receive.c
- libraries/c_sdk/standard/mqtt/test/unit/iot_tests_mqtt_subscription.c
- tests/integration_test/core_mqtt_system_test.c
Description
-----------
This follows changes from [https://github.com/FreeRTOS/coreMQTT/pull/86](https://github.com/FreeRTOS/coreMQTT/pull/86) & [https://github.com/FreeRTOS/FreeRTOS/commit/398abbaa6199a12377a6254b197ab12f9788cc32](https://github.com/FreeRTOS/FreeRTOS/commit/398abbaa6199a12377a6254b197ab12f9788cc32). The const qualifier is removed from send/recv because there are transport implementations that require a member of the network context to be modified such as in the case of mbedtls.
Checklist:
----------
> Remove const qualifier from NetworkContext_t* in send/recv

- demos/coreMQTT/mqtt_demo_mutual_auth.c
- vendors/cypress/boards/CY8CKIT_064S0S2_4343W/aws_demos/config_files/mqtt_demo_keep_alive_config.h
- vendors/cypress/boards/CY8CKIT_064S0S2_4343W/aws_demos/config_files/mqtt_demo_mutual_auth_config.h
- vendors/cypress/boards/CYW943907AEVAL1F/aws_demos/config_files/mqtt_demo_mutual_auth_config.h
- vendors/cypress/boards/CYW954907AEVAL1F/aws_demos/config_files/mqtt_demo_mutual_auth_config.h
- vendors/espressif/boards/esp32/aws_demos/config_files/mqtt_demo_mutual_auth_config.h
- vendors/infineon/boards/xmc4800_iotkit/aws_demos/config_files/mqtt_demo_mutual_auth_config.h
- vendors/infineon/boards/xmc4800_plus_optiga_trust_x/aws_demos/config_files/mqtt_demo_mutual_auth_config.h
- vendors/marvell/boards/mw300_rd/aws_demos/config_files/mqtt_demo_mutual_auth_config.h
- vendors/mediatek/boards/mt7697hx-dev-kit/aws_demos/config_files/mqtt_demo_mutual_auth_config.h
- vendors/microchip/boards/curiosity_pic32mzef/aws_demos/config_files/mqtt_demo_mutual_auth_config.h
- vendors/microchip/boards/ecc608a_plus_winsim/aws_demos/config_files/mqtt_demo_mutual_auth_config.h
- vendors/nuvoton/boards/numaker_iot_m487_wifi/aws_demos/config_files/mqtt_demo_mutual_auth_config.h
- vendors/nxp/boards/lpc54018iotmodule/aws_demos/config_files/mqtt_demo_mutual_auth_config.h
- vendors/pc/boards/windows/aws_demos/config_files/mqtt_demo_mutual_auth_config.h
- vendors/renesas/boards/rx65n-rsk/aws_demos/config_files/mqtt_demo_mutual_auth_config.h
- vendors/st/boards/stm32l475_discovery/aws_demos/config_files/mqtt_demo_mutual_auth_config.h
- vendors/ti/boards/cc3220_launchpad/aws_demos/config_files/mqtt_demo_mutual_auth_config.h
- vendors/vendor/boards/board/aws_demos/config_files/mqtt_demo_mutual_auth_config.h
- vendors/xilinx/boards/microzed/aws_demos/config_files/mqtt_demo_mutual_auth_config.h
In this repo the client certificate and private key are configured in aws_clientcredential_keys.h only. We delete the unused democonfigCLIENT_CERTIFICATE_PEM and democonfigCLIENT_PRIVATE_KEY_PEM configurations from the mqtt_demo_mutual_auth_config.h files.
Checklist:
----------
> Delete unused configs in the MQTT mutual auth demo configs.

- demos/coreMQTT/mqtt_demo_serializer.c
Fix core MQTT serializer demo 
Description
-----------
Problem: core MQTT serializer demo was failing due to an incorrect shutdown of the secure socket.
Fix: Corrected the shutdown of the secure socket used in core MQTT serializer demo.
Test results : https://amazon-freertos-ci.corp.amazon.com/job/im_v2_master/job/nightly_custom_job/1318/
Checklist:
----------
> Fix core MQTT serializer demo 

- tools/cbmc/proofs/MakefileCommon.json
This pull request adds the new CBMC malloc flags to the list of cbmc command line arguments.
> Add malloc flags to CBMC proofs

- projects/cypress/CY8CKIT_064S0S2_4343W/mtb/aws_demos/afr.mk
- projects/cypress/CY8CKIT_064S0S2_4343W/mtb/aws_tests/afr.mk
Fix linker issue `undefined reference to RunDeviceShadowDemo` linker error in Cypress64 MTB build from FreeRTOS console download due to missing demo and library files in the project makefile. 
Also, update the `aws_tests` Makefile with the library and test files of Device Shadow
> Fix Device Shadow demo build on Cypress64 IDE

- demos/coreMQTT/mqtt_demo_mutual_auth.c
MQTT mutual auth demo fix
Description
-----------
MQTT mutual auth demo fix.
Problem: MQTTDisconnect() was getting called in an error path and resulting in internal errors.
Fix: Avoid calling MQTTDisconnect in error path.
Checklist:
----------
> MQTT mutual auth demo fix

- libraries/abstractions/platform/freertos/iot_metrics.c
Description
-----------
`iot_metrics.c` uses `IotMetrics_FreeTcpConnection` to free malloc'ed TCP connections, but `pvPortMalloc` to allocate them. This changes `pvPortMalloc` to `IotMetrics_MallocTcpConnection` so both malloc and free use the metrics specific macros
Checklist:
----------
> Change metrics malloc to metrics specific macro

- libraries/core_mqtt_demo_dependencies.cmake
Add dependency on `AFR::ble` for `AFR::core_mqtt_demo_dependencies` metadata module (relevant to FreeRTOS console) so that when MQTT library is selected on the FreeRTOS console, it auto-includes the BLE library on BLE capable boards.
This allows the **MQTT over BLE** demo to be displayed when MQTT is selected, and **Shadow over BLE** demo to be displayed when Device Shadow library is selected.
> Auto-include BLE for MQTT library for FreeRTOS console

- demos/https/iot_demo_https_s3_download_async.c
- demos/https/iot_demo_https_s3_download_sync.c
- demos/https/iot_demo_https_s3_upload_async.c
- demos/https/iot_demo_https_s3_upload_sync.c
The HTTP demos connecting to S3 contain connection congifuration logic with client certificate and private key. This is not required as the AWS S3 TLS connection does not require client certificate. The client authentication is performed through use of _pre-signed URLs_ in the demos instead.
> Remove unused client credentials configuration in HTTP demos

- vendors/marvell/boards/mw300_rd/aws_demos/application_code/main.c
- vendors/marvell/boards/mw300_rd/aws_demos/config_files/aws_demo_config.h
- vendors/marvell/boards/mw300_rd/aws_demos/config_files/iot_config.h
Fix demos on Marvell
Description
-----------
Problem: Many demos were failing in Marvell board due to lack of memory in heap while establishing a TLS connection.
Root Cause: Establishing a TLS connection requires a good amount of memory in the HEAP. The tasks created with xTaskCreate() function also allocates the memory for the stack in the heap. Marvell's heap(~73KB) was running out of space due to these allocations.
Fix: Optimized the stack sizes for different tasks for the demo and verified the demos.
The demo verification CI job can be found here
https://amazon-freertos-ci.corp.amazon.com/job/im_v2_master/job/nightly_custom_job/1312/
The stack high water mark are analyzed using the jobs
https://amazon-freertos-ci.corp.amazon.com/job/im_v2_master/job/nightly_custom_job/1356/ …
> Fix demos on Marvell

- demos/ble/shadow_ble/shadow_demo_ble_transport.c
- libraries/c_sdk/standard/ble/test/iot_mqtt_ble_system_test.c
Update timeout for BLE demos and tests.
PR is equivalent to  #2634
Description
-----------
The timeout values for BLE transport in MQTT demos were too short considering BLE connection interval for certain devices. Increased the timeout to adequate values.
Removed unused transport interface timeout parameter.
Checklist:
----------
> Update timeout for BLE demo and integration test

- projects/cypress/CY8CKIT_064S0S2_4343W/mtb/aws_tests/afr.mk
* Fixed the BLE_Unit_MQTT_Serialize MTB Build Failure.
* Remove the file path to a proper place in the afr.mk file.
* Move ble_mqtt_serialize under BLE supported section.
Description
-----------
Checklist:
----------
> Fixed the BLE_Unit_MQTT_Serialize MTB Build Failure. (#2630)

- tools/echo_server/config.json
- tools/echo_server/echo_server.go
- tools/echo_server/readme.md
Repeat mode and Secure mode cmdline args support for Echo Server
Description
-----------
- Added repeat mode cmdline args support: `-repeat` & `-interval`
- Added secure mode cmdline args support: `-cert` & `-key`
- Updated Readme.
Checklist:
----------
> Added repeat mode and secure mode cmdline args support
