aws/amazon-freertos

- tools/git/hooks/README.md
- tools/git/hooks/install_hooks.ps1
Description
-----------
Add a Windows installation script for git hooks.
Checklist:
----------
> chore: Add a installation script for git hooks

- demos/common/defender/aws_defender_demo.c
- lib/defender/aws_defender.c
- lib/defender/portable/freertos/aws_defender_uptime.c
Fix Device Defender library and demo compiler warnings plus code format compliance.
Description
-----------
git issue #82
Checklist:
----------
> fix/style: Device Defender library and demo compiler warnings plus code format compliance.

- CHANGELOG.md
Updating the change log for a Nov 19th release.
Checklist:
----------
> Update release date in CHANGELOG.md

- tools/checks/afqp/afqp_check/README.md
tools: Update afqp_check.py README.md for usage.
Description
-----------
The README.md for tools/checks/afqp/afqp_check/ is update for usage. 
This script checks AFQP compliance of a board's portable code within amazon-freertos.
Checklist:
----------
> tools: Update afqp_check.py README.md for usage.

- tests/common/ble/aws_test_ble.c
Fix for BLE AFQP tests
Description
-----------
Fixing a bug in BLE AFQP tests. If several events are received at the same time, some of them could be ignored.
The way the code was designed would also consume a lot of CPU ressource.
Checklist:
----------
> Fix: BLE AFQP tests

- lib/bluetooth_low_energy/aws_ble_gatt.c
- lib/bluetooth_low_energy/services/mqtt_ble/aws_iot_mqtt_ble.c
Coverity findings
Description
-----------
Fixing findings found by coverity
Checklist:
----------
> Fix:Coverity findings

- demos/nordic/nrf52840-dk/common/application_code/nordic_code/thumb_crt0.s
- demos/nordic/nrf52840-dk/ses/aws_demos_ble.emProject
Description
-----------
This change fixes the embedded studio project layout as per source layout on disk.
Checklist:
----------
> Nordic port - Fix Embedded Studio project layout 

- demos/nordic/nrf52840-dk/ses/aws_demos_ble.emProject
Description
-----------
Add missing config files in the config folder in Embedded Studio project.
Checklist:
----------
> Nordic Port - Add config files in Embedded Studio Project

- tests/common/ble/aws_test_ble.c
Fixing bug in test framework.
Description
-----------
CCCD are now correctly created
Checklist:
----------
> Fix: Test framework

- demos/nordic/nrf52840-dk/common/application_code/main.c
- lib/bluetooth_low_energy/portable/nordic/nrf52840-dk/aws_ble_hal_common_gap.c
- lib/third_party/mcu_vendor/nordic/nRF5_SDK_15.2.0/components/softdevice/common/nrf_sdh_freertos.c
Fix: Improving nordic board reliability
Description
-----------
Increase softdevice task size
Removing lesc task
Adding delete  bond if needed
Checklist:
----------
> Fix: Improving nordic board reliability

- lib/bluetooth_low_energy/portable/nordic/nrf52840-dk/aws_ble_hal_common_gap.c
Add Nordic PHY update event handling
Description
-----------
Phy update event handling was missing and this change adds that.
Checklist:
----------
> Fix - Nordic BLE port - Add PHY update event handling

- lib/FreeRTOS-Plus-POSIX/source/FreeRTOS_POSIX_pthread.c
- lib/include/FreeRTOS_POSIX/sys/types.h
Description
-----------
1. pthread_attr_t is changed to use stack type semantics
2. size of pthread_attr_internal_t is reduced by 8 bytes
Checklist:
----------
> Update pthread_attr_t and pthread_attr_internal_t

- tests/common/include/aws_clientcredential.h
- tests/common/include/aws_clientcredential_keys.h
Remove test credentials
Description
-----------
PR removes the test credentials which got checked in.
Checklist:
----------
> Remove test credentials

- lib/defender/aws_iot_defender.c
- lib/include/aws_iot_defender.h
- lib/include/private/aws_iot_defender_internal.h
Description
-----------
- add initial implementation for defender start/stop functions 
- use two timers (this might be a temporary approach. TBD)
- MQTT connect/disconnect
Checklist:
----------
- [NO] I have tested my changes. No regression in existing tests.
> add initial implementation of defender start/stop functions

- lib/defender/aws_iot_defender.c
- lib/include/aws_iot_defender.h
- lib/include/private/aws_iot_defender_internal.h
Description
-----------
- add user input for endpoint/port, tls information
- manage network connection
- create/destroy
- manage mqtt connection
- connect, subscribe, publish, disconnect
Smoke Test
-----------
I run a demo on dev (code not included in PR). It successfully connect/subscribe/publish in each timer expiration execution.
Checklist:
----------
> manage network and mqtt connections internally

- lib/defender/aws_iot_defender.c
- lib/include/aws_iot_defender.h
- lib/include/private/aws_iot_defender_internal.h
Description
-----------
- separate implementation source files, adding internal functions in internal header
- api functions
- mqtt/network management (not included in this PR)
- metrics collector (not included in this PR)
- specific metrics reporter (not included in this PR)
Checklist:
----------
> update implementation for defender's public APIs

- lib/defender/aws_iot_defender.c
- lib/defender/aws_iot_defender_mqtt.c
- lib/include/aws_iot_defender.h
Description
-----------
- implement mqtt operations used by defender
- resolve comments of last PR
- rename the metrics macro with long name
Checklist:
----------
> implement mqtt operations used by defender library

- lib/defender/aws_iot_defender_collector.c
Description
-----------
implement collecor which collects metrics and aggregate to single report
- "dryrun" to calculate the required size of report
- allocate buffer once
- redo the actual encoding 
Checklist:
----------
> implement collecor which collects metrics and aggregate to single report

- lib/defender/aws_iot_defender_collector.c
- lib/defender/portable/freertos/aws_iot_defender_metrics_socket.c
- lib/include/private/aws_iot_defender_metrics_socket.h
Description
-----------
- define socket metrics header
- add implementation of freertos tcp/ip
Checklist:
----------
> create socket metrics header and add implementation of freertos tcp/ip

- lib/mqtt/aws_iot_mqtt_serialize_ble.c
- tests/common/mqtt/unit/aws_iot_tests_mqtt_serialize_ble.c
- tests/common/test_runner/aws_test_runner.c
- tests/espressif/esp32_devkitc_esp_wrover_kit/make/.project
Modify ble serializer tests with new serializer interface code
Description
-----------
Modify serializer tests since length parsing has changed.
Also fix some minor bugs while running the tests.
Unit tests and demo is successful on ESP32.
Checklist:
----------
> Modify mqtt ble serializer tests

- lib/defender/aws_iot_defender.c
- lib/defender/aws_iot_defender_collector.c
- lib/include/aws_iot_defender.h
- lib/include/aws_iot_serializer.h
- lib/include/private/aws_iot_defender_internal.h
- lib/serializer/cbor/aws_iot_serializer_tinycbor_decoder.c
- lib/serializer/json/aws_iot_serializer_json_decoder.c
Description
-----------
- add logging to defender api
- pass metrics data to user's callback
- remove "print" function from decoder interface
Checklist:
----------
> add logging to defender api and pass metrics data to user's callback

- demos/common/defender/aws_iot_demo_defender.c
- demos/common/include/aws_defender_demo.h
- demos/common/include/aws_iot_config_common.h
- demos/pc/windows/common/config_files/aws_demo_config.h
- demos/pc/windows/common/config_files/aws_iot_config.h
- lib/defender/aws_iot_defender.c
Description
-----------
- add defender demo code
- fix minor bug of defender timer
Checklist:
----------
> create defender demo

- README.md
docs: Update README.md for now availible Renesas Getting Started AWS Docs link.
Checklist:
----------
- [n/a] I have tested my changes. No regression in existing tests.
> docs: Update README.md for now availible Renesas Getting Started AWS Docs link.

- lib/defender/aws_iot_defender.c
- lib/defender/aws_iot_defender_collector.c
- lib/defender/aws_iot_defender_mqtt.c
- lib/defender/aws_iot_defender_reporter_socket.c
- lib/include/aws_iot_defender.h
- lib/include/private/aws_iot_defender_internal.h
Description
-----------
- add Doxygen comments
- structure metrics flag and mutex
Checklist:
----------
> add Doxygen comments; attempt to connect in start function

- demos/espressif/esp32_devkitc_esp_wrover_kit/common/application_code/espressif_code/amazon-freertos-common/component.mk
- demos/espressif/esp32_devkitc_esp_wrover_kit/common/application_code/main.c
- demos/espressif/esp32_devkitc_esp_wrover_kit/common/config_files/aws_demo_config.h
OTA over BLE: Minor fixes
Description
-----------
Increase stack size in main
Remove old ota update
Checklist:
----------
> Fix: OTA over BLE

- lib/defender/aws_iot_defender_collector.c
- lib/defender/aws_iot_defender_reporter_socket.c
- lib/include/platform/aws_iot_static_memory.h
- lib/include/private/aws_iot_defender_internal.h
Description
-----------
define portable malloc and free for defender library
Checklist:
----------
TODO:
----------
- add document for static allocation interfaces
- implementation for static allocation interfaces
> define portable malloc and free for defender library

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
Description
-----------
Standard issue templates help debug the issue efficiently. 
Checklist:
----------
> Issue template files for new incoming issues.

- demos/espressif/esp32_devkitc_esp_wrover_kit/common/application_code/espressif_code/amazon-freertos-common/component.mk
- demos/ti/cc3220_launchpad/ccs/.project
- lib/FreeRTOS-Plus-POSIX/include/FreeRTOS_POSIX_internal.h
- lib/FreeRTOS-Plus-POSIX/include/FreeRTOS_POSIX_types.h
- lib/FreeRTOS-Plus-POSIX/include/portable/FreeRTOS_POSIX_portable_default.h
- lib/FreeRTOS-Plus-POSIX/source/FreeRTOS_POSIX_pthread_barrier.c
- lib/FreeRTOS-Plus-POSIX/source/FreeRTOS_POSIX_pthread_cond.c
- lib/FreeRTOS-Plus-POSIX/source/FreeRTOS_POSIX_pthread_mutex.c
- lib/FreeRTOS-Plus-POSIX/source/FreeRTOS_POSIX_semaphore.c
- lib/include/FreeRTOS_POSIX/pthread.h
- lib/include/FreeRTOS_POSIX/semaphore.h
- lib/include/FreeRTOS_POSIX/sys/types.h
- lib/third_party/mcu_vendor/espressif/esp-idf/components/pthread/include/esp_pthread.h
- tests/common/posix/aws_test_posix_pthread.c
- tests/common/posix/aws_test_posix_semaphore.c
- tests/common/posix/aws_test_posix_timer.c
- tests/espressif/esp32_devkitc_esp_wrover_kit/common/application_code/espressif_code/amazon-freertos-tests/component.mk
changed posix types to use stack based allocation instead of dynamic
* changed pthread_mutex_t pthread_cond_t pthread_barrier_t sem_t
Description
-----------
Checklist:
----------
> refactor: posix types

- lib/include/FreeRTOS_POSIX/pthread.h
- lib/third_party/mcu_vendor/espressif/esp-idf/components/pthread/include/esp_pthread.h
esp_pthread.h is third party file and should not be modified.
Description
-----------
Checklist:
----------
> fix: undoing modification to esp specific file.

- lib/FreeRTOS-Plus-POSIX/source/FreeRTOS_POSIX_timer.c
* Posix timer need not spawn thread everytime it is invoked,
* instead a callback function is directlly called.
Description
-----------
Checklist:
----------
> fix: stop posix timer from spawning thread.

- lib/include/aws_iot_serializer.h
- lib/serializer/cbor/aws_iot_serializer_tinycbor_decoder.c
- lib/serializer/cbor/aws_iot_serializer_tinycbor_encoder.c
- lib/serializer/json/aws_iot_serializer_json_decoder.c
- tests/pc/windows/visual_studio/aws_tests.vcxproj.filters
Description
-----------
clean cbor serializer code
Checklist:
----------
> clean cbor serializer code

- lib/include/iot_linear_containers.h
Description
-----------
Add files which implement "linear containers" queues and lists.
Checklist:
----------
> Add linear containers header file

- demos/espressif/esp32_devkitc_esp_wrover_kit/common/application_code/espressif_code/amazon-freertos-common/component.mk
- lib/secure_sockets/aws_secure_sockets_wrapper_metrics.c
- lib/serializer/json/aws_iot_serializer_json_encoder.c
- tests/espressif/esp32_devkitc_esp_wrover_kit/common/application_code/espressif_code/amazon-freertos-tests/component.mk
Description
-----------
- Fix espressif mk file
- fix json encoder destory
Checklist:
----------
> Fix espressif mk file; fix json encoder destory

- demos/nordic/nrf52840-dk/bootloader/bootloader.h
- demos/nordic/nrf52840-dk/bootloader/crypto.c
- demos/nordic/nrf52840-dk/bootloader/main.c
- demos/nordic/nrf52840-dk/bootloader/pca10056/ses/bootloader_mbr_pca10056.emProject
- demos/nordic/nrf52840-dk/bootloader/utils.c
- lib/ota/portable/nordic/nrf52840-dk/aws_ota_pal.c
- lib/ota/portable/nordic/nrf52840-dk/aws_ota_pal_settings.h
Changing the bootloader to support firmware rollback
Description
-----------
We have imlemented the bootloader that supports firmware swapping. We have tested for OTA procedure, image reverting and power loss during swapping.
Checklist:
----------
> Feature/ble beta (Nordic bootloader with firmware swapping)

- demos/nordic/nrf52840-dk/bootloader/crypto.c
- lib/ota/portable/nordic/nrf52840-dk/aws_ota_pal.c
Description
-----------
This is a port of bugfix for PAL layer for bootloader
Checklist:
----------
> Bugfix for Nordic bootloader

- tools/ota_e2e_tests/board.json
* Update the list of supported tests to be the complete set.
* Update the comments on the tool_paths and build_config commands to be up to date.
Checklist:
----------
> docs: Update the OTA_E2E board.json for the current signer platformId.

- demos/common/network_manager/aws_iot_demo_network.c
- lib/utils/platform/aws_iot_network_afr.c
Fix Network Manager and MQTT Network log level
Description
-----------
1. Fix rename MQTT Network log level
2. Remove static connection object from Network manager
Checklist:
----------
> Network manager and mqtt network log level fix

- tests/common/serializer/aws_test_serializer_json.c
Description
-----------
add json encoder tests
Checklist:
----------
> add json encoder tests

- demos/common/include/aws_iot_config_common.h
- demos/espressif/esp32_devkitc_esp_wrover_kit/common/application_code/espressif_code/amazon-freertos-common/component.mk
- demos/espressif/esp32_devkitc_esp_wrover_kit/make/.project
- lib/include/aws_iot_taskpool.h
- lib/include/aws_iot_taskpool_types.h
- lib/include/private/aws_iot_taskpool_internal.h
- lib/mqtt/aws_iot_mqtt_api.c
- lib/mqtt/aws_iot_mqtt_operation.c
- lib/ota/aws_iot_ota_agent.c
- lib/utils/aws_system_init.c
- lib/utils/taskpool/aws_iot_taskpool.c
Enabling task pool feature for the new MQTT library
Description
-----------
Enabling task pool feature for the new MQTT library
Checklist:
----------
> Using taskpool for MQTT library

- demos/common/defender/aws_iot_demo_defender.c
- demos/common/include/aws_iot_config_common.h
- lib/defender/aws_iot_defender_collector.c
- tests/common/defender/aws_iot_tests_defender_api.c
Description
-----------
- add tests/demo for multiple socket connections: it relies on echo server.
- fix bug in defender collector when copying metrics data
- get IoT ip address in tests for verification
- refactor tests verification
Checklist:
----------
> add tests/demo for multiple socket connections

- demos/common/ble/aws_ble_gatt_server_demo.c
- demos/common/include/aws_ble_gatt_server_demo.h
- demos/common/network_manager/aws_iot_network_manager.c
- demos/espressif/esp32_devkitc_esp_wrover_kit/make/.project
- demos/nordic/nrf52840-dk/ses/aws_demos_ble.emProject
- lib/bluetooth_low_energy/aws_ble_gap.c
- lib/bluetooth_low_energy/aws_ble_gatt.c
- lib/bluetooth_low_energy/portable/espressif/aws_ble_hal_gatt_server.c
- lib/bluetooth_low_energy/portable/nordic/nrf52840-dk/aws_ble_hal_gatt_server.c
- lib/bluetooth_low_energy/services/device_information/aws_ble_device_information.c
- lib/bluetooth_low_energy/services/mqtt_ble/aws_iot_mqtt_ble.c
- lib/bluetooth_low_energy/services/wifi_provisioning/aws_ble_wifi_provisioning.c
- lib/include/aws_ble.h
- lib/include/aws_ble_device_information.h
- lib/include/aws_ble_wifi_provisioning.h
- lib/include/aws_iot_mqtt_ble.h
- lib/include/bluetooth_low_energy/bt_hal_gatt_server.h
- lib/include/bluetooth_low_energy/bt_hal_gatt_types.h
- lib/include/iot_linear_containers.h
- lib/include/private/aws_ble_config_defaults.h
- lib/include/private/aws_ble_internals.h
- lib/ota/aws_iot_ota_agent.c
Removing malloc from middleware.
Description
-----------
Removing malloc from middleware.
Changed API so the services can be allocated in ROM
Checklist:
----------
> Removing malloc from middleware.

- demos/common/ble/aws_ble_gatt_server_demo.c
- demos/nordic/nrf52840-dk/common/config_files/aws_ble_config.h
- demos/nordic/nrf52840-dk/ses/aws_demos_ble.emProject
- lib/bluetooth_low_energy/aws_ble_gatt.c
- lib/bluetooth_low_energy/services/device_information/aws_ble_device_information.c
- lib/bluetooth_low_energy/services/mqtt_ble/aws_iot_mqtt_ble.c
- lib/bluetooth_low_energy/services/wifi_provisioning/aws_ble_wifi_provisioning.c
- lib/include/aws_ble.h
- lib/include/aws_ble_device_information.h
- lib/include/aws_ble_wifi_provisioning.h
- lib/include/aws_iot_mqtt_ble.h
- lib/include/bluetooth_low_energy/bt_hal_gatt_server.h
- lib/include/bluetooth_low_energy/bt_hal_gatt_types.h
- lib/include/private/aws_ble_internals.h
- tests/nordic/nrf52840-dk/ses/aws_tests.emProject
Changed naming from HAL
Description
-----------
Changed naming from HAL
Checklist:
----------
> Fix/ble hal Naming

- lib/ota/portable/nordic/nrf52840-dk/aws_ota_pal.c
- tests/common/ble/aws_test_ble.c
- tests/common/ota/aws_test_ota_pal.c
- tests/nordic/nrf52840-dk/common/application_code/main.c
nordic tests
Description
-----------
Fixing nordic ble and ota pal tests
Checklist:
----------
> Fixing test on Nordic

- demos/common/combined/aws_iot_combined_demo.c
- demos/common/demo_runner/aws_demo_runner.c
- demos/espressif/esp32_devkitc_esp_wrover_kit/common/application_code/espressif_code/amazon-freertos-common/component.mk
- demos/espressif/esp32_devkitc_esp_wrover_kit/common/application_code/main.c
- demos/espressif/esp32_devkitc_esp_wrover_kit/common/config_files/aws_demo_config.h
<Combined Demo of MQTT and OTA >
Description
-----------
<Combined Demo of MQTT and OTA that uses Network Manager and BLE provisioning of WiFi>
Checklist:
----------
> Combined Demo integration

- lib/mqtt/aws_mqtt_agent.c
Related Issues: https://github.com/aws/amazon-freertos/issues/277
Checklist:
----------
> Why: MQTT Agent attempts to connect when secure sockets returns an invalid socket

- lib/include/aws_iot_serializer.h
- lib/serializer/cbor/aws_iot_serializer_tinycbor_decoder.c
- lib/serializer/cbor/aws_iot_serializer_tinycbor_encoder.c
- tests/common/include/aws_iot_config_common.h
- tests/common/serializer/aws_test_serializer_cbor.c
Description
-----------
fix serializer code and tests by removing FreeRTOS specific code
- remove FreeRTOS's malloc and free
- remove including FreeRTOS's headers
Checklist:
----------
> fix serializer code and tests by removing FreeRTOS specific code

- tests/common/tls/aws_test_tls.c
* Add function prvExpectFailAfterDataSentWithProvisioning() for AWS IoT Core changes.
* Update AFQP_TLS_ConnectUntrustedCert and AFQP_TLS_ConnectMalformedCert tests for the changes.
A separate function for this case is added to isolate the logic to only the two tests updated, to preserve other tests current behavior, and avoid possible breakage.
Checklist:
----------
> fix: Update some TLS tests for changes in AWS IoT Core.

- tools/aws_config_quick_start/misc.py
Related Issues: https://github.com/aws/amazon-freertos/issues/299
Checklist:
----------
> Why:Change Startup script to generate ATS Endpoint by default.

- demos/common/network_manager/aws_iot_network_manager.c
Fix so name length is not limited to 5 characters anymore
Description
-----------
Fix so name length is not limited to 5 characters anymore
Checklist:
----------
> Fix to increase name length

- demos/common/network_manager/aws_iot_network_manager.c
- lib/bluetooth_low_energy/iot_ble_gap.c
- lib/bluetooth_low_energy/iot_ble_gatt.c
- lib/bluetooth_low_energy/services/mqtt_ble/aws_iot_mqtt_ble.c
- lib/include/iot_ble.h
- lib/include/private/iot_ble_internal.h
Fix BLE connection disconnection stuck in a deadlock
Description
-----------
Fix BLE connection disconnection stuck in a deadlock
Checklist:
----------
> Fix BLE connection disconnection stuck in a deadlock

- lib/third_party/mcu_vendor/espressif/esp-idf/components/driver/uart.c
[fix] Interrupt-unsafe calls in espressif uart isr
Description
-----------
The default isr uses interrupt-unsafe masking operations. Attempting to install it causes asserts to fail if the relevant events are ever received. 
Checklist:
----------
> Fix interrupt-unsafe calls in espressif uart isr

- demos/common/network_manager/aws_iot_network_manager.c
- lib/bluetooth_low_energy/aws_ble_gatt.c
Update BLE beta demo
Description
-----------
Update BLE beta demo
Checklist:
----------
> Updating: BLE beta demos

- tools/ota_e2e_tests/poetry.lock
- tools/ota_e2e_tests/pyproject.toml
To facilitate better portability to other machines we have added Poetry files to the OTA E2E test scripts.
Checklist:
----------
> Add python package dependency manager files to OTA E2E tests scripts.

- tools/ota_e2e_tests/aws_ota_test/aws_ota_test_case_unsigned_image.py
If the "codeSigning" field is specified at all, other fields within are expected.
Checklist:
----------
> Fix OtaTestUnsignedImage test case for change in the AWS IoT OTA API.

- lib/greengrass/aws_greengrass_discovery.c
Don't assume that the Thing name define is a string literal, per #219. 
Checklist:
----------
> Don't assume that the Thing name #define is a string literal.

- demos/espressif/esp32_devkitc_esp_wrover_kit/common/application_code/espressif_code/freertos/Kconfig
- demos/espressif/esp32_devkitc_esp_wrover_kit/common/config_files/FreeRTOSConfig.h
- lib/FreeRTOS/portable/ThirdParty/GCC/Xtensa_ESP32/include/portmacro.h
- lib/third_party/mcu_vendor/espressif/esp-idf/components/driver/rtc_module.c
- lib/third_party/mcu_vendor/espressif/esp-idf/components/esp32/pm_esp32.c
- lib/third_party/mcu_vendor/espressif/esp-idf/components/esp32/pm_locks.c
- tests/espressif/esp32_devkitc_esp_wrover_kit/common/application_code/espressif_code/freertos/Kconfig
- tests/espressif/esp32_devkitc_esp_wrover_kit/common/config_files/FreeRTOSConfig.h
Description
-----------
Merge fix for the following issue from Espressif: aws/amazon-freertos#345
Checklist:
----------
> esp32: support for power management framework

- demos/common/combined/aws_iot_combined_demo.c
Added retry logic for MQTT connection. When performing JITP, the peer connection gets dropped. This logic allows the device to connect without a reboot.
Checklist:
----------
> MQTT Initial connection retry logic

- lib/mqtt/iot_mqtt_api.c
- lib/utils/platform/iot_network_afr.c
- tests/common/include/iot_config_common.h
- tests/common/mqtt/system/iot_tests_mqtt_system.c
- tests/common/mqtt/unit/iot_tests_mqtt_api.c
- tests/common/mqtt/unit/iot_tests_mqtt_receive.c
- tests/common/mqtt/unit/iot_tests_mqtt_subscription.c
- tests/common/mqtt/unit/iot_tests_mqtt_validate.c
Description
-----------
Fixes the MQTT system tests on ESP, Last Will and Testament excepted.
Checklist:
----------
> Fix the MQTT system tests on ESP.

- demos/espressif/esp32_devkitc_esp_wrover_kit/common/config_files/iot_demo_config.h
- lib/mqtt/aws_mqtt_agent.c
- tests/espressif/esp32_devkitc_esp_wrover_kit/common/config_files/aws_test_runner_config.h
- tests/espressif/esp32_devkitc_esp_wrover_kit/common/config_files/iot_test_config.h
Description
-----------
Adjust parameters formerly set in common config for ESP.
Checklist:
----------
> Adjust default thread params on ESP.

- demos/common/include/iot_config_common.h
Match task priorities to test config file and update comments
Checklist:
----------
- [] My code is Linted.
> Update config file

- tests/common/ota/aws_test_ota_agent.c
Description
-----------
Change OTA agent tests to use MQTT v4 and test against new OTA agent.
Checklist:
----------
> Change OTA agent tests to use MQTT v4.

- demos/nordic/nrf52840-dk/common/config_files/aws_demo_config.h
- demos/nordic/nrf52840-dk/ses/aws_demos.emProject
- tests/nordic/nrf52840-dk/common/config_files/aws_test_runner_config.h
- tests/nordic/nrf52840-dk/common/config_files/iot_test_config.h
- tests/nordic/nrf52840-dk/ses/aws_tests.emProject
Adjust default thread params on Nordic.
Description
-----------
Adjust default thread params on Nordic.
Checklist:
----------
> Adjust default thread params on Nordic.

- lib/include/platform/iot_platform_types_afr.h
- lib/utils/platform/iot_clock_afr.c
- lib/utils/platform/iot_threads_afr.c
- tests/common/utils/platform/iot_test_platform_threads.c
Change internal type for recursive mutex to be BaseType_t instead of bool
Also removed the StackSize test for threads_afr 
Checklist:
----------
> Change internal type for recursive mutex 

- tests/common/mqtt/unit/iot_tests_mqtt_receive.c
Description
-----------
Fixes a unit test with new abstraction layer.
Checklist:
----------
> Don't create receive count semaphore is expecting 0.

- demos/common/include/iot_config_common.h
- demos/espressif/esp32_devkitc_esp_wrover_kit/common/application_code/espressif_code/amazon-freertos-common/component.mk
- lib/mqtt/aws_mqtt_agent.c
- lib/ota/aws_iot_ota_agent.c
- lib/utils/platform/iot_network_afr.c
- lib/utils/platform/iot_threads_afr.c
- tests/common/include/iot_config_common.h
- tests/common/mqtt/unit/iot_tests_mqtt_subscription.c
Description
-----------
Delete POSIX header config and reimplements a test that used those.
Checklist:
----------
> Remove POSIX from SDK common config

- demos/common/defender/aws_iot_demo_defender.c
- demos/common/include/iot_config_common.h
- demos/pc/windows/visual_studio/aws_demos.vcxproj
- demos/pc/windows/visual_studio/aws_demos.vcxproj.filters
- lib/defender/aws_iot_defender_api.c
- lib/defender/aws_iot_defender_collector.c
- lib/include/aws_iot_defender.h
- lib/include/platform/iot_metrics.h
- lib/metrics/iot_metrics.c
- lib/secure_sockets/aws_secure_sockets_wrapper_metrics.c
- tests/common/include/iot_config_common.h
Description
-----------
- fix metrics library
- fix defender demo
Checklist:
----------
> fix metrics library and defender demo

- tests/common/test_runner/iot_tests_network.c
Description
-----------
Checklist:
----------
> Fixing compile error in VS

- lib/utils/platform/iot_network_afr.c
Description
-----------
Check for errors from gethostbyname() in platform network abstraction.
Checklist:
----------
> Check for DNS lookup failure in platform network

- lib/defender/aws_iot_defender_v1.c
- lib/include/private/aws_secure_sockets_wrapper_metrics.h
- tests/common/defender/aws_iot_tests_defender_api.c
- tests/pc/windows/visual_studio/aws_tests.vcxproj
- tests/pc/windows/visual_studio/aws_tests.vcxproj.filters
Description
-----------
- fix defender tests
- add defender_v1 tests back
Checklist:
----------
> fix defender tests

- demos/common/demo_runner/aws_demo_runner.c
- demos/common/demo_runner/iot_demo_afr.c
- demos/nordic/nrf52840-dk/common/application_code/main.c
- lib/shadow/aws_iot_shadow_api.c
- lib/utils/aws_system_init.c
- tests/common/defender/aws_iot_tests_defender_api.c
- tests/common/defender/aws_iot_tests_defender_api_v1.c
- tests/common/greengrass/aws_test_greengrass_discovery.c
- tests/common/greengrass/aws_test_helper_secure_connect.c
- tests/common/mqtt/aws_test_mqtt_agent.c
- tests/common/mqtt/unit/iot_tests_mqtt_subscription.c
- tests/common/ota/aws_test_ota_agent.c
- tests/common/shadow/aws_test_shadow.c
- tests/common/test_runner/aws_test_runner.c
Description
-----------
Checklist:
----------
> Remove MQTT and common init from system init

- lib/common/static_memory/iot_static_memory_metrics.c
- lib/include/iot_serializer.h
- lib/include/platform/iot_metrics.h
- lib/include/private/iot_static_memory.h
- lib/metrics/iot_metrics.c
- tests/pc/windows/visual_studio/aws_tests.vcxproj
- tests/pc/windows/visual_studio/aws_tests.vcxproj.filters
Description
-----------
- fix static memory allocation for defender
Checklist:
----------
> fix defender with static memory

- tests/pc/windows/visual_studio/aws_tests.vcxproj
- tests/pc/windows/visual_studio/aws_tests.vcxproj.filters
removing deleted defender file from project. 
Description
-----------
N/A
Checklist:
----------
> removing deleted defender file from project. 

- lib/secure_sockets/aws_secure_sockets_wrapper_metrics.c
- tests/common/defender/aws_iot_tests_defender_api.c
Description
-----------
- update defender test to use echo server in EC2
Checklist:
----------
> update echo server in defender test

- lib/FreeRTOS-Plus-POSIX/include/portable/FreeRTOS_POSIX_portable_default.h
- lib/FreeRTOS-Plus-POSIX/source/FreeRTOS_POSIX_clock.c
- lib/include/FreeRTOS_POSIX/time.h
- tests/common/posix/aws_test_posix_clock.c
Description
-----------
Remove functions used in previous POSIX platform layer.
Checklist:
----------
> Remove stubs used by former platform layer

- lib/common/static_memory/iot_static_memory_metrics.c
- lib/defender/aws_iot_defender_api.c
- lib/include/aws_iot_defender.h
- lib/include/private/iot_static_memory.h
- lib/serializer/cbor/iot_serializer_tinycbor_decoder.c
Description
-----------
Checklist:
----------
> revert changes that were accidentally removed during syncing with C-SDK

- demos/common/network_manager/aws_iot_network_manager.c
Changes in network manager
Description
-----------
This PR contains changes to simplify network manager code.
* Use recyclable task pool job and avoid static job cache within NM
* pending invocations to serialize network events.
* Use mutex, linear containers
* Variable and function name changes according to new coding conventions.
Checklist:
----------
> Changes in network manager

- lib/include/bluetooth_low_energy/bt_hal_avsrc_profile.h
- lib/include/bluetooth_low_energy/bt_hal_gatt_client.h
- lib/include/bluetooth_low_energy/bt_hal_gatt_server.h
- lib/include/bluetooth_low_energy/bt_hal_gatt_types.h
- lib/include/bluetooth_low_energy/bt_hal_manager.h
- lib/include/bluetooth_low_energy/bt_hal_manager_adapter_ble.h
- lib/include/bluetooth_low_energy/bt_hal_manager_adapter_classic.h
- lib/include/bluetooth_low_energy/bt_hal_manager_types.h
New BLE API
Description
-----------
New BLE API
Checklist:
----------
> New BLE API

- cmake/vendors/ti/cc3220_launchpad/CMakeLists.txt
- lib/ota/CMakeLists.txt
Description
-----------
Checklist:
----------
> Fix CMake build on TI

- demos/pc/windows/visual_studio/aws_demos.vcxproj
- demos/pc/windows/visual_studio/aws_demos.vcxproj.filters
- tests/pc/windows/visual_studio/aws_tests.vcxproj
- tests/pc/windows/visual_studio/aws_tests.vcxproj.filters
Description
-----------
Checklist:
----------
> Move socket metrics in VS project

- tests/espressif/esp32_devkitc_esp_wrover_kit/common/config_files/aws_test_runner_config.h
- tests/nordic/nrf52840-dk/common/config_files/aws_test_runner_config.h
Fixing OTA end to end tests
Description
-----------
Fixing OTA end to end tests
Checklist:
----------
> Fixing OTA end to end

- tests/espressif/esp32_devkitc_esp_wrover_kit/common/application_code/espressif_code/amazon-freertos-tests/component.mk
- tests/espressif/esp32_devkitc_esp_wrover_kit/common/config_files/iot_test_config.h
2. Adding warnings on MQTT to catch issue on OTA
1. fixing tcp tests on ESP
Description
-----------
Checklist:
----------
> Fix TCP and OTA

- lib/mqtt/iot_ble_mqtt_serialize.c
- tests/common/mqtt/unit/aws_iot_tests_mqtt_serialize_ble.c
Fixing mqtt serializer tests as per the new mqtt packet structure
Description
-----------
* Fix failing tests as part of mqtt packet structure changes
* Correct off indentations
Checklist:
----------
> Fixing mqtt serializer tests

- tests/common/test_runner/aws_test.c
- tests/common/test_runner/iot_test_afr.c
- tests/nordic/nrf52840-dk/ses/aws_tests.emProject
Updated the Nordic Test project to match demo changes
Checklist:
----------
> Updated Nordic Tests

- tools/ota_e2e_tests/aws_ota_test/aws_ota_aws_agent.py
Fix OTA end to end
Description
-----------
The versioning enabling should happen when we create a bucket.
It was happening for every initialization previously and causing a potentional
for conflicting operations.
Checklist:
----------
> Fix OTA end to end

- lib/bluetooth_low_energy/portable/nordic/nrf52840-dk/aws_ble_hal_gatt_server.c
Fixing nordic error Status
Description
-----------
Fixing nordic error Status
Checklist:
----------
> Fixing nordic error Status

- lib/bluetooth_low_energy/iot_ble_gap.c
fix error messages
Description
-----------
fix error messages
Checklist:
----------
> fix error messages

- demos/demo_runner/iot_demo_afr.c
- demos/ota/aws_iot_ota_update_demo.c
- doc/lib/ble.txt
- modules/libraries/aws/ota/test/aws_test_ota_end_to_end.c
- modules/ports/ble/include/iot_ble_config_defaults.h
- modules/ports/ble/include/iot_ble_wifi_provisioning.h
- modules/ports/ble/services/wifi_provisioning/iot_ble_wifi_provisioning.c
- modules/ports/ble/test/aws_test_wifi_provisioning.c
- modules/ports/ble/test/iot_ble_wifi_prov_test_access_define.h
- vendors/espressif/boards/esp32/ports/wifi/aws_wifi.c
- vendors/nordic/boards/nrf52840-dk/ports/ble/aws_ble_hal_gatt_server.c
merge from ble beta
Description
-----------
merge from ble beta
Checklist:
----------
> merge from ble beta

- modules/libraries/standard/common/platform/iot_network_afr.c
- modules/libraries/standard/mqtt/test/system/iot_tests_mqtt_system.c
Description
-----------
Checklist:
----------
> Temporary fix for MQTT system test

- demos/defender/aws_iot_demo_defender.c
- demos/demo_runner/iot_demo_afr.c
- demos/demo_runner/iot_demo_runner.c
- demos/include/aws_clientcredential.h
- demos/include/aws_clientcredential_keys.h
- demos/include/aws_demo.h
- demos/include/iot_config_common.h
- demos/mqtt/aws_hello_world.c
- demos/mqtt/aws_mqtt_ble_hello_world.c
- demos/mqtt/iot_demo_mqtt.c
- demos/network_manager/aws_iot_network_manager.c
- demos/ota/aws_iot_ota_update_demo.c
- demos/shadow/aws_iot_demo_shadow.c
- demos/shadow/aws_shadow_lightbulb_on_off.c
- vendors/espressif/boards/esp32/aws_demos/common/config_files/aws_demo_config.h
- vendors/espressif/boards/esp32/aws_demos/common/config_files/iot_ble_config.h
- vendors/espressif/boards/esp32/aws_demos/common/config_files/iot_demo_config.h
- vendors/nordic/boards/nrf52840-dk/aws_demos/common/config_files/aws_demo_config.h
- vendors/nordic/boards/nrf52840-dk/aws_demos/common/config_files/iot_demo_config.h
- vendors/pc/boards/windows/aws_demos/common/config_files/aws_demo_config.h
- vendors/ti/boards/cc3220_launchpad/aws_demos/common/config_files/aws_demo_config.h
Merge PR#358 from ble-beta 
Description
-----------
Merge PR#358 from ble-beta 
Changes
---------
-     Have network type demo configuration, which can be overriden per demo
-     Initialize Mqtt library from within demos instead of demo runner.
-     Refactor and add logging in demo runner.
-     Add serializer overrides for the demo.
Checklist:
----------
>  Merge PR#358 from ble-beta 

- modules/libraries/standard/common/include/platform/iot_network.h
- modules/libraries/standard/common/platform/iot_network_afr.c
- modules/libraries/standard/mqtt/src/iot_mqtt_api.c
- modules/libraries/standard/mqtt/src/iot_mqtt_network.c
- modules/libraries/standard/mqtt/src/iot_mqtt_operation.c
- modules/libraries/standard/mqtt/src/iot_mqtt_subscription.c
- modules/libraries/standard/mqtt/src/private/iot_mqtt_internal.h
- modules/libraries/standard/mqtt/test/system/iot_tests_mqtt_system.c
- vendors/pc/boards/windows/aws_tests/visual_studio/aws_tests.vcxproj.filters
Description
-----------
Checklist:
----------
> Sync with latest C SDK (67a2965)

- vendors/nxp/boards/lpc54018iotmodule/CMakeLists.txt
- vendors/nxp/boards/lpc54018iotmodule/aws_demos/common/config_files/aws_demo_config.h
- vendors/nxp/boards/lpc54018iotmodule/aws_tests/common/application_code/main.c
- vendors/nxp/boards/lpc54018iotmodule/aws_tests/common/config_files/iot_config.h
Description
-----------
Checklist:
----------
> fix nxp build for both demo and test

- doc/config/atomic
- doc/config/layout_main.xml
- doc/guidance.md
- doc/lib/atomic.txt
atomic API documentation
Description
-----------
Doxygen and related.
Checklist:
----------
> atomic API documentation

- vendors/nxp/boards/lpc54018iotmodule/CMakeLists.txt
- vendors/nxp/boards/lpc54018iotmodule/iar.cmake
- vendors/nxp/boards/lpc54018iotmodule/mcuxpresso.cmake
Description
-----------
Both IAR and GCC compile successfully.
Checklist:
----------
> combine mcuxpresso and iar in cmake file

- tests/xilinx/microzed/xsdk/aws_tests/.project
Description
-----------
Checklist:
----------
> Update Xilinx test project for new PKCS files

- lib/third_party/mcu_vendor/cypress/WICED_SDK/libraries/aws/aws.mk
Description
-----------
Checklist:
----------
> Cypressround2

- vendors/ti/boards/cc3220_launchpad/CMakeLists.txt
- vendors/ti/boards/cc3220_launchpad/ccs.cmake
- vendors/ti/boards/cc3220_launchpad/iar.cmake
Description
-----------
Checklist:
----------
> add IAR support for TI cmake

- lib/secure_sockets/portable/freertos_plus_tcp/aws_secure_sockets.c
prvSocketsGetCryptoSession should leave the scheduler running during PKCS #11 calls in order to allow hardware crypto calls that require interrupt handling. See #570.
> Leave the scheduler running during PKCS #11 calls.

- lib/FreeRTOS-Plus-TCP/include/FreeRTOS_DNS.h
- lib/FreeRTOS-Plus-TCP/source/FreeRTOS_DNS.c
> Add a function for clearing the FreeRTOS+TCP DNS cache.

- tests/microchip/curiosity_pic32mzef/mplab/nbproject/configurations.xml
Description
-----------
Checklist:
----------
> Add aws_pkcs11.c and aws_pki_utils.c to mplab test project

- lib/secure_sockets/portable/freertos_plus_tcp/aws_secure_sockets.c
> ulApplicationGetNextSequenceNumber must be thread safe without stopping the scheduler

- vendors/espressif/boards/esp32/CMakeLists.txt
- vendors/espressif/boards/esp32/aws_demos/make/.project
- vendors/espressif/boards/esp32/aws_demos/make/aws_demos.launch
- vendors/espressif/boards/esp32/aws_tests/make/.project
- vendors/espressif/boards/esp32/aws_tests/make/aws_tests.launch
- vendors/espressif/boards/esp32/run_idf_monitor.cmake
Description
-----------
C make fix to add make monitor to ESP32
Fixing eclipse project for ESP32
Checklist:
----------
> C make fix to add make monitor to ESP32

- lib/tls/aws_tls.c
- tests/common/pkcs11/aws_test_pkcs11.c
- tests/nxp/lpc54018iotmodule/iar/aws_tests.ewp
Description
-----------
Checklist:
----------
> Update NXP IAR project to build with updated PKCS #11

- lib/FreeRTOS-Plus-TCP/source/FreeRTOS_DNS.c
- lib/FreeRTOS-Plus-TCP/source/FreeRTOS_Sockets.c
- lib/FreeRTOS-Plus-TCP/source/FreeRTOS_TCP_IP.c
- tests/common/posix/aws_test_posix_utils.c
FreeRTOS+TCP improvements based on offline code-review.
> Improvements to FreeRTOS+TCP robustness

- vendors/cypress/WICED_SDK/Makefile
- vendors/cypress/WICED_SDK/WICED/RTOS/FreeRTOS/FreeRTOS.mk
- vendors/cypress/WICED_SDK/WICED/network/LwIP/LwIP.mk
- vendors/cypress/WICED_SDK/WICED/network/LwIP/WWD/FreeRTOS/FreeRTOS.mk
- vendors/cypress/WICED_SDK/WICED/network/LwIP/WWD/WWD.mk
- vendors/cypress/WICED_SDK/apps/demo/aws_demo/aws_demo.mk
- vendors/cypress/WICED_SDK/apps/test/aws_test/aws_test.mk
- vendors/cypress/WICED_SDK/libraries/aws/aws.mk
- vendors/cypress/boards/CYW943907AEVAL1F/aws_demos/common/application_code/main.c
- vendors/cypress/boards/CYW943907AEVAL1F/aws_demos/common/config_files/FreeRTOSConfig.h
- vendors/cypress/boards/CYW943907AEVAL1F/aws_demos/common/config_files/aws_demo_config.h
- vendors/cypress/boards/CYW954907AEVAL1F/aws_demos/common/application_code/main.c
- vendors/cypress/boards/CYW954907AEVAL1F/aws_demos/common/config_files/FreeRTOSConfig.h
- vendors/cypress/boards/CYW954907AEVAL1F/aws_demos/common/config_files/aws_demo_config.h
Description
-----------
Modified the files and directory path in makefiles of cypress to work with latest release-1.5. 
Checklist:
----------
> Changes to cypress Makefiles to work with release-1.5

- demos/network_manager/aws_iot_network_manager.c
- doc/lib/taskpool.txt
- modules/libraries/aws/defender/src/aws_iot_defender_api.c
- modules/libraries/standard/common/CMakeLists.txt
- modules/libraries/standard/common/include/iot_taskpool.h
- modules/libraries/standard/common/include/private/iot_taskpool_internal.h
- modules/libraries/standard/common/include/types/iot_taskpool_types.h
- modules/libraries/standard/common/static_memory/iot_static_memory_taskpool.c
- modules/libraries/standard/common/taskpool/iot_taskpool.c
- modules/libraries/standard/common/test/iot_tests_taskpool.c
- modules/libraries/standard/mqtt/include/iot_mqtt.h
- modules/libraries/standard/mqtt/src/iot_mqtt_api.c
- modules/libraries/standard/mqtt/src/iot_mqtt_network.c
- modules/libraries/standard/mqtt/src/iot_mqtt_operation.c
- modules/libraries/standard/mqtt/src/private/iot_mqtt_internal.h
- modules/libraries/standard/mqtt/test/unit/iot_tests_mqtt_api.c
- modules/ports/ble/services/wifi_provisioning/iot_ble_wifi_provisioning.c
- test/src/aws_test_runner.c
- vendors/pc/boards/windows/aws_tests/common/config_files/aws_test_runner_config.h
- vendors/pc/boards/windows/aws_tests/common/config_files/iot_config.h
- vendors/pc/boards/windows/aws_tests/visual_studio/aws_tests.vcxproj
- vendors/pc/boards/windows/aws_tests/visual_studio/aws_tests.vcxproj.filters
Change the task pool public API to support opaque types.
> Make task pool types opaque.

- demos/common/devmode_key_provisioning/aws_dev_mode_key_provisioning.c
- lib/include/aws_pkcs11.h
- lib/pkcs11/aws_pkcs11.c
- lib/pkcs11/mbedtls/aws_pkcs11_mbedtls.c
- lib/pkcs11/portable/microchip/curiosity_pic32mzef/aws_pkcs11_pal.c
- lib/tls/aws_tls.c
- tests/common/pkcs11/aws_test_pkcs11.c
- tests/espressif/esp32_devkitc_esp_wrover_kit/common/config_files/aws_pkcs11_config.h
Signed-off-by: Alexa Noxon <33439348+alexa-noxon@users.noreply.github.com>
Description
-----------
Checklist:
----------
> Incorporating Dan Griffin's changes to fix warnings

- demos/espressif/esp32_devkitc_esp_wrover_kit/common/application_code/espressif_code/mbedtls/port/include/mbedtls/esp_config.h
- tests/common/pkcs11/aws_test_pkcs11.c
- tests/espressif/esp32_devkitc_esp_wrover_kit/common/application_code/espressif_code/mbedtls/port/include/mbedtls/esp_config.h
Description
-----------
Checklist:
----------
> Update Esp32 mbedTLS config to remove MBEDTLS_ECDSA_DETERMINISTIC

- modules/libraries/standard/common/CMakeLists.txt
- modules/libraries/standard/common/test/iot_tests_taskpool.c
- vendors/espressif/boards/esp32/aws_tests/common/config_files/aws_test_runner_config.h
- vendors/espressif/boards/esp32/aws_tests/make/.project
- vendors/nordic/boards/nrf52840-dk/aws_tests/common/config_files/aws_test_runner_config.h
- vendors/nordic/boards/nrf52840-dk/aws_tests/ses/aws_tests.emProject
Fixing Task pool not running in test setup
Description
-----------
- Fxing manually nordic project
- Fixing cmake to include it
- Adding tests to project
- Replace initialization {{0}, 0} with memset since it was not compiling on ESP32
Checklist:
----------
> Fixing Task pool not running in test setup

- vendors/cypress/WICED_SDK/apps/test/aws_test/aws_test.mk
- vendors/cypress/boards/CYW943907AEVAL1F/aws_tests/common/application_code/main.c
- vendors/cypress/boards/CYW943907AEVAL1F/aws_tests/common/config_files/FreeRTOSConfig.h
- vendors/cypress/boards/CYW943907AEVAL1F/aws_tests/common/config_files/aws_test_runner_config.h
- vendors/cypress/boards/CYW954907AEVAL1F/aws_tests/common/application_code/main.c
- vendors/cypress/boards/CYW954907AEVAL1F/aws_tests/common/config_files/FreeRTOSConfig.h
- vendors/cypress/boards/CYW954907AEVAL1F/aws_tests/common/config_files/aws_test_runner_config.h
Description
-----------
- Added wifi connect in the initialization sequence of main in tests.
- Changed aws_test_runner_config.h according to new tests.
Checklist:
----------
> Added Wifi Connect in the initialization sequence of tests

- vendors/renesas/boards/rx65n-rsk/aws_demos/common/config_files/iot_config.h
- vendors/renesas/boards/rx65n-rsk/aws_demos/e2studio/.cproject
- vendors/renesas/boards/rx65n-rsk/aws_demos/e2studio/.project
- vendors/renesas/manifest.cmake
Description
-----------
Checklist:
----------
> update demo project for Renesas

- vendors/renesas/boards/rx65n-rsk/CMakeLists.txt
- vendors/renesas/boards/rx65n-rsk/aws_demos/common/config_files/aws_secure_sockets_config.h
- vendors/renesas/boards/rx65n-rsk/aws_demos/e2studio/.cproject
- vendors/renesas/boards/rx65n-rsk/aws_demos/e2studio/.project
- vendors/renesas/boards/rx65n-rsk/aws_tests/e2studio/.cproject
- vendors/renesas/boards/rx65n-rsk/aws_tests/e2studio/.project
Description
-----------
Enable defender demo in Renesas.
Run the demo locally and verify it works.
Checklist:
----------
> enable defender demo in Renesas

- vendors/cypress/WICED_SDK/apps/test/aws_test/aws_test.mk
- vendors/cypress/boards/CYW943907AEVAL1F/aws_tests/common/config_files/aws_test_runner_config.h
- vendors/cypress/boards/CYW943907AEVAL1F/aws_tests/common/config_files/iot_config.h
- vendors/cypress/boards/CYW954907AEVAL1F/aws_tests/common/config_files/aws_test_runner_config.h
- vendors/cypress/boards/CYW954907AEVAL1F/aws_tests/common/config_files/iot_config.h
Description
-----------
- Added the missing test files for the tests to run in aws_test.mk
- Removed Logging in iot_config.h
Checklist:
----------
> Changes for tests to run on cypress

- demos/CMakeLists.txt
- demos/network_manager/aws_iot_network_manager.c
- modules/ports/ble/CMakeLists.txt
- modules/ports/ble/include/iot_ble_wifi_provisioning.h
- modules/ports/ble/iot_ble_gap.c
- modules/ports/ble/services/wifi_provisioning/iot_ble_wifi_provisioning.c
- modules/ports/ble/test/aws_test_wifi_provisioning.c
- vendors/espressif/boards/esp32/CMakeLists.txt
- vendors/infineon/boards/xmc4800_iotkit/CMakeLists.txt
- vendors/infineon/boards/xmc4800_iotkit/aws_demos/dave4/.cproject
- vendors/infineon/boards/xmc4800_iotkit/aws_demos/dave4/.project
Cmake module for WiFi provisioning
Description
-----------
Create new cmake module for wifi provisioning as it has dependency on both BLE and WiFi libraries. 
Added network manager to demo cmakelists.
Checklist:
----------
> Cmake module for WiFi provisioning

- vendors/microchip/boards/curiosity_pic32mzef/aws_demos/common/config_files/aws_secure_sockets_config.h
- vendors/microchip/boards/curiosity_pic32mzef/aws_tests/common/config_files/aws_secure_sockets_config.h
Description
-----------
enable socket metrics to pass defender tests
Tests almost pass: https://amazon-freertos-ci.corp.amazon.com/view/5-CMake/job/afr_test_cmake/320/testReport/
Checklist:
----------
> enable metrics to fix defender tests

- modules/libraries/aws/defender/test/aws_iot_tests_defender_api.c
- vendors/nxp/boards/lpc54018iotmodule/CMakeLists.txt
- vendors/nxp/boards/lpc54018iotmodule/aws_demos/common/config_files/aws_secure_sockets_config.h
- vendors/nxp/boards/lpc54018iotmodule/aws_demos/common/config_files/iot_config.h
- vendors/nxp/boards/lpc54018iotmodule/aws_demos/iar/aws_demos.ewp
- vendors/nxp/boards/lpc54018iotmodule/aws_tests/common/config_files/aws_secure_sockets_config.h
- vendors/nxp/boards/lpc54018iotmodule/aws_tests/common/config_files/iot_config.h
- vendors/nxp/boards/lpc54018iotmodule/aws_tests/iar/aws_tests.ewp
Description
-----------
- enable defender so that serializer tests and defender tests are added
Checklist:
----------
> enable serializer and defender tests

- vendors/pc/boards/windows/aws_demos/common/config_files/aws_secure_sockets_config.h
- vendors/renesas/boards/rx65n-rsk/aws_tests/common/config_files/aws_secure_sockets_config.h
Description
-----------
Checklist:
----------
> enable metrics in pc demo and renesas test

- vendors/cypress/WICED_SDK/apps/demo/aws_demo/aws_demo.mk
Description
-----------
Demo files were missing in the makefiles of cypress. Added them.
Checklist:
----------
> Add files to enable Defender, Shadow, TCPEcho demos

- tools/ota_e2e_tests/aws_ota_test/aws_ota_project.py
- tools/ota_e2e_tests/aws_ota_test/aws_ota_test_runner.py
Updated the file paths for ota e2e tests in accordance with the new folder structure.
Description
-----------
Updated the file paths for ota e2e tests in accordance with the new folder structure.
Checklist:
----------
> Updated the file paths for ota e2e tests in accordance with the new folder structure.

- tools/ota_e2e_tests/aws_ota_test/aws_flash_serial_comm.py
- tools/ota_e2e_tests/aws_ota_test/aws_ota_project.py
Updated the file paths in accordance with the new-new folder structure. These folder structure changes were merged today.
Description
-----------
These folder structure changes were merged today. So changed the test cases to follow that structure.
Checklist:
----------
> Updated the file paths in accordance with the new-new folder structure.

- tools/cbmc/proofs/DNS/DNSHandlePacket/Makefile.json
- tools/cbmc/proofs/DNS/DNSHandlePacket/cbmc-batch.yaml
Description
-----------
Updated the json file.
Checklist:
----------
> adding DNShandlePacket

- tools/ota_e2e_tests/aws_ota_test/aws_flash_serial_comm.py
- tools/ota_e2e_tests/aws_ota_test/aws_ota_project.py
- tools/ota_e2e_tests/aws_ota_test/aws_ota_test_case.py
- tools/ota_e2e_tests/aws_ota_test/aws_ota_test_main.py
- tools/ota_e2e_tests/aws_ota_test/aws_ota_test_result.py
- tools/ota_e2e_tests/aws_ota_test/aws_ota_test_runner.py
Updated the test cases to work with new folder structure. Incase of build and flash failure the test will stop.
Description
-----------
Updated the test cases to work with new folder structure. Also in case of test or build failure, the test would be marked as ERROR instead of FAIL and the test would stop instead of continuing. On Jenkins these tests will be shown as skipped.
Checklist:
----------
> Updated the test cases to work with new folder structure.

- vendors/ti/boards/cc3220_launchpad/ports/secure_sockets/aws_secure_sockets.c
Description
-----------
Checklist:
----------
> Update TI secure sockets comments with new filepath to errors.h

- demos/common/devmode_key_provisioning/aws_dev_mode_key_provisioning.c
PR #650 broke the MediaTek demo project build. This commit fixes it.
> Fix MediaTek demo build break in #650.

- vendors/cypress/WICED_SDK/WICED/network/LwIP/LwIP.mk
- vendors/cypress/WICED_SDK/WICED/network/LwIP/WWD/FreeRTOS/FreeRTOS.mk
- vendors/cypress/WICED_SDK/WICED/network/LwIP/WWD/WWD.mk
- vendors/cypress/WICED_SDK/apps/demo/aws_demo/aws_demo.mk
- vendors/cypress/WICED_SDK/apps/test/aws_test/aws_test.mk
- vendors/cypress/WICED_SDK/libraries/aws/aws.mk
Description
-----------
Changed the location of files in cypress makefiles
Checklist:
----------
> Changed Cypress Makefiles according to new folder stucture

- vendors/cypress/WICED_SDK/apps/test/aws_test/aws_test.mk
Description
-----------
Added missing serializer test files.
Checklist:
----------
> Added serializer files to Cypress makefiles

- projects/microchip/curiosity_pic32mzef/mplab/aws_demos/nbproject/configurations.xml
- projects/microchip/curiosity_pic32mzef/mplab/aws_tests/nbproject/configurations.xml
- projects/microchip/curiosity_pic32mzef/mplab/aws_tests/nbproject/project.xml
- projects/microchip/curiosity_pic32mzef/mplab/bootloader_tests/nbproject/configurations.xml
- projects/microchip/curiosity_pic32mzef/mplab/bootloader_tests/nbproject/project.xml
Description
-----------
Fix the microchip bootloader test project for new folder structure.
Checklist:
----------
> Fix: Microchip Bootloader tests project fix

- tools/ota_e2e_tests/aws_ota_test/aws_flash_serial_comm.py
- tools/ota_e2e_tests/aws_ota_test/aws_ota_project.py
Added print statement for debugging and resolved the None error.
Description
-----------
Added print statement for debugging and resolved the None error.
Checklist:
----------
> Added print statement for debugging and resolved the None error.

- tools/ota_e2e_tests/aws_ota_test/aws_ota_project.py
Added print statement for debugging.
Description
-----------
Added print statement for debugging to check the current working directory for the tests.
Checklist:
----------
> Added print statement for debugging.

- tests/common/aws_test_runner.c
Description
-----------
Remove Quarantine test group for TCP and WIFI
Checklist:
----------
> Remove Quarantine test group for TCP and WIFI

- tools/ota_e2e_tests/aws_ota_test/aws_ota_project.py
Updated the MQTT endpoint variable name as updated in the latest branch.
Description
-----------
Updated the MQTT endpoint variable name as updated in the latest branch in aws_credentials.h file. 
Checklist:
----------
> Updated the MQTT endpoint variable name as updated in the latest branch.

- tools/ota_e2e_tests/aws_ota_test/aws_ota_test_case_dummy_test.py
Fixed the None type error in the dummy test.
Description
-----------
Fixed the None type error in the dummy test.
Checklist:
----------
> Fixed the None type error in the dummy test.

- tools/cbmc/proofs/ARP/ARPAgeCache/README.md
- tools/cbmc/proofs/ARP/ARPGenerateRequestPacket/README.md
- tools/cbmc/proofs/ARP/ARPSendGratuitous/Makefile.json
- tools/cbmc/proofs/ARP/ARPSendGratuitous/README.md
- tools/cbmc/proofs/ARP/ARPSendGratuitous/cbmc-batch.yaml
Description
-----------
I added README.md files summarizing the proofs added for ARP.
Further, I expanded the ARPSendGratuitos proof by including more function bodies.
> Add proof statement for existing CBMC harnesses

- tools/ota_e2e_tests/aws_ota_test/aws_ota_test_case.py
- tools/ota_e2e_tests/aws_ota_test/aws_ota_test_result.py
Add elasped time for test case execution
Description
-----------
Add elasped time for test case execution
Checklist:
----------
> Add elasped time for test case execution

- tools/ota_e2e_tests/aws_ota_test/aws_ota_aws_agent.py
- tools/ota_e2e_tests/aws_ota_test/aws_ota_project.py
- tools/ota_e2e_tests/aws_ota_test/aws_ota_test_case.py
- tools/ota_e2e_tests/aws_ota_test/aws_ota_test_main.py
- tools/ota_e2e_tests/aws_ota_test/aws_ota_test_result.py
Updating the bootloader files only for the boards needed. Fixed the test results in case of failure.
Description
-----------
Updating the bootloader files only for the boards needed. Fixed the test results in case of failure it was not getting marked as FAIL in the xml in all the scenarios.
Checklist:
----------
> Gevariah/ota e2e tests fixes release 1.5

- tools/ota_e2e_tests/aws_ota_test/aws_ota_project.py
Fixed the paths for the bootloader files.
Description
-----------
Fixed the paths for the bootloader files in ota e2e test scripts.
Checklist:
----------
> Fixed the paths for bootloader files.

- tools/ota_e2e_tests/aws_ota_test/aws_ota_test_case_back_to_back_downloads.py
Fixed the tuple errors causing back to back downloads to fail.
Description
-----------
Fixed the tuple errors causing back to back downloads to fail.
Checklist:
----------
> Fixed the tuple errors causing back to back downloads to fail.

- doc/config/common
- doc/lib/wifi.txt
- libraries/abstractions/wifi/include/aws_wifi.h
Description
-----------
Checklist:
----------
> update wifi doxygen doc

- doc/config/secure_sockets
- doc/lib/secure_sockets.txt
- libraries/abstractions/secure_sockets/include/aws_secure_sockets.h
Description
-----------
Checklist:
----------
> update doxygen doc for secure socket

- .github/CODE_OF_CONDUCT.md
- .github/PULL_REQUEST_TEMPLATE.md
Description
-----------
Checklist:
----------
> update pull request template and add code of conduct

- demos/dev_mode_key_provisioning/include/aws_dev_mode_key_provisioning.h
- demos/dev_mode_key_provisioning/src/aws_dev_mode_key_provisioning.c
Description
-----------
Checklist:
----------
> Add Doxygen comments for aws_dev_mode_key_provisioning.h

- CHANGELOG.md
- README.md
- directories.txt
> changelog.md for release 1.5. And rewording for 1.4.8.

- CHANGELOG.md
Description
-----------
See subject.
Checklist:
----------
> Removing reference to Device Defender under BLE.

- projects/espressif/esp32/make/aws_tests/.project
- tests/bleTestsScripts/testClass.py
Fixing BLE PI tests for AFQP
Description
-----------
Fixing BLE PI tests for AFQP
Checklist:
----------
> Fixing PI tests

- projects/mediatek/mt7697hx-dev-kit/uvision/aws_demos/aws_demos.uvprojx
- projects/mediatek/mt7697hx-dev-kit/uvision/aws_tests/aws_tests.uvprojx
Fixing mediatek project
Description
-----------
Fixing mediatek project
Checklist:
----------
> Fixing mediatek project

- libraries/abstractions/pkcs11/mbedtls/aws_pkcs11_mbedtls.c
Description
-----------
Checklist:
----------
> Top of aws_pkcs11_mbedtls.c docs update/deletion of unused configs.

- doc/README.md
Description
-----------
Adds a README with links to the doc folder.
Checklist:
----------
> Add README for documentation folder

- libraries/3rdparty/CMakeLists.txt
- libraries/3rdparty/http-parser/LICENSE-MIT
- libraries/3rdparty/http-parser/http_parser.c
- libraries/3rdparty/http-parser/http_parser.h
Add third-party library http-parser from nodejs.
https://github.com/nodejs/http-parser
This PR adds third party library http-parser from nodejs. This is not for comments. This just to show the library going in.
Checklist:
----------
- [n/a] I have tested my changes. No regression in existing tests.
> HTTPS Client: Add third-party library http-parser from nodejs.

- demos/dev_mode_key_provisioning/include/aws_dev_mode_key_provisioning.h
- demos/dev_mode_key_provisioning/src/aws_dev_mode_key_provisioning.c
- freertos_kernel/include/atomic.h
- libraries/freertos_plus/standard/freertos_plus_tcp/test/aws_freertos_tcp_test_access_declare.h
- libraries/freertos_plus/standard/freertos_plus_tcp/test/aws_freertos_tcp_test_access_dns_define.h
- libraries/freertos_plus/standard/freertos_plus_tcp/test/aws_freertos_tcp_test_access_tcp_define.h
- libraries/freertos_plus/standard/freertos_plus_tcp/test/aws_test_freertos_tcp.c
Description
-----------
Some of the files did not have correct version numbers in their license
header. This commit fixes them.
Checklist:
----------
> Fix version numbers in some AFR components

- tools/cbmc/patches/compute_patch.py
Description
-----------
Enabling the auto patch script to pick up the defines from the `MakefileCommon.json` in the future.
Checklist:
----------
> Update compute_patch.py to pick up MakefileCommon.json

- vendors/ti/README.txt
Adds some details behind the subset of the TI SDK provided with Amazon
FreeRTOS, as well as a link to the 2.10.00.04 SDK.
Signed-off-by: Chris Ring <cring@ti.com>
> Wordsmithing of TI README.txt

- tools/cmake/afr_metadata.cmake
Description
-----------
Add some missing files to cmake.
Checklist:
----------
> Add code of conduct and contributing guid to cmake

- tools/git/hooks/src/pre_commit.py
Description
-----------
Checklist:
----------
> Fix uncrustify config path in pre-commit hook

- tools/cbmc/proofs/ARP/ARPAgeCache/cbmc-batch.yaml
- tools/cbmc/proofs/ARP/ARPGenerateRequestPacket/cbmc-batch.yaml
- tools/cbmc/proofs/ARP/ARPGetCacheEntry/cbmc-batch.yaml
- tools/cbmc/proofs/ARP/ARPProcessPacket/cbmc-batch.yaml
- tools/cbmc/proofs/ARP/ARPRefreshCacheEntry/cbmc-batch.yaml
- tools/cbmc/proofs/ARP/ARPSendGratuitous/cbmc-batch.yaml
- tools/cbmc/proofs/ARP/ARP_FreeRTOS_ClearARP/cbmc-batch.yaml
- tools/cbmc/proofs/ARP/ARP_FreeRTOS_OutputARPRequest/cbmc-batch.yaml
- tools/cbmc/proofs/CheckOptions/cbmc-batch.yaml
- tools/cbmc/proofs/CheckOptionsInner/cbmc-batch.yaml
- tools/cbmc/proofs/CheckOptionsOuter/cbmc-batch.yaml
- tools/cbmc/proofs/DNS/DNSHandlePacket/cbmc-batch.yaml
- tools/cbmc/proofs/DNS/DNSclear/cbmc-batch.yaml
- tools/cbmc/proofs/ParseDNSReply/cbmc-batch.yaml
- tools/cbmc/proofs/ProcessDHCPReplies/cbmc-batch.yaml
- tools/cbmc/proofs/ReadNameField/cbmc-batch.yaml
- tools/cbmc/proofs/SkipNameField/cbmc-batch.yaml
These files are now generated from the tools/cbmc/prepare.py script.
> Remove generated `cbmc-batch.yaml` files from repo

- vendors/cypress/WICED_SDK/apps/demo/aws_demo/aws_demo.mk
Description
-----------
Please refer issue #905 
Checklist:
----------
> fix for build error in Cypress kits Fix for issue #905

- libraries/c_sdk/aws/shadow/test/aws_test_shadow.c
Fixes the signature of the Shadow test delta callback to resolve compiler warnings/error in IAR.
> Fix signature of Shadow test delta callback

- libraries/freertos_plus/standard/freertos_plus_tcp/source/portable/NetworkInterface/pic32mzef/NetworkInterface_eth.c
pic32mzef: Let xNetworkInterfaceInitialise wait for the PHY Link Status
-----------
This PR is about the Microchip Ethernet interface of the pic32mzef.
The function `xNetworkInterfaceInitialise()` is supposed to return `pdPASS` when the driver is operational. The IP-task will call it repeatedly ( every 3 seconds ) until it returns `pdPASS`.
The module `NetworkInterface_eth.c` needs two changes:
- Let it initialise the MAC only once, and not every time when it is called.
- Let it return pdPASS only when the MAC is initialised successfully **and** when the PHY Link Status is high.
Checklist:
----------
> pic32mzef : Let xNetworkInterfaceInitialise wait for the PHY Link Status

- tools/git/hooks/src/pre_commit.py
Description
-----------
Checklist:
----------
> Fix uncrustify config path

- vendors/espressif/boards/esp32/CMakeLists.txt
Fixing cmake build on ESP demos
Description
-----------
Fixing cmake build on ESP demos
Checklist:
----------
> Fixing cmake build on ESP demos

- libraries/c_sdk/standard/serializer/CMakeLists.txt
- libraries/c_sdk/standard/serializer/src/json/iot_serializer_json_decoder.c
- libraries/c_sdk/standard/serializer/test/iot_tests_deserializer_json.c
- projects/mediatek/mt7697hx-dev-kit/uvision/aws_tests/aws_tests.uvprojx
- projects/microchip/curiosity_pic32mzef/mplab/aws_tests/nbproject/configurations.xml
- projects/nordic/nrf52840-dk/ses/aws_tests/aws_tests.emProject
- projects/nxp/lpc54018iotmodule/iar/aws_tests/aws_tests.ewp
- projects/pc/windows/visual_studio/aws_tests/aws_tests.vcxproj
- projects/pc/windows/visual_studio/aws_tests/aws_tests.vcxproj.filters
- tests/common/aws_test_runner.c
- vendors/cypress/WICED_SDK/apps/test/aws_test/aws_test.mk
- vendors/espressif/boards/esp32/aws_tests/config_files/aws_test_runner_config.h
Description
-----------
Update JSON deserializer to parse nested objects. 
- Add unit tests for deserializer. 
- update parser to make `find_nested_key_array_of_objects_value` pass
Checklist:
----------
> Update JSON deserializer to parse nested objects

- tools/cbmc/proofs/Makefile.template
Description
-----------
This scripts re runs --drop-unused-functions.
Checklist:
----------
> Changing the Makefile template to re run --drop-unused-functions

- vendors/vendor/boards/board/CMakeLists.txt
Description
-----------
Update cmake template with correct path which matches latest folder structure.
Checklist:
----------
> update cmake template under vendor folder

- vendors/microchip/boards/curiosity_pic32mzef/CMakeLists.txt
Description
-----------
Checklist:
----------
> Add instructions for finding MPLAB hexmate tool to CMake build

- projects/nordic/nrf52840-dk/ses/aws_tests/aws_tests.emProject
- vendors/espressif/boards/esp32/ports/ble/bluedroid/iot_ble_hal_common_gap.c
- vendors/espressif/boards/esp32/ports/ble/bluedroid/iot_ble_hal_gap.c
- vendors/espressif/boards/esp32/ports/ble/bluedroid/iot_ble_hal_gatt_server.c
- vendors/nordic/boards/nrf52840-dk/aws_demos/config_files/iot_config.h
- vendors/nordic/boards/nrf52840-dk/ports/ble/iot_ble_hal_common_gap.c
- vendors/nordic/boards/nrf52840-dk/ports/ble/iot_ble_hal_gap.c
- vendors/nordic/boards/nrf52840-dk/ports/ble/iot_ble_hal_gatt_server.c
Removing FreeRTOS from BLE hal
Description
-----------
Removing FreeRTOS from BLE hal
Checklist:
----------
> Removing FreeRTOS from BLE hal

- libraries/freertos_plus/standard/tls/test/iot_test_tls.c
- tests/common/aws_test_runner.c
Description
-----------
Checklist:
----------
> Remove TLS tests that require elliptic curve from quarantine

- tools/git/hooks/src/pre_commit.py
Description
-----------
Update pre-commit hook script according to the new folder structure
Checklist:
----------
> Update pre-commit hook script according to the new folder structure

- doc/config/layout_main.xml
Description
-----------
Checklist:
----------
> Add missing closing tag

- libraries/abstractions/ble_hal/test/iot_test_ble_hal.c
- tests/bleTestsScripts/attributesCommon.py
- tests/bleTestsScripts/bleAdapter.py
- tests/bleTestsScripts/gattClient.py
- tests/bleTestsScripts/securityAgent.py
- tests/bleTestsScripts/startTests.py
- tests/bleTestsScripts/test1.py
- tests/bleTestsScripts/testClass.py
- tests/bleTestsScripts/testutils.py
Changes on iot_test_ble_hal.c to remove FreeRTOS references and on bleTestsScripts to change tabs into spaces
Description
-----------
* Removed any remaining FreeRTOS references from iot_test_ble_hal.c to make it os agnostic
* Replaced tabs with spaces on bleTestsScripts
Checklist:
----------
> Changes on iot_test_ble_hal.c to remove FreeRTOS references and on bleTestsScripts to change tabs into spaces

- libraries/c_sdk/standard/mqtt/test/unit/iot_tests_mqtt_serialize_ble.c
Fix MQTT BLE Serializer unit tests
Description
-----------
New CBOR version does mandatory check for the number of parameters serialized. The number of parameters was incorrect for some test cases.
Checklist:
----------
All serializer tests passes.
> Fix MQTT BLE Serializer unit tests

- demos/dev_mode_key_provisioning/include/aws_dev_mode_key_provisioning.h
Description
-----------
Checklist:
----------
> Uncrustify

- freertos_kernel/include/task.h
Description
-----------
Update FreeRTOS version number in task.h
Checklist:
----------
> Update FreeRTOS version number in task.h

- vendors/nuvoton/boards/numaker_iot_m487_wifi/CMakeLists.txt
Description
-----------
Checklist:
----------
> update metadata for Nuvoton

- CHANGELOG.md
Description
-----------
Update changelog for FreeRTOS kernel update
Checklist:
----------
> Update changelog for FreeRTOS kernel update

- libraries/c_sdk/standard/common/include/iot_logging_task.h
- libraries/c_sdk/standard/common/include/iot_taskpool.h
- libraries/c_sdk/standard/common/logging/iot_logging.c
- libraries/c_sdk/standard/mqtt/include/iot_mqtt.h
Doxygen Updates
Description
-----------
Fix various small doxygen comments
Checklist:
----------
> Fix various small doxygen comments

- tools/cbmc/patches/.gitignore
- tools/cbmc/proofs/.gitignore
> Add CBMC .gitignores

- CHANGELOG.md
Update changelog.md for OTA changes 
Description
-----------
Checklist:
----------
> Update Changlog.md for OTA updates

- demos/dev_mode_key_provisioning/src/aws_dev_mode_key_provisioning.c
Description
-----------
This fixes the ESP demo build.
Checklist:
----------
> Cast PIN input to C_InitToken

- demos/mqtt/iot_demo_mqtt.c
Description
-----------
Checklist:
----------
> Fix MQTT demo calculation for counting incoming messages

- tools/cbmc/proofs/HTTP/IotHttpsClient_AddHeader/IotHttpsClient_AddHeader_harness.c
- tools/cbmc/proofs/HTTP/IotHttpsClient_AddHeader/Makefile.json
Add IotHttpsClient_AddHeader memory safety proof.
Checklist:
----------
> Add IotHttpsClient_AddHeader memory safety proof.

- libraries/abstractions/ble_hal/CMakeLists.txt
- libraries/abstractions/ble_hal/test/include/iot_test_ble_hal_afqp.h
- libraries/abstractions/ble_hal/test/include/iot_test_ble_hal_common.h
- libraries/abstractions/ble_hal/test/include/iot_test_ble_hal_integration.h
- libraries/abstractions/ble_hal/test/include/iot_test_ble_hal_kpi.h
- libraries/abstractions/ble_hal/test/include/iot_test_ble_hal_stress_test.h
- libraries/abstractions/ble_hal/test/src/iot_test_ble_hal_afqp.c
- libraries/abstractions/ble_hal/test/src/iot_test_ble_hal_integration.c
- libraries/abstractions/ble_hal/test/src/iot_test_ble_hal_kpi.c
- libraries/abstractions/ble_hal/test/src/iot_test_ble_hal_stress_test.c
- tests/bleTestsScripts/startTests_integration.py
- tests/bleTestsScripts/startTests_kpi.py
- tests/bleTestsScripts/startTests_stress.py
- tests/bleTestsScripts/test_integration.py
- tests/bleTestsScripts/test_kpi.py
- tests/bleTestsScripts/test_stress.py
- tests/common/aws_test_runner.c
- vendors/espressif/boards/esp32/aws_tests/config_files/aws_test_runner_config.h
ble_hal test cases achitectural change
Description
-----------
Re-organization of ble hal test files to accommodate adding additional test groups into their own separate files.
Checklist:
----------
> ble_hal test cases achitectural change

- freertos_kernel/portable/MemMang/heap_4.c
- freertos_kernel/portable/MemMang/heap_5.c
Description
-----------
https://sourceforge.net/p/freertos/code/HEAD/tree/trunk/FreeRTOS/Source/portable/MemMang/heap_4.c   [r2714]
https://sourceforge.net/p/freertos/code/HEAD/tree/trunk/FreeRTOS/Source/portable/MemMang/heap_5.c   [r2714]
Note for myself -- Check with Richard before merging this branch. As kernel code is updated by this branch. 
Checklist:
----------
> Heap stats -- vPortGetHeapStats

- libraries/freertos_plus/standard/pkcs11/include/iot_pkcs11.h
- libraries/freertos_plus/standard/pkcs11/src/iot_pkcs11.c
- vendors/pc/boards/windows/ports/pkcs11/softhsm/ReadMe.md
- vendors/pc/boards/windows/ports/pkcs11/softhsm/iot_pkcs11_softhsm.c
Amazon FreeRTOS port and instructions for the SoftHSMv2 PKCS #11 module.
> Amazon FreeRTOS port for SoftHSM (#1035)

- libraries/abstractions/platform/freertos/include/platform/iot_network_freertos.h
- libraries/abstractions/platform/freertos/iot_network_freertos.c
- libraries/abstractions/platform/include/platform/iot_network.h
Description
-----------
Checklist:
----------
> Add network ReceiveUpto

- vendors/ti/boards/cc3220_launchpad/aws_demos/config_files/aws_demo_config.h
Description
-----------
Checklist:
----------
> Increase stack size for Shadow demo on TI

- libraries/c_sdk/standard/mqtt/include/iot_mqtt.h
Mqtt documentation
Description
-----------
Changed example documentation in mqtt
Checklist:
----------
> Fix mqtt example documentation

- vendors/xilinx/boards/microzed/aws_demos/config_files/aws_demo_config.h
Description
-----------
Checklist:
----------
> Increase stack size for Xilinx Shadow demo

- vendors/st/boards/stm32l475_discovery/aws_demos/config_files/aws_demo_config.h
Description
-----------
As in title.
Checklist:
----------
> Increase stack size of ST Shadow demo

- vendors/ti/boards/cc3220_launchpad/aws_demos/config_files/aws_demo_config.h
Fix GG stack overflow
Description
-----------
Fix GG stack overflow
Checklist:
----------
> Fixing stack overflow on GG

- CMakeLists.txt
Version update
Description
-----------
Highlevel version string update for the 201908.00 release
> Highlevel version update for the 201908.00 release

- CHANGELOG.md
CHANGELOG update
Description
-----------
Update CHANGELOG with release version header for release 201908.00
> Update CHANGELOG with release version header

- CHANGELOG.md
CHANGELOG.md correction for renamed files
Description
-----------
CHANGELOG.md correction for renamed files as the script in one of the changes renamed the Changelog in the older releases.
> CHANGELOG.md correction for renamed files

- libraries/c_sdk/standard/https/CMakeLists.txt
Update for the name of the library and the description to be displayed in the
software configuration download in the Amazon FreeRTOS Device Software page in
AWS IoT core.
Checklist:
----------
> Update CMakeLists.txt for the HTTPS Client Library.

- libraries/3rdparty/lwip/src/portable/arch/sys_arch.c
- libraries/abstractions/secure_sockets/lwip/iot_secure_sockets.c
Full_DEFENDER tests all passing for cypress54
This PR is the same as #1117, but targeted at the release candidate.
> fix stack garbage return and drop ineffectual yield

- demos/dev_mode_key_provisioning/include/aws_dev_mode_key_provisioning.h
- demos/dev_mode_key_provisioning/src/aws_dev_mode_key_provisioning.c
- libraries/abstractions/pkcs11/test/iot_test_pkcs11.c
- libraries/freertos_plus/standard/tls/test/iot_test_tls.c
The purpose of this PR is to modify developer-mode key provisioning in order to conditionally use existing crypto objects in storage.
> Update developer-mode key provisioning for secure elements

- CHANGELOG.md
Description
-----------
Change the date in CHANGELOG.md to match release date 08/22/2019
> Change the date in CHANGELOG.md to match release date

- libraries/3rdparty/pkcs11/pkcs11.h
- libraries/3rdparty/pkcs11/pkcs11f.h
- libraries/3rdparty/pkcs11/pkcs11t.h
- libraries/abstractions/pkcs11/mbedtls/iot_pkcs11_mbedtls.c
- libraries/freertos_plus/standard/pkcs11/include/iot_pkcs11.h
- vendors/infineon/boards/xmc4800_iotkit/ports/pkcs11/iot_pkcs11_pal.c
- vendors/nxp/boards/lpc54018iotmodule/ports/pkcs11/iot_pkcs11_pal.c
- vendors/pc/boards/windows/ports/pkcs11/softhsm/iot_pkcs11_softhsm.c
Header files from:
o    http://docs.oasis-open.org/pkcs11/pkcs11-base/v2.40/errata01/os/include/pkcs11-v2.40/pkcs11.h
o    http://docs.oasis-open.org/pkcs11/pkcs11-base/v2.40/errata01/os/include/pkcs11-v2.40/pkcs11t.h
o    http://docs.oasis-open.org/pkcs11/pkcs11-base/v2.40/errata01/os/include/pkcs11-v2.40/pkcs11f.h
Description
-----------
Updated 3P header files for PKCS #11 .
https://amazon-freertos-ci.corp.amazon.com/job/all_boards_ide/22/
https://amazon-freertos-ci.corp.amazon.com/job/all_boards_ide/26/
Checklist:
----------
> Update PKCS #11 headers to match latest

- libraries/c_sdk/standard/ble/src/iot_ble_gap.c
Adding wait for BLE on
Description
-----------
Make sure IotBLEOn waits for the callback.
Checklist:
----------
> Adding wait for BLE on

- doc/config/atomic
- doc/config/ble
- doc/config/common
- doc/config/defender
- doc/config/linear_containers
- doc/config/logging
- doc/config/main
- doc/config/mqtt
- doc/config/platform
- doc/config/posix
- doc/config/secure_sockets
- doc/config/shadow
- doc/config/static_memory
- doc/config/taskpool
- doc/config/wifi
- doc/guidance.md
Doxygen minor updates to documentation
Description
-----------
Added missing libraries to doxygen guide. Added missing step of creating a tag folder.
Checklist:
----------
> Doxygen documentation update

- vendors/espressif/boards/esp32/aws_demos/application_code/espressif_code/mbedtls/component.mk
- vendors/espressif/boards/esp32/aws_tests/application_code/espressif_code/mbedtls/component.mk
Description
-----------
Checklist:
----------
> Fix include order of mbedtls in espressif

- vendors/espressif/boards/esp32/aws_tests/config_files/iot_test_pkcs11_config.h
Description
-----------
Checklist:
----------
> Up the stack size for PKCS #11 multithread tests on ESP

- CHANGELOG.md
Description
-----------
Changelog date update for release 201908.00
> Date change for CHANGELOG.md for release 201908.00

- vendors/espressif/boards/esp32/ports/ble/nimble/iot_ble_hal_common_gap.c
BLE: Fix issues in NimBLE at the AFR layer
Description
-----------
1. Modify prvBTEnable to trigger pxDeviceStateChangedCb
2. Handle BLE_GAP_EVENT_NOTIFY_TX appropriately for indications and notifications
Checklist:
----------
> BLE: Fix issues in NimBLE at the AFR layer

- libraries/abstractions/pkcs11/ReadMe.md
Updates for post-merge PKCS #11 documenation.
Description
-----------
Checklist:
----------
> Update PKCS #11 READMEs

- vendors/espressif/boards/esp32/ports/ble/nimble/iot_ble_hal_common_gap.c
AFR: NimBLE - Add support to disable and deinit NimBLE
Description
-----------
1. Implement .pxDisable for NimBLE
2. Also, remove `esp_bt_controller_mem_release( ESP_BT_MODE_BTDM )` from
pxBtManagerCleanup as it is not required. That's because, controller
memory for classic BT is already freed in case of NimBLE. So, we just
need to free controller memory for BLE in case of cleanup
Checklist:
----------
> AFR: NimBLE - Add support to disable and deinit NimBLE

- libraries/abstractions/pkcs11/CMakeLists.txt
https://amazon-freertos-ci.corp.amazon.com/job/all_boards_cmake/32/
Description
-----------
Checklist:
----------
> Add PKCS #11 PAL for mbedTLS based implementation to CMake

- tools/certificate_configuration/PEMfileToCString.html
- tools/certificate_configuration/js/generator.js
Move javascript function into common js generator file.
Resolves #1193
Description
-----------
Checklist:
----------
> Refactor PEMfileToCString & correct JS reference

- vendors/microchip/boards/curiosity_pic32mzef/bootloader/bootloader/README.md
Fix Readme: Microchip bootloader paths in readme
-----------
Checklist:
----------
> Fix Readme: Microchip bootloader paths in readme

- demos/https/iot_demo_https_s3_download_async.c
- demos/https/iot_demo_https_s3_download_sync.c
- demos/https/iot_demo_https_s3_upload_async.c
- demos/https/iot_demo_https_s3_upload_sync.c
- libraries/c_sdk/standard/https/include/iot_https_client.h
- libraries/c_sdk/standard/https/src/iot_https_client.c
- libraries/c_sdk/standard/https/test/system/iot_tests_https_system.c
- libraries/c_sdk/standard/https/test/unit/iot_tests_https_async.c
- libraries/c_sdk/standard/https/test/unit/iot_tests_https_client.c
- libraries/c_sdk/standard/https/test/unit/iot_tests_https_sync.c
This is for consistency with other C SDK libraries.
Checklist:
----------
> Renamed IotHttpsClient_Deinit() to IotHttpsClient_Cleanup().

- README.md
Description
-----------
Since we are adding submodules to our repository, we will need to update the README to reflect the new procedures to download/clone the repository 
Checklist:
----------
> Add info about submodules to README

- libraries/abstractions/common_io/include/iot_battery.h
1. change callback arg
2. change iot_battery_open() comment
Description
-----------
Checklist:
----------
> iot_battery.h pull reuqest

- libraries/abstractions/common_io/test/test_iot_cli.c
- libraries/abstractions/common_io/test/test_iot_main.c
- libraries/abstractions/common_io/test/test_iot_usb_device.c
Add iot usb device test.
Description
-----------
Checklist:
----------
> Add iot usb device test.

- libraries/freertos_plus/standard/freertos_plus_tcp_multi/include/FreeRTOSIPConfigDefaults.h
- libraries/freertos_plus/standard/freertos_plus_tcp_multi/include/FreeRTOS_IP.h
- libraries/freertos_plus/standard/freertos_plus_tcp_multi/include/FreeRTOS_IP_Private.h
- libraries/freertos_plus/standard/freertos_plus_tcp_multi/include/FreeRTOS_ND.h
- libraries/freertos_plus/standard/freertos_plus_tcp_multi/include/FreeRTOS_Routing.h
- libraries/freertos_plus/standard/freertos_plus_tcp_multi/include/FreeRTOS_Sockets.h
- libraries/freertos_plus/standard/freertos_plus_tcp_multi/include/FreeRTOS_TCP_IP.h
- libraries/freertos_plus/standard/freertos_plus_tcp_multi/source/BufferTesting.c
- libraries/freertos_plus/standard/freertos_plus_tcp_multi/source/FreeRTOS_ARP.c
- libraries/freertos_plus/standard/freertos_plus_tcp_multi/source/FreeRTOS_DHCP.c
- libraries/freertos_plus/standard/freertos_plus_tcp_multi/source/FreeRTOS_DNS.c
- libraries/freertos_plus/standard/freertos_plus_tcp_multi/source/FreeRTOS_IP.c
- libraries/freertos_plus/standard/freertos_plus_tcp_multi/source/FreeRTOS_ND.c
- libraries/freertos_plus/standard/freertos_plus_tcp_multi/source/FreeRTOS_Routing.c
- libraries/freertos_plus/standard/freertos_plus_tcp_multi/source/FreeRTOS_Sockets.c
- libraries/freertos_plus/standard/freertos_plus_tcp_multi/source/FreeRTOS_TCP_IP.c
- libraries/freertos_plus/standard/freertos_plus_tcp_multi/source/FreeRTOS_TCP_WIN.c
- libraries/freertos_plus/standard/freertos_plus_tcp_multi/source/FreeRTOS_UDP_IP.c
- libraries/freertos_plus/standard/freertos_plus_tcp_multi/source/portable/NetworkInterface/Common/phyHandling.c
- libraries/freertos_plus/standard/freertos_plus_tcp_multi/source/portable/NetworkInterface/STM32Fxx/NetworkInterface.c
Description
-----------
Merged PR 1197 into this branch.
Applied the latest PC-LINT / MISRA 2012 on all source files
Repaired FreeRTOS_ARP: it would not work for devices on the LAN: now repaired
Checklist:
----------
> Sept 18, took over PR 1197, applied PC-LINT / MISRA 2012, repaired FreeRTOS_ARP

- libraries/abstractions/common_io/test/test_iot_uart.c
Used semaphores instead of task delay for UART cancel test.
Description
-----------
Checklist:
----------
> Used semaphores instead of task delay for UART cancel test.

- libraries/abstractions/common_io/include/iot_i2c.h
Description
-----------
- add detailed API document to i2c
- format
Checklist:
----------
> add detailed API document to i2c

- libraries/abstractions/ble_hal/test/include/iot_test_ble_hal_afqp.h
- libraries/abstractions/ble_hal/test/include/iot_test_ble_hal_common.h
- libraries/abstractions/ble_hal/test/src/iot_test_ble_hal_afqp.c
- libraries/abstractions/ble_hal/test/src/iot_test_ble_hal_common.c
- libraries/abstractions/ble_hal/test/src/iot_test_ble_hal_integration.c
- tests/bleTestsScripts/startTests_integration.py
- tests/bleTestsScripts/testClass.py
Description
-----------
Checklist:
----------
> Ble test zshijing

- freertos_kernel/croutine.c
- freertos_kernel/include/StackMacros.h
- freertos_kernel/include/croutine.h
- freertos_kernel/include/stdint.readme
- freertos_kernel/readme.txt
Description
-----------
As subject. Source of truth: SVN 2720. 
Once this PR is merged, to be checked in Jenkins that croutine.{c, h} are not causing issue. 
Checklist:
----------
> Adding files in FreeRTOS SVN but not in GitHub

- libraries/freertos_plus/standard/freertos_plus_tcp/source/portable/BufferManagement/BufferAllocation_2.c
Let pxGetNetworkBufferWithDescriptor check if the counting semaphore has been created (again)
-----------
I submitted this PR before as  [#674](https://github.com/aws/amazon-freertos/pull/674). To void branch conflicts, I will sresubmit it here:
When a user tries to get a Network Buffer before the IP-task has been started, the function `pxGetNetworkBufferWithDescriptor()` might crash.
`BufferAllocation_1.c` already checks if the semaphore has been created, let `BufferAllocation_2.c` do the same check.
It was first reported [on the forum](https://sourceforge.net/p/freertos/discussion/382005/thread/a93c19999d/?limit=25#02be)
It was already reviewed by  @dcgaws and @dan4thewin
Checklist:
----------
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute …
> BufferAllocation_2.c : extra check in xNetworkBufferSemaphore()

- libraries/abstractions/common_io/include/iot_i2c.h
Description
-----------
Enhanced I2C API doc
Checklist:
----------
> Enhanced I2C API doc

- CHANGELOG.md
ChangeLog update for PUT and POST in HTTPS Client.
Checklist:
----------
> ChangeLog update for PUT and POST in HTTPS Client.

- doc/generate_doc.sh
- doc/guidance.md
Add script to generate all doxygen docs.
Description
-----------
This script generates all of the doxygen for the repo. I added instructions in the guidance. Running each of the doxygen commands is tedious. 
This script was taken from the CSDK.
Checklist:
----------
> Add script to generate all doxygen docs.

- demos/dev_mode_key_provisioning/src/aws_dev_mode_key_provisioning.c
- demos/include/aws_clientcredential.h
- libraries/freertos_plus/standard/tls/src/iot_tls.c
- vendors/microchip/boards/secure_element/aws_demos/config_files/aws_ota_agent_config.h
- vendors/microchip/secure_elements/lib/atcacert/atcacert_def.c
- vendors/microchip/secure_elements/lib/pkcs11/pkcs11_init.c
Bug fixes include provisioning and runtime changes from AWS and Microchip integration testing.
> Merge bug fixes into ECC608 feature branch

- CHANGELOG.md
This change adds the Infineon XMC4800 IoT Connectivity Kit with OPTIGA Trust X to the change log.
> Add the OPTIGA Trust X board to the change log.

- tools/ota_e2e_tests/aws_ota_test/aws_ota_project.py
Description
-----------
Checklist:
----------
> Fix a build log issue in OTA E2E tests

- libraries/abstractions/ble_hal/test/include/iot_test_ble_hal_common.h
- tests/include/iot_config_common.h
ble_hal test cases header file abstraction
Description
-----------
For ble_hal test cases, header file abstraction is needed
Checklist:
----------
> ble_hal test cases header file abstraction

- vendors/infineon/boards/xmc4800_plus_optiga_trust_x/CMakeLists.txt
Description
-----------
Checklist:
----------
> Fix Infineon Optiga Trust X CMake metadata

- vendors/espressif/boards/esp32/ports/ble/nimble/iot_ble_hal_common_gap.c
- vendors/espressif/boards/esp32/ports/ble/nimble/iot_ble_hal_gatt_server.c
- vendors/espressif/boards/esp32/ports/ble/nimble/iot_ble_hal_internals.h
AFR: NimBLE - Ensure that a GATT request is valid in prvBTSendResponse()
Checklist:
----------
> AFR: NimBLE - Ensure that a GATT request is valid in prvBTSendResponse()

- libraries/abstractions/common_io/include/iot_i2c.h
- libraries/abstractions/common_io/include/iot_uart.h
Description
-----------
enhance API doc for uart
Checklist:
----------
> enhance API doc for uart

- CHANGELOG.md
Update BLE Changelog
Description
-----------
Checklist:
----------
> Update BLE Changelog for upcoming release

- libraries/abstractions/common_io/include/iot_adc.h
Improving ADC api documentation
Why: ADC header needed clarification on proper use of return codes,
and on what data types to expect for some of the api's.
Checklist:
----------
> docs: Improve ADC api documentation

- vendors/nuvoton/boards/numaker_iot_m487_wifi/aws_demos/config_files/FreeRTOSConfig.h
Description
-----------
Reduce heap size to allow HTTPS demo build on Nutovon. 
Checklist:
----------
> Nuvoton - reduce heap size

- libraries/c_sdk/standard/ble/include/iot_ble_config_defaults.h
Update doc for MQTT GATT service flag
Description
-----------
Doc update to make it more clear on the purpose of the flag.
Checklist:
----------
> [BLE] Update doc for MQTT GATT service flag

- libraries/abstractions/common_io/test/test_iot_i2c.c
Description
-----------
remove read tests whose behavior is not defined by I2C standard.
Checklist:
----------
> remove read tests whose behavior is not defined by I2C standard.

- libraries/abstractions/common_io/include/iot_uart.h
- libraries/abstractions/common_io/test/test_iot_uart.c
Description
Improve iot_uart.h with enum
-----------
Checklist:
----------
> Improve iot_uart.h with enum

- libraries/abstractions/common_io/include/iot_flash.h
- libraries/abstractions/common_io/include/iot_gpio.h
Improve header file documentation for Flash and GPIo APIs
Why:  There is need to clarify some of the data types and return
values used in many of the APIs
@lundinc2 , @qiutongs 
Checklist:
----------
> docs: Improve documentation for Flash and GPIO APIs

- demos/dev_mode_key_provisioning/README.md
- demos/dev_mode_key_provisioning/src/aws_dev_mode_key_provisioning.c
- libraries/abstractions/pkcs11/test/iot_test_pkcs11.c
- vendors/infineon/boards/xmc4800_plus_optiga_trust_x/aws_demos/config_files/iot_pkcs11_config.h
- vendors/infineon/boards/xmc4800_plus_optiga_trust_x/aws_tests/config_files/iot_pkcs11_config.h
Rationalize key import policy settings. Fix public key slot location. Improve key provisioning flow.
> Fix provisioning and key import policy on OPTIGA.

- libraries/abstractions/common_io/test/test_iot_uart.c
- libraries/abstractions/common_io/test/test_scripts/test_iot_assisted_tests.py
- libraries/abstractions/common_io/test/test_scripts/uart/test_iot_runonPI_uart.sh
- libraries/abstractions/common_io/test/test_scripts/uart/test_iot_uart_rp3.py
- libraries/abstractions/common_io/test/test_scripts/uart/test_iot_uart_test.py
Added UART assisted test RPI scripts
Description
-----------
Checklist:
----------
> Added UART assisted test RPI scripts

- CHANGELOG.md
- demos/defender/aws_iot_demo_defender.c
- libraries/c_sdk/aws/defender/src/aws_iot_defender_api.c
- libraries/c_sdk/aws/defender/test/aws_iot_tests_defender_api.c
Added defender changes to changelog and some code cleanup.
Description
-----------
Checklist:
----------
> chore: update changelog for defender and cleanup.

- libraries/abstractions/common_io/test/test_iot_spi.c
Description
-----------
Checklist:
----------
> Added test_iot_internal.h to spi tests.

- libraries/abstractions/common_io/include/iot_power.h
Clarify return values and improve documentation
Why:  We need to clarify what return codes are acceptible for
each API, and improve the overall documentation regarding the
low level Power APIs.
@qiutongs , @lundinc2 :  Please review
Checklist:
----------
> docs: Improve documentation for Power APIs

- vendors/marvell/boards/mw300_rd/aws_demos/config_files/FreeRTOSConfig.h
- vendors/marvell/boards/mw300_rd/aws_tests/config_files/FreeRTOSConfig.h
Description
-----------
cherry picking #1382 into release-candidate.
Checklist:
----------
> Fixing taskpool on marvell

- libraries/abstractions/ble_hal/test/ble_test_scipts/testClass.py
- libraries/abstractions/ble_hal/test/ble_test_scipts/testutils.py
- libraries/abstractions/ble_hal/test/include/iot_test_ble_hal_afqp.h
- libraries/abstractions/ble_hal/test/include/iot_test_ble_hal_common.h
- libraries/abstractions/ble_hal/test/include/iot_test_ble_hal_integration.h
- libraries/abstractions/ble_hal/test/src/iot_test_ble_hal_afqp.c
- libraries/abstractions/ble_hal/test/src/iot_test_ble_hal_common.c
- libraries/abstractions/ble_hal/test/src/iot_test_ble_hal_integration.c
- vendors/nordic/boards/nrf52840-dk/ports/ble/iot_ble_hal_gap.c
- vendors/nordic/boards/nrf52840-dk/ports/ble/iot_ble_hal_gatt_server.c
Description
-----------
Add Callback NULL Check test & add included service test& Long Write test & secondary service test. Add macros to disable/enable them.
Checklist:
----------
> Add test cases

- libraries/abstractions/common_io/include/iot_spi.h
Description
-----------
enhance API doc for SPI
Checklist:
----------
> enhance API doc for SPI

- libraries/abstractions/common_io/include/iot_timer.h
Improve the documentation on iot_timer APIs
Why:  Need to clarify parameters going into the APIs and
what the expected return values are for each.
Checklist:
----------
> docs: Improve documentation on iot_timer APIs

- libraries/abstractions/common_io/include/iot_tsensor.h
- libraries/abstractions/common_io/include/iot_watchdog.h
Improve the documentation on the tsensor and watchdog APIs
Why:  We needed to clarify parameter types for the various ioctls
as well as return codes for each API.
Checklist:
----------
> docs: Improve documentation on tsensor and watchdog APIs

- libraries/c_sdk/aws/defender/include/aws_iot_defender.h
- libraries/c_sdk/aws/defender/src/aws_iot_defender_api.c
Defender: cleaned up doxygen comments and parameter validation.
Description
-----------
Checklist:
----------
> chore: Defender doxygen comments cleanup.

- libraries/abstractions/common_io/include/iot_i2s.h
Improve the overall documentation on the iot_i2s APIs
Why:  We needed to clarify data types, and return values for
all of the iot_i2s APIs
@lundinc2, @qiutongs 
Checklist:
----------
> docs: Improve documentation on iot_i2s APIs

- doc/config/common_io
- libraries/abstractions/common_io/include/iot_i2c.h
Description
-----------
add doxygen config and fix header syntax
Checklist:
----------
> add doxygen config and fix header syntax

- libraries/abstractions/common_io/include/iot_uart.h
Description
-----------
add uart code example in header
Checklist:
----------
> add uart code example in header

- CMakeLists.txt
- tools/cmake/afr.cmake
Description
-----------
Checklist:
----------
> Versioning update and Cmake auto submodule download

- vendors/microchip/boards/ecc608a_plus_winsim/ecc608a_plus_winsim.cmake
Description
-----------
Changing it to match Microchip convention
Checklist:
----------
> ECC608A console display name change

- CONTRIBUTING.md
Description
-----------
Add coding style guide section to contributing doc
Checklist:
----------
> Coding style guide in contributing doc

- libraries/abstractions/common_io/test/test_iot_i2s.c
Adding unit tests for iot_i2s APIs
Why:  We need to have comprehensive unit tests for all of the LL-Hal
APIs, including i2s
@qiutongs @lundinc2 
Checklist:
----------
> test: adding tests for iot_i2s APIs

- vendors/cypress/boards/CYW943907AEVAL1F/ports/pkcs11/hw_poll.c
- vendors/cypress/boards/CYW954907AEVAL1F/ports/pkcs11/hw_poll.c
- vendors/marvell/boards/mw300_rd/ports/pkcs11/iot_pkcs11_pal.c
- vendors/nuvoton/boards/numaker_iot_m487_wifi/aws_demos/application_code/nuvoton_code/entropy_hardware_poll.c
- vendors/nuvoton/boards/numaker_iot_m487_wifi/aws_tests/application_code/nuvoton_code/entropy_hardware_poll.c
- vendors/renesas/amazon_freertos_common/entropy_hardware_poll.c
Description
-----------
Checklist:
----------
> RNG warning wording update

- vendors/cypress/boards/CYW943907AEVAL1F/ports/pkcs11/hw_poll.c
- vendors/cypress/boards/CYW954907AEVAL1F/ports/pkcs11/hw_poll.c
- vendors/marvell/boards/mw300_rd/ports/pkcs11/iot_pkcs11_pal.c
- vendors/nuvoton/boards/numaker_iot_m487_wifi/aws_demos/application_code/nuvoton_code/entropy_hardware_poll.c
- vendors/nuvoton/boards/numaker_iot_m487_wifi/aws_tests/application_code/nuvoton_code/entropy_hardware_poll.c
- vendors/renesas/amazon_freertos_common/entropy_hardware_poll.c
Description
-----------
Checklist:
----------
> RNG warning re-wording

- libraries/abstractions/common_io/test/test_iot_uart.c
Fixing bug in ioctl testing of iot_uart APIs
Why:  Existing test was trying to test for config values changing
when calling ioctl xUartSetConfig without first setting the value
to a known state.  This test would falsely fail if the value being
changed to happen to match with the previous value.  The fix is
to set the config to a set of known values first, and then one by
one change each parameter, and confirm.
Checklist:
----------
> test: Fix bug in testing of iot_uart APIs

- vendors/nordic/boards/nrf52840-dk/CMakeLists.txt
Description
-----------
Checklist:
----------
> Move bootloader build after metadata mode check

- CHANGELOG.md
Description
-----------
Nordic now support CMake builds for demos and tests.
Checklist:
----------
> Add nordic cmake support to changelog

- CHANGELOG.md
- libraries/3rdparty/lwip/src/include/lwip/sys.h
- libraries/3rdparty/lwip/src/portable/arch/lwipopts_freertos.h
- libraries/3rdparty/lwip/src/portable/arch/sys_arch.c
- libraries/3rdparty/lwip/src/portable/arch/sys_arch.h
Add commit from master to release-candidate
> Implement LWIP_NETCONN_SEM_PER_THREAD and LWIP_NETCONN_FULLDUPLEX

- tools/cmake/afr.cmake
- vendors/infineon/boards/xmc4800_iotkit/CMakeLists.txt
- vendors/infineon/boards/xmc4800_plus_optiga_trust_x/CMakeLists.txt
- vendors/nordic/boards/nrf52840-dk/CMakeLists.txt
- vendors/nxp/boards/lpc54018iotmodule/CMakeLists.txt
Description
-----------
- Auto submodule download when building through CMake
- Fix metadata for OCW Console
Checklist:
----------
>  Bring in CMake changes from release-candidate 

- libraries/abstractions/ble_hal/CMakeLists.txt
- libraries/abstractions/ble_hal/test/ble_test_scipts/startTests_afqp.py
- libraries/abstractions/ble_hal/test/ble_test_scipts/startTests_integration.py
- libraries/abstractions/ble_hal/test/ble_test_scipts/testClass.py
- libraries/abstractions/ble_hal/test/include/iot_test_ble_hal_common.h
- libraries/abstractions/ble_hal/test/include/iot_test_ble_hal_config_defaults.h
- libraries/abstractions/ble_hal/test/include/iot_test_ble_hal_integration.h
- libraries/abstractions/ble_hal/test/src/iot_test_ble_hal_afqp.c
- libraries/abstractions/ble_hal/test/src/iot_test_ble_hal_common.c
- libraries/abstractions/ble_hal/test/src/iot_test_ble_hal_integration.c
- libraries/abstractions/ble_hal/test/src/iot_test_ble_hal_stress_test.c
Description
-----------
- Add "add characteristic in Callback" test
- revise long write test
- individualize each test cases
Checklist:
----------
> Add "add characteristic in Callback" test

- CHANGELOG.md
- libraries/3rdparty/lwip/src/include/lwip/sys.h
- libraries/3rdparty/lwip/src/portable/arch/lwipopts_freertos.h
- libraries/3rdparty/lwip/src/portable/arch/sys_arch.c
- libraries/3rdparty/lwip/src/portable/arch/sys_arch.h
This reverts commit 2f4cf42aa3bd06ad0721325af0c008e3f77415e9 due to the introduced MediaTek regression.
> Revert "Implement LWIP_NETCONN_SEM_PER_THREAD... (#1447)"

- vendors/nordic/boards/nrf52840-dk/ports/ble/iot_ble_hal_gap.c
Description
-----------
Company ID is a separate field in ble_advdata_manuf_data_t struct which was being set as uninitialized (or 0x0000) inside prvBTAdvDataConvert() of AFR's BLE port for Nordic. First two octets of manufacturer specific data are used as company identifier. Nordic SDK's  struct ble_advdata_manuf_data_t has two fields company_identifier and data. Previously only data field was being set as manufacturer specific data inside function prvBTAdvDataConvert() and it was ignoring company_identifier field and BLE clients were receiving the company id as 0x0000.
Checklist:
----------
> Set missing company identifier in BLE Adv data for Nordic

- CHANGELOG.md
Description
-----------
Checklist:
----------
> Add release version and date to chaneglog

- vendors/microchip/secure_elements/app/example_trust_chain_tool/README.md
- vendors/microchip/secure_elements/app/example_trust_chain_tool/docs/policy_template.json
Description
-----------
Checklist:
----------
> Update ECC608a+WinSim getting started instructions

- CHANGELOG.md
Description
-----------
Checklist:
----------
> Add freertos kernel submodule to changelog

- libraries/c_sdk/standard/ble/include/iot_ble_mqtt_serialize.h
Fixes #1472
Description
-----------
* Fix documentation to change from JSON to CBOR.
* Make documentation more clear.
Checklist:
----------
> Fix MQTT BLE documentation

- demos/dev_mode_key_provisioning/src/aws_dev_mode_key_provisioning.c
Description
-----------
Checklist:
----------
> Resolve merge conflict in aws_dev_mode_key_provisioning.c

- libraries/abstractions/common_io/test/test_iot_main.c
- libraries/abstractions/common_io/test/test_iot_tsensor.c
- libraries/abstractions/common_io/test/test_scripts/test_iot_assisted_tests.py
- libraries/abstractions/common_io/test/test_scripts/tsensor/test_iot_runonPI_tsensor.sh
- libraries/abstractions/common_io/test/test_scripts/tsensor/test_iot_tsensor_rp3.py
- libraries/abstractions/common_io/test/test_scripts/tsensor/test_iot_tsensor_test.py
Description
-----------
Add tsensor assisted test.
Checklist:
----------
> Add tsensor assisted test.

- libraries/freertos_plus/standard/freertos_plus_tcp/include/FreeRTOSIPConfigDefaults.h
- libraries/freertos_plus/standard/freertos_plus_tcp/source/FreeRTOS_DNS.c
- libraries/freertos_plus/standard/freertos_plus_tcp/source/FreeRTOS_UDP_IP.c
- tools/cbmc/patches/0001-Remove-static-storage-class-from-entry-points.patch
- tools/cbmc/proofs/DNS/DNSHandlePacket/DNShandlePacket_harness.c
- tools/cbmc/proofs/DNS/DNSgetHostByName/DNSgetHostByName_harness.c
- tools/cbmc/proofs/DNS/DNSgetHostByName_a/DNSgetHostByName_a_harness.c
- tools/cbmc/proofs/ParseDNSReply/ParseDNSReply_harness.c
Description
-----------
This PR replaces [#1195](https://github.com/aws/amazon-freertos/pull/1195).
That PR had merging problems and it was hard to get it rebased.
My GIT client ( SmartGit ) has problems switching between old and new branches, since `/freertos_kernel` has become a link to a different repo.
Checklist:
----------
Oops, I automatically filled in two crosses [x]. The patch was tested within the earlier repo, not yet in the latest ( ever-changing ) release of software. I will test the change on both PC and an ST board.
Hein
> FreeRTOS_DNS : changes to make asynchronous lookup work, version 4

- tools/cbmc/proofs/prepare.py
The prepare.py script under tools/cbmc is run during CI (and only for
the CBMC proofs) to prepare the source tree for checking the CBMC
proofs.  Under tools/cbmc it generates Makefiles and build
configurations to check. In the source tree generally it makes minor
changes to the source code like removing static attributes from
functions under test.
This patch adds to release-candidate the prepare.py from master.
> Restart CBMC proofs on merges and pull requests to release-candidate.

- vendors/nordic/boards/nrf52840-dk/CMakeLists.txt
Description
-----------
Checklist:
----------
> Fix Nordic Metadata mode

- libraries/abstractions/common_io/test/test_iot_main.c
- libraries/abstractions/common_io/test/test_iot_pwm.c
- libraries/abstractions/common_io/test/test_scripts/pwm/test_iot_pwm_rp3.py
- libraries/abstractions/common_io/test/test_scripts/pwm/test_iot_pwm_test.py
- libraries/abstractions/common_io/test/test_scripts/pwm/test_iot_runonPI_pwm.sh
Description
-----------
Modify pwm test input pin to a different one. It was conflict with gpio test before.  
Checklist:
----------
> Modify pwm test input pin to a different one. 

- vendors/espressif/boards/esp32/ports/ble/nimble/iot_ble_hal_common_gap.c
Handle adv complete event in AFR
Checklist:
----------
> NimBLE - Handle adv complete event in AFR

- vendors/microchip/boards/ecc608a_plus_winsim/aws_tests/config_files/iot_pkcs11_config.h
Description
-----------
Checklist:
----------
> Import private keys = 1 in ECC test project

- vendors/espressif/boards/esp32/ports/ble/nimble/iot_ble_hal_common_gap.c
Facilitate enable-disable cycle
Checklist:
----------
> AFR: NimBLE - Facilitate enable-disable cycle

- libraries/freertos_plus/standard/pkcs11/src/iot_pkcs11.c
- libraries/freertos_plus/standard/utils/src/iot_pki_utils.c
Using a third party static analysis tool a possible NULL de-reference was found and also possible usage of a NULL checked pointer was found. Fixes are found in this PR.
I then checked the rest of the file and took to the liberty of helping with other error checks. 
Checklist:
----------
> PKCS #11 support: Fix error checks and possible NULL de-references

- libraries/abstractions/common_io/test/test_iot_main.c
- libraries/abstractions/common_io/test/test_iot_usb_device.c
- libraries/abstractions/common_io/test/test_scripts/test_iot_test_template.py
- libraries/abstractions/common_io/test/test_scripts/usb_device/test_iot_usb_device_test.py
Description
-----------
Add assisted tests for usb interrupt type device.
Checklist:
----------
> Add assisted tests for usb interrupt type device.

- libraries/abstractions/ble_hal/include/bt_hal_manager_adapter_ble.h
- libraries/c_sdk/standard/ble/include/iot_ble.h
Fix BLE HAL documentation
Description
-----------
Referencing #1514 
Checklist:
----------
> Fix BLE HAL documentation

- projects/espressif/esp32/make/aws_demos/README.md
- projects/espressif/esp32/make/aws_demos/esp-solo-1.cfg
Description
-----------
Add file for ESP-DevKitC-S1 OpenOCD configuration.
Checklist:
----------
> Add file for ESP-DevKitC-S1 OpenOCD configuration.

- libraries/abstractions/ble_hal/test/ble_test_scipts/bleAdapter.py
- libraries/abstractions/ble_hal/test/ble_test_scipts/startTests_integration.py
- libraries/abstractions/ble_hal/test/ble_test_scipts/testClass.py
- libraries/abstractions/ble_hal/test/ble_test_scipts/testutils.py
- libraries/abstractions/ble_hal/test/include/iot_test_ble_hal_common.h
- libraries/abstractions/ble_hal/test/include/iot_test_ble_hal_config_defaults.h
- libraries/abstractions/ble_hal/test/src/iot_test_ble_hal_afqp.c
- libraries/abstractions/ble_hal/test/src/iot_test_ble_hal_common.c
- libraries/abstractions/ble_hal/test/src/iot_test_ble_hal_integration.c
Description
-----------
1. add check bond state test
2. revise add characteristic in callback test
3. add macros to disable/enable test cases
Checklist:
----------
> add check bond state test

- vendors/st/stm32l475_discovery/BSP/Components/es_wifi/es_wifi.c
> Updated ES-WiFi driver to fix compile bug

- libraries/abstractions/common_io/include/iot_spi.h
- libraries/abstractions/common_io/test/test_iot_main.c
- libraries/abstractions/common_io/test/test_iot_spi.c
- libraries/abstractions/common_io/test/test_scripts/spi_master/test_iot_spi_master_pyb.sh
- libraries/abstractions/common_io/test/test_scripts/spi_master/test_iot_spi_master_test.py
Description
-----------
Add spi master assisted test.
The reference board is a pyboard instead of raspberry pi.
https://www.digikey.com/product-detail/en/adafruit-industries-llc/2390/1528-1565-ND/5824409
Checklist:
----------
> Add spi master assisted test.

- libraries/abstractions/common_io/test/test_scripts/tsensor/test_iot_tsensor_test.py
Description
-----------
Fix a typo in the tesensor test script.
Checklist:
----------
> Fix a typo in the tesensor test script.

- vendors/espressif/boards/esp32/ports/ble/nimble/iot_ble_hal_gap.c
Add support of slave connection interval range in advertisement data
Checklist:
----------
> AFR : NimBLE - Add support of slave connection interval range

- vendors/renesas/boards/rx65n-rsk/aws_demos/config_files/FreeRTOSConfig.h
Description
-----------
Checklist:
----------
> Corrected under clocked Renesas demo project clock speeds.

- libraries/abstractions/common_io/test/test_scripts/test_iot_assisted_tests.py
- libraries/abstractions/common_io/test/test_scripts/uart/test_iot_runonPI_uart.sh
- libraries/abstractions/common_io/test/test_scripts/uart/test_iot_uart_rp3.py
- libraries/abstractions/common_io/test/test_scripts/uart/test_iot_uart_test.py
Description
-----------
- Add UART assisted tests
Checklist:
----------
> Add UART assisted tests

- demos/demo_runner/iot_demo_freertos.c
Description
-----------
Checklist:
----------
> Reduce collision chance when parsing demo output.

- vendors/st/boards/stm32l475_discovery/aws_tests/config_files/test_iot_config.h
- vendors/st/boards/stm32l475_discovery/ports/common_io/test_iot_internal.c
Description
-----------
Checklist:
----------
> Added frequency and dummy value config.

- libraries/abstractions/common_io/CMakeLists.txt
- libraries/abstractions/common_io/include/iot_adc.h
- libraries/abstractions/common_io/include/iot_battery.h
- libraries/abstractions/common_io/include/iot_efuse.h
- libraries/abstractions/common_io/include/iot_flash.h
- libraries/abstractions/common_io/include/iot_gpio.h
- libraries/abstractions/common_io/include/iot_hw.h
- libraries/abstractions/common_io/include/iot_i2c.h
- libraries/abstractions/common_io/include/iot_i2s.h
- libraries/abstractions/common_io/include/iot_perfcounter.h
- libraries/abstractions/common_io/include/iot_power.h
- libraries/abstractions/common_io/include/iot_pwm.h
- libraries/abstractions/common_io/include/iot_reset.h
- libraries/abstractions/common_io/include/iot_rtc.h
- libraries/abstractions/common_io/include/iot_spi.h
- libraries/abstractions/common_io/include/iot_timer.h
- libraries/abstractions/common_io/include/iot_tsensor.h
- libraries/abstractions/common_io/include/iot_uart.h
- libraries/abstractions/common_io/include/iot_usb_device.h
- libraries/abstractions/common_io/include/iot_watchdog.h
- libraries/abstractions/common_io/test/iot_test_common_io.c
- libraries/abstractions/common_io/test/test_iot_i2c.c
- libraries/abstractions/common_io/test/test_iot_internal.h
- libraries/abstractions/common_io/test/test_iot_spi.c
- libraries/abstractions/common_io/test/test_iot_uart.c
Description
-----------
1. All peripheral headers
2. Tests for I2C, UART, SPI
This is a copy from feature/common-io branch with formatting and small changes on CMakeList.txt
Checklist:
----------
> Initial merge of Common IO libraries and tests

- CMakeLists.txt
Description
-----------
revert recent changes on CMakeLists.txt which failed cmake build
Related PR: revert recent changes on CMakeLists.txt which failed cmake build
Checklist:
----------
> revert recent changes on CMakeLists.txt which failed cmake build

- libraries/abstractions/common_io/test/iot_test_common_io.c
- libraries/abstractions/common_io/test/test_iot_spi.c
- libraries/abstractions/common_io/test/test_iot_uart.c
…tests
Description
-----------
- support running common tests on multiple instances
- fix SPI tests: IOT_SPI_MASTER_NOT_INITIALIZED return code was removed
- fix UART tests: not assert in ISR context
Checklist:
----------
> support running common tests on multiple instances

- libraries/abstractions/common_io/test/test_iot_spi.c
- libraries/abstractions/common_io/test/test_scripts/adc/test_iot_adc_rp3.py
- libraries/abstractions/common_io/test/test_scripts/adc/test_iot_adc_test.py
- libraries/abstractions/common_io/test/test_scripts/adc/test_iot_runonPI_adc.sh
- libraries/abstractions/common_io/test/test_scripts/gpio/test_iot_gpio_rp3.py
- libraries/abstractions/common_io/test/test_scripts/gpio/test_iot_gpio_test.py
- libraries/abstractions/common_io/test/test_scripts/pwm/test_iot_pwm_test.py
- libraries/abstractions/common_io/test/test_scripts/spi_master/test_iot_spi_master_test.py
- libraries/abstractions/common_io/test/test_scripts/test_iot_assisted_tests.py
- libraries/abstractions/common_io/test/test_scripts/tsensor/test_iot_tsensor_test.py
Description
-----------
Set fixed serial baudrate.
Update spi tests with a dedicated instance.
Update copyright for all the scripts.
Checklist:
----------
> Updates for assisted tests

- .gitattributes
Description
-----------
To prevent CRLF and LF confusion during git checkout and commit of html and css files.
Resolves: TS-10066 
Checklist:
----------
> Add *.html and *.css as text in .gitattributes

- libraries/freertos_plus/aws/ota/test/aws_ota_agent_test_access_declare.h
- libraries/freertos_plus/aws/ota/test/aws_ota_agent_test_access_define.h
- libraries/freertos_plus/aws/ota/test/aws_test_ota_agent.c
- libraries/freertos_plus/aws/ota/test/aws_test_ota_cbor.c
Description
-----------
- Add some detailed messages in OTA tests.
- Fix and renamed a failed test.
Checklist:
----------
> More OTA fixes

- libraries/abstractions/common_io/test/test_iot_spi.c
Description
-----------
The instance arguments for slave select api were not changed in the
previous commit.
Checklist:
----------
> Modify spi instance variable in the asssited test.

- libraries/abstractions/ble_hal/include/bt_hal_manager.h
- libraries/abstractions/ble_hal/include/bt_hal_manager_adapter_ble.h
- libraries/abstractions/ble_hal/test/include/iot_test_ble_hal_common.h
- libraries/abstractions/ble_hal/test/src/iot_test_ble_hal_common.c
- libraries/c_sdk/standard/ble/src/iot_ble_gap.c
- vendors/espressif/boards/esp32/ports/ble/bluedroid/iot_ble_hal_common_gap.c
- vendors/espressif/boards/esp32/ports/ble/bluedroid/iot_ble_hal_gatt_server.c
- vendors/espressif/boards/esp32/ports/ble/nimble/iot_ble_hal_common_gap.c
- vendors/espressif/boards/esp32/ports/ble/nimble/iot_ble_hal_gap.c
- vendors/espressif/boards/esp32/ports/ble/nimble/iot_ble_hal_gatt_server.c
- vendors/nordic/boards/nrf52840-dk/ports/ble/iot_ble_hal_gap.c
- vendors/nordic/boards/nrf52840-dk/ports/ble/iot_ble_hal_gatt_server.c
BLE Hal API modifications
Description
-----------
* Change advertisement timeout to 16 bit value as per spec, handle this in ESP and nordic.
* Implementation for pxConfigureMTU()
* Fix API pxAdvStatusCb() to pass adapter interface 
Checklist:
----------
> BLE Hal API modifications

- projects/ti/cc3220_launchpad/iar/aws_demos/aws_demos.ewp
Description
-----------
The TI IAR demo project was not updated in the previous OTA PR. It doesn't build with OTA demo enabled.
Update TI IAR project with automated tool.
Checklist:
----------
> update TI IAR project

- libraries/abstractions/ble_hal/include/bt_hal_manager.h
- libraries/abstractions/ble_hal/include/bt_hal_manager_adapter_ble.h
- libraries/abstractions/ble_hal/test/include/iot_test_ble_hal_common.h
- libraries/abstractions/ble_hal/test/src/iot_test_ble_hal_common.c
- libraries/c_sdk/standard/ble/src/iot_ble_gap.c
- vendors/espressif/boards/esp32/ports/ble/bluedroid/iot_ble_hal_common_gap.c
- vendors/espressif/boards/esp32/ports/ble/bluedroid/iot_ble_hal_gatt_server.c
- vendors/espressif/boards/esp32/ports/ble/nimble/iot_ble_hal_common_gap.c
- vendors/espressif/boards/esp32/ports/ble/nimble/iot_ble_hal_gap.c
- vendors/espressif/boards/esp32/ports/ble/nimble/iot_ble_hal_gatt_server.c
- vendors/nordic/boards/nrf52840-dk/ports/ble/iot_ble_hal_gap.c
- vendors/nordic/boards/nrf52840-dk/ports/ble/iot_ble_hal_gatt_server.c
BLE HAL modifications
Description
-----------
Cherry-pick master 1e1df661bfa169a5e885eae6f322f72c8f642473
Checklist:
----------
> BLE HAL modifications

- CHANGELOG.md
Change log update for BLE
Description
-----------
Updated change log for major changes.
Checklist:
----------
> Changelog update for BLE

- CHANGELOG.md
Description
-----------
Update change log for Nuvoton Ethernet and Common I/O library.
Checklist:
----------
> Update change log for Nuvoton Ethernet and Common I/O library.

- demos/ota/aws_iot_ota_update_demo.c
- libraries/freertos_plus/aws/ota/include/aws_iot_ota_agent.h
- libraries/freertos_plus/aws/ota/src/aws_iot_ota_agent.c
- libraries/freertos_plus/aws/ota/src/aws_iot_ota_interface.c
- libraries/freertos_plus/aws/ota/test/aws_test_ota_end_to_end.c
Description
-----------
OTA Agent State fixes and cleanup.
Checklist:
----------
> Fix: OTA Agent State handling and internal file close function

- vendors/espressif/esp-idf/tools/cmake/kconfig.cmake
Description
-----------
Fix issue #1589.
Checklist:
----------
> Fix an issue when AFR is in a CMake subdirectory

- vendors/infineon/boards/xmc4800_iotkit/aws_demos/config_files/aws_demo_config.h
- vendors/infineon/boards/xmc4800_plus_optiga_trust_x/aws_demos/config_files/aws_demo_config.h
- vendors/mediatek/boards/mt7697hx-dev-kit/aws_demos/config_files/aws_demo_config.h
- vendors/microchip/boards/curiosity_pic32mzef/aws_demos/config_files/aws_demo_config.h
- vendors/microchip/boards/ecc608a_plus_winsim/aws_demos/config_files/aws_demo_config.h
- vendors/nordic/boards/nrf52840-dk/aws_demos/config_files/aws_demo_config.h
- vendors/nuvoton/boards/numaker_iot_m487_wifi/aws_demos/config_files/aws_demo_config.h
- vendors/nxp/boards/lpc54018iotmodule/aws_demos/config_files/aws_demo_config.h
- vendors/pc/boards/windows/aws_demos/config_files/aws_demo_config.h
- vendors/st/boards/stm32l475_discovery/aws_demos/config_files/aws_demo_config.h
- vendors/ti/boards/cc3220_launchpad/aws_demos/config_files/aws_demo_config.h
- vendors/xilinx/boards/microzed/aws_demos/config_files/aws_demo_config.h
Added demo memory metrics to infineon, mediatek, microchip, nordic, nuvoton, nxp, xilinx.
Description
-----------
Checklist:
----------
> Add demo metrics to 9 boards

- vendors/espressif/docs/ESP-EYE_getting_started_with_AFR.md
README for ESP-EYE 
Description
-----------
README file for ESP-EYE, It contains getting started instructions with AFR. Its a part of DQP(Device Qualification Program).
Checklist:
----------
> Adding getting started README file for ESP-EYE

- vendors/nxp/boards/lpc54018iotmodule/aws_demos/config_files/FreeRTOSConfig.h
- vendors/nxp/boards/lpc54018iotmodule/aws_demos/config_files/aws_ota_agent_config.h
- vendors/nxp/boards/lpc54018iotmodule/aws_tests/config_files/aws_ota_agent_config.h
> Avoid "Error: No OTA data buffers available" on LPC54018

- CMakeLists.txt
Description
-----------
Update project version to 201912.00
Checklist:
----------
> Update project version to 201912.00

- CHANGELOG.md
Description
-----------
Update changelog for Greengrass V2.0.0
Checklist:
----------
> Update changelog for Greengrass

- CHANGELOG.md
Description
-----------
- Changelog for OTA.
- Fixed trailing whitespaces.
Checklist:
----------
> OTA changelog

- doc/config/ota
- libraries/freertos_plus/aws/ota/include/aws_iot_ota_agent.h
Description
-----------
Add a doxygen config for OTA and fix some doxygen comments.
Checklist:
----------
> Fix OTA doxygen

- libraries/abstractions/ble_hal/test/ble_test_scipts/startTests_integration.py
- libraries/abstractions/ble_hal/test/ble_test_scipts/testClass.py
- libraries/abstractions/ble_hal/test/include/iot_test_ble_hal_common.h
- libraries/abstractions/ble_hal/test/include/iot_test_ble_hal_config_defaults.h
- libraries/abstractions/ble_hal/test/src/iot_test_ble_hal_afqp.c
- libraries/abstractions/ble_hal/test/src/iot_test_ble_hal_common.c
- libraries/abstractions/ble_hal/test/src/iot_test_ble_hal_integration.c
- libraries/c_sdk/standard/ble/src/iot_ble_gap.c
Description
-----------
1. add test case to check pxConfigureMtu
2. add MtuChanged event & check MTU size
3. add argument to check specific field before get the callback from event queue
4. disable stopAdv while disconnected
5. make  longwrite&longread tests scalable
Checklist:
----------
> Add test case & fix issues

- demos/demo_runner/iot_demo_freertos.c
- tests/common/iot_test_freertos.c
- vendors/espressif/boards/esp32/aws_demos/config_files/iot_config.h
- vendors/espressif/boards/esp32/aws_tests/config_files/iot_config.h
- vendors/microchip/boards/ecc608a_plus_winsim/aws_demos/config_files/FreeRTOSConfig.h
- vendors/microchip/boards/ecc608a_plus_winsim/aws_tests/config_files/FreeRTOSConfig.h
- vendors/pc/boards/windows/aws_demos/config_files/FreeRTOSConfig.h
- vendors/pc/boards/windows/aws_tests/config_files/FreeRTOSConfig.h
Description
-----------
Checklist:
----------
> Added macro to disable common folder hooks

- libraries/abstractions/common_io/test/test_iot_gpio.c
Sync test_iot_gpio.c with iot branch
Description
See difference between AFR common-io and iot branch. Sync with iot branch.
Checklist:
----------
> Sync test_iot_gpio.c with iot branch

- README.md
Reword the ReadMe.md language for inline versus device catalog listed boards.
> Clarify description of console-tested versus IDT supported boards.

- libraries/abstractions/wifi/test/iot_test_wifi.c
Description
-----------
Unapologetically deleting WiFi test cases that don't do much. 
Checklist:
----------
> Unapologetically deleting WiFi test cases.

- tools/ota_e2e_tests/aws_ota_test/aws_ota_aws_agent.py
- tools/ota_e2e_tests/poetry.lock
- tools/ota_e2e_tests/pyproject.toml
Description
-----------
Don't wipe out the whole S3 bucket as this will cause data race when running in parallel. Instead just delete the files uploaded.
Checklist:
----------
> Only delete files uploaded in OTA E2E

- libraries/abstractions/common_io/test/test_scripts/adc/test_iot_adc_test.py
Description
-----------
Make up for pr https://github.com/aws/amazon-freertos/pull/1693.
Missed adc script.
Checklist:
----------
> Update for adc script

- libraries/freertos_plus/aws/ota/include/aws_iot_ota_agent.h
- libraries/freertos_plus/aws/ota/src/aws_iot_ota_agent_internal.h
- libraries/freertos_plus/aws/ota/src/http/aws_iot_ota_http.c
- libraries/freertos_plus/aws/ota/src/mqtt/aws_iot_ota_mqtt.c
Description
-----------
Addressing compiler warnings in OTA.
Checklist:
----------
> Fix compiler warnings in OTA

- libraries/abstractions/common_io/include/iot_battery.h
- libraries/abstractions/common_io/include/iot_rtc.h
- libraries/abstractions/common_io/include/iot_spi.h
- libraries/abstractions/common_io/include/iot_tsensor.h
- libraries/abstractions/common_io/include/iot_uart.h
- libraries/abstractions/common_io/test/test_iot_i2c.c
- libraries/abstractions/common_io/test/test_iot_spi.c
- libraries/abstractions/common_io/test/test_iot_uart.c
Description
-----------
Copy latest code change in feature/common-io.
For detailed commit history, please look at feature/common-io branch
Checklist:
----------
> Copy latest code change from feature/common-io

- tools/aws_config_quick_start/SetupAWS.py
- tools/aws_config_quick_start/certs.py
- tools/aws_config_quick_start/misc.py
- tools/aws_config_quick_start/policy.py
- tools/aws_config_quick_start/thing.py
Description
-----------
Happy path of quick start script lacked visual feedback.
Checklist:
----------
> Added additional logs to AWS quick start scripts.

- demos/dev_mode_key_provisioning/src/aws_dev_mode_key_provisioning.c
- vendors/st/boards/stm32l475_discovery/aws_demos/config_files/iot_pkcs11_config.h
- vendors/ti/boards/cc3220_launchpad/aws_demos/config_files/iot_pkcs11_config.h
- vendors/ti/boards/cc3220_launchpad/aws_tests/config_files/iot_pkcs11_config.h
Description
-----------
Checklist:
----------
> Fixed Hard Fault in ST and TI. Reverted secure element key generation regression.

- libraries/abstractions/common_io/include/iot_reset.h
all void functions need explict void
Description
-----------
Checklist:
----------
> all void functions need explict void

- libraries/abstractions/common_io/include/iot_sdio.h
Add iot_sdio.h and address PR comments.
Description
-----------
Checklist:
----------
> Add iot_sdio.h and address PR comments.

- vendors/espressif/esp-idf/components/nimble/esp-hci/src/esp_nimble_hci.c
Description
-----------
This PR makes NimBLE host wait for ESP controller to be ready to receive data. This bugfix is already present in `esp-idf` however not yet present in AFR.
Checklist:
----------
> NimBLE AFR: Fix erroneous behaviour of NimBLE porting layer when controller is not ready to receive

- libraries/abstractions/common_io/include/iot_sdio.h
- libraries/abstractions/common_io/test/test_iot_sdio.c
add test_iot_sdio.c
Description
-----------
Checklist:
----------
> add test_iot_sdio.c

- libraries/freertos_plus/aws/ota/include/aws_iot_ota_agent.h
- libraries/freertos_plus/aws/ota/src/http/aws_iot_ota_http.c
Description
-----------
When copying OTA to FreeRTOS org repo, we have to make several changes
to fix the build. This commit cherry picks most of the changes back to
make it easier to maintain 2 copies.
Checklist:
----------
> Sync FreeRTOS org changes back

- libraries/abstractions/common_io/test/test_iot_internal.h
adding needed extern variables for sdio test.
Description
-----------
Checklist:
----------
> adding needed extern variables for sdio test.

- libraries/abstractions/common_io/test/test_scripts/uart/test_iot_runonPI_uart.sh
- libraries/abstractions/common_io/test/test_scripts/uart/test_iot_uart_rp3.py
- libraries/abstractions/common_io/test/test_scripts/uart/test_iot_uart_test.py
Description
-----------
Why: The original scripts does not completely work with the internal board. The console output is not parsed correctly.
All tests are passed.
run test_iot_uart_test.py -l <login> -s <pwd> -i <ip> -p <port0>
2020-02-19 11:26:13.718892 [INFO] test_IotUartWriteReadAsync 0  PASS  :  test_IotUartWriteReadAsync Passed
2020-02-19 11:26:17.293624 [INFO] test_IotUartBaudChange 0  PASS  :  test_IotUartBaudChange Passed
2020-02-19 11:26:20.821071 [INFO] test_IotUartWriteAsync 0  PASS  :  test_IotUartWriteAsync Passed
Checklist:
----------
> test: Update uart scripts

- libraries/freertos_plus/aws/ota/include/aws_iot_ota_agent.h
Description
-----------
Update the doxygen comments to make OTA conform to C-SDK doxygen style. Some parts are rearranged to make it better organized, no real code change.
Checklist:
----------
> Update doxygen comments in OTA agent header

- libraries/abstractions/secure_sockets/lwip/iot_secure_sockets.c
Description
-----------
Checklist:
----------
> fix: secure sockets regression error

- demos/demo_runner/iot_demo_freertos.c
- tests/common/aws_test_framework.c
Description
-----------
We are handling the delay from the test infrastructure side now, so we do not need it in the source.
Checklist:
----------
> Remove delays before tests and demos

- doc/config/pkcs11
- doc/lib/pkcs11.txt
- libraries/abstractions/pkcs11/include/iot_pkcs11_pal.h
- libraries/abstractions/pkcs11/mbedtls/iot_pkcs11_mbedtls.c
- libraries/freertos_plus/standard/pkcs11/include/iot_pkcs11.h
- libraries/freertos_plus/standard/pkcs11/src/iot_pkcs11.c
- libraries/freertos_plus/standard/utils/include/iot_pki_utils.h
- libraries/freertos_plus/standard/utils/src/iot_pki_utils.c
- vendors/pc/boards/windows/ports/pkcs11/iot_pkcs11_pal.c
This commit syncs the Doxygen code that was used to generate the FreeRTOS.org PKCS #11 Doxygen.
Description
-----------
Checklist:
----------
> Added Doxygen For PKCS #11.

- doc/config/pkcs11
- doc/lib/pkcs11.txt
- libraries/abstractions/pkcs11/include/iot_pkcs11_pal.h
- libraries/abstractions/pkcs11/mbedtls/iot_pkcs11_mbedtls.c
- libraries/abstractions/pkcs11/mbedtls/threading_alt.h
- libraries/freertos_plus/standard/pkcs11/include/iot_pkcs11.h
- libraries/freertos_plus/standard/pkcs11/src/iot_pkcs11.c
- libraries/freertos_plus/standard/utils/include/iot_pki_utils.h
- vendors/pc/boards/windows/ports/pkcs11/iot_pkcs11_pal.c
Description
-----------
This PR cleans up warnings generated by Doxygen, as well as some minor errors in the doxygen comments.
Checklist:
----------
> PKCS #11 Doxygen cleanup

- libraries/abstractions/pkcs11/mbedtls/iot_pkcs11_mbedtls.c
Description
-----------
Checklist:
----------
> Silence PKCS #11 mbedTLS warnings by default.

- libraries/freertos_plus/standard/freertos_plus_tcp/source/portable/NetworkInterface/Zynq/NetworkInterface.c
- libraries/freertos_plus/standard/freertos_plus_tcp/source/portable/NetworkInterface/Zynq/README.txt
- libraries/freertos_plus/standard/freertos_plus_tcp/source/portable/NetworkInterface/Zynq/uncached_memory.c
- libraries/freertos_plus/standard/freertos_plus_tcp/source/portable/NetworkInterface/Zynq/x_emacpsif.h
- libraries/freertos_plus/standard/freertos_plus_tcp/source/portable/NetworkInterface/Zynq/x_emacpsif_dma.c
- libraries/freertos_plus/standard/freertos_plus_tcp/source/portable/NetworkInterface/Zynq/x_emacpsif_hw.c
- libraries/freertos_plus/standard/freertos_plus_tcp/source/portable/NetworkInterface/Zynq/x_emacpsif_physpeed.c
- vendors/xilinx/boards/microzed/aws_demos/config_files/FreeRTOSConfig.h
- vendors/xilinx/boards/microzed/aws_demos/config_files/FreeRTOSIPConfig.h
- vendors/xilinx/boards/microzed/aws_tests/config_files/FreeRTOSConfig.h
- vendors/xilinx/boards/microzed/aws_tests/config_files/FreeRTOSIPConfig.h
Xilinx Zynq NetworkInterface v3
-----------
Description
-----------
My PR #1628 was closed because another PR #1785 came in between.
In the first commit of this PR I'm restoring the situation as it was when @gkwicker approved the PR. I hope that makes it easier to review the last few changes.
I tested all changes both in [aws_demos](https://github.com/aws/amazon-freertos/tree/master/projects/xilinx/microzed/xsdk/aws_demos) as well as in my own Zybo testing project.
Checklist:
----------
> Applied commits from PR #1628

- vendors/espressif/boards/esp32/ports/wifi/iot_wifi.c
Description
-----------
Initially, `WIFI_Off()` returned with a NOP in ESP32 port layer. Hence, there was no support to turn Off WiFi in runtime.
This PR is intended to support turning WiFi On and Off in runtime.
I have also run AFQP tests for `FullWiFi` group on this branch. I'm attaching the results for the same.
```
========== Test Summary ==========
Execution Time: 	7m55s
Tests Completed: 	37
Tests Passed: 		37
Tests Failed: 		0
Tests Skipped: 		0
----------------------------------
Test Groups:
Optional Test Groups:
FullWiFi: 		PASSED
```
Checklist:
----------
> Add definition for WIFI_Off in port layer of ESP32

- libraries/CMakeLists.txt
- libraries/c_sdk/standard/ble/CMakeLists.txt
- libraries/c_sdk/standard/ble/src/services/mqtt_ble/iot_ble_data_transfer.c
- libraries/c_sdk/standard/ble/utest/CMakeLists.txt
- libraries/c_sdk/standard/ble/utest/iot_ble_data_transfer_utest.c
- tests/unit_test/linux/config_files/iot_ble_config.h
- tests/unit_test/linux/config_files/iot_config.h
- tests/unit_test/linux/config_files/iot_config_common.h
- tools/cmock/create_test.cmake
100% branch/line coverage for iot_ble_data_transfer.h API
cmock + unity
-----------
Checklist:
----------
> unity + cmock iot_ble_data_transfer unit test

- vendors/nxp/boards/lpc54018iotmodule/aws_demos/config_files/aws_wifi_config.h
- vendors/nxp/boards/lpc54018iotmodule/aws_tests/config_files/aws_secure_sockets_config.h
- vendors/nxp/boards/lpc54018iotmodule/ports/secure_sockets/iot_secure_sockets.c
- vendors/nxp/boards/lpc54018iotmodule/ports/wifi/iot_wifi.c
- Serialize all access to the WiFi module via semaphore
- Toggle WiFi power at startup
- Decrease secure socket test timeout to 10s
Description
-----------
Checklist:
----------
> Address issues in NXP port

- libraries/freertos_plus/aws/greengrass/test/aws_test_helper_secure_connect.c
- tests/common/aws_test_runner.c
Description
-----------
Rename test group for Greengrass connect helper from Full_GGD_Helper to GGD_Helper_System to be consistent with other GGD test groups
Checklist:
----------
> Rename GGD Helper test group

- libraries/c_sdk/standard/serializer/test/iot_tests_deserializer_json.c
- libraries/c_sdk/standard/serializer/test/iot_tests_serializer_cbor.c
- libraries/c_sdk/standard/serializer/test/iot_tests_serializer_json.c
- tests/common/aws_test_runner.c
Description
-----------
Rename serializer unit tests
Checklist:
----------
> Rename serializer tests

- libraries/abstractions/common_io/include/iot_usb_host.h
Add iot usb host interface
Description
-----------
Checklist:
----------
> Add iot usb host interface on master branch

- libraries/abstractions/common_io/test/test_iot_spi.c
Description
-----------
Refactored tests to perform open/close during setup/tear-down phases.
This is part of the work related to the following issue: https://github.com/aws/amazon-freertos/issues/1859
Checklist:
----------
> common-io: Refactoring SPI test cases

- libraries/abstractions/common_io/test/test_iot_watchdog.c
Description
-----------
* Refactored test cases to use TEST_PROTECT sections to guard against cascading failures.
* Moved to a single shared bark/bite callback with separate semaphores. This allows for the status to be evaluated as part of the callback instead of waiting for the semaphore to go back. 
* Added a WD reset in the case of a bite interrupt, this as some devices require a reset in order to escape the interrupt. 
* Added global test instance variable to allow the test framework to define which WD instance to test.
Checklist:
----------
> common-io: Refactoring Watchdog test cases

- libraries/abstractions/common_io/test/iot_test_common_io_internal.h
Description
-----------
Checklist:
----------
> Common-IO Peripheral Tests Default to Off

- libraries/freertos_plus/standard/pkcs11/src/iot_pkcs11.c
Description
-----------
Checklist:
----------
> Initialize function list to NULL.

- libraries/CMakeLists.txt
- libraries/freertos_plus/standard/pkcs11/CMakeLists.txt
- libraries/freertos_plus/standard/pkcs11/utest/CMakeLists.txt
- libraries/freertos_plus/standard/pkcs11/utest/iot_pkcs11_utest.c
- tests/unit_test/linux/config_files/iot_pkcs11_config.h
- tools/cmock/create_test.cmake
Description
-----------
Checklist:
----------
> Added unit tests for iot_pkcs11.c.

- libraries/abstractions/common_io/test/iot_test_common_io_internal.h
- vendors/st/boards/stm32l475_discovery/ports/common_io/iot_test_common_io_internal.c
Description
-----------
Declare common io configuration in headers
This solves compile error in this PR: https://github.com/aws/amazon-freertos/pull/1905
Checklist:
----------
> Declare common io configuration in headers

- projects/cypress/CY8CKIT_064S0S2_4343W/mtb/aws_demos/Makefile
- projects/cypress/CY8CKIT_064S0S2_4343W/mtb/aws_demos/afr.mk
CY8CKIT_064S0S2_4343W: Fix aws_demos build
Description
-----------
Fixes build issue
Checklist:
----------
> CY8CKIT_064S0S2_4343W: Fix aws_demos build

- projects/cypress/CY8CKIT_064S0S2_4343W/mtb/aws_demos/.mtbLaunchConfigs/aws_demos Attach (KitProg3).launch
- projects/cypress/CY8CKIT_064S0S2_4343W/mtb/aws_demos/.mtbLaunchConfigs/aws_demos Debug (KitProg3).launch
- projects/cypress/CY8CKIT_064S0S2_4343W/mtb/aws_demos/.mtbLaunchConfigs/aws_demos Erase (KitProg3).launch
- projects/cypress/CY8CKIT_064S0S2_4343W/mtb/aws_demos/.mtbLaunchConfigs/aws_demos Program (KitProg3).launch
- vendors/cypress/psoc6/psoc6make/make/toolchains/GCC_ARM.mk
MTB: Fix launch configs
Description
-----------
Enables programming and debugging in MTB.
Checklist:
----------
> MTB: Fix launch configs

- libraries/freertos_plus/standard/pkcs11/src/iot_pkcs11.c
- libraries/freertos_plus/standard/pkcs11/utest/iot_pkcs11_utest.c
Description
-----------
Checklist:
----------
> Fix potential NULL reference in xFindObjectWithLabelAndClass.

- libraries/CMakeLists.txt
- libraries/abstractions/pkcs11/CMakeLists.txt
- libraries/abstractions/pkcs11/mbedtls/iot_pkcs11_mbedtls.c
- libraries/abstractions/pkcs11/utest/CMakeLists.txt
- libraries/abstractions/pkcs11/utest/iot_pkcs11_mbedtls_utest.c
- libraries/abstractions/pkcs11/utest/project.yml
- libraries/abstractions/secure_sockets/utest/CMakeLists.txt
- libraries/c_sdk/standard/ble/utest/CMakeLists.txt
- libraries/freertos_plus/standard/pkcs11/utest/CMakeLists.txt
- tests/unit_test/linux/config_files/config.h
- tools/cmock/create_test.cmake
Added cmock unit test harness for iot_pkcs11_mbedtls.c
Created seperate cmock configs
100% line coverage and branch coverage for:
* C_Initialize
* C_Finialize
* C_GetFunctionList
Description
-----------
Checklist:
----------
> iot_pkcs11_mbedtls.c Unit Tests

- demos/include/aws_clientcredential_keys.h
- libraries/abstractions/pkcs11/mbedtls/iot_pkcs11_mbedtls.c
- tests/include/aws_clientcredential_keys.h
Description
-----------
Checklist:
----------
> Fix msvc compiler warnings in iot_pkcs11_mbedtls.c

- projects/cypress/CY8CKIT_064S0S2_4343W/mtb/aws_tests/.cproject
- projects/cypress/CY8CKIT_064S0S2_4343W/mtb/aws_tests/.mtbLaunchConfigs/aws_tests Attach (JLink).launch
- projects/cypress/CY8CKIT_064S0S2_4343W/mtb/aws_tests/.mtbLaunchConfigs/aws_tests Attach (KitProg3).launch
- projects/cypress/CY8CKIT_064S0S2_4343W/mtb/aws_tests/.mtbLaunchConfigs/aws_tests Debug (JLink).launch
- projects/cypress/CY8CKIT_064S0S2_4343W/mtb/aws_tests/.mtbLaunchConfigs/aws_tests Debug (KitProg3).launch
- projects/cypress/CY8CKIT_064S0S2_4343W/mtb/aws_tests/.mtbLaunchConfigs/aws_tests Erase (JLink).launch
- projects/cypress/CY8CKIT_064S0S2_4343W/mtb/aws_tests/.mtbLaunchConfigs/aws_tests Erase (KitProg3).launch
- projects/cypress/CY8CKIT_064S0S2_4343W/mtb/aws_tests/.mtbLaunchConfigs/aws_tests Program (JLink).launch
- projects/cypress/CY8CKIT_064S0S2_4343W/mtb/aws_tests/.mtbLaunchConfigs/aws_tests Program (KitProg3).launch
- projects/cypress/CY8CKIT_064S0S2_4343W/mtb/aws_tests/.project
Create aws_tests project
Description
-----------
Requires cmake to be run before importing into ModusToolbox.
cmake -G "Unix Makefiles" -S .
-B projects\cypress\CY8CKIT_064S0S2_4343W\mtb\aws_tests
-DVENDOR=cypress
-DBOARD=CY8CKIT_064S0S2_4343W
-DCOMPILER=arm-gcc
-DAFR_IS_TESTING=1
Checklist:
----------
> Create aws_tests project

- libraries/abstractions/common_io/include/iot_usb_host.h
- libraries/abstractions/pkcs11/ecc608a/atca_cert_chain.c
- libraries/abstractions/pkcs11/ecc608a/atca_cert_chain.h
- libraries/abstractions/pkcs11/ecc608a/iot_pkcs11_secure_element.c
Only changes are uncrustifying said 4 files.
Description
-----------
Checklist:
----------
> Uncrustified Files Failing Uncrustify Check

- vendors/espressif/boards/esp32/esp32_plus_ecc608a_devkitc.cmake
Description
-----------
Checklist:
----------
> Fix ESP-WROOM-32SE key import metadata.

- libraries/abstractions/pkcs11/ecc608a/iot_pkcs11_secure_element.c
- libraries/abstractions/pkcs11/utest/CMakeLists.txt
- libraries/abstractions/secure_sockets/utest/CMakeLists.txt
- libraries/c_sdk/standard/ble/utest/CMakeLists.txt
- libraries/freertos_plus/standard/pkcs11/utest/CMakeLists.txt
- tests/unit_test/linux/CMakeLists.txt
- tools/cmock/create_test.cmake
- vendors/pc/boards/linux/CMakeLists.txt
Simplify Unit test cmake for a better user experience adding new unit tests
Description
-----------
Simplify the cmake file for unit tests
Checklist:
----------
> Test: simplify adding new unit tests

- demos/https/iot_demo_https_s3_upload_async.c
- libraries/freertos_plus/standard/freertos_plus_posix/source/FreeRTOS_POSIX_pthread_cond.c
- libraries/freertos_plus/standard/freertos_plus_tcp/source/FreeRTOS_DNS.c
- vendors/pc/boards/windows/aws_demos/config_files/FreeRTOSConfig.h
Fix some low-hanging fruit MSVC warnings
Description
-----------
Checklist:
----------
> Fix some low-hanging fruit MSVC warnings

- libraries/abstractions/pkcs11/mbedtls/iot_pkcs11_mbedtls.c
This commit fixes some logic in fuctions touched by the unit tests written so far for iot_pkcs11_mbedtls.c
Description
-----------
Checklist:
----------
> iot_pkcs11_mbedtls.c Bug Fixes/Refactor/MbedTLS Error Logging

- tools/ota_e2e_tests/board.json
-----------
Update OTA e2e board.json with new test cases for suspend/resume.
Description
Checklist:
----------
> Update OTA e2e board.json for new test cases

- libraries/abstractions/secure_sockets/test/iot_test_tcp.c
Description
-----------
Fix format of iot_test_tcp.c
Checklist:
----------
> Fix format of iot_test_tcp.c

- vendors/st/boards/stm32l475_discovery/ports/common_io/iot_test_common_io_internal.c
Description
-----------
Fix common io test configurations for ST
Checklist:
----------
> Fix common io test configurations for ST

- demos/demo_runner/iot_demo_freertos.c
Description
-----------
Reported by:
https://github.com/aws/amazon-freertos/issues/2013
Checklist:
----------
> Fix Typos.

- libraries/abstractions/pkcs11/utest/iot_pkcs11_mbedtls_utest.c
Fix comment on C_CloseSession suite. Fixed regressions caused by refactoring. Better coverage for C_Verify. Coverage now at 99.3%.
Description
-----------
Checklist:
----------
> PKCS #11 Unit Tests

- libraries/abstractions/pkcs11/mbedtls/iot_pkcs11_mbedtls.c
- libraries/freertos_plus/standard/pkcs11/include/iot_pkcs11.h
This commit contains various MISRA fixes and logic refactors.
Some MISRA violations that were fixed:
* 8.7
* 20.7
* 21.16
* 7.2
* 8.3
* 8.4
* 8.6
* 8.7
* 8.9
* 16.3
* 17.7
* 12.1
* 13.1
* 14.2
* 14.3
* 14.4
* 15.7
* 16.1
* 11.4
* 10.4
Description
-----------
Checklist:
----------
> PKCS #11 MISRA Fixes

- vendors/xilinx/boards/microzed/aws_demos/application_code/main.c
Pull Xilinx demo logging fix of #2043 to `release-candidate` branch
Description
-----------
Checklist:
----------
> Increase the logging queue size in Xilinx microzed (#2043)

- CMakeLists.txt
Update `PROJECT_VERSION` string to match release number, `202006.00`
Checklist:
----------
> Update version number to match release

- tools/uncrustify.cfg
Pull uncrustify config update made in #2015 into the `release-candidate` branch
Checklist:
----------
> Revert uncrustify change from PR #2015. (#2038)

- libraries/abstractions/ble_hal/include/bt_hal_avsrc_profile.h
- libraries/abstractions/ble_hal/include/bt_hal_gatt_server.h
- libraries/abstractions/ble_hal/include/bt_hal_manager.h
- libraries/abstractions/ble_hal/include/bt_hal_manager_adapter_ble.h
- libraries/abstractions/ble_hal/include/bt_hal_manager_adapter_classic.h
- libraries/abstractions/ble_hal/include/bt_hal_manager_types.h
Update BLE HAL doxygen
Description
-----------
Update BLE HAL doxygen
Remove unnecessary extern in front of function prototype
Checklist:
----------
> Update BLE HAL doxygen

- libraries/c_sdk/standard/mqtt/src/iot_mqtt_api.c
- libraries/c_sdk/standard/mqtt/src/iot_mqtt_operation.c
- libraries/c_sdk/standard/mqtt/src/iot_mqtt_validate.c
- libraries/c_sdk/standard/mqtt/src/private/iot_mqtt_internal.h
- libraries/c_sdk/standard/mqtt/test/unit/iot_tests_mqtt_api.c
Description
-----------
Fixes a bug in mqtt keep alive. Cherry picked commits from #2064 and #2068
Checklist:
----------
> Fix: MQTT Keep Alive Scheduling

- libraries/freertos_plus/aws/ota/src/aws_iot_ota_agent.c
Description
-----------
Same PR #2090 that's merged into master.
Checklist:
----------
> Start OTA self test timer before job doc is requested.

- projects/ti/cc3220_launchpad/iar/aws_demos/aws_demos.ewp
Description
-----------
Added missing path.
Checklist:
----------
> Fixed TI IAR project files.

- libraries/c_sdk/standard/https/test/system/iot_tests_https_system.c
Reverts aws/amazon-freertos#2072
> Revert "Change https echo server domain"

- libraries/abstractions/pkcs11/mbedtls/iot_pkcs11_mbedtls.c
- libraries/freertos_plus/standard/pkcs11/src/iot_pkcs11.c
- libraries/freertos_plus/standard/utils/src/iot_pki_utils.c
This reverts commit 7a89b4c523b64bbb56c4fd671244b8d6b02d7813.
Description
-----------
Checklist:
----------
> Revert "Enforce PKCS 11 80 char column limit (#2077)"

- CHANGELOG.md
Add ChangeLog for `202006.00` release
> ChangeLog for 202006.00 release

- libraries/abstractions/common_io/test/test_iot_gpio.c
Description
-----------
Comment out TEST_MESSAGE in GPIO tests, in the same way as PR #2047.
Checklist:
----------
> Comment out TEST_MESSAGE in GPIO tests, in the same way as PR #2047

- libraries/abstractions/secure_sockets/test/iot_test_tcp.c
Description
-----------
Move the multiple-address DNS test to a separate test group.
Checklist:
----------
> Move test_dns_multiple_addresses to a new test group

- tools/cmake/afr_utils.cmake
- vendors/espressif/boards/esp32/CMakeLists.txt
Explicitly add missing header files to fix OCW
Description
-----------
Explicitly add missing header files to fix OCW as the folder gets put in the include path, but the files are not getting copied.
Checklist:
----------
> Explicitly add missing header files to fix OCW.

- tools/cmake/afr_utils.cmake
- vendors/espressif/boards/esp32/CMakeLists.txt
* Explicitly add missing header files to fix OCW.
* Fix error caused by missing manifest.
Description
-----------
cherry pick of  https://github.com/aws/amazon-freertos/pull/2122
Checklist:
----------
> Explicitly add missing header files to fix OCW. (#2122)

- libraries/abstractions/wifi/test/iot_test_wifi.c
- vendors/espressif/boards/esp32/ports/wifi/iot_wifi.c
implement wifi_getip for LwIP on espressif
Description
-----------
implement wifi_getip for LwIP on espressif
Checklist:
----------
> Espressif wifi_getip for LwIP

- vendors/cypress/MTB/psoc6/cmake/toolchains/arm-gcc.cmake
- vendors/cypress/MTB/psoc6/psoc6make/make/toolchains/GCC_ARM.mk
Signed-off-by: Charley Chu <haoc@cypress.com>
Description
-----------
Checklist:
----------
> Switch ARM GCC libc from nano to normal

- projects/cypress/CY8CKIT_064S0S2_4343W/mtb/aws_demos/afr.mk
Tested with make, cmake and GCC, ARM CLang, IAR
Signed-off-by: Andrei Narkevitch <ainh@cypress.com>
Description
-----------
Checklist:
----------
> PSoC64: GreenGrass and Defender demos fix

- libraries/freertos_plus/aws/ota/src/mqtt/aws_iot_ota_mqtt.c
Description
-----------
Reduced complexity of following functions,
- `prvUpdateJobStatus_Mqtt`
- `prvSubscribeToJobNotificationTopics`
- `prvRequestFileBlock_Mqtt`
Checklist:
----------
> OTA reduce complexity 2

- libraries/freertos_plus/aws/ota/include/aws_iot_ota_agent.h
- libraries/freertos_plus/aws/ota/src/aws_iot_ota_agent.c
Description
-----------
Reduced complexity of following functions,
- `prvSetImageStateWithReason`
- `prvGetFileContextFromJob`
- `prvOTAAgentTask`
- `OTA_AgentInit_internal`
Checklist:
----------
> OTA reduce complexity 1

- libraries/freertos_plus/aws/ota/src/aws_iot_ota_agent.c
Description
-----------
Reduced complexity of following functions,
- `prvIngestDataBlock`
- `prvParseJSONbyModel`
Checklist:
----------
> OTA reduce complexity 3

- projects/cypress/CY8CKIT_064S0S2_4343W/mtb/aws_demos/afr.mk
- projects/cypress/CY8CKIT_064S0S2_4343W/mtb/aws_tests/Makefile
- projects/cypress/CY8CKIT_064S0S2_4343W/mtb/aws_tests/afr.mk
- projects/cypress/CY8CKIT_064S0S2_4343W/mtb/jitp/afr.mk
- projects/cypress/CY8CKIT_064S0S2_4343W/mtb/wifi_scanner/afr.mk
CY_USE_FREERTOS_PLUS_TCP
Signed-off-by: Charley Chu <haoc@cypress.com>
Description
-----------
Checklist:
----------
> Remove unused build option

- libraries/abstractions/pkcs11/ReadMe.md
- libraries/abstractions/pkcs11/include/iot_pkcs11_pal.h
Update PKCS #11 PAL Documentation to Latest Code Changes
Description
-----------
Updates the PKCS #11 PAL readme after the earlier refactoring of the initialization sequence. 
Checklist:
----------
> Update PKCS #11 PAL Documentation to Latest Code Changes

- libraries/freertos_plus/aws/ota/include/aws_iot_ota_agent.h
- libraries/freertos_plus/aws/ota/src/aws_iot_ota_agent.c
- libraries/freertos_plus/aws/ota/src/aws_iot_ota_agent_internal.h
- libraries/freertos_plus/aws/ota/src/aws_iot_ota_interface.c
- libraries/freertos_plus/aws/ota/src/mqtt/aws_iot_ota_mqtt.c
- vendors/espressif/boards/esp32/aws_demos/config_files/FreeRTOSConfig.h
- vendors/espressif/boards/esp32/aws_demos/config_files/aws_ota_agent_config.h
- vendors/espressif/boards/esp32/aws_tests/config_files/aws_ota_agent_config.h
- vendors/nordic/boards/nrf52840-dk/aws_demos/config_files/aws_ota_agent_config.h
- vendors/nordic/boards/nrf52840-dk/aws_tests/config_files/aws_ota_agent_config.h
Description
-----------
Fix MISRA warnings in OTA agent.
Checklist:
----------
> OTA MISRA warnings fix

- demos/tcp/aws_tcp_echo_client_single_task.c
Port fix of TCP echo client demo race condition made in #2181  to `release-candidate`
> Sync Single Echo Client demo tasks (#2181)

- projects/cypress/CY8CKIT_064S0S2_4343W/mtb/aws_demos/afr.mk
- projects/cypress/CY8CKIT_064S0S2_4343W/mtb/jitp/afr.mk
- projects/cypress/CY8CKIT_064S0S2_4343W/mtb/jitp/config_files/aws_ota_agent_config.h
CY8CKIT-064S0S2-4343W: Allow for OTA builds
Description
-----------
Updates to projects to allow for successful OTA build when
enabled.
Signed-off-by: Raymond Ngun <raymond.ngun@cypress.com>
Checklist:
----------
> CY8CKIT-064S0S2-4343W: Allow for OTA builds

- libraries/abstractions/wifi/test/iot_test_wifi.c
- vendors/espressif/boards/esp32/ports/wifi/iot_wifi.c
Port #2135  to `release-candidate`
> Fix: Support for lwip getip with espressif (#2135)

- projects/cypress/CY8CKIT_064S0S2_4343W/mtb/aws_demos/Makefile
Description
-----------
Checklist:
----------
> Fix: Enable BLE in Cypress PSoC64 MTB demo project.

- libraries/freertos_plus/aws/ota/include/aws_iot_ota_agent.h
- libraries/freertos_plus/aws/ota/src/aws_iot_ota_agent.c
- libraries/freertos_plus/aws/ota/src/aws_iot_ota_agent_internal.h
Description
-----------
Cherry pick PR from master branch, https://github.com/aws/amazon-freertos/pull/2223
Checklist:
----------
> OTA: Support force cancel and abort

- vendors/xilinx/boards/microzed/aws_demos/application_code/main.c
Adds https://github.com/aws/amazon-freertos/pull/2129 into the release-candidate.
Checklist:
----------
> Increase the logging queue size for Xilinx Microzed (#2129)

- libraries/freertos_plus/standard/freertos_plus_tcp/include/FreeRTOSIPConfigDefaults.h
- libraries/freertos_plus/standard/freertos_plus_tcp/source/FreeRTOS_IP.c
Description
-----------
Get the changes from PRs #2225, #2226 and #2227 to RC.
Checklist:
----------
> Add Changes from #2225, #2226 & #2227

- libraries/freertos_plus/standard/freertos_plus_tcp/source/FreeRTOS_DNS.c
Count only A records in DNS resolution logic
Description
-----------
Adding change from [PR #2241](https://github.com/aws/amazon-freertos/pull/2241)
Checklist:
----------
> Count only A records in DNS resolution logic

- libraries/freertos_plus/aws/ota/src/aws_iot_ota_agent.c
Description
-----------
Cherry pick PR #2257 and #2260 to release-candidate.
Checklist:
----------
> Sync OTA fixes from master branch

- CHANGELOG.md
Remove lingering bullet in Changelog in [Espressif New board section](https://github.com/aws/amazon-freertos/blob/876c007321e63926382bb7ecf430d7f7adcfab22/CHANGELOG.md#new-board-esp32-wroom-32se)
> Remove empty bullet point in CHANGELOG.md layout

- CHANGELOG.md
Update text for Mbed TLS submodule update in ChangeLog file.
> Update text for Mbed TLS submodule update in ChangeLog

- libraries/c_sdk/standard/mqtt/src/iot_mqtt_api.c
- libraries/c_sdk/standard/mqtt/src/iot_mqtt_managed_function_wrapper.c
- libraries/c_sdk/standard/mqtt/src/iot_mqtt_network.c
- libraries/c_sdk/standard/mqtt/src/iot_mqtt_operation.c
- libraries/c_sdk/standard/mqtt/src/iot_mqtt_serializer_deserializer_wrapper.c
- libraries/c_sdk/standard/mqtt/src/private/iot_mqtt_internal.h
Description
-----------
Checklist:
----------
> PR: Phase 2 - Shim Implementation for Subscribe, Unsubscribe and Publish Using MQTT LTS Library APIs.

- libraries/c_sdk/standard/mqtt/src/iot_mqtt_managed_function_wrapper.c
- libraries/c_sdk/standard/mqtt/src/iot_mqtt_operation.c
- libraries/c_sdk/standard/mqtt/src/private/iot_mqtt_internal.h
Implementing PINGREQ using Managed MQTT API.
> Send Ping request using MQTT_PING.

- libraries/c_sdk/standard/mqtt/CMakeLists.txt
- libraries/c_sdk/standard/mqtt/src/iot_mqtt_api.c
- libraries/c_sdk/standard/mqtt/src/iot_mqtt_context_connection.c
- libraries/c_sdk/standard/mqtt/src/iot_mqtt_managed_function_wrapper.c
- libraries/c_sdk/standard/mqtt/src/iot_mqtt_mutex_wrapper.c
- libraries/c_sdk/standard/mqtt/src/iot_mqtt_network.c
- libraries/c_sdk/standard/mqtt/src/iot_mqtt_operation.c
- libraries/c_sdk/standard/mqtt/src/iot_mqtt_serializer_deserializer_wrapper.c
- libraries/c_sdk/standard/mqtt/src/iot_mqtt_subscription.c
- libraries/c_sdk/standard/mqtt/src/iot_mqtt_subscription_container.c
- libraries/c_sdk/standard/mqtt/src/private/iot_mqtt_internal.h
Optimization of Subscription list and Synchronization primitives using native freeRTOS implementation.
> PHASE 3: Shim Layer Optimization

- libraries/abstractions/common_io/include/iot_adc.h
Minor iot_adc.h documentation update
Description
-----------
Update the requirement for sample time and resolution to be the closest possible value the hardware can report
Checklist:
----------
> Minor iot_adc.h documentation update

- demos/mqtt_transport/mqtt_demo_transport.c
- libraries/c_sdk/standard/ble/include/iot_ble_mqtt_transport.h
- libraries/c_sdk/standard/ble/src/iot_ble_mqtt_transport.c
- libraries/c_sdk/standard/ble/utest/ble_mqtt_transport/iot_ble_mqtt_transport_utest.c
MQTT over BLE utest improvements
Description
-----------
Addressed comments from #2382 
Checklist:
----------
> MQTT over BLE utest improvements

- tools/ota_e2e_tests/aws_ota_test/aws_ota_test_runner.py
Description
-----------
Add a missing exception.
Checklist:
----------
> Fix a bug in OTA e2e script

- libraries/abstractions/pkcs11/mbedtls/iot_pkcs11_mbedtls.c
Reduced mutex wait time for PKCS #11.
Description
-----------
Currently all of the mutexes in PCKS #11 mbedTLS were waiting forever. This reduces the wait to 5 seconds before giving up.
Checklist:
----------
> Reduced mutex wait time for PKCS #11.

- libraries/abstractions/pkcs11/mbedtls/iot_pkcs11_mbedtls.c
Remove constants if logging is disabled.
Description
-----------
Remove constants if logging is disabled.
Checklist:
----------
> Remove constants if logging is disabled.

- libraries/abstractions/pkcs11/mbedtls/iot_pkcs11_mbedtls.c
- libraries/abstractions/pkcs11/test/iot_test_pkcs11.c
- libraries/freertos_plus/standard/pkcs11/src/iot_pkcs11.c
- libraries/freertos_plus/standard/utils/include/iot_pki_utils.h
- libraries/freertos_plus/standard/utils/src/iot_pki_utils.c
Removed Kernel dependency from PKCS.
Description
-----------
Removed Kernel dependency from PKCS.
Checklist:
----------
> Removed Kernel dependency from PKCS.

- libraries/abstractions/secure_sockets/utest/CMakeLists.txt
- libraries/abstractions/secure_sockets/utest/include/lwipopts.h
- libraries/abstractions/secure_sockets/utest/include/mocked-types.h
- libraries/abstractions/secure_sockets/utest/project.yml
- libraries/abstractions/secure_sockets/utest/secure_sockets_utest.c
- Remove wifi dependency
- Improve testcoverage in SOCKETS_GetHostByName()
Description
-----------
Checklist:
----------
> Update secure sockets lwip unit test.

- tools/echo_server/readme.md
Added documentation for self signed EC certs
Description
-----------
Added documentation for self signed EC certs.
Checklist:
----------
> Added documentation for self signed EC certs.

- libraries/abstractions/ble_hal/test/src/iot_test_ble_hal_common.c
Description
-----------
Wrap included service definition under the config flag.
Move the definition to beginning of the attribute table  as per core spec version 5.2, Vol 3, Part G, 3.1.
Checklist:
----------
> BLE HAL test fixes

- demos/mqtt_transport/mqtt_demo_transport.c
Fix build failure in demo
Description
-----------
Fix build failure in demo caused by a typo.
Checklist:
----------
> Fix build failure in demo

- .gitmodules
Add submodule references to `v1.0.0` tags of [coreJSON](https://github.com/FreeRTOS/coreJSON) and [Device Shadow](https://github.com/aws/device-shadow-for-aws-iot-embedded-sdk) libraries
> Add submodules to coreJSON and Device Shadow repos

- demos/demo_runner/iot_demo_freertos.c
- demos/mqtt/iot_demo_mqtt.c
- demos/network_manager/aws_iot_demo_network.c
- libraries/c_sdk/standard/mqtt/src/iot_mqtt_api.c
- libraries/c_sdk/standard/mqtt_v2/src/mqtt_lightweight.c
Fix esp32 MQTT demo.
Description
-----------
Fix MQTT demo on ESP32. This is to work with the MQTT shim. The fixes are
1. Fix the build failures.
2. Fix the demo runtime failures.
Checklist:
----------
> Fix esp32 MQTT demo

- libraries/freertos_plus/standard/freertos_plus_tcp/source/FreeRTOS_IP.c
Description
-----------
See Similar PR https://github.com/FreeRTOS/FreeRTOS/pull/301
Checklist:
----------
- [] I have tested my changes. No regression in existing tests.
- [] My code is Linted.
> Remove const to fix breaking Nuvoton build

- vendors/espressif/boards/esp32/ports/common_io/iot_uart.c
Fix common io uart for ESP32
Description
-----------
This PR fixes two bugs:
1. The Tx and Rx bytes are not cleared before the next write/read operation.
2. `iot_uart_cancel` implementation does not kick off a timer to perform the read cancel, so if no bytes are pending the cancel operation never succeeds.
Checklist:
----------
> Fix common io uart for ESP32

- libraries/abstractions/ble_hal/include/bt_hal_manager_adapter_ble.h
Add new API pxSetBgScanParameters() to set BG scan parameters
Signed-off-by: Adham Abozaeid <adhsal@amazon.com>
Description
-----------
Added new API pxSetBgScanParameters() to set BG scan parameters
Checklist:
----------
> Adding API to set BG scan parameters

- libraries/abstractions/ble_hal/include/bt_hal_avsrc_profile.h
- libraries/abstractions/ble_hal/include/bt_hal_gatt_client.h
- libraries/abstractions/ble_hal/include/bt_hal_gatt_server.h
- libraries/abstractions/ble_hal/include/bt_hal_gatt_types.h
- libraries/abstractions/ble_hal/include/bt_hal_manager.h
- libraries/abstractions/ble_hal/include/bt_hal_manager_adapter_ble.h
- libraries/abstractions/ble_hal/include/bt_hal_manager_adapter_classic.h
- libraries/abstractions/ble_hal/include/bt_hal_manager_types.h
- libraries/abstractions/ble_hal/test/src/iot_test_ble_hal_common.c
- libraries/abstractions/ble_hal/test/src/iot_test_ble_hal_integration.c
Add ACL state changed callback
Description
-----------
Add ACL state changed callback and corresponding reason codes
Checklist:
----------
> Add ACL state changed callback

- libraries/c_sdk/standard/mqtt/test/unit/iot_tests_mqtt_api.c
Fix IAR build issues.
Description
-----------
Fix IAR build issues for both NXP and TI.
Checklist:
----------
> Fix IAR build issues

- projects/nxp/lpc54018iotmodule/mcuxpresso/aws_tests/.cproject
- projects/nxp/lpc54018iotmodule/mcuxpresso/aws_tests/.project
Fix NXP build.
Description
-----------
Build was broken due to logging stack being in the wrong location.
Checklist:
----------
> Fix NXP build.

- demos/coreMQTT/mqtt_demo_basic_tls.c
- demos/coreMQTT/mqtt_demo_connection_sharing.c
- demos/coreMQTT/mqtt_demo_mutual_auth.c
- vendors/cypress/boards/CY8CKIT_064S0S2_4343W/aws_demos/config_files/mqtt_demo_basic_tls_config.h
- vendors/cypress/boards/CYW943907AEVAL1F/aws_demos/config_files/mqtt_demo_basic_tls_config.h
- vendors/cypress/boards/CYW954907AEVAL1F/aws_demos/config_files/mqtt_demo_basic_tls_config.h
- vendors/espressif/boards/esp32/aws_demos/config_files/mqtt_demo_basic_tls_config.h
- vendors/infineon/boards/xmc4800_iotkit/aws_demos/config_files/mqtt_demo_basic_tls_config.h
- vendors/infineon/boards/xmc4800_plus_optiga_trust_x/aws_demos/config_files/mqtt_demo_basic_tls_config.h
- vendors/marvell/boards/mw300_rd/aws_demos/config_files/mqtt_demo_basic_tls_config.h
- vendors/mediatek/boards/mt7697hx-dev-kit/aws_demos/config_files/mqtt_demo_basic_tls_config.h
- vendors/microchip/boards/curiosity_pic32mzef/aws_demos/config_files/mqtt_demo_basic_tls_config.h
- vendors/microchip/boards/ecc608a_plus_winsim/aws_demos/config_files/mqtt_demo_basic_tls_config.h
- vendors/nuvoton/boards/numaker_iot_m487_wifi/aws_demos/config_files/mqtt_demo_basic_tls_config.h
- vendors/nxp/boards/lpc54018iotmodule/aws_demos/config_files/mqtt_demo_basic_tls_config.h
- vendors/pc/boards/windows/aws_demos/config_files/mqtt_demo_basic_tls_config.h
- vendors/renesas/boards/rx65n-rsk/aws_demos/config_files/mqtt_demo_basic_tls_config.h
- vendors/st/boards/stm32l475_discovery/aws_demos/config_files/mqtt_demo_basic_tls_config.h
- vendors/ti/boards/cc3220_launchpad/aws_demos/config_files/mqtt_demo_basic_tls_config.h
- vendors/vendor/boards/board/aws_demos/config_files/mqtt_demo_basic_tls_config.h
- vendors/xilinx/boards/microzed/aws_demos/config_files/mqtt_demo_basic_tls_config.h
Description
-----------
- Reverting accidental PC config file commit
- Remove string example in comment for `democonfigMQTT_BROKER_PORT`
Checklist:
----------
> MQTT Basic TLS demo config hygiene update

- libraries/c_sdk/standard/mqtt/src/iot_mqtt_api.c
Remove assert for context index in destroy MQTT connection.
Description
-----------
Problem: In an OTA test an issue was observed when the MQTT connect was not successful. The program hit an assert.
Root cause: The MQTT connection was created without a MQTT context associated with it in an error case. Trying to remove the MQTT context resulted in an assert.
Fix: Remove the assert and replace it with conditional checks to expect the error case when destroying a connection.
Checklist:
----------
> Remove assert for context index in destroy MQTT connection.

- libraries/c_sdk/standard/mqtt/src/iot_mqtt_api.c
- libraries/c_sdk/standard/mqtt/src/iot_mqtt_network.c
- libraries/c_sdk/standard/mqtt/src/iot_mqtt_operation.c
- libraries/c_sdk/standard/mqtt/test/unit/iot_tests_mqtt_api.c
Mqtt connection clean up on error.
Description
-----------
Clean up MQTT connection and the related memory when a network is closed.
Checklist:
----------
> Mqtt connection clean up on error

- libraries/c_sdk/standard/mqtt/src/iot_mqtt_api.c
- libraries/c_sdk/standard/mqtt/src/iot_mqtt_network.c
- libraries/c_sdk/standard/mqtt/src/iot_mqtt_operation.c
- libraries/c_sdk/standard/mqtt/src/iot_mqtt_serializer_deserializer_wrapper.c
- libraries/c_sdk/standard/mqtt/src/iot_mqtt_subscription.c
- libraries/c_sdk/standard/mqtt/src/iot_mqtt_subscription_container.c
- libraries/c_sdk/standard/mqtt/test/unit/iot_tests_mqtt_receive.c
Compiler warning fixes
Description
-----------
Compiler warning fixes in MQTT Shim.
Checklist:
----------
> Compiler warning fixes

- libraries/core_mqtt_demo_dependencies.cmake
> Add BLE dependency on MQTT for FreeRTOS console

- projects/cypress/CY8CKIT_064S0S2_4343W/mtb/aws_tests/afr.mk
Description
-----------
Added a missing file to MTB makefile.
Checklist:
----------
> Fixed the BLE_Unit_MQTT_Serialize MTB Build Failure.

- .github/CODEOWNERS
> Add codeowners file to RC

- vendors/ublox/modules/sara_r4/CMakeLists.txt
- vendors/ublox/modules/sara_r4/ports/cellular/cellular_r4.c
- vendors/ublox/modules/sara_r4/ports/cellular/cellular_r4.h
- vendors/ublox/modules/sara_r4/ports/cellular/cellular_r4_api.c
- vendors/ublox/modules/sara_r4/ports/cellular/cellular_r4_urc_handler.c
- vendors/ublox/modules/sara_r4/ports/cellular/cellular_r4_wrapper.c
SARA-R4 Cellular Modem Support
Description
-----------
Complete support is added for SARA-R4 modem, till now all cellular test cases are passed. 
In the PR following changes can be seen:
- New cellular APIs implementation for SARA-R4.
- New URCs implementation for SARA-R4.
This PR is tested for u-blox modem SARA-R412M-02B and SARA-R410-02B using UART Interface on [u-blox evk](https://www.u-blox.com/en/product/evk-r4).
Checklist:
----------
> Added u-blox cellular modem support for sara-r4
